NuGet/NuGetGallery

- src/NuGetGallery.Cloud/ServiceConfiguration.Cloud.cscfg
- src/NuGetGallery.Cloud/ServiceConfiguration.Local.cscfg
- src/NuGetGallery.Cloud/ServiceDefinition.csdef
- src/NuGetGallery/App_Start/ContainerBindings.cs
- src/NuGetGallery/Configuration/AppConfiguration.cs
- src/NuGetGallery/Configuration/IAppConfiguration.cs
- src/NuGetGallery/Infrastructure/Lucene/ExternalSearchService.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/PackageService.cs
- src/NuGetGallery/Services/StatusService.cs
- src/NuGetGallery/Web.config
- src/NuGetGallery/packages.config
Make the gallery read and respect search service configuration from
api.nuget.org/v3/index.json so that we can straightforwardly re-point it
later.
> Add ServiceDiscovery support to Gallery.

- src/NuGetGallery/Content/Site.css
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Scaled down the font size on the `stat-number` class. The Newtonsoft.Json (as an example) page looks like a mess with the current size.
> Prevent last updated date from wrapping

- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/Views/Users/Profiles.cshtml
When we pushed Nancy 1.1 today, we wanted a way to see the latest version of all [nancyfx packages](https://www.nuget.org/profiles/nancyfx), to verify that all packages was uploaded successfully. Unfortunately there's no way to see this today, without checking each package individually.
This PR adds the latest version to the packages listing under the profile page. It might not be the sexiest placement, but it does the job :sparkles:
> Added latest version for packages in profile

- src/NuGetGallery/App_Start/Routes.cs
Should fix this issue: https://github.com/NuGet/NuGetGallery/issues/2229
Problem: The route to the team api was missing. I guess it was accidentally deleted in this commit https://github.com/NuGet/NuGetGallery/commit/7d35cc0d8d12f0a5da0681f995877fcc9970afb9
> Fix broken About Page - Readded Route for Team Api

- src/NuGetGallery/ViewModels/UserProfileModel.cs
- src/NuGetGallery/Views/Users/Profiles.cshtml
As suggested in this PR https://github.com/NuGet/NuGetGallery/pull/2215 I implemented a link back to the paged package list, so that a user can navigate from the paged package list to the full package list and back again. This is only visible if paging is necessary.
Screenshot:
> Implemented a "show paged list" link in Profile UI

- src/NuGetGallery/Content/Site.css
- src/NuGetGallery/Helpers/StringHelper.cs
- src/NuGetGallery/Views/Shared/_ListPackage.cshtml
* Listing page to show at-the-glance `Last Published` and `Latest Version` info: 2731fe6 
* For instance, on http://www.nuget.org/packages?q=casablanca result listing page, if the user is looking for the most recent package or checking if the newer Version of certain package has arrived, with this change its possible without navigating to the details page.
* Adds helper to truncate description at word boundary: 34ae737
> View: Misc. fixes for listing page

- src/NuGetGallery/App_Code/ViewHelpers.cshtml
- src/NuGetGallery/App_Data/Files/Content/Home.html
- src/NuGetGallery/Views/Shared/LayoutFooter.cshtml
Should fix 2 pagespeed issues on the nuget.org:
- SpecifyImageDimensions for outercurve and nuget image
- Include Google Analytics via the Async Helper
Didn't made an end to end test with the Google Analytics stuff, but the scripts seems proper and didn't found anything bad about the async helper.
> PageSpeed Fix: Height&Width on Images & Async GA

- src/NuGetGallery.Backend/NuGetGallery.Backend.csproj
- src/NuGetGallery.Backend/app.config
- src/NuGetGallery.Backend/packages.config
- src/NuGetGallery.Operations/NuGetGallery.Operations.csproj
- src/NuGetGallery.Operations/packages.config
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/packages.config
- src/galops/packages.config
- tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj
- tests/NuGetGallery.Core.Facts/packages.config
the most confusing part actually is  tests/NuGetGallery.Core.Facts/packages.config
system.spatial was missing there, so package didn't restore at build
5.5 --> 5.6 is a cosmetic change
> System.Spatial reference cleanup

- src/NuGetGallery/Web.config
- tests/NuGetGallery.FunctionalTests/WebUITests/BasicPages/SecurityHeaderTest.cs
Per https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security#Enabling_Strict_Transport_Security
Fixes https://github.com/NuGet/Home/issues/616
> Fix typo in SSL configuration

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/UrlExtensions.cs
Issue: https://github.com/NuGet/NuGetGallery/issues/858
I removed the unnecessary version parameter from the action. Old URLs are still valid, but now the UI will render just "http://nuget.localtest.me/packages/{package}/ManagePackageOwners"
If there is a more elegant way to get a "Package"-Object from the PackageService just let me know. String.Empty is a bit... well... ;)
> Fix for #858: Remove Version Param in ManagePackageOwner Url

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
This PR fixes #2522 and:
* Shows a message on top of the package details page if it has not yet been indexed
* Shows "Indexed = yes / no" in the package version history
Screenshot for a package that is not yet in the index:
> Show indexing status next to new package versions #2522

- src/NuGetGallery/DataServices/V2Feed.svc.cs
These changes should properly enable caching on search results for the empty query (cacheability = public), and also return the $count from the cached resultset.
These changes should be merged in and go live once we have some app-insights data collected from today's deployment, so we can compare the data before and after this change.
> set cacheability to public and return $count from cached search results

- README.md
Updated the Update-Database command in the readme.md file to add -StartupProjectName parameter as NuGetGallery. (Without it it uses NuGetGallery.Operations as the Startup project which does not have the database connection string in its config...)
> Updated .md Update-Database Command

- src/NuGetGallery/Web.config
It seems that this "n" was introduced as a typo, but now the site is crashing with the default configuration
> Fixed default configuration in Web.config

- src/NuGetGallery/Content/Site.css
- src/NuGetGallery/Scripts/perpackagestatsgraphs.js
- src/NuGetGallery/Views/Statistics/PackageDownloadsByVersion.cshtml
- src/NuGetGallery/Views/Statistics/PackageDownloadsDetail.cshtml
- src/NuGetGallery/Views/Statistics/_PivotTable.cshtml
This PR changes the way charts are displayed for package detailed statistics.
Please review/comment @csharpfritz @yishaigalatzer @maartenba 
* Convert vertical bar chart to horizontal bar chart for group by client and group by operation. Note that group by package version remains a vertical bar chart, ordered by version, as the horizontal axis can be interpreted as a time dimension.
* Make height of chart dynamic with a minimum bar height on horizontal bars, and respecting a minimum chart height when few bars
* Added chart title to charts
* Added data labels to horizontal bar charts
* Moved "Total over the last 6 weeks" to top of the page and included it in the title, to have it positioned consistently independent of amount of data in the data grid below the chart
* Moved last update time …
> Charts visualization changes for package detailed stats

- build.msbuild
Fix for issue #2038 ("build.md fails when path contains spaces").
Note that the same bug exists in the NuGet.Services.Build project.  In
order to completely fix this issue, both NuGetGallery and
NuGet.Services.Build will need to be patched.
I'll create a pull request for NuGet.Services.Build as well.
> Fix for issue #2038 (part 1 of 2)

- src/NuGetGallery/ViewModels/AccountViewModel.cs
- src/NuGetGallery/ViewModels/LogOnViewModel.cs
Allow passwords with HTML chars, like `'yj^0b]'nh*'l{}*=;=^W{<Y`. Fixes #2438.
The problem was not only at registering, but also at logon and change profile/password.
Without `[AllowHtml]` ASP.net throws: 
[HttpRequestValidationException (0x80004005): A potentially
dangerous Request.Form value was detected from the client. 
Is the password ever printed somewhere? (confirmation or recover mail?) - if so, we need maybe also an escape there. 
NB: PR to DEV branch, but let me know if it should be to another branch. 
@maartenba Thanks for the proposed solution.
> Allow passwords with HTML chars

- src/NuGetGallery.Cloud/ServiceConfiguration.Cloud.cscfg
- src/NuGetGallery.Cloud/ServiceConfiguration.Local.cscfg
- src/NuGetGallery.Cloud/ServiceDefinition.csdef
- src/NuGetGallery/App_Code/ViewHelpers.cshtml
- src/NuGetGallery/App_Start/OwinStartup.cs
- src/NuGetGallery/ApplicationInsights.config
- src/NuGetGallery/Configuration/AppConfiguration.cs
- src/NuGetGallery/Configuration/IAppConfiguration.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Web.config
- src/NuGetGallery/packages.config
This PR fixes #2747:
* Upgrades Application Insights SDK to 2.0.0-beta2
* Adds support for telemetry sampling through new configuration setting `Gallery.AppInsightsSamplingPercentage`, which has default value of 100 (effectively disabling sampling by default)
cc @maartenba @joyhui @yishaigalatzer @johnataylor
> fixes #2747

- src/NuGetGallery/Infrastructure/Lucene/ExternalSearchService.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/IRawSearchService.cs
- src/NuGetGallery/Services/ISearchService.cs
- src/NuGetGallery/Services/SearchResults.cs
Relates to https://github.com/NuGet/NuGetGallery/issues/2781
This PR ensures the gallery no longer crashes with an HTTP 500 when the external search service call returns a non-200 HTTP status code.
cc @maartenba @joyhui
> No more HTTP 500 when external search service calls fail

- src/NuGetGallery.Operations/ExtensionMethods.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/ExtensionMethods.cs
- src/NuGetGallery/Services/IPackageService.cs
- src/NuGetGallery/Services/PackageService.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
> Frameworks within the portable profile are not allowed to have profiles themselves

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/RequestModels/VerifyPackageRequest.cs
- src/NuGetGallery/Views/Packages/VerifyPackage.cshtml
New PR with just the VerifyPackage enhancements (instead of https://github.com/NuGet/NuGetGallery/pull/2242) - just in read only mode.
The Verify Package Page now shows also:
- Language
- Minimum Client Version
- Dev Dependeny
- FrameworkAssemblies
- Other Dependencies
Sample 1:
Sample 2 - with DevDependency:
Sample 3:
Problems: 
The "PackageMetadata" doesn't read the MinimumClientVersion at all and a real DevelopmentDependency property is missing on the class. I could get the DevelopmentDependency Value via the key, but maybe a real property would be cleaner. 
If the DevelopmentDependency property is not found the default "not specified" appears, but this would be easy to change.
I noticed that the frameworkassembly/dependency stuff has changed - I just saw the visualization of the …
> Verify package with language, devdep & deps

- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
I reused the old unit tests from the old PR and added 3 test cases:
- Check for Dependencies
- Check for Language
- Check for MinClientVersion
This PR is related to this one https://github.com/NuGet/NuGetGallery/pull/2834
> Adding unit tests for VerifyPackage page

- src/NuGetGallery/Content/PageStylings.css
- src/NuGetGallery/Content/Site.css
The uneven styling between the headers and the paragraphs and the label stats are a bit odd in my eyes, but design can always be discussed. So this PR removes the left margins to get a straight alignment. 
I also made the labels for the stats a bit smaller.
(The red lines are only to demonstrate it)
vs. current version:
> Straight alignment for package detail page

- content/DEV/Home.html
- content/INT/Home.html
- content/PROD/Home.html
The gallery should have a link to nuget feed urls #2809 
@csharpfritz How's this?
> The gallery should have a link to nuget feed urls #2809

- src/NuGetGallery/Content/Layout.css
Currently on sites with few content the footer is somewhere in the middle of the screen:
For most people this will be the case on the upload package page and on the Manage Package page, so I made a few CSS changes.
The good part:
It should work in all browers. The only issue: If the NuGet Websites shows the yellow warning bar the scrollbar might be displayed, because the warning bar is not part of the overall container.
Result:
> Footer always at bottom

- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/EditPackageService.cs
- src/NuGetGallery/Services/PackageIdAndTitleValidationService.cs
- src/NuGetGallery/Services/PackageNamingConflictValidator.cs
- src/NuGetGallery/Services/PackageService.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/Services/PackageNamingConflictValidatorFacts.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
Fixes #2849
On upload/edit package:
* Title of newly uploaded package should not match existing package registration id
* New package registration id should not match an existing package title
/cc @yishaigalatzer @joyhui @joelverhagen
> Title of newly uploaded package should not match existing package registration id

- src/NuGetGallery/Controllers/JsonApiController.cs
- src/NuGetGallery/Services/IMessageService.cs
- src/NuGetGallery/Services/MessageService.cs
- tests/NuGetGallery.Facts/Services/MessageServiceFacts.cs
This PR fixes issue #1844 by sending an email to the package owner when being removed from a package.
I have taken some liberties as I wasn't sure how to phrase the message - feedback on the code and the message would be much appreciated.
> Fix for issue #1844 - Email sent when removing package owner

- src/NuGetGallery/Migrations/201602181939424_RemovePackageStatistics.cs
RemovePackageStatistics migration will remove foreign key from GallerySettings table so the PackageStatistics table can be correctly dropped.
Fixes #2909
Supersedes #2910
> RemovePackageStatistics will remove foreign key from GallerySettings

- tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj
Removed reference to WindowsAzure.Storage library as it is not used by the NuGetGallery.Core.Facts unit tests project.
> NuGetGallery.Core.Facts project references cleanup

- src/NuGetGallery/Migrations/201210312150156_AggregateStatistics_TotalDownloadCount.cs
In #2933, `AggregateStatistics.sql` was removed. Making the actual migration be a no-op was overlooked and that causes fresh environments to break when migrating.
References issue #2932.
> Fix broken migration from #2933

- src/NuGetGallery/Views/Packages/UploadPackage.cshtml
I noticed that the manual package upload will accept anything and will fail after the postback if the file extension is not a .nupkg:
To guide the user to their own luck I added the accept attribute, which will work on most browsers:
http://caniuse.com/#search=accept
This is not a security feature - the security part is already handled on the server - it's just cosmetic. The result (in supported browsers) is this:
> Adding accept attr for .nupkg upload to guide the user

- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
Return 400 Bad Request instead of 500 Internal Server Error when
NuGet.exe push encounters a validation error.
@xavierdecoster @skofman1
> Return 400 Bad Request instead of 500 Internal Server Error when NuGet.exe push encounters a validation error

- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Services/IMessageService.cs
- src/NuGetGallery/Services/MessageService.cs
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
- tests/NuGetGallery.Facts/Services/MessageServiceFacts.cs
Send package published notification to package owner(s) when new version
is published
> Send package published notification to package owner(s) when new version is published

- src/NuGetGallery/Content/Layout.css
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Instead of linking those heavy JS-libraries from Facebook or Twitter, I used the simple link-method.
The buttons should work the same way as before and are represented as the logos from FontAwesome.
The "downside": It's a pretty simple integration, so there is no "37 friends of you already likes this"-FB message shown.
On the pro-side:
* No more privacy issues.
* Cleaner looking page
* Faster rendering, because no JS is involved
* Saves client bandwith
* easier styling
... and because of the last point I moved this part to the sidebar:
> Remove social network JS-bloat and move social buttons to sidebar

- src/NuGetGallery/Views/Packages/ManagePackageOwners.cshtml
Issue: https://github.com/NuGet/NuGetGallery/issues/427
The flickering is a result of the knockout visible binding and that the intial display setting is block.
To prevent this I set it the error message element to display: none. Not very elegant, but works.
When knockout kicks in everything works as expected.
> Fix for flickering red bar on ManagePackageOwners page

- src/NuGetGallery.Core/Packaging/ManifestValidator.cs
- tests/NuGetGallery.Core.Facts/Packaging/ManifestValidatorFacts.cs
E.g. https://www.nuget.org/packages/Castle.Core/4.0.0-alpha001 should be
blocked
@skofman1 @xavierdecoster
> Do not allow "Unsupported" framework in package dependencies

- src/NuGetGallery/NuGetGallery.csproj
Azure SDK 2.9 comes with version 33.1.0.0 of MonAgentListener, so this change reflects the switch to 2.9.
The build was crashing before I made this change, since I only had the latest Azure SDK.
> Updating MonAgentListener (Azure SDK 2.9)

- tools/Enable-LocalTestMe.ps1
Following the current readme, makecert is located in a Visual Studio extension folder installed by Azure SDK, instead of the Windows SDK that the script previously scanned the registry for.  The scan is still there, but if the scan doesn't find the makecert properly, then the extension folder is tested instead.
> Update Enable-LocalTestMe.ps1 to find makecert

- README.md
In order to have a localdb (and also to install the latest Azure SDK), one needs to include Microsoft SQL Server Data Tools in their VS 2015 install.
These changes made to the readme (as well as the others I've pulled into the dev branch) should help anyone trying NuGetGallery out for the first time, from a fresh environment, have the least amount of bumps possible.
> Updating README - Some more details

- src/NuGetGallery.Cloud/ServiceConfiguration.Cloud.cscfg
- src/NuGetGallery.Cloud/ServiceConfiguration.Local.cscfg
- src/NuGetGallery.Cloud/ServiceDefinition.csdef
- src/NuGetGallery.Core/Entities/User.cs
- src/NuGetGallery/Authentication/AuthenticatedUser.cs
- src/NuGetGallery/Authentication/AuthenticationService.cs
- src/NuGetGallery/Authentication/Providers/Authenticator.cs
- src/NuGetGallery/Authentication/Providers/AuthenticatorT.cs
- src/NuGetGallery/Authentication/Providers/AuthenticatorUI.cs
- src/NuGetGallery/Authentication/Providers/AzureActiveDirectory/AzureActiveDirectoryAuthenticator.cs
- src/NuGetGallery/Authentication/Providers/AzureActiveDirectory/AzureActiveDirectoryAuthenticatorConfiguration.cs
- src/NuGetGallery/Authentication/Providers/LocalUser/LocalUserAuthenticator.cs
- src/NuGetGallery/Configuration/AppConfiguration.cs
- src/NuGetGallery/Configuration/IAppConfiguration.cs
- src/NuGetGallery/Controllers/AuthenticationController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- src/NuGetGallery/Views/Authentication/LogOn.cshtml
- src/NuGetGallery/Views/Users/Account.cshtml
- src/NuGetGallery/Web.config
- src/NuGetGallery/packages.config
- tests/NuGetGallery.Core.Facts/Entities/UserFacts.cs
- tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj
- tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
- tests/NuGetGallery.Facts/TestUtils/ResultAssert.cs
Enforce administrators to a specific authentication mechanism. For example, admins can be required to have Azure AD authentication setup and used as the sign-in mechanism.
* Adds Azure AD support
* Adds enforcement mechanism which will require the admin to login using the configured mechanism
/cc @xavierdecoster @skofman1 @blowdart
> Enforce administrators to a specific authentication mechanism

- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/IPackageService.cs
- src/NuGetGallery/Services/PackageService.cs
- src/NuGetGallery/Services/ReflowPackageService.cs
- src/NuGetGallery/UrlExtensions.cs
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/Services/ReflowPackageServiceFacts.cs
Implement a means of re-flowing packages so that, for example, Unsupported frameworks can be recognized usign newer NuGet.* libraries.
@skofman1 @xavierdecoster
> Make it possible to re-flow packages (detect new TFM's)

- src/NuGetGallery/Configuration/FeatureConfiguration.cs
- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Services/IPackageService.cs
- src/NuGetGallery/Services/PackageService.cs
- src/NuGetGallery/Web.config
As noted in issue #3046 download counts for packages are not being saved to the database for standalone galleries.  This PR (re-?)implements that based on an appSetting of `Feature.TrackPackageDownloadCountInLocalDatabase`.
> 3046 - allow for local tracking of download counts (rebased)

- README.md
Because of this change, it is not needed anymore https://github.com/NuGet/NuGetGallery/pull/3051
> Remove "Add MSBuild to Path" section

- src/NuGetGallery.Core/Auditing/CloudAuditingService.cs
- src/NuGetGallery.Core/Auditing/FileSystemAuditingService.cs
This PR fixes issue: https://github.com/NuGet/NuGetGallery/issues/3099
@maartenba @xavierdecoster @yishaigalatzer
> Use guid instead of timestamp in auditing files

- tests/NuGetGallery.Facts/SearchClient/RetryingHttpClientWrapperFacts.cs
Fixes #3107 - Gallery UTs take a long time to finish.
The tests were hanging in an infinite loop due to condition check failure plus a url redirection causing failure of tests.
It looks like the requestUri for `http://www.bing.com` is redirected to `https://www.bing.com/?toHttps=1&redig=414F637CC2A1431BACF5E4B0D0F90FF0` probably an SSL change on bing. I think just changing the url should be sufficient for validating tests.
Validation: All UTs passed in under 1 minute, also command line build would hang for gallery which now finishes in under 2 minutes.
> Fix 3107 - Gallery UTs take a long time to finish.

- src/NuGetGallery/Areas/Admin/Controllers/DeleteController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/ViewModels/ReportPackageReason.cs
Issue #3117:
@alpaix wrote: As it was discussed offline “The package was published as the wrong version” is not a legitimate reason for package delete request anymore. Please update the support request web form to keep customers from submitting such requests. Otherwise support person has to apologize every time in response :(.
@skofman1 @xavierdecoster @maartenba
> Remove "The package was published as the wrong version” from "package delete reasons" (Issue #3117)

- src/NuGetGallery/Helpers/StringExtensions.cs
Our package list view is displaying the description of each package by truncating it with a method called `TruncateAtWordBoundary`.
Razor normally HTML encodes every string in an `@`-tag; however, to avoid double-encoding, Razor does not encode `MvcHtmlString`s because it assumes that they are already encoded.
`TruncateAtWordBoundary` was returning an `MvcHtmlString` but not encoding the string when it was shorter than the truncate length. As a result, if the description of a package included HTML that was shorter than 300 characters, the HTML would be run in the browser.
To prevent this, I've modified `TruncateAtWordBoundary` to return a regular string, since it had no real reason to return a `MvcHtmlString` anyway. This encodes the description as usual.
(Fixes #3124)
> Don't return MvcHtmlString in TruncateAtWordBoundary (#3124)

- tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs
- tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/CuratedFeedsControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/CuratedPackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/JsonApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
- tests/NuGetGallery.Facts/Framework/Fakes.cs
- tests/NuGetGallery.Facts/Framework/TestContainer.cs
- tests/NuGetGallery.Facts/Framework/UnitTestBindings.cs
The `Fakes` object used by our tests was static, and thus shared across tests. When a test would remove, for example, a credential from this static object, other tests would fail when depending on that credential being there.
This PR makes the `Fakes` object non-static, so that each test uses a fresh copy of test data.
Ran this build a number of times, seems to fix the sporadic failures properly. (https://github.com/NuGet/NuGetGallery/issues/3105)
@skofman1 @ryuyu @scottbommarito @xavierdecoster
> Gallery UTs fail sporadically in CI

- src/NuGetGallery/Services/FileSystemFileStorageService.cs
Addresses issue https://github.com/NuGet/NuGetGallery/issues/2252
The core of the issue here was that when we were saving a file, we would write to the stream returned by the given file path. However, if the file already existed, it was not cleared before writing. In the case where the existing file was larger than the one we were trying to write, it would overwrite a portion of the file and leave the remainder, essentially corrupting both files.
This change simple removes the file if it already exists on the file system when we attempt to write to it.
@maartenba @yishaigalatzer @skofman1
> Fix issue 2252 - Hidden File Writing bug

- src/NuGetGallery/App_Start/Routes.cs
- src/NuGetGallery/Public/Blocked.html
- src/NuGetGallery/Public/Error.html
- tests/NuGetGallery.FunctionalTests.Core/Helpers/UrlHelper.cs
- tests/NuGetGallery.FunctionalTests.Fluent/ExtensionMethods.cs
- tests/NuGetGallery.FunctionalTests.Fluent/Pages.csv
Currently, if someone creates a package with an id of "upload", "upload-progress", "verify-upload", or "cancel-upload", they can potentially run into conflicts with our routing scheme. In other words, a package with an id of "upload" would be impossible to view through `packages/<id>`, because MVC would route it to our upload package path route, `packages/upload`.
To avoid conflicts with our system, this PR changes those routes to `packages/manage/upload` and so on. Since `packages/<id>` and `packages/manage/<action>` are now completely distinct routes, users can upload a package with an id equal to any of our actions and view it without any issues. Note that a package id of "manage" is also still supported.
Will be making some additional PRs in different repos to update the references to …
> Change routes from packages/<action> to packages/manage/<action> to avoid conflicts with package ids

- src/NuGetGallery/Helpers/HttpContextBaseExtensions.cs
- src/NuGetGallery/Services/FormsAuthenticationService.cs
- src/NuGetGallery/Web.config
- tests/NuGetGallery.Facts/Infrastructure/CookieTempDataProviderFacts.cs
https://devdiv.visualstudio.com/DevDiv/_workitems?id=244714&_a=edit
Not sure how necessary any of this is, but now every usage of HttpCookie sets HttpOnly to true.
> Added HttpOnly to all cookies

- src/NuGetGallery/Public/opensearch.xml
There's apparently a problem with opensearch on NuGet gallery when used with current versions of Mozilla Firefox / Firefox Developer Edition.
I am the person who contributed opensearch functionality (PR: #2833, deployed in #2685), and now I suggest this fix to solve the issue with Firefox-based browsers.
> Fix opensearch for usage with Firefox

- src/NuGetGallery.Core/Packaging/NupkgRewriter.cs
- tests/NuGetGallery.Core.Facts/Packaging/NupkgRewriterFacts.cs
The NugetGallery.Core's repackaging would rewrite the package manifest with incorrect tag for release notes (HandlePackageEdits uses this functionality). This fails to open up the package in 'Nuget Package Explorer'. This PR simply fixes the tag.
> Fix casing for release notes metadata tag in NupkgRewriter

- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery.Core/Packaging/ManifestEdit.cs
- src/NuGetGallery.Core/Packaging/NupkgRewriter.cs
- src/NuGetGallery.Core/Packaging/PackageMetadata.cs
- src/NuGetGallery.Core/Packaging/PackageMetadataStrings.cs
- tests/NuGetGallery.Core.Facts/Packaging/NupkgRewriterFacts.cs
This fixes the nupkg rewriter's packaging of nuspec to not add empty elements for metadata.
The way it works:
- If there is an existing element which is optional, defined by the nuspec schema, and the edit removes the value(by setting null/empty), we remove the element from the <metadata>.
- If there is no existing element which is optional and the edit adds a new value, this would create a new element in the <metadata> node.
- If there is a change of value(not null or empty)  to the optional element, we will update the value.
Also added test coverage. I checked with @emgarten and it looks like the client mostly cares to not have null/empty value for URI(licenseUrl, projectUrl, iconUrl). It doesnt matter if the optional fields are not present in the nuspec, this shouldn't break the …
> Fix NugetGallery.Core's NupkgRewriter

- src/NuGetGallery/Controllers/AuthenticationController.cs
- tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
The route is used as both GET and POST, so in order for it to function correctly it needs to be split into two methods.
> Split AuthenticationController.Authenticate into a POST and a GET

- src/NuGetGallery/Constants.cs
- src/NuGetGallery/Controllers/StatisticsController.cs
- src/NuGetGallery/Scripts/stats.js
- src/NuGetGallery/Scripts/statsdimensions.js
- src/NuGetGallery/Scripts/statsgraphs.js
- src/NuGetGallery/ViewModels/StatisticsFact.cs
- src/NuGetGallery/Views/Statistics/PackageDownloadsByVersion.cshtml
- src/NuGetGallery/Views/Statistics/PackageDownloadsDetail.cshtml
- src/NuGetGallery/Views/Statistics/_PivotTable.cshtml
- tests/NuGetGallery.Facts/Controllers/StatisticsControllerFacts.cs
Fixes https://github.com/NuGet/NuGetGallery/issues/3200
Fixed by checking for known dimensions (and if an unknown dimension is
specified, it's ignored).
@xavierdecoster @skofman1 @ryuyu @shishirx34 @scottbommarito
> Statistics/PackageDownloadsDetail throws System.ArgumentNullException #3200

- src/NuGetGallery/Services/PackageService.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
Fixes #3215. Note that I did respect [this unit test](https://github.com/NuGet/NuGetGallery/blob/dbe578b69eefd03671977974d221d2ceb680df1e/tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs#L951), hence the check for `IsAny`.
Please review and take over from me during vacation.
@skofman1 @ryuyu @shishirx34 @yishaigalatzer @xavierdecoster @qianjun22 
/cc @joelverhagen
> Supported frameworks not always populated correctly (fixes #3215)

- src/NuGetGallery.Core/NuGetVersionExtensions.cs
- src/NuGetGallery.Core/Packaging/ManifestValidator.cs
- tests/NuGetGallery.Core.Facts/Packaging/ManifestValidatorFacts.cs
Fixes https://github.com/NuGet/NuGetGallery/issues/3226
@skofman1 @scottbommarito @ryuyu @xavierdecoster 
@emgarten can you have a look as well if this is the intended course?
> Version validation should use the original NuGet.Core regex to ensure compat #3226

- src/NuGetGallery/Controllers/ApiController.cs
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
Fixes https://github.com/NuGet/Home/issues/3391 and #3218 
/cc @xavierdecoster @ryuyu @scottbommarito @emgarten
> Fix push package API to return conlfict for existing ID

- src/NuGetGallery/Constants.cs
- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/Services/MessageService.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
@yishaigalatzer @qianjun22 @maartenba
> Reduce password reset token expiration latency to 1 hour

- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
I think using the newer `NuGet.Client` library broke this test case (it consolidated every "theFirstDependency" into a single dependency).
> Fix broken test case after validation PR

- src/NuGetGallery/Services/FileSystemFileStorageService.cs
I noticed a bug when uploading a new package via the web ui without setting absolute filepath as FileStorageDirectory. The default value is "~/App_Data/Files", which will lead to this exception when you try to upload a new package:
The actual resolvepath method was called below the CreateDirectory-Call. I just moved the ResolvePath stuff up and make sure that the actual directoy exists.
> Resolve path before exists-or-create dir handling

- src/NuGetGallery/Controllers/JsonApiController.cs
- src/NuGetGallery/Services/IMessageService.cs
- src/NuGetGallery/Services/MessageService.cs
- src/NuGetGallery/Views/Packages/ManagePackageOwners.cshtml
- tests/NuGetGallery.Facts/Controllers/JsonApiControllerFacts.cs
- tests/NuGetGallery.Facts/Services/MessageServiceFacts.cs
UI, message-service & tests enhanced for "message"
Email body will look like this:
```
The user 'admin' wants to add you as an owner of the package 'OpenXMLSDK-MOT'.
If you do not want to be listed as an owner of this package, simply delete this email.
To accept this request and become a listed owner of the package, click the following URL:
[https://nuget.localtest.me/packages/OpenXMLSDK-MOT/owners/tester1/confirm/hqVPnrJcMiOBD06SkBFOog2](https://nuget.localtest.me/packages/OpenXMLSDK-MOT/owners/tester1/confirm/hqVPnrJcMiOBD06SkBFOog2)
The user 'admin' added the following message for you:
'asda sd asd asd ,,, &lt; .&gt;&gt;'
Thanks,
The NuGet Gallery Team
```
`'asda sd asd asd ,,, &lt; .&gt;&gt;'` => the given message
The message itself will be html encoded and will be sent in the email. …
> Feature: Add message for AddOwner request

- src/NuGetGallery/Views/Users/Account.cshtml
Issue #3386: AuthenticationService.GeneratePasswordResetToken throws InvalidOperationException when unconfirmed user re-enables password auth in profile. Proposed fix is to only show Enable button when account is confirmed, to match check in AuthService.GeneratePasswordResetToken.
@skofman1
> Prevent unconfirmed users from re-enabling password auth #3386

- src/NuGetGallery/App_Start/OwinStartup.cs
- src/NuGetGallery/Helpers/TelemetryResponseCodeFilter.cs
- src/NuGetGallery/NuGetGallery.csproj
#3316 prevent logging of 400 and 404 responses
> 3316: Filter out 400 and 404 response codes from telemetry logs

- src/NuGetGallery/Views/Packages/ManagePackageOwners.cshtml
I noticed this issue https://github.com/NuGet/NuGetGallery/issues/3356 and found that the main "blocker" for this is based in the knockout.js viewmodel.
I changed the view logic so that someone could remove his account from the owner list if there are other "non-pending" owners.
The logic is: 
If I'm the only owner, I can't remove myself.
If there are other non-pending owners, than I could remove myself, but I can always remove others.
When I try to remove myself from the owners the user will get this warning:
When the operation is completed the user will be redirected to the package page (because he is not an owner anymore).
"normal" view:
> Add ability to remove "myself" from the owner list

- tests/NuGetGallery.FunctionalTests.Core/Helpers/ClientSdkHelper.cs
- tests/NuGetGallery.FunctionalTests.Core/Helpers/CommandlineHelper.cs
- tests/NuGetGallery.FunctionalTests.Core/Helpers/ODataHelper.cs
- tests/NuGetGallery.FunctionalTests/Commandline/NuGetCommandLineTests.cs
- tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedExtendedTests.cs
Idea behind the test case is this:
1. Upload `x` packages synchronously (wait for each request to finish before starting the next one).
2. Verify that the `Created` timestamps of the packages in the feed are in the correct order.
3. Unlist the packages synchronously (wait for each request to finish before starting the next one).
4. Verify that the `LastEdited` timestamps of the packages in the feed are in the correct order.
Had to make some modifications to the framework behind the tests because a number of things were not supported that were necessary for the test case (i.e. getting timestamps from the feed, deleting packages using nuget.exe).
> Functional test that verifies the order of packages in the feed

- tests/NuGetGallery.FunctionalTests.Core/Helpers/CommandlineHelper.cs
Change -f to -force. We get "ambiguous option" error when using only -f.
> Functional tests: nuget.exe spec -f fails after nuget.exe update to 3.5

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/ViewModels/PackageListSearchViewModel.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
This PR should fix this behavior: https://github.com/NuGet/NuGetGallery/issues/1191
Background:
Currently NuGet.org doesn't allow "potentially dangerous content", e.g. < helloworld > because of the ASP.NET Request Validation.
My fix:
To suppress this I needed to introduce a new "viewmodel" in order to decorate the "query" parameter with the AllowHtml attribute.
After that everything worked as expected. The searchterm itself is html encoded displayed and shouldn't be a threat.
With this fix the NuGet.org website can trigger the search engine with those angle brackets.
> Enable angle brackets search queries (AllowHtml vs. ASP.NET Req Validation)

- tests/NuGetGallery.FunctionalTests.Core/Helpers/ODataHelper.cs
- tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedTests.cs
Encountered some deadlocks with running groups of functional tests and this appeared to be the cause.
> Functional tests: Close all web responses after use

- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Services/CloudBlobFileStorageService.cs
- src/NuGetGallery/Services/FileSystemFileStorageService.cs
- src/NuGetGallery/Services/IFileStorageService.cs
- src/NuGetGallery/Services/PackageFileService.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Services/CloudBlobFileStorageServiceFacts.cs
- tests/NuGetGallery.Facts/Services/FileSystemFileStorageServiceFacts.cs
- tests/NuGetGallery.Facts/Services/PackageFileServiceFacts.cs
- tests/NuGetGallery.Facts/Services/UploadFileServiceFacts.cs
- tests/NuGetGallery.Facts/TestUtils/MockExtensions.cs
Added an `overwrite` parameter to `IFileStorageService.SaveFileAsync`. If `overwrite` is false, the file storage service will not overwrite existing files.
Added logic to the `ApiController` and `PackagesController` upload flows to surface a UI message.
Added unit testing to verify that overwriting is handled correctly.
> Prevent overwriting of packages in blob storage

- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
The package is saved to blob storage before saving changes to the database. When the DB is in read-only mode (or there is some other failure when saving to the database), the saved package is not cleaned up from the database. [With overwriting packages in blob storage now disallowed](https://github.com/NuGet/NuGetGallery/pull/3457), this can lead to some strange failures when uploading packages.
> Delete uploaded package from blob storage if saving changes to DB fails

- src/NuGetGallery.Core/Auditing/UserAuditRecord.cs
- src/NuGetGallery.Core/CredentialTypes.cs
- src/NuGetGallery/Controllers/UsersController.cs
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
- tests/NuGetGallery.Facts/Infrastructure/UserAuditRecordFacts.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
A change that needs to be deployed prior to scoped API keys, to prevent unexpected behavior in case of rollback.
@dtivel , @xavierdecoster
> Filter out unsupported credentials from account view and auditing

- tests/NuGetGallery.FunctionalTests.Core/EnvironmentSettings.cs
- tests/NuGetGallery.FunctionalTests.Core/Helpers/CommandlineHelper.cs
- tests/NuGetGallery.FunctionalTests/Commandline/NuGetCommandLineTests.cs
- tests/NuGetGallery.FunctionalTests/ODataFeeds/CuratedFeedTest.cs
- tests/NuGetGallery.FunctionalTests/ODataFeeds/SearchTest.cs
- tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedExtendedTests.cs
- tests/NuGetGallery.WebUITests.P0/UploadAndDownload/UploadPackageFromUI.cs
- tests/Scripts/DownloadLatestNuGetExeRelease.ps1
Addresses https://github.com/NuGet/NuGetGallery/issues/3483.
When testing the staging instance before deploying the gallery, the URL being tested is some random string (dot) cloudapp (dot) .net. This URL does not match the SSL certificate so nuget.exe rejects pushing.
This change adds a custom build of nuget.exe based off of this branch:
https://github.com/NuGet/NuGet.Client/tree/dev-jver-trust-https
This nuget.exe has a feature to trust the fingerprint (a.k.a. thumbprint) of specific certificates. 
In short, this PR:
1. Uses this custom nuget.exe for functional tests.
1. Removes code that was causing some P0 tests to no-op (!!!).
1. Fix one test that depended on a package being in the first page of search results.
As a side note, the feature request for nuget.exe supporting this …
> Allow tests to run against URLs not matching "nuget.org" pattern

- .gitignore
- build.ps1
- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery/NuGetGallery.csproj
If web requests are made without this attribute, they will fail on machines that have not completed first-run configuration of Internet Explorer (VSTS hosted build agents).
> UseBasicParsing on web requests in Powershell

- tests/NuGetGallery.FunctionalTests.Core/EnvironmentSettings.cs
- tests/NuGetGallery.FunctionalTests.Core/XunitExtensions/GalleryTestFixture.cs
- tests/NuGetGallery.WebUITests.P0/UploadAndDownload/UploadPackageFromUI.cs
- tests/NuGetGallery.WebUITests.ReadOnlyMode/AccountManagement/AccountManagementInReadOnlyModeTest.cs
- tests/NuGetGallery.WebUITests.ReadOnlyMode/AccountManagement/RegisterNewUserInReadOnlyModeTest.cs
- tests/NuGetGallery.WebUITests.ReadOnlyMode/UploadAndDownload/UploadPackageFromInUIInReadOnlyMode.cs
1. `UploadPackageFromUI` was improperly asserting 503 against a non-read-only server.
1. Remove checks that skipped test logic based on `ReadOnly` flag. This is the wrong way to skip tests.
Addresses https://github.com/NuGet/Engineering/issues/188.
Found https://github.com/NuGet/Engineering/issues/200 in the process. Will address separately.
> Fix functional tests

- src/NuGetGallery/WebApi/QueryResult.cs
- tests/NuGetGallery.Facts/Services/FeedServiceFacts.cs
Before this change, an HTTP `500 Internal Server Error` was being thrown.
Fixes https://github.com/NuGet/NuGetGallery/issues/3435
> Handle case where $filter makes Package(Id=...,Version=...) yield an empty result

- src/NuGetGallery/Views/Pages/Contact.cshtml
Related to this PR https://github.com/NuGet/NuGetGallery/pull/3415 
Currently the "Contact Us" page is also missing the required-badge icon. 
The contact-us form was also not using the normal <fieldset ...> container, which is needed to render the img as a block element.
With the PR applied:
Current version:
Nothing fancy, but a consistent UI is helpful.
> Contact-Page: Add Required-badge and use fieldset

- tests/NuGetGallery.FunctionalTests.Core/EnvironmentSettings.cs
Not sure how this snuck in, but it was probably test code left over from the scoped API keys work. This prevents the environment variables set by the CI (in particular the staging slot URL) from sticking.
> Remove hard coded base URL in functional tests

- src/NuGetGallery/Views/Packages/Edit.cshtml
I noticed that on nearly all NuGet forms, e.g. create user form, change password, change email, contact support form there is this little "[blue border] = required" image - but currently it is missing from the Edit-Package page.
This PR will just add the little image to the edit page, resulting in this:
Currently it looks like this:
> Added "Required"-badge on Edit Package Page

- src/NuGetGallery/ApplicationInsights.config
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Web.config
- src/NuGetGallery/packages.config
Fixes #3101 - Gallery doesn't log traces to Application Insights.
Project was missing trace listener for AI. Adding it now logs all traces to AI. Note: adding the project, updated some dependencies, hence the proj changes.
> Enable trace listeners for app insights in Gallery

- src/NuGetGallery/Views/Shared/LayoutFooter.cshtml
Hi NuGet team! We really appreciate the Octopus link in the footer. Mind if we update the URL? 
Git seems to really want a newline at the bottom of the file for some reason too.
> Update Octopus link

- tests/NuGetGallery.FunctionalTests.Core/Helpers/ClientSdkHelper.cs
- tests/NuGetGallery.FunctionalTests/Commandline/PackageVersionTest.cs
- tests/NuGetGallery.FunctionalTests/ODataFeeds/CuratedFeedTest.cs
- tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedExtendedTests.cs
- tests/NuGetGallery.LoadTests/NuGetGallery.LoadTests.csproj
- tests/NuGetGallery.WebUITests.P1/BasicPages/StatisticsPageTest.cs
- tests/NuGetGallery.WebUITests.P2/BasicPages/SecurityHeaderTest.cs
- tests/Scripts/RunP1Tests.bat
- tests/Scripts/RunP2Tests.bat
1. Retry calls to `FindPackagesById` since it delegates to search service.
1. Delete tests than take > 10 minutes. Two of the three of that type were already skipped.
1. Fix statistics page web UI test to not depend on a specific package ID.
After this, P1 and P2 tests work just fine against DEV, INT, and PROD.
The whole suite takes 30 - 40 minutes to run.
> Fix P1 and P2 functional tests 

- .gitignore
- tests/Scripts/Configure-FunctionalTests.ps1
- tests/Scripts/RunEverything.cmd
- tests/Scripts/RunP0Tests.bat
- tests/Scripts/RunP1Tests.bat
- tests/Scripts/RunP2Tests.bat
- tests/Scripts/RunReadonlyModeTests.bat
Changed the outputs of our test scripts to output `xml` instead of `html` and to use `VSTest` instead of `MSTest` (when possible).
Also added a script to determine the url of the gallery being tested using an Azure service principal.
> Make functional tests output xml instead of html and use VSTest instead of MSTest

- src/NuGetGallery/Services/PackageNamingConflictValidator.cs
- tests/NuGetGallery.Facts/Services/PackageNamingConflictValidatorFacts.cs
Fix #3456.
A package title should be available for reuse by another package if the title is not otherwise in use by any non-deleted package.  Before this change, a soft-deleted package's title was still reserved.
Added a few unit tests.  Verified the new experience from both the command line (nuget.exe) and from the gallery web site.
> Allow package title reuse after package soft-deletion

- src/NuGetGallery/Authentication/AuthenticationService.cs
- src/NuGetGallery/Authentication/Providers/AuthenticatorUI.cs
- src/NuGetGallery/Services/MessageService.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- src/NuGetGallery/Views/Users/ApiKeys.cshtml
- tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs
- tests/NuGetGallery.Facts/Services/MessageServiceFacts.cs
Fix for: https://github.com/NuGet/NuGetGallery/issues/3525
The message will be similar to this:
API Key 'blabla' was added to your account and can now be used. If you did not request this change, please reply to this email to contact support.
API Key 'blabla' was removed from your account and can no longer be used. If you did not request this change, please reply to this email to contact support.
> Fix api key add/remove e-mail message

- src/NuGetGallery.Core/Entities/EntitiesConfiguration.cs
- src/NuGetGallery.Core/Entities/EntitiesContext.cs
- src/NuGetGallery.Core/Entities/IEntitiesContext.cs
- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Services/IPackageService.cs
- src/NuGetGallery/Services/PackageDeleteService.cs
- src/NuGetGallery/Services/PackageService.cs
- src/NuGetGallery/Services/ReflowPackageService.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Services/PackageDeleteServiceFacts.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
- tests/NuGetGallery.Facts/Services/ReflowPackageServiceFacts.cs
- tests/NuGetGallery.Facts/TestUtils/FakeEntitiesContext.cs
- tests/NuGetGallery.FunctionalTests.Core/Helpers/ODataHelper.cs
- tests/NuGetGallery.FunctionalTests.Core/NuGetGallery.FunctionalTests.Core.csproj
- tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedExtendedTests.cs
Approach is same as discussed, but implementation is more complex due to our need to restrict the optimistic concurrency check to CUD operations only on specific columns - which EF doesn't support.
> Fix #2514 - Use optimistic concurrency to prevent multiple UpdateIsLatest calls on same package

- tests/Scripts/RunEverything.cmd
- tests/Scripts/RunP0Tests.bat
- tests/Scripts/RunP1Tests.bat
- tests/Scripts/RunP2Tests.bat
- tests/Scripts/RunReadonlyModeTests.bat
One of our functional test scripts was attempting to run VSTest with MSTest parameters and failing. As VSTS supports both MSTest and VSTest, and VSTest cannot run all of our functional tests, rather than splitting our functional tests between both, for clarity's sake we should use only one.
> Remove VSTest from functional tests

- src/NuGetGallery.Core/Auditing/AggregateAuditingService.cs
- src/NuGetGallery.Core/Auditing/AuditingService.cs
- src/NuGetGallery.Core/Auditing/CloudAuditingService.cs
- src/NuGetGallery.Core/Auditing/FileSystemAuditingService.cs
- src/NuGetGallery.Core/Auditing/IAuditingService.cs
- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/App_Start/RuntimeServiceProvider.cs
- src/NuGetGallery/Authentication/AuthenticationService.cs
- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Properties/AssemblyInfo.cs
- src/NuGetGallery/Services/PackageDeleteService.cs
- src/NuGetGallery/Services/PackageService.cs
- src/NuGetGallery/Services/UserService.cs
- tests/NuGetGallery.Core.Facts/Auditing/AggregateAuditingServiceTests.cs
- tests/NuGetGallery.Core.Facts/Auditing/AuditingServiceTests.cs
- tests/NuGetGallery.Core.Facts/Auditing/FileSystemAuditingServiceTests.cs
- tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj
- tests/NuGetGallery.Facts/App_Start/RuntimeServiceProviderTests.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Framework/TestAuditingService.cs
- tests/NuGetGallery.Facts/Framework/UnitTestBindings.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/Services/PackageDeleteServiceFacts.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
Internally we (nuget.org) have to log audit data to an additional service.  Without polluting NuGetGallery code with implementation details of this internal auditing service, this change enables the NuGetGallery to discover new `AuditingService` implementations and add them to an `AggregateAuditingService` instance.
> Enable runtime discovery/loading of optional AuditingService implementations

- src/NuGetGallery.Core/CoreStrings.Designer.cs
- src/NuGetGallery.Core/CoreStrings.resx
- src/NuGetGallery.Core/Infrastructure/AzureEntityList.cs
- src/NuGetGallery.Core/Infrastructure/TableErrorLog.cs
- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery.Core/packages.config
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
These are used by dashboard. Right now, dashboard depends on a checked in version of NuGetGallery.Core and NuGetGallery (!!!). This needs to be fixed up for signing. Moving these types to NuGetGallery.Core means we don't have start signing NuGetGallery quite yet. And it simplifies dashboard dependencies.
> Move AzureEntityList and TableErrorLog to NuGetGallery.Core

- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery.Core/packages.config
- src/NuGetGallery/Diagnostics/ElmahHandleErrorAttribute.cs
- src/NuGetGallery/Diagnostics/SendErrorsToTelemetryAttribute.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Web.config
- src/NuGetGallery/packages.config
1. Change from `elmah.sqlserver` to `elmah.sqlserver.strongname`
1. Change from `elmah` to `elmah.strongname`
1. Change from `elmah.corelibrary` to `elmah.corelibrary.strongname`
1. Remove `Elmah.Contrib.Mvc` and copy the source (it's a single class from a StackOverflow answer).
This means that dashboard can remove its NuGetGallery dependency and just depend on NuGetGallery.Core (which can not be strong name signed).
Verification steps:
1. Generate exception with SQL Server error sink.
1. Generate exception with Azure Table Storage error sink.
1. Make sure the admin error page works.
1. Make sure non-admins cannot access the error page.
> Depend on signed version of Elmah

- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery.Core/packages.config
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/packages.config
- tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj
- tests/NuGetGallery.Core.Facts/app.config
- tests/NuGetGallery.Core.Facts/packages.config
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/packages.config
This is to align with NuGet.Services.Metadata.Catalog ([source](https://github.com/NuGet/NuGet.Services.Metadata/blob/d1a39464c5ef4cf54c6afa60e3ce7d8ddccb6686/src/Catalog/packages.config#L15)).
The alignment is necessary because the dashboard jobs depend on both NuGetGallery.Core and NuGet.Services.Metadata.Catalog. There was a breaking API change from 4.3.0 to 7.0.0 resulting in the following error in the dashboard jobs at runtime:
```
error: MissingMethodException: Method not found: 'Microsoft.WindowsAzure.Storage.Table.TableOperation Microsoft.WindowsAzure.Storage.Table.TableOperation.Retrieve(System.String, System.String)'.
error:  Stack Trace:    at NuGetGallery.Infrastructure.AzureEntityList`1..ctor(String connStr, String tableName)
error:    at …
```
> Update WindowsAzure.Storage to 7.0.0

- src/NuGetGallery/Services/PackageService.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
- tests/NuGetGallery.Facts/Services/ReflowPackageServiceFacts.cs
- tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedExtendedTests.cs
Regression from PR #3548, found during dev deployment
EntitiesContext default ctor pulls connection string from web.config (localdb), but we needed cloud configuration.
Updated functional test to push first package non-concurrently to avoid conflict on registration creation, and to spread remaining pushes over 5s period (~6 pkg/second) which is more realistic.
> Fix for UpdateIsLatestAsync retry connection string

- src/NuGetGallery/Controllers/UsersController.cs
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
Fixes this: https://github.com/NuGet/NuGetGallery/issues/3598
> Send e-mail when a new API key is created

- src/NuGetGallery/Helpers/StringExtensions.cs
- src/NuGetGallery/ViewModels/ListPackageItemViewModel.cs
- src/NuGetGallery/Views/Shared/_ListPackage.cshtml
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/ViewModels/ListPackageItemViewModelFacts.cs
Split description truncation from extra information so we can parse html in extra info.
Fix for https://github.com/NuGet/NuGetGallery/issues/3604
@skofman1 @shishirx34 @joelverhagen
> Fixing Package Description truncation

- src/NuGet.Services.Search.Client/NuGet.Services.Search.Client.csproj
- src/NuGet.Services.Search.Client/app.config
- src/NuGet.Services.Search.Client/packages.config
- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery.Core/Packaging/ManifestValidator.cs
- src/NuGetGallery.Core/app.config
- src/NuGetGallery.Core/packages.config
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Web.config
- src/NuGetGallery/packages.config
- tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj
- tests/NuGetGallery.Core.Facts/app.config
- tests/NuGetGallery.Core.Facts/packages.config
- tests/NuGetGallery.Facts/App.config
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/packages.config
This PR
* upgrades our `NuGet.*` dependencies to version **4.0.0**
* consolidates `Moq` and `Newtonsoft.Json` dependencies to vLatest
* leverages the now public field `NuGet.Packaging.PackageIdValidator.MaxPackageIdLength` instead of copy/paste + [#sadpanda comment](https://github.com/NuGet/NuGetGallery/compare/dev...dev-pkgid-validation?expand=1#diff-0e2dd4dc7cd7407bf362381962b58326L17) in the gallery code base
This PR will also facilitate other validation improvements that are required for semver2 work (and didn't want to pollute those PRs with this upgrade).
> Upgrade to NuGet.* v4.0.0 dependencies

- src/NuGetGallery.Core/CredentialTypes.cs
- src/NuGetGallery/App_Start/Routes.cs
- src/NuGetGallery/Authentication/AuthenticationService.cs
- src/NuGetGallery/Authentication/NuGetScopes.cs
- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/Infrastructure/Authentication/CredentialBuilder.cs
- src/NuGetGallery/Infrastructure/Authentication/ICredentialBuilder.cs
- src/NuGetGallery/RouteNames.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs
- tests/NuGetGallery.Facts/Authentication/TestCredentialBuilder.cs
- tests/NuGetGallery.Facts/Authentication/TestCredentialHelper.cs
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
- tests/NuGetGallery.Facts/Framework/Fakes.cs
- tests/NuGetGallery.Facts/Framework/TestExtensionMethods.cs
- tests/NuGetGallery.Facts/Infrastructure/UserAuditRecordFacts.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
Telemetry will come in separate PR
> Temp keys implementation (#3563)

- src/NuGetGallery/Authentication/AuthenticationService.cs
`UserAuditRecord`'s constructor does not allow a null `Credential`.
> Fix regression from #3666

- src/NuGetGallery/Services/PackageService.cs
- tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedExtendedTests.cs
Prevents marking concurrently unlisted/deleted package as latest/latestStable
Functional test improvement that increases concurrent unlist conflicts. Instead of unlisting 2 sections (15 concurrent), it unlists 6 sections (5 concurrent unlists).
Still not able to repro in local dev environment. Will need more testing once deployed to dev/int.
> UpdateIsLatest concurrent unlist fix

- src/NuGetGallery.Core/Entities/EntitiesConfiguration.cs
- src/NuGetGallery.Core/Entities/EntitiesContext.cs
- src/NuGetGallery.Core/Entities/IEntitiesContext.cs
- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Services/IPackageService.cs
- src/NuGetGallery/Services/PackageDeleteService.cs
- src/NuGetGallery/Services/PackageService.cs
- src/NuGetGallery/Services/ReflowPackageService.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Services/PackageDeleteServiceFacts.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
- tests/NuGetGallery.Facts/Services/ReflowPackageServiceFacts.cs
- tests/NuGetGallery.Facts/TestUtils/FakeEntitiesContext.cs
- tests/NuGetGallery.FunctionalTests.Core/Helpers/ODataHelper.cs
- tests/NuGetGallery.FunctionalTests.Core/NuGetGallery.FunctionalTests.Core.csproj
- tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedExtendedTests.cs
Revert of attempted fix to UpdateIsLatest, which still had concurrency issue for unlist. Deployed to dev0, with all tests passing except the concurrency functional test which will be removed as part of this revert.
> Revert UpdateIsLatest optimistic concurrency changes

- src/NuGetGallery/Services/CloudBlobFileStorageService.cs
- src/NuGetGallery/Services/CloudBlobWrapper.cs
- src/NuGetGallery/Services/FileSystemFileStorageService.cs
- src/NuGetGallery/Services/FileSystemService.cs
- src/NuGetGallery/Services/IFileSystemService.cs
- src/NuGetGallery/Services/ISimpleCloudBlob.cs
- tests/NuGetGallery.Core.Facts/Utilities/TestDirectory.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/Services/CloudBlobFileStorageServiceFacts.cs
- tests/NuGetGallery.Facts/Services/FileSystemFileStorageServiceFacts.cs
- tests/NuGetGallery.FunctionalTests/NuGetGallery.FunctionalTests.csproj
- tests/NuGetGallery.FunctionalTests/PackageCreation/ApiPushTests.cs
Addresses https://github.com/NuGet/NuGetGallery/issues/3661.
The problem here is that the `overwrite` parameter on `IFileStorageService.SaveFileAsync` is not implemented in a thread-safe way. In both file system and Azure blob storage cases, the logic is:
1. Check if the file exists.
1. If we are allowed to overwrite, delete the file if it exists.
1. If we are not allowed to overwrite, throw.
1. Persist the provided stream.
1. Commit the package to the database.
1. If the commit fails, delete the package file.
Between step number 1 and 4, two threads can enter and persist the stream successfully when one thread should have failed on step 3. The two threads continue on to the next step in the push flow, which is persisting the package to the database. The first thread succeeds but the …
> Make file storage implementations atomically check for overwrite

- src/NuGetGallery/ViewModels/DependencySetsViewModel.cs
- src/NuGetGallery/Views/Packages/_PackageDependencies.cshtml
- tests/NuGetGallery.Facts/ViewModels/DependencySetsViewModelFacts.cs
This PR should fix this issue https://github.com/NuGet/NuGetGallery/issues/3550
The change is only added in the view-logic and this partial-view is used on the upload-verify page and the display package page. These are the only two sites that are able to list dependencies, so with this PR everything should be ordered the same way on the website.
Some dependencySets (e.g. .NET 4.5 Framework) only have on "null" empty in it, so I needed to split those with dependencies and those with the null dependency - thats why I inserted the if/else stuff.
The result of this PR. Lets take a example from this package: https://www.nuget.org/packages/NLog/5.0.0-beta06
The order is pretty random on all levels:
With this PR:
The verify upload page is ordered the same way:
Another example (the AutoMapper …
> Order Dependencies

- src/NuGetGallery/Content/Site.css
- src/NuGetGallery/Views/Packages/Edit.cshtml
This is a follow up on the original PR (https://github.com/NuGet/NuGetGallery/pull/3416)
I made a small CSS changes, so that the padding-changes are only used for the form-field-full inputs.
This css class is only used on the edit page and the signin:
, which looks like that in Chrome:
IE 11:
Edit Package in Chrome:
& IE 11:
Maybe you notice, that the validation error is not 100% the same width as the input field. The reason here is the padding-right, which I needed to set to 0px, otherwise the login/register would look like that:
Its a trade off, but I think it is still ok and enhancement to the NuGet.org UX.
]
> Use 100% width for input controls on edit package page (Nr. 2)

- src/NuGetGallery/App_Start/VersionRouteConstraint.cs
- src/NuGetGallery/Constants.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Services/IPackageService.cs
- src/NuGetGallery/Services/PackageService.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Routing/VersionRouteConstraintFacts.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
URLs like `https://www.nuget.org/packages/PACKAGE/prerelease` will display the latest prereleased version. Will fall back to latest stable version if no pre-releases exist.
> Code and tests for issue #2567

- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery.Core/Packaging/PackageMetadata.cs
- src/NuGetGallery.Core/app.config
- src/NuGetGallery.Core/packages.config
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Scripts/nugetgallery.js
- src/NuGetGallery/Services/PackageService.cs
- src/NuGetGallery/Web.config
- src/NuGetGallery/packages.config
- tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj
- tests/NuGetGallery.Core.Facts/Packaging/ManifestValidatorFacts.cs
- tests/NuGetGallery.Core.Facts/Packaging/PackageMetadataFacts.cs
- tests/NuGetGallery.Core.Facts/app.config
- tests/NuGetGallery.Core.Facts/packages.config
- tests/NuGetGallery.Facts/App.config
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
- tests/NuGetGallery.Facts/Services/ReflowPackageServiceFacts.cs
- tests/NuGetGallery.Facts/packages.config
Fixes #3482 
Using `strictVersionCheck=true` by default, to block packages from being uploaded to nuget.org if they contain package dependencies with an invalid version range.
> Block packages with illegal package dependency version ranges

- src/NuGetGallery.Core/CoreStrings.Designer.cs
- src/NuGetGallery.Core/CoreStrings.resx
- src/NuGetGallery.Core/NuGetVersionExtensions.cs
- src/NuGetGallery.Core/Packaging/ManifestValidator.cs
- src/NuGetGallery/Services/PackageService.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- tests/NuGetGallery.Core.Facts/Packaging/ManifestValidatorFacts.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
This is not to be merged into dev yet, but would like to get it reviewed and merged into semver2 feature branch earlier :)
This PR:
* Removes additional version validation for legacy clients (2.x). The fact this version is parsed as a `NuGetVersion` already is good enough as for validating the version. The default semver2 filtering on v2 endpoints will still prevent these old 2.x clients from consuming such package versions, and can be considered a replacement for this.
* Rejects dependency version ranges that have the metadata part
* No longer blocks semver2 packages
> Remove validation rules that block uploading valid semver2 versions

- src/NuGetGallery.Core/SemVerLevelKey.cs
- src/NuGetGallery/App_Start/NuGetODataV2FeedConfig.cs
- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/ODataV2CuratedFeedController.cs
- src/NuGetGallery/Controllers/ODataV2FeedController.cs
- src/NuGetGallery/OData/Serializers/NuGetEntityTypeSerializer.cs
- src/NuGetGallery/Queries/AutoCompleteDatabasePackageIdsQuery.cs
- src/NuGetGallery/Queries/AutoCompleteDatabasePackageVersionsQuery.cs
- src/NuGetGallery/Queries/AutoCompleteDatabaseQuery.cs
- src/NuGetGallery/Queries/AutoCompleteServiceQuery.cs
- src/NuGetGallery/Queries/AutocompleteServicePackageIdsQuery.cs
- src/NuGetGallery/Queries/AutocompleteServicePackageVersionsQuery.cs
- src/NuGetGallery/Queries/IAutoCompletePackageIdsQuery.cs
- src/NuGetGallery/Queries/IAutoCompletePackageVersionsQuery.cs
- tests/NuGetGallery.Core.Facts/SemVerLevelKeyFacts.cs
- tests/NuGetGallery.Facts/Controllers/ODataV1FeedControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/ODataV2CuratedFeedControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/ODataV2FeedControllerFacts.cs
- tests/NuGetGallery.Facts/Services/FeedServiceFacts.cs
- tests/NuGetGallery.Facts/TestUtils/Infrastructure/FeedServiceHelpers.cs
This PR is about adding support for the new `semVerLevel` query parameter on the V2, V2-curatedfeed and V2 AutoComplete endpoints, as per the [design](https://github.com/NuGet/Home/wiki/SemVer2-support-for-nuget.org-(server-side)).
This PR changes V2 OData feed projections to always use normalized versions in navigation links.
It is a follow-up on https://github.com/NuGet/NuGetGallery/issues/3686 (filter SemVer2 package versions by default).
> Add support for semVerLevel query parameter to V2 endpoints

- src/NuGetGallery/Services/PackageService.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
Fix for #2483
I enhanced the PackageValidation for the "null-cases" for the description and author element. The NuGet package author itself is never (or at least currently) null, but maybe filled with an empty element. 
No <description> element set (or an empty description element will trigger the same behavior):
No <authors> or <owners> element set:
Without those checks some other processes might fail (e.g. the lucene job needs the description and might fail if it is null).
Currently you could upload something without the author tag, but when you try to update it you will get a validation error:
This PR should fix the null handling and discard any uploads without a description or an empty author.
It seems that a empty <description></description> is also catched, because somewhere in the …
> Fix for 2483 Author and description null checks & tests

- tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedExtendedTests.cs
Remove flaky assert which depends on client/server clocks being in sync. Instead will just continue verifying that key is expired after first use.
> Remove flaky assert dependent on system clocks

- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
PR #3728 changed PackageService.CreatePackageAsync to throw InvalidPackageException instead of EntityException.
> PR#3741 test fix, per integration with PR#3728

- src/NuGetGallery/ExtensionMethods.cs
- src/NuGetGallery/Services/TelemetryService.cs
- tests/NuGetGallery.Facts/ExtensionMethodsFacts.cs
Reported by @skofman1, we noticed IsVerificationKeyUsed also returns true when legacy (non-scoped) API keys are used. This fixes it so only API keys with package:verify scope are reported for this property.
> IsVerificationKeyUsed telemetry fix

- src/NuGetGallery/Content/Site.css
- src/NuGetGallery/Views/Users/Packages.cshtml
Fix for https://github.com/NuGet/NuGetGallery/issues/3783
With the changes applied it looks like this:
* Table is stretched to the full content 
* last column is right aligned, so it has a straight line
Currently both tables can still look "different", because the width of the columns are not fix, but at least the downloads count will be aligned.
The simplest fix was to use a new css class, because the "sexy-table" is used on other sites as well. The "last" css class on all last tds was needed to ensure everything is aligned the right way and is compatible with all IE versions.
What do you think?
> 100% Table width for Manage My Package overview

- src/NuGetGallery/Infrastructure/Lucene/LuceneIndexingService.cs
Fixes https://github.com/NuGet/NuGetGallery/issues/3862
Depends on https://github.com/NuGet/NuGetGallery/issues/3708
> LuceneIndexingService in Gallery should take into account IsLatest(Stable)SemVer2

- src/NuGetGallery.Core/SemVerLevelKey.cs
- tests/NuGetGallery.Core.Facts/SemVerLevelKeyFacts.cs
There was a bug where the semVerLevelKey computation would fail if the package contained an empty dependency group (ie targetFramework specified, but no actual package dependencies).
This PR adds a null check to guard against this failure.
@xavierdecoster @joelverhagen @cristinamanum @skofman1
> Fix Parsing of Empty Dependency Groups

- src/NuGetGallery/Constants.cs
Fixes https://github.com/NuGet/Home/issues/5156
> Support MinClientVersion <= 4.1.0.0

- src/NuGetGallery/Views/Authentication/_Register.cshtml
- src/NuGetGallery/Views/Packages/VerifyPackage.cshtml
This pull request does the following accessibility improvements:
* Improved the titles of the buttons and select drop-down box on the Upload Verification page
* Improved the registration form
* Fixed issue where the email input wasn't properly labelled
* Made all help texts part of the fields' labels.
All of these changes are on the UI, thus, I didn't do any changes to unit tests.
Fixes VSTS bugs [#395317](https://devdiv.visualstudio.com/DevDiv/_workitems?id=395317&_a=edit&triage=true), [#395879](https://devdiv.visualstudio.com/DevDiv/_workitems?id=395879&_a=edit&triage=true), and [#395340](https://devdiv.visualstudio.com/DevDiv/_workitems?id=395340&_a=edit&triage=true).
> Improved the Gallery's Screen Reader Accessibility

- src/NuGetGallery/Views/Packages/VerifyPackage.cshtml
Previously, while tabbing through the VerifyPackage page, pressing Edit or Undo would reset the focus to the top of the page. With this change, the focus remains on the buttons.
> Pressing Edit or Undo on the VerifyPackage page does not reset focus

- src/NuGetGallery/Content/Site.css
- src/NuGetGallery/Helpers/AccordeonHelper.cs
- src/NuGetGallery/Scripts/nugetgallery.js
- src/NuGetGallery/Views/Packages/UploadPackage.cshtml
- src/NuGetGallery/Views/Users/Account.cshtml
- src/NuGetGallery/Views/Users/ApiKeys.cshtml
- src/NuGetGallery/Views/Users/Packages.cshtml
Improved accessibility for the following pages:
* Account Page
* Improved the upload and manage package links by separating the label
and describe sections. Resolves [VSTS #395337](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=395337&_a=edit)
* Improved accessibility of "Change" button toggles. The screen reader
will now describe their state as "expanded" or "collapsed".
Fixes [VSTS #395336](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=395336&_a=edit)
* Improved accessibility of "Add Key" button for API Key management.
The screen reader will now describe the button as disabled or not.
Fixes [VSTS #395343](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=395343&_a=edit).
* Improved accessibility of "Example glob …
> Improved NuGet Gallery's Accessibility

- README.md
This is easier since it does not require an SSH key.
> Use HTTPS clone in README.md instead of SSH

- tools/Setup-DevEnvironment.ps1
1. Only use the certificate, since `netsh http add sslcert` only accepts a single certificate at a time
1. Throw if netsh complains about incorrect parameters
> Handle case where there are multiple localhost certs

- src/NuGetGallery/Content/Site.css
We were setting outline: none in a few places, which caused many elements to not show when they had focus. Set a :focus style globally, and override where necessary.
@xavierdecoster, @skofman1 Is there a reason this was done in these places? I don't want to mess up any explicit decisions we made.
@joelverhagen
> Fix Focus Visibility

- src/NuGetGallery/App_Start/Routes.cs
- src/NuGetGallery/Controllers/StatisticsController.cs
- src/NuGetGallery/RouteNames.cs
- src/NuGetGallery/Scripts/statsdimensions.js
- src/NuGetGallery/ViewModels/StatisticsPackagesViewModel.cs
- src/NuGetGallery/Views/Statistics/PackageDownloadsByVersion.cshtml
- src/NuGetGallery/Views/Statistics/PackageDownloadsDetail.cshtml
- src/NuGetGallery/Views/Statistics/_PivotTable.cshtml
- tests/NuGetGallery.Facts/Controllers/StatisticsControllerFacts.cs
This is an accessibility fix that has developed into a user experience improvement in general.
Previously, the [PackageDownloadsDetail](https://www.nuget.org/stats/packages/newtonsoft.json/10.0.1) and [PackageDownloadsByVersion](https://www.nuget.org/stats/packages/newtonsoft.json) pages would refresh every time the selected dimensions were changed. This was obviously bad for accessibility, as the focus would be lost every time the page refreshed, which disorients users.
I have fixed this.
- Previously, the logic to inflate the table of information used by the browser was done in CSHTML, which is created server side. This logic is now done in JS using knockout (see `_PivotTable.cshtml`). We already had knockout in our project so I used the existing version.
- Added a route that returns …
> Make PackageDownloadsDetail and PackageDownloadsByVersion graphs update without refreshing the page

- tests/NuGetGallery.FunctionalTests/PackageCreation/SecurityPolicyTests.cs
Re-enables security policy functional tests for Gallery
New test account created and configured in Octopus. Will need to onboard the test account once migrations have been done in order for tests to pass.
> Enable security policy functional tests

- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/OData/QueryAllowed/ODataQueryFilter.cs
- src/NuGetGallery/OData/SearchService/SearchAdaptor.cs
- src/NuGetGallery/WebApi/QueryResult.cs
- src/NuGetGallery/WebApi/QueryResultDefaults.cs
- tests/NuGetGallery.Facts/Controllers/ODataFeedControllerFactsBase.cs
- tests/NuGetGallery.Facts/Controllers/ODataV1FeedControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/ODataV2CuratedFeedControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/ODataV2FeedControllerFacts.cs
> Hijack IsLatest(Stable)Version OData filter when semVerLevel=2.0.0

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
When an exact package id and version (including metadata) match is detected during package upload, we still show the current error message.
However, when we detect that the newly uploaded package version only differs by metadata with an existing package version, we'll enhance the message and clarify.
Fixes #3910
> Detect if package only differ by metadata and show optimal user-facing error message

- src/NuGetGallery/Infrastructure/ApplicationVersionHelper.cs
Link to "master" in the footer points to a 410 page on GitHub: https://github.com/NuGet/NuGetGallery/issues/3828
> fix for issue 3828: Link to "master" in the footer points to a 410 page on GitHub

- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
Issue found in DEV: SecurityPolicyService.SubscribeAsync adds user policies but EF wasn't saving the changes to the DB. The issue is that the controller and service have different EF contexts, resulting in a user from the controller being in a detached state when it reaches the policy service.
Changing back to InstancePerLifetimeScope results in the same EF context instance.
> Avoid separate context from policy service

- src/NuGetGallery/Content/Site.css
Allow auto outlining. Fix issue with outline on click.
This gets rid of the orange outline in favour of letting the browser decide, and fixes the issue with seeing the outline when clicking an item.
@joelverhagen @skofman1
> Fix focus outlining for real

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/ViewModels/ReportAbuseViewModel.cs
- src/NuGetGallery/ViewModels/ReportPackageReason.cs
- src/NuGetGallery/Views/Packages/ReportAbuse.cshtml
This PR updates the report abuse page with the following:
1. Hides the block that only pertains to copyright claims when the report reason is not copyrighting.
2. Moves validation of Signature to controller from model.
3. Updates option to read "copyright" instead of "license"
4. Adds a small blurb about contact via an email address.
See https://github.com/NuGet/NuGetGallery/issues/3792 for more information.
@karann-msft @xavierdecoster @skofman1
> Update Report Abuse Page

- src/NuGetGallery/Views/Packages/ReportAbuse.cshtml
Fixes #4002. Relevant to [VSTS #395879](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=395879&_a=edit). This help-text bug was for the sign-in page, but this also affects the Report Abuse page.
> Fixed Report Abuse Page's Accessibility

- src/NuGetGallery/Migrations/201705031714183_AddIndexSemVerLevelKey.cs
Now, the change is deployed, removing the non-SQL express friendly bits.
> Removing the "WITH(ONLINE=ON)" from the index creation as per #3952

- src/NuGetGallery/Services/PackageService.cs
Fixes #3916
The code was relying on `NuGetVersion.ToString` implementation instead of `NuGetVersion.ToFullString`.
> Version validation should happen on the full string

- src/NuGetGallery/Views/Statistics/_PivotTable.cshtml
A quick fix for the date format on stats page. Fixes https://github.com/NuGet/NuGetGallery/issues/4053
> Fix the date format on stats page

- src/NuGetGallery/Queries/AutoCompleteDatabasePackageVersionsQuery.cs
Related to #4092
Same here, we need to improve test-coverage (tracked by separate issue #4094)
> v2 package-versions auto-complete endpoint should exclude unlisted versions when backed by database

- src/NuGetGallery.Core/Auditing/CloudAuditingService.cs
see: https://github.com/NuGet/Engineering/issues/495
Attaching original exception for access to the ExtendedErrorInformation.ErrorCode which may provide more insight into what the conflict was. I think it's unlikely to be BlobAlreadyExists, since that would imply the retry path due to ContainerNotFound.
> Preserve original 409/conflict exception for transient auditing issue

- src/NuGetGallery/Scripts/gallery/common.js
- src/NuGetGallery/Scripts/gallery/page-home.js
- src/NuGetGallery/Scripts/gallery/stats-dimensions.js
- src/NuGetGallery/Scripts/gallery/stats-perpackagestatsgraphs.js
- src/NuGetGallery/Views/Statistics/Index.cshtml
- src/NuGetGallery/Views/Statistics/PackageDownloadsByVersion.cshtml
- src/NuGetGallery/Views/Statistics/PackageDownloadsDetail.cshtml
- src/NuGetGallery/Views/Statistics/_LastUpdated.cshtml
- [Stray semicolon on the package statistics page #4189](https://github.com/NuGet/NuGetGallery/issues/4189)
- Removed Semicolon
- [[Redesign] Statistics Overview page Last Updated timestamp has no gutter #4180](https://github.com/NuGet/NuGetGallery/issues/4180)
- Removed encapsulating row
- [[Redesign] JavaScript Error on Statistic Page #4174](https://github.com/NuGet/NuGetGallery/issues/4174)
- Added a null check to js.
- [[Redesign][PackageStats]High download versions are losing digits on the chart. #4163](https://github.com/NuGet/NuGetGallery/issues/4163)
- Generalized and switched to better number parsing
- [[Redesign] package statistics - when all downloads are from unknown client - graph is empty …
> [Redesign]Small Fixes for StatisticsPages

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/base.less
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
- src/NuGetGallery/Views/Shared/Gallery/Footer.cshtml
> Make sure the footer release information does not wrap when the content is too long

- src/NuGetGallery/App_Code/ViewHelpers.cshtml
- src/NuGetGallery/Scripts/nugetgallery.js
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
https://github.com/NuGet/NuGetGallery/issues/4122
> Add outbound click event tracking for project URL, license URL, and manual download

- src/NuGetGallery/Services/PackageService.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
Fix for #4281
Note that this selects later version if multiple since order by is descending, whereas DisplayPackage history selects earlier version due to using First with order ascending.
Will file separate bug to fix IsLatest flags with reflow package, as well as trying to make selection of later latest consistent.
> Fix InvalidOperationException from profile when multiple version are set to latest

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/common-list-packages.less
- src/NuGetGallery/App_Start/AppActivator.cs
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Scripts/gallery/page-manage-packages.js
- src/NuGetGallery/ViewModels/ManagePackagesListViewModel.cs
- src/NuGetGallery/Views/Shared/_ListPackage.cshtml
- src/NuGetGallery/Views/Users/Packages.cshtml
- src/NuGetGallery/Views/Users/_UserPackagesList.cshtml
Note that the package controls ("edit package", "manage owners', etc) now appear on all the other package lists in the site if you are the owner of those packages, e.g.:
Packages list:
Profile:
@microsoftsam
> [Redesign] Manage Packages Page

- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Infrastructure/HttpStatusCodeWithServerWarningResult.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- tests/NuGetGallery.Facts/App.config
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/packages.config
Related to https://github.com/nuget/nugetgallery/issues/4215
> Add X-NuGet-Warning header to response when pushing SemVer2 package

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/RequestModels/VerifyPackageRequest.cs
- src/NuGetGallery/Views/Packages/VerifyPackage.cshtml
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
This PR is a proposal we can start working from. Awaiting final wording from @anangaur. 
I'd suggest to have the warning as close as possible to the submit button to ensure maximum visibility (people don't always read messages at the top of the page).
When a package has a semver2 version itself:
When a package has a non-semver2 version, but is considered semver2 due to a dependency declaration:
> Warn package authors when uploading a semver2 package through the web site

- tests/Scripts/RunP0Tests.bat
- tests/Scripts/RunP1Tests.bat
- tests/Scripts/RunP2Tests.bat
Fixes https://github.com/NuGet/Engineering/issues/548
> Fix trx output of functional tests not to override each other

- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/ViewModels/ConfirmationViewModel.cs
- src/NuGetGallery/Views/Users/Confirm.cshtml
- src/NuGetGallery/Views/Users/ConfirmationRequired.cshtml
- src/NuGetGallery/Views/Users/_ConfirmationResendForm.cshtml
Did some minor refactoring to the controller code because it expected the user to specify all of the `ConfirmationViewModel`'s fields manually instead of automatically populating them from a `User` ([this line, case in point](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Views/Users/ConfirmationRequired.cshtml#L4)).
The following pictures aren't all possible states, but they should be a good sampler of the possibilities.
@microsoftsam
> [Redesign] Email Confirmation

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/common-list-packages.less
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
- src/NuGetGallery/ViewModels/ListPackageItemViewModel.cs
- src/NuGetGallery/Views/Shared/_ListPackage.cshtml
- src/NuGetGallery/Views/Users/Profiles.cshtml
* Made Profile Picture appear before packages on mobile profile page
* Made package lists' statistics and management links flat on mobile
* Hid package icons on very narrow screens
* Fixed empty tag issue
Fixed #4173, #4185, and #4184
> [Redesign] Fix Several Package Listing Issues

- src/NuGetGallery/Scripts/gallery/stats-dimensions.js
- src/NuGetGallery/Views/Statistics/_PivotTable.cshtml
Addresses the following:
* Fix accessibilty of filter checkboxes on stats page (table -> div layout)
* Fix an issue with empty table cells
@joelverhagen @scottbommarito @loic-sharma @microsoftsam
> [Redesign]Fix accessibility on Stats Page

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/page-forgot-password.less
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
- src/NuGetGallery/Views/Users/ForgotPassword.cshtml
- src/NuGetGallery/Views/Users/PasswordSent.cshtml
This moves them to a 4-column layout with centered text to be consistent with #4252 
@microsoftsam
> [Redesign] Updated Forgot Password Pages' Column Layouts

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/common-list-packages.less
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
- src/NuGetGallery/Views/Shared/_ListPackage.cshtml
The global styling changes for h2 links (intended only for collapsible sections) broke the styling for package search and profile page by turning their links black. This change fixes that by removing the h2 around the link.
> [Redesign] Fixed link color on package search and profile page

- src/NuGetGallery/Services/PackageDeleteService.cs
- src/NuGetGallery/Services/PackageService.cs
- src/NuGetGallery/Services/ReflowPackageService.cs
- tests/NuGetGallery.Facts/Services/ReflowPackageServiceFacts.cs
See:
- https://github.com/NuGet/NuGetGallery/issues/4308
- https://github.com/NuGet/Engineering/issues/545
> Update reflow to update IsLatest state

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/all.less
- src/Bootstrap/less/theme/common-high-contrast.less
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
- src/NuGetGallery/Scripts/gallery/stats-perpackagestatsgraphs.js
Addresses the following:
* Text was invisible on high-contrast mode.
* [[Redesign] The word "downloads" hidden on package stats page #4154 ](https://github.com/NuGet/NuGetGallery/issues/4154)
@joelverhagen @skofman1 @microsoftsam @loic-sharma @scottbommarito
> [Redesign]Few Stats Chart fixes

- src/NuGetGallery/App_Start/OwinStartup.cs
- src/NuGetGallery/Configuration/AppConfiguration.cs
- src/NuGetGallery/Configuration/IAppConfiguration.cs
- src/NuGetGallery/Configuration/StringArrayConverter.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Web.config
- tests/NuGetGallery.FunctionalTests.Core/EnvironmentSettings.cs
- tests/NuGetGallery.FunctionalTests.Core/Helpers/UrlHelper.cs
- tests/NuGetGallery.FunctionalTests/Security/HttpToHttpsRedirectTests.cs
Fixes: https://github.com/NuGet/NuGetGallery/issues/4336
Noticed HttpToHttps functional tests don't run during deployment, so fixed it.
> Expose api/status with HTTP + fix functional tests

- src/NuGetGallery/Views/Packages/Delete.cshtml
Fixes: https://github.com/NuGet/NuGetGallery/issues/4323
> Fix: Choosing package list view trash icon leads to failure path

- src/NuGetGallery/Views/Users/ForgotPassword.cshtml
- src/NuGetGallery/Views/Users/PasswordSent.cshtml
- src/NuGetGallery/Views/Users/ResetPassword.cshtml
Made the forgot password and reset password pages be 6 columns when on small screen layouts.
Fixes #4252
> [Redesign] Made authentication pages' layout consistent

- src/NuGetGallery/Views/Packages/ReportAbuse.cshtml
Changed the report abuse form to hide the fields upon selecting the "bug/failed to install" as the reason. Fixes #4188
> [Redesign] Improve Report Abuse form

- src/Bootstrap/dist/css/bootstrap.css
- src/Bootstrap/less/variables.less
- src/NuGetGallery/Content/gallery/css/bootstrap.css
Fix https://github.com/NuGet/NuGetGallery/issues/4196
I chose to leave the gray buttons as-is.
Windows, normal constrast
High contrast
> [Redesign] Use a darker border for input fields so that high contrast on macOS is more usable

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/dist/css/bootstrap.css
- src/Bootstrap/less/dropdowns.less
- src/Bootstrap/less/theme/common-list-packages.less
- src/NuGetGallery/App_Code/ViewHelpers.cshtml
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
- src/NuGetGallery/Content/gallery/css/bootstrap.css
- src/NuGetGallery/Views/Packages/ManagePackageOwners.cshtml
- src/NuGetGallery/Views/Packages/ReportAbuse.cshtml
- src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
- src/NuGetGallery/Views/Shared/_ListPackage.cshtml
- src/NuGetGallery/Views/Users/Profiles.cshtml
Fixes the following issues:
* Increases space between account dropdown menu entries from 6px to 10px
* Added separator between API Keys and Manage Packges on account dropdown menu
* Fixed spacing issue where the manage package links increased a package's bottom margin on search/profile page.
* Fixed column layout of profile page (packages are now 9 columns, profile aside is 3 columns)
* Fixed link styling to remove a package owner
* Removed toggles on Report Abuse page
> [Redesign] Address PM pass redesign issues (loshar)

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/base.less
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
- src/NuGetGallery/Views/Statistics/Index.cshtml
- src/NuGetGallery/Views/Statistics/_PivotTable.cshtml
* Limits client usage chart to Most recent 15 versions to prevent overlapping of labels. The entire information is still available via table.
* Add a new selector to hide elements at 480px threshold. Used to hide charts on package stats page when page width becomes too small.
Should address:
[Redesign] Text cut off on the chart on the statistics page in Edge #4140
[Redesign] Package Statistics / Package Version Statistics page looks odd with small window #4190
@joelverhagen @scottbommarito @loic-sharma
> [Redesign] More Stats chart fixes

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/page-statistics-per-package.less
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
- src/NuGetGallery/Views/Statistics/_PivotTable.cshtml
Switch loading spinner from an svg to a div with border.
This is due to an issue where svg's cannot be animated through css in Edge/IE.
See https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8487752/
Addresses:
[Redesign] Spinning loading indicator does not spin in Edge #4150
@joelverhagen @agr
> [Redesign]Fix loading Spinner in Edge/IE

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/page-statistics-overview.less
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
- src/NuGetGallery/Views/Statistics/Index.cshtml
Add ability for columns to hide content with ellipsis when narrow screen.
Addresses:
[Redesign] Statistics overview page Version Downloads graph with small window cuts off data #4176
@joelverhagen @scottbommarito
> [Redesign]Add Column content overflow

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/page-statistics-per-package.less
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
- src/NuGetGallery/Scripts/gallery/page-edit.js
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- src/NuGetGallery/Views/Shared/_ListPackage.cshtml
[Redesign] Statistics page - top client name appears cut-off #4416
[Redesign] Package page - versions list "show less" doesn't have a tab stop #4417
[Redesign] Horizontal rule at the top of the packages page is narrower than the others #4425
[Redesign] Package edit - submit-button enabled only by focus change #4418
@joelverhagen
> [Redesign]Few Small fixes

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/common-list-packages.less
- src/Bootstrap/less/theme/page-display-package.less
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
- src/NuGetGallery/Views/Packages/Delete.cshtml
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- src/NuGetGallery/Views/Packages/Edit.cshtml
- src/NuGetGallery/Views/Packages/ManagePackageOwners.cshtml
- src/NuGetGallery/Views/Shared/_ListPackage.cshtml
Address https://github.com/NuGet/NuGetGallery/issues/4413.
Top of package details page:
Search result:
> [Redesign] Make package ID more prominent than package title (but still keep title visible)

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/common-list-packages.less
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
Fix https://github.com/NuGet/NuGetGallery/issues/4421.
Before:
After:
> [Redesign] Make the package list more compact

- src/NuGetGallery.Core/Cookies/CookieComplianceServiceBase.cs
- src/NuGetGallery.Core/Cookies/CookieConsentMessage.cs
- src/NuGetGallery.Core/Cookies/ICookieComplianceService.cs
- src/NuGetGallery.Core/Cookies/NullCookieComplianceService.cs
- src/NuGetGallery.Core/CoreStrings.Designer.cs
- src/NuGetGallery.Core/CoreStrings.resx
- src/NuGetGallery.Core/Diagnostics/IDiagnosticsService.cs
- src/NuGetGallery.Core/Diagnostics/IDiagnosticsSource.cs
- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery.Core/Properties/AssemblyInfo.cs
- src/NuGetGallery/App_Code/ViewHelpers.cshtml
- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/Configuration/AppConfiguration.cs
- src/NuGetGallery/Configuration/IAppConfiguration.cs
- src/NuGetGallery/Content/Layout.css
- src/NuGetGallery/Controllers/NuGetContext.cs
- src/NuGetGallery/Diagnostics/DiagnosticsServiceExtensions.cs
- src/NuGetGallery/Diagnostics/DiagnosticsSourceExtensions.cs
- src/NuGetGallery/Diagnostics/NullDiagnosticsSource.cs
- src/NuGetGallery/Diagnostics/TraceDiagnosticsSource.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Properties/AssemblyInfo.cs
- src/NuGetGallery/Views/NuGetViewBase.cs
- src/NuGetGallery/Views/Shared/Layout.cshtml
- src/NuGetGallery/Web.config
- tests/NuGetGallery.Core.Facts/Cookies/CookieComplianceServiceBaseFacts.cs
- tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj
There will be 3 PRs altogether: Gallery, Shims, Deployment
When shim is deployed, banner will display if client IP is from region which requires it. Message indicates that user gives consent if they continue to navigate, and does not include any buttons. Provided JS detects and sets consent cookie if user clicks on any non-external links, which automatically closes the banner.
I've verified the banner locally, by spoofing the consent status. I've verified AI logs in DEV, but am not able to test the banner there yet since domain isn't enabled. Will see if there's a way to enable this.
Note:
- Onus is on us to monitor logs and report if service isn't working.
- API includes 'fire and forget' background refresh; with initial refresh done when service is created (see …
> Adding support for EU cookie compliance

- src/NuGetGallery/Views/Users/Account.cshtml
Fixes this: https://github.com/NuGet/Engineering/issues/622
> Fix password autocomplete

- src/NuGetGallery/Views/Statistics/Index.cshtml
Addresses the following issue:
[Redesign] Stats page crashes when there are no client versions #4464
Skips rendering of components that break if we don't have data.
@joelverhagen
> [Redesign] Hide charts if data to display isn't there.

- src/NuGetGallery/Views/Statistics/Index.cshtml
Addresses issue https://github.com/NuGet/NuGetGallery/issues/4450
The problem was that when the svg was being generated, the floating point numbers were being rendered with commas as decimal separators, which SVG render didn't understand.
Fix was to make this part of rendering culture invariant.
@joelverhagen
> [Redesign]Make svg render culture invariant.

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/all.less
- src/Bootstrap/less/theme/common-user-package-list.less
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/Views/Users/_UserPackagesList.cshtml
Make manage package page more compact through horizontal layout.
First part of addressing https://github.com/NuGet/NuGetGallery/issues/4431
@joelverhagen @jonwchu 
Preview:
> [Redesign]Update Manage Packages to be more compact.

- src/NuGetGallery/Views/Packages/UploadPackage.cshtml
- src/NuGetGallery/Views/Packages/_EditMetadata.cshtml
- src/NuGetGallery/Views/Statistics/_PivotTable.cshtml
Addresses the Following:
- 467730: "Browse" Button is not accessible using keyboard in "Upload your package" page. 
- Made Browse button have a tab stop. Added a hook to enter and space keys to trigger the file dialog.
- 469489: Name property value is null for all the edit field  present in "Upload your package" page.
- Added an aria-label. Hooked up the labels to the proper input boxes.
- 470353: Keyboard focus is going to invisible elements in View full status package page. 
- Removed the offending element. It wasn't supposed to be there.
@joelverhagen @microsoftsam @jonwchu
> [Redesign]Addressing some more Accessibility issues

- src/NuGetGallery/App_Code/ViewHelpers.cshtml
- src/NuGetGallery/Views/Packages/_EditMetadata.cshtml
Fixes a small issue with the alert dialogs that was causing them to not be able to have their content read out by screen readers.
@joelverhagen @microsoftsam
> [Redesign]Fix structure of alerts for screen-readers

- src/NuGetGallery/App_Start/Routes.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Helpers/ReadMeHelper.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/RequestModels/EditPackageVersionRequest.cs
- src/NuGetGallery/RequestModels/ReadMeRequest.cs
- src/NuGetGallery/RouteNames.cs
- src/NuGetGallery/Scripts/gallery/async-file-upload.js
- src/NuGetGallery/Scripts/gallery/page-edit.js
- src/NuGetGallery/Services/IPackageFileService.cs
- src/NuGetGallery/Services/PackageFileService.cs
- src/NuGetGallery/Views/Packages/_EditMetadata.cshtml
- src/NuGetGallery/packages.config
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Services/PackageFileServiceFacts.cs
@fayrose @laurenshen @JarahSi 
Changes include:
- Post-rebase fixes for upload E2E (cherry-picked from feature-nuggets)
- Allow HTML input for written README
- Use HtmlSanitizer after MD conversion to protect against XSS
- Edit E2E fixes
> Upload README html sanitization and E2E fixes

- src/Bootstrap/dist/css/bootstrap.css
- src/Bootstrap/less/component-animations.less
- src/NuGetGallery/Constants.cs
- src/NuGetGallery/Content/gallery/css/bootstrap.css
- src/NuGetGallery/Scripts/gallery/common.js
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- Remove transition CSS from .collapsing class since the transition time is 0 in the JS
- This was causing weirdness in Edge.
- Automatically expand the version list if the selected version is in the collapsed section
- Fix ctrl + click on data-track links
> [Redesign] Address three points of feedback from the survey

- src/NuGetGallery/App_Code/ViewHelpers.cshtml
- src/NuGetGallery/Areas/Admin/Controllers/LuceneController.cs
- src/NuGetGallery/Areas/Admin/Controllers/SecurityPolicyController.cs
- src/NuGetGallery/Areas/Admin/Controllers/SupportRequestController.cs
- src/NuGetGallery/Areas/Admin/Views/Lucene/Index.cshtml
- src/NuGetGallery/Areas/Admin/Views/SecurityPolicy/Index.cshtml
- src/NuGetGallery/Areas/Admin/Views/SupportRequest/Admins.cshtml
- src/NuGetGallery/Areas/Admin/Views/SupportRequest/Index.cshtml
- src/NuGetGallery/Controllers/CuratedPackagesController.cs
- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/Scripts/nugetgallery.js
- src/NuGetGallery/Scripts/supportrequests.js
- src/NuGetGallery/Views/CuratedFeeds/CuratedFeed.cshtml
- src/NuGetGallery/Views/Packages/ManagePackageOwners.cshtml
- tests/NuGetGallery.Facts/Controllers/ControllerTests.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
Mostly admin routes.
These include
- LuceneController
- SupportRequestController
- SecurityPolicyController
- CuratedPackagesController
- UsersController
https://github.com/NuGet/Engineering/issues/638
> Add AntiForgery tokens to some actions that were missing them

- src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
- tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs
It should consider the oldest package version instead of the lowest version.
> Fix #4513: avg download count calculated incorrectly.

- src/NuGetGallery/ViewModels/StatisticsPackagesViewModel.cs
Previously this was using a locale-unaware format `MM/dd/yy`.
Fix https://github.com/NuGet/NuGetGallery/issues/4529
> Use date format "d" for week start and ends on the stat pages

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/common-user-package-list.less
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
- src/NuGetGallery/Views/Users/_UserPackagesList.cshtml
1. Allow long IDs to wrap on the manage packages package
1. Don't let the package controls to wrap unless screen size is xs
1. Hide images on xs
1. Allow browser to control column widths
Fix https://github.com/NuGet/NuGetGallery/issues/4527
Normal display:
Long IDs simulated by displaying `ID + ID`:
> Improve manage package page handling of long IDs

- src/NuGetGallery/Scripts/gallery/common.js
`datetime.format("l")` always assumes English culture. Instead, fall back to the server side render.
> Don't use moment.js for absolute date formatting since it is not culture aware

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/base.less
- src/Bootstrap/less/theme/page-display-package.less
- src/NuGetGallery/App_Code/ViewHelpers.cshtml
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
- src/NuGetGallery/Views/Packages/UploadPackage.cshtml
- src/NuGetGallery/Views/Shared/_ListPackage.cshtml
1. Enable "enter" key press on Upload button
1. Make selected package command tab apparent on high-contrast Firefox
1. Add `icon-text` class for text with an icon that is NOT a link (`icon-link` has other undesired rules)
Fix accessibility issue 470376
Fix accessibility issue 476608
> Fix two accessibility issues and fix hover underline on alerts

- src/NuGetGallery/Authentication/AuthenticationService.cs
- src/NuGetGallery/Authentication/PasswordResetResult.cs
- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
I'm only submitting this PR because the work was already done on my devbox. It should have no functional different from @loic-sharma's https://github.com/NuGet/NuGetGallery/pull/4551 aside from a clarified message to the user. I poorly communicated my intent to fix issue https://github.com/NuGet/NuGetGallery/issues/4548.
There are three potential outcomes from this reset flow:
1. Success (the user exists and is confirmed)
1. User not found
1. User not confirmed (the user exists but has not confirmed his email)
I have added a type to clearly represent these three states. In general we should not be using exceptions as non-exceptional signals. Additionally, null is ambiguous signal in many cases so it should be avoided especially in a tri(/N)-state outcomes like this.
> Introduce a type to represent the different password reset results (instead of null and exceptions)

- src/NuGetGallery.Core/Auditing/CloudAuditingService.cs
- src/NuGetGallery.Core/ICloudStorageStatusDependency.cs
- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/App_Start/StorageDependent.cs
- src/NuGetGallery/Configuration/AppConfiguration.cs
- src/NuGetGallery/Configuration/IAppConfiguration.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/CloudBlobFileStorageService.cs
- src/NuGetGallery/Services/CloudReportService.cs
- src/NuGetGallery/Services/StatusService.cs
- src/NuGetGallery/Web.config
- tests/NuGetGallery.Facts/App_Start/StorageDependentFacts.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
Replaced configuration `Gallery.AzureStorageConnectionString` with new variables:
- `Gallery.AzureStorage.Auditing.ConnectionString`
- `Gallery.AzureStorage.Content.ConnectionString`
- `Gallery.AzureStorage.Errors.ConnectionString`
- `Gallery.AzureStorage.NuGetExe.ConnectionString`
- `Gallery.AzureStorage.Packages.ConnectionString`
- `Gallery.AzureStorage.Statistics.ConnectionString`
- `Gallery.AzureStorage.Uploads.ConnectionString`
Why the dots in the configuration name? I think the proper mental model here is that each storage purpose (e.g. `Errors`) may eventually have additional properties. For example, the `Gallery.AzureStorageReadAccessGeoRedundant` setting could become account-specific or we could configure the table/container name that `Uploads` go into (for example). For that …
> Add storage connection strings for each distinct purpose in the gallery

- src/NuGetGallery/Web.config
https://github.com/NuGet/Engineering/issues/695
Tested locally by generating a cert for preview.nuget.org and www.nuget.org and adding a host file entry for these two names pointing to localhost.
> Redirect preview.nuget.org to www.nuget.org

- src/NuGetGallery/Views/Pages/Home.cshtml
- src/NuGetGallery/Views/Shared/_SearchBar.cshtml
Fix https://github.com/NuGet/NuGetGallery/issues/4575
/cc @microsoftsam - what are your thoughts on the accessibility here? The only drawback I can think of is inconsistent tab start point:
- Home page: first <kbd>Tab</kbd> goes to the search button.
- All other pages: first <kbd>Tab</kbd> goes to logo in navbar.
The tab sequence is the same, but the start point is now different.
All pages still focus the search bar when you start typing (including the home page).
> Autofocus the search bar on the front page

- src/NuGetGallery/Infrastructure/Lucene/ExternalSearchService.cs
Missed adding the `IsVerified` flag to the search results in the external search service in the previous PR.
> [Prefix]Fix external search service to reflect the verified flag

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/page-display-package.less
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Scripts/gallery/page-display-package.js
- src/NuGetGallery/ViewModels/PackageManagerViewModel.cs
- src/NuGetGallery/ViewModels/ThirdPartyPackageManagerViewModel.cs
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Fixes #4589. Note that this doesn't actually add any third-party tabs, it simply adds the necessary styling to support third-party tabs. This [gist](https://gist.github.com/loic-sharma/43ac56a07d59cea430fb658a5961cad5) shows the necessary changes needed to add Paket.
> Add support for third-party tabs on package details page

- src/NuGetGallery/Services/FormsAuthenticationService.cs
- src/NuGetGallery/Services/IFormsAuthenticationService.cs
We now always force SSL (if set up in configuration). So no need to have code specific for the authentication.
Addresses #4132.
> Drop everything related to the ForceSSL cookie.

- src/NuGetGallery/Views/Shared/ListPackages.cshtml
Based on the idea posted here: https://github.com/NuGet/NuGetGallery/issues/782 
Maybe the issue then already solved that way - nothing to fancy. It should look like this:
The link points to this location:
https://docs.microsoft.com/nuget/consume-packages/finding-and-choosing-packages#search-syntax
> Adding a search hint if query results in no items

- src/NuGetGallery/Controllers/AppController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- tests/NuGetGallery.Facts/Controllers/AppControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
Fixes https://github.com/NuGet/NuGetGallery/issues/4597.
> Use JsonRequestBehavior.AllowGet on endpoints that both return JSON and support GET

- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/Configuration/ConfigurationService.cs
- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/AuthenticationController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Services/ReportPackageRequest.cs
- src/NuGetGallery/UrlExtensions.cs
- src/NuGetGallery/Views/Authentication/Register.cshtml
- src/NuGetGallery/Views/Authentication/SignIn.cshtml
- src/NuGetGallery/Views/Authentication/_Register.cshtml
- src/NuGetGallery/Views/CuratedFeeds/CuratedFeed.cshtml
- src/NuGetGallery/Views/Packages/Delete.cshtml
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- src/NuGetGallery/Views/Packages/ManagePackageOwners.cshtml
- src/NuGetGallery/Views/Packages/ReportAbuse.cshtml
- src/NuGetGallery/Views/Packages/UploadPackage.cshtml
- src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
- src/NuGetGallery/Views/Shared/LayoutFooter.cshtml
- src/NuGetGallery/Views/Shared/SiteMenu.cshtml
- src/NuGetGallery/Views/Shared/UserDisplay.cshtml
- src/NuGetGallery/Views/Statistics/PackageDownloadsByVersion.cshtml
- src/NuGetGallery/Views/Statistics/PackageDownloadsDetail.cshtml
- src/NuGetGallery/Views/Users/Account.cshtml
- tests/NuGetGallery.Facts/App_Start/ConfigurationServiceFacts.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/TestUtils/TestUtility.cs
- tests/NuGetGallery.Facts/Views/UrlHelperFacts.cs
When having a proxy in front of the gallery deployment, the gallery currently generates hyperlinks (e.g. in emails, UI, ...) that use the deployment host name instead of the proxy's.
This fix leverages the `SiteRoot` config setting instead of the resolved host name of the deployment's environment.
> Use SiteRoot config setting for generated URLs

- src/NuGetGallery/Controllers/JsonApiController.cs
- src/NuGetGallery/UrlExtensions.cs
- tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs
- tests/NuGetGallery.Facts/Authentication/AuthenticatorFacts.cs
- tests/NuGetGallery.Facts/Authentication/Providers/ApiKey/ApiKeyAuthenticationHandlerFacts.cs
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/JsonApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/StatisticsControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
- tests/NuGetGallery.Facts/Filters/RequiresAccountConfirmationAttributeFacts.cs
- tests/NuGetGallery.Facts/Framework/Fakes.cs
- tests/NuGetGallery.Facts/Framework/TestContainer.cs
- tests/NuGetGallery.Facts/Framework/TestGalleryConfigurationService.cs
- tests/NuGetGallery.Facts/Framework/UnitTestBindings.cs
- tests/NuGetGallery.Facts/Services/MessageServiceFacts.cs
- tests/NuGetGallery.Facts/TestUtils/TestUtility.cs
This PR contains various fixes in NuGetGallery test infrastructure, which surface now as the gallery is checking for the `Gallery.SiteRoot` config setting. In other words: test routing and config setup must reflect a real possible scenario. 
In addition, `FormatException` were thrown due to invalid, dummy values for e-mail fields, as well as `NullReferenceException` due to service mocks that did not have all dependencies injected.
Tests are now more consistent:
* `Gallery.SiteRoot` = "http://localhost/"
* `IAppConfiguration.RequireSSL` = "true"
* all requests are HTTPS, assertions assume HTTPS (unless otherwise specified)
* we target fewer service mocks, more real implementations
> Fix and consolidate routing in NuGetGallery unit test configurations.

- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Revised PR that replaces #4437 to add support for Paket as a third-party NuGet client.
> Add support for Paket CLI.

- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/AuthenticationController.cs
- src/NuGetGallery/Controllers/JsonApiController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/Filters/RequiresAccountConfirmationAttribute.cs
- src/NuGetGallery/Services/ReportPackageRequest.cs
- src/NuGetGallery/UrlExtensions.cs
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
Follow-up PR for https://github.com/NuGet/NuGetGallery/pull/4661.
The change to rely on the `Gallery.SiteRoot` config setting had the side-effect of no longer returning any relative URLs. This broke some functional tests that relied on the assumption that these URLs were relative. As the `Gallery.SiteRoot` setting is the same for both staging and production slots in any environment, this became a hard to solve problem. Properly using relative URLs (and absolute ones where applicable, e.g. in outbound e-mails) fixes this and works around the test infrastructure complexity.
> Properly generate relative/absolute URLs.

- src/NuGetGallery/App_Code/ViewHelpers.cshtml
- src/NuGetGallery/Views/Shared/Gallery/Footer.cshtml
A previous PR removed all build information from the footer.
This PR adds it back as a comment so the visuals are not affected, but the information is still there.
It will be added to the bottom of the source as a comment
@joelverhagen @karann-msft @skofman1
> Re-add build information to footer

- src/NuGetGallery/Views/Packages/_EditMetadata.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/4614
The old check always failed because DependencySets was a object and didn't have a length property.
@joelverhagen @jonwchu
> Fix an issue with a check on dependency set length that always failed.

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/page-display-package.less
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Made the height of first-party vs third-party tabs consistent.
First-party tab (there is 37 more pixels of space below the tab):
Third-party tab (no changes here):
> Improve Third-Party Installation Tabs' UI

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/base.less
- src/Bootstrap/less/theme/common-list-packages.less
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
Fix https://github.com/NuGet/NuGetGallery/issues/4676.
`break-all` breaks in the middle of words. Instead use the different `break-word` forms (for maximum browser compatibility).
More details here:
https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/
Tested:
1. All browsers (Edge, IE, Firefox, Chrome)
1. Search results page and display page page
1. Long ID
1. Long Title
1. Long description
1. Long version
1. Small windows
> Fix improper word breaking in long text fields

- src/NuGetGallery/Services/ReservedNamespaceService.cs
- tests/NuGetGallery.Facts/Services/ReservedNamespaceServiceFacts.cs
There was a bug which would mark all package registrations under an owner which started with the reserved prefix even if the prefix is an absolute namespace.
This fixes it, plus added test.
> [Prefix] Fix the bug with absolute namespace reservation for an owner

- src/NuGetGallery/Controllers/PackagesController.cs
Adding model validation to VerifyPackage, same as done for Edit
Issue is #4706. Note that Edit/Upload currently would require refresh on validation errors because handleErrors does a bindData(null). Isn't ideal, but leaving as-is because:
- Upload uses single error handler for cancel, submit, upload failure
- Upload/Edit form is long, so it's not apparent that validation failed unless user scrolls up
> Add model validation for package upload

- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs
Related to  #4619 and #4709 
"A newer prerelease version is available" should also be shown when currently displayed version is a prerelease.
Thus far, this was not the case. 
However, it seems more logical to me to also show it in this scenario.
Example: https://int.nugettest.org/packages/SemVer2MetadataTestPackage/1.2.0-alpha
> "A newer prerelease version is available" should also be shown when currently displayed version is a prerelease

- src/NuGetGallery/NuGetGallery.csproj
This was a file I used to have but got rid of. Not sure why VS and local build doesn't fail/alert on this, but it fails on the build machines.
> Fix "OwnerRequests.cshtml could not be found"

- src/NuGetGallery.Core/CoreConstants.cs
- src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs
- src/NuGetGallery.Core/Services/CorePackageFileService.cs
- src/NuGetGallery.Core/Services/ICorePackageFileService.cs
- tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceFacts.cs
- tests/NuGetGallery.Core.Facts/Services/CorePackageFileServiceFacts.cs
Depends on https://github.com/NuGet/NuGetGallery/pull/4759.
This introduces a new private container which is a sibling to the existing `packages` container. The file name pattern is the same as the packages container. The reason I did this is that currently we are using the file storage service to synchronously (with respect to push) reject cases where `{id}.{version}.nupkg` collides with another package. If a package is pushed into the `validation` container, we should still detect this case synchronously instead of having the collision occur asychronously and beyond the user's control. When we move `packages` to a better format, then we can do the same with `validation`.
These APIs will be called by gallery (save) and orchestrator (download and delete).
> Add APIs to upload, download, and delete a package from the validation container

- src/NuGetGallery/UrlExtensions.cs
- tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
Don't rewrite return URL when linking external accounts, as it likely breaks MSA/AAD state during auth.
> Do not rewrite return URL for MSA/AAD auth

- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Services/IPackageUploadService.cs
- src/NuGetGallery/Services/PackageUploadService.cs
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs
Right now, `ApiController` and `PackagesController` both have the logic where we reliably write to `packages` container and to the database whilst still handling failures. This logic is duplicated.
I have moved this logic to `IPackageUploadService.CommitPackageAsync`. Right now, this is just a refactoring but the goal in a subsequent PR is to write (and delete in failure cases) packages to the `validating` container if the package has `PackageStatus.Validating`. Otherwise, existing behavior is maintained.
Progress on https://github.com/NuGet/NuGetGallery/issues/4646.
> Move package commit logic to IPackageUploadService

- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/packages.config
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/packages.config
The current dependency is prerelease and unsigned. The API surface area and implementation has not changed at all.
> Update NuGet.Services.Validation to 2.3.0 (stable, signed)

- src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs
- src/NuGetGallery.Core/Services/CorePackageFileService.cs
- src/NuGetGallery.Core/Services/ICoreFileStorageService.cs
- src/NuGetGallery.Core/Services/ICorePackageFileService.cs
- src/NuGetGallery.Core/Services/ISimpleCloudBlob.cs
- src/NuGetGallery/Services/CloudBlobFileStorageService.cs
- src/NuGetGallery/Services/CloudBlobWrapper.cs
- src/NuGetGallery/Services/FileSystemFileStorageService.cs
- tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceFacts.cs
- tests/NuGetGallery.Core.Facts/Services/CorePackageFileServiceFacts.cs
Need a URI to an uploaded package for the validation orchestrator to know how to obtain the file to validate.
This change implements SAS-enabled URI generation for the cloud storage, the local file storage leaves it not implemented.
> File storage read URI generation

- src/NuGetGallery/Web.config
Fixes https://github.com/NuGet/NuGetGallery/issues/4793
This is a regression introduced by https://github.com/NuGet/NuGetGallery/commit/f08ce16bb524666add5a961f84574562af7ae763
We never had custom pages for 400 errors.
> Disable custom pages for 400 errors

- src/NuGetGallery/Areas/Admin/AdminAreaRegistration.cs
- src/NuGetGallery/Areas/Admin/Controllers/DeleteController.cs
- src/NuGetGallery/UrlExtensions.cs
Fix https://github.com/NuGet/NuGetGallery/issues/4786.
/cc @xavierdecoster, could you approve this one? You've been doing a lot of work in this area.
/cc @loic-sharma, we talked about this before. I dug into the code via ILSpy and read online. Looks like always specifying the empty area is the right move.
> Specify the empty string area in UrlExtensions unless otherwise specified

- src/NuGetGallery/Controllers/ODataV1FeedController.cs
- src/NuGetGallery/Controllers/ODataV2CuratedFeedController.cs
- src/NuGetGallery/Controllers/ODataV2FeedController.cs
- tests/NuGetGallery.Facts/Controllers/ODataV1FeedControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/ODataV2CuratedFeedControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/ODataV2FeedControllerFacts.cs
Fix https://github.com/NuGet/NuGetGallery/issues/4760. AI clearly shows many 404s on this endpoint for the past 90 days.
This has been broken since https://github.com/NuGet/NuGetGallery/commit/3f92c55e42f2905dd415a8bb765fe4adef714c5a (circa February, 2016). We simply forgot to add the `Count` methods required for this to work.
> Add missing FindPackagesById()/$count endpoints

- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/App_Start/StorageDependent.cs
Addresses https://github.com/NuGet/NuGetGallery/issues/4753
Adds a new property so we can tell if a storageDependent is supposed to be a SingleInstance or not.
@joelverhagen @skofman1
> Fix caching of static files.

- tests/NuGetGallery.FunctionalTests.Core/EnvironmentSettings.cs
- tests/NuGetGallery.WebUITests.P0/BasicPages/BrandingValidationTest.cs
- tests/NuGetGallery.WebUITests.P0/NuGetGallery.WebUITests.P0.csproj
Addresses https://github.com/NuGet/NuGetGallery/issues/4714
Adds a configurable functional test for customized branding.
Falls back to default branding if no custom options are used.
@joelverhagen @skofman1 @shishirx34
> Add branding test

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/RequestModels/EditPackageRequest.cs
- src/NuGetGallery/ViewModels/DeletePackageViewModel.cs
- src/NuGetGallery/Views/Packages/Delete.cshtml
- src/NuGetGallery/Views/Packages/Edit.cshtml
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
Fixes #4756 
Show normalized version (incl metadata) in edit package dropdown.
Fix semver2 package edit navigation (URLs must always use normalized version).
> Show normalized version (incl metadata) in edit/delete package dropdown.

- src/NuGetGallery.Core/Auditing/AuditActor.cs
- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/Authentication/NuGetClaims.cs
- src/NuGetGallery/Authentication/Providers/ApiKey/ApiKeyAuthenticationHandler.cs
- src/NuGetGallery/Helpers/AuditingHelper.cs
- src/NuGetGallery/NuGetGallery.csproj
- tests/NuGetGallery.Core.Facts/Auditing/AuditActorTests.cs
- tests/NuGetGallery.Core.Facts/Auditing/AuditEntryTests.cs
- tests/NuGetGallery.Core.Facts/Auditing/FileSystemAuditingServiceTests.cs
- tests/NuGetGallery.Facts/Helpers/AuditingHelperFacts.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
Moved some of the AuditActor creation code from NuGetGallery.Core to NuGetGallery to allow usage of NuGetClaims.
Let me know if this looks good, and I will apply changes to Shims.
> Added credential key to AuditActor

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/base.less
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
- src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
- src/NuGetGallery/Views/Shared/Gallery/Layout.cshtml
Page view on load:
Page View on First tab
This element is only reachable by tab navigation.
@joelverhagen @skofman1 @xavierdecoster
> Add a hidden skip to content link.

- src/NuGetGallery/Helpers/HttpContextBaseExtensions.cs
- src/NuGetGallery/Services/TelemetryService.cs
- src/NuGetGallery/Telemetry/ClientInformationTelemetryEnricher.cs
- tests/NuGetGallery.Facts/HttpContextBaseExtensionsFacts.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/Telemetry/ClientInformationTelemetryEnricherTests.cs
Extracts client information from user agent and logs on push/verify id events.
https://github.com/NuGet/Engineering/issues/797
> Log product information on push+verify events

- src/NuGetGallery.Core/Entities/IEntityRepository.cs
- src/NuGetGallery/App_Start/AppActivator.cs
- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/Areas/Admin/Controllers/HomeController.cs
- src/NuGetGallery/Areas/Admin/Controllers/ValidationController.cs
- src/NuGetGallery/Areas/Admin/Models/DeletedStatus.cs
- src/NuGetGallery/Areas/Admin/Services/ValidationAdminService.cs
- src/NuGetGallery/Areas/Admin/Services/ValidationEntityRepository.cs
- src/NuGetGallery/Areas/Admin/ViewModels/HomeViewModel.cs
- src/NuGetGallery/Areas/Admin/ViewModels/PackageValidationViewModel.cs
- src/NuGetGallery/Areas/Admin/ViewModels/ValidationPageViewModel.cs
- src/NuGetGallery/Areas/Admin/Views/Home/Index.cshtml
- src/NuGetGallery/Areas/Admin/Views/Validation/Index.cshtml
- src/NuGetGallery/Configuration/AppConfiguration.cs
- src/NuGetGallery/Configuration/IAppConfiguration.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/UrlExtensions.cs
- src/NuGetGallery/Web.config
- tests/NuGetGallery.Facts/Areas/Admin/Services/ValidationAdminServiceFacts.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
https://github.com/NuGet/NuGetGallery/issues/4653
> Add UI for validation tables (just orchestrator tables)

- src/NuGetGallery/Scripts/gallery/page-manage-owners.js
- src/NuGetGallery/ViewModels/ManagePackageOwnersViewModel.cs
- src/NuGetGallery/Views/Packages/ManagePackageOwners.cshtml
Fixes a bug with prefix ownership management changes, where admin was not able to delete owners owning namespaces.
> Allow admin to delete all owners

- src/NuGetGallery/Services/PackageOwnerRequestService.cs
- src/NuGetGallery/ViewModels/OwnerRequestsListItemViewModel.cs
- src/NuGetGallery/ViewModels/OwnerRequestsListViewModel.cs
The EF queries for retrieving `PackageOwnerRequest` did not include the `PackageRegistration` relationship, which the view models now seem to rely on.
cc @scottbommarito
> Fix NullReferenceException on GET Users/Packages

- src/NuGetGallery/App_Start/AppActivator.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Scripts/gallery/clamp.js
- src/NuGetGallery/Scripts/gallery/page-display-package.js
- src/NuGetGallery/Services/IReadMeService.cs
- src/NuGetGallery/Services/ReadMeService.cs
- src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Fixes #4812 and #4770 
This revives the client-side clamping from @JarahSi. I've disabled the native (-webkit-line-clamp) support due to formatting issues possibly caused by conflicts with the redesign css. Instead, it does javascript clamping which adjusts the max height.
> Documentation clamp fixes

- src/NuGetGallery/App_Start/AppActivator.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Scripts/gallery/clamp.js
- src/NuGetGallery/Scripts/gallery/page-display-package.js
- src/NuGetGallery/Services/IReadMeService.cs
- src/NuGetGallery/Services/ReadMeService.cs
- src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Services/ReadMeServiceFacts.cs
Fixes #4783 and #4816, plus restricts markdown links to http/s
> Documentation parser fixes

- src/NuGetGallery.Core/Auditing/AuditedPackageAction.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/UrlExtensions.cs
- src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
- src/NuGetGallery/ViewModels/ListPackageItemViewModel.cs
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- tests/NuGetGallery.Core.Facts/Auditing/AuditedPackageActionTests.cs
Fixes https://github.com/NuGet/NuGetGallery/issues/4788 (see issue for details)
> Get rid of obsolete notifications on package details view

- src/NuGetGallery/Scripts/gallery/stats-perpackagestatsgraphs.js
Update number shortener to maintain enough sig figs for distinction.
Addresses https://github.com/NuGet/NuGetGallery/issues/4811
Before:
After:
> Fix graph labels on statistics

- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
Fix for Gallery deadlocking when run with async validaitons enabled in dev environment.
> Slightly different way to initialize service bus topic client wrapper

- src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
- tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs
> Do not consider unlisted prerelease versions when showing "newer prerelease available" message.

- src/NuGetGallery.Core/Services/CorePackageFileService.cs
- src/NuGetGallery.Core/Services/ICorePackageFileService.cs
- tests/NuGetGallery.Core.Facts/Services/CorePackageFileServiceFacts.cs
Validation.Orchestrator needs a way to get public package URL, too (for the revalidation case when we don't have a package in validation container, also needed for the non-blocking validation case).
Also, methods that check for package file existence would allow to figure out where package file is located on Orchestrator side without trying to download either file.
> Pakage URL generation method and checks whether package file exists

- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Views/Shared/_ListPackage.cshtml
Also turned on MvcBuildViews compilation by default, so Visual Studio fails the build when this happens in the future. (It was already enabled in our build scripts.)
> Fix permission-related renaming issue

- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
I believe this should fix it. Haven't tested, as I'm not sure how to run Owin hosted locally. If anyone knows, please let me know :-)
```
[NullReferenceException: Object reference not set to an instance of an object.]
NuGetGallery.<>c__DisplayClass4_1.<Configuration>b__2(ITelemetryProcessor next) in C:\vsts-agent\_work\3\s\src\Gallery\submodules\Gallery\src\NuGetGallery\App_Start\OwinStartup.cs:84
Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChainBuilder.Build() +231
NuGetGallery.OwinStartup.Configuration(IAppBuilder app) in C:\vsts-agent\_work\3\s\src\Gallery\submodules\Gallery\src\NuGetGallery\App_Start\OwinStartup.cs:83
[TargetInvocationException: Exception has been thrown by the target of an invocation.]
System.RuntimeMethodHandle.InvokeMethod(Object …
```
> OwinStartup NullRef fix

- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/packages.config
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/packages.config
Need the latest version of the NuGet.Services.Validation to be able to properly send ServiceBus messages from Gallery to the Orchestrator.
Tested in dev.
> Updating to the latest version of NuGet.Services.Validation

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/ViewModels/ReportPackageReason.cs
- src/NuGetGallery/Views/Packages/ReportAbuse.cshtml
- src/NuGetGallery/Views/Packages/ReportMyPackage.cshtml
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
Updates the wording for some report reasons.
Adds text requesting additional details for trademark/copyright requests.
Addresses https://github.com/NuGet/NuGetGallery/issues/4716
@joelverhagen @karann-msft @skofman1
> Update Report Reasons

- src/NuGetGallery/Views/Packages/Delete.cshtml
Fixing the package delete page to remove outdated and potentially misleading content and adding a pointer to docs which is significantly easier to maintain. Fixing issue https://github.com/NuGet/NuGetGallery/issues/4960
> Updating package delete page

- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
This broke with https://github.com/NuGet/NuGetGallery/pull/4956 because we updated the report reason in the test to ViolateALicense, but failed to update the mocked view model to reflect a valid model for this reason.
Update ReportAbuseViewModel in tests to include signature for new reason.
@skofman1 @cristinamanum @agr
> Fix PackageControllerFacts

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/page-statistics-most-downloaded.less
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/StatisticsController.cs
- src/NuGetGallery/Services/IStatisticsService.cs
- src/NuGetGallery/Services/JsonStatisticsService.cs
- src/NuGetGallery/Services/NullStatisticsService.cs
- src/NuGetGallery/Services/StatisticsReportName.cs
- src/NuGetGallery/Services/StatisticsReportResult.cs
- src/NuGetGallery/UrlExtensions.cs
- src/NuGetGallery/ViewModels/StatisticsPackagesViewModel.cs
- src/NuGetGallery/Views/Statistics/Index.cshtml
- src/NuGetGallery/Views/Statistics/PackageVersions.cshtml
- src/NuGetGallery/Views/Statistics/Packages.cshtml
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/StatisticsControllerFacts.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/Services/JsonStatisticsServiceFacts.cs
This change introduces the concept of "community" statistics report that will be displayed by default. These reports filter out packages owned by Microsoft and .NET Framework. Users can choose to "Show all packages" to view reports that include Microsoft's and .NET Framework's packages. With this change, packages like `System.Globalization` will no longer clutter our default statistic reports! 😄 
Note: The `JsonStatisticsService` had some serious concurrency issue and did not cache reports that it loaded from blob storage. This pull request fixes that by loading reports once an hour.
This change depends on https://github.com/NuGet/NuGet.Jobs/pull/239.
Fixes https://github.com/NuGet/NuGetGallery/issues/3417.
Clicking on the "Show more..." links at the bottom of the homepage will take you …
> [Statistics] Introduce Community Statistics Reports

- src/NuGetGallery/Filters/ApiScopeRequiredAttribute.cs
- tests/NuGetGallery.Facts/Filters/ApiScopeRequiredAttributeFacts.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
Regression from PR #4945 
https://github.com/NuGet/NuGetGallery/pull/4945/files#diff-1463a262f19818464c6a4983b635e94aL18
When I changed type from `List<string>` to `string[]`, the property was getting overwritten by AutofacFilterProvider property injection. Fix is to make the property private.
> Fixing ApiScopeRequiredAttribute regression

- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- src/NuGetGallery/Web.config
Fix https://github.com/NuGet/NuGetGallery/issues/4717.
I recommend ignoring whitespace in the diff:
https://github.com/NuGet/NuGetGallery/pull/4978/files?w=1
This also add a default warning banner for local development (like DEV and INT).
> Hide package metadata when the package is deleted

- tests/NuGetGallery.FunctionalTests/PackageCreation/SecurityPolicyTests.cs
The test broke due to default security policy flag being on. This is the fix.
> Fix test VerifyPackageKey_Returns404ForMissingPackage

- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Preventing showing the 
>This package has not been indexed yet. It will appear in search results and will be available for install/restore after indexing is complete. 
message while validation is in progress, as package is not available in V2, so no indexing is happening.
> Not showing "indexing" message while validation is in progress.

- src/NuGetGallery.Core/Auditing/CredentialAuditRecord.cs
- src/NuGetGallery.Core/Auditing/ScopeAuditRecord.cs
- tests/NuGetGallery.Core.Facts/Auditing/ScopeAuditRecordTests.cs
Issue #4958 
Shims change doesn't seem to be necessary, since IfxAuditingService only records the AffectedCredential key and type (e.g., DB PK and "apikey.v2"). This change will ensure that the owner scope is included in CloudBlobAuditingService audit records.
> Add ApiKey owner scope auditing

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/page-report-abuse.less
- src/NuGetGallery/Areas/Admin/Services/ISupportRequestService.cs
- src/NuGetGallery/Areas/Admin/Services/SupportRequestService.cs
- src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/ExtensionMethods.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/IMessageService.cs
- src/NuGetGallery/Services/IPackageDeleteService.cs
- src/NuGetGallery/Services/MessageService.cs
- src/NuGetGallery/Services/PackageDeleteService.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- src/NuGetGallery/ViewModels/DeletePackageViewModel.cs
- src/NuGetGallery/ViewModels/PackageDeleteDecision.cs
- src/NuGetGallery/ViewModels/ReportAbuseViewModel.cs
- src/NuGetGallery/ViewModels/ReportMyPackageViewModel.cs
- src/NuGetGallery/ViewModels/ReportViewModel.cs
- src/NuGetGallery/Views/Packages/ReportAbuse.cshtml
- src/NuGetGallery/Views/Packages/ReportMyPackage.cshtml
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
- tests/NuGetGallery.Facts/Services/MessageServiceFacts.cs
Progress on https://github.com/NuGet/Engineering/issues/921.
The changes were getting big so I stopped and made a PR. Hopefully easier to review.
This PR:
1. Update the "report my package" form to support a new hidden drop-down (delete decision) and confirmation checkbox.
1. Add new notification message so that all owners know a version was deleted.
1. Add method to `IPackageDeleteService` to determine if a package can be deleted. It always returns false right now.
1. Add logic to soft delete the package and auto-close the support request.
TODO:
1. Implement "can I delete this?" logic.
1. Introduce configuration for the aforementioned logic.
1. Functional test (hopefully)
Without these TODOs, the new code paths introduced by this PR will not be available yet.
> Add initial support for user deletion request

- src/NuGetGallery.Core/Entities/Scope.cs
- src/NuGetGallery/Authentication/AuthenticationService.cs
- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/Extensions/ScopeExtensions.cs
- src/NuGetGallery/Infrastructure/Authentication/CredentialBuilder.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Scripts/gallery/page-api-keys.js
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- src/NuGetGallery/ViewModels/ApiKeyListViewModel.cs
- src/NuGetGallery/ViewModels/ApiKeyOwnerViewModel.cs
- src/NuGetGallery/ViewModels/ApiKeyViewModel.cs
- src/NuGetGallery/ViewModels/ScopeViewModel.cs
- src/NuGetGallery/Views/Users/ApiKeys.cshtml
- tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
- tests/NuGetGallery.Facts/Extensions/ScopeExtensionsFacts.cs
- tests/NuGetGallery.Facts/Extensions/UserExtensionsFacts.cs
- tests/NuGetGallery.Facts/Framework/Fakes.cs
Issue #4872.
Work remaining for API key owner (org) scopes:
- Auditing (#4958)
- Remove deprecated Scope.cs ctor (will do in separate PR, to minimize this PR)
- Integrate with PermissionsService
> ApiKey owner (org) scope UI work

- src/NuGetGallery/Authentication/AuthenticationService.cs
- src/NuGetGallery/Controllers/AuthenticationController.cs
- src/NuGetGallery/Services/ITelemetryService.cs
- src/NuGetGallery/Services/TelemetryService.cs
- tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
- tests/NuGetGallery.Facts/Services/TelemetryServiceFacts.cs
This PR fixes https://github.com/NuGet/NuGetGallery/issues/5020 where new Login UI wouldn't show validation errors for bad username and password. Also added telemetry for credential added(for getting data on MSA account linking)
> Fix new Login UI validation errors missing bug and add telemetry

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Scripts/gallery/async-file-upload.js
https://github.com/NuGet/NuGetGallery/issues/4787
A couple fixes here:
1 - if starting an edit request fails (due to title/ID collision), return the error message in JSON
2 - keep the form open when verifying fails
3 - clear warnings when showing errors for an upload
4 - clear errors when canceling an upload
> Show VerifyPackage errors correctly in UI

- src/NuGetGallery/Services/PermissionsService.cs
- tests/NuGetGallery.Facts/Services/PermissionsServiceFacts.cs
Previously, the `PermissionsService` would
1 - Get a list of all permissions that the user has
2 - Check that list with the permissions required by the action
This PR now allows the `PermissionsService` to short-circuit and stop checking permissions when it finds that the user has a permission that's required.
E.g. if I am an owner of the package and this action is allowed if I have owner permissions, I don't need to check if I am a member of any organizations that own the package.
> Improve performance of the PermissionsService

- src/NuGetGallery/Controllers/JsonApiController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Scripts/gallery/common.js
- src/NuGetGallery/Scripts/gallery/page-manage-owners.js
- src/NuGetGallery/Services/AccountActions.cs
- src/NuGetGallery/Services/PermissionsService.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- src/NuGetGallery/ViewModels/PackageOwnersResultViewModel.cs
- src/NuGetGallery/Views/Packages/ManagePackageOwners.cshtml
- tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs
- tests/NuGetGallery.Facts/Controllers/JsonApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Framework/Fakes.cs
- tests/NuGetGallery.Facts/Framework/UnitTestBindings.cs
- Adds "(your organization)" to organizations accounts that you are a member of in the Current Owners list
- Fixes the "who I can remove" logic with respect to organization users
- Improves messaging when users try to add a package owner that already exists or remove a package owner that doesn't exist
- Adds organization users to `Fakes`
- **Vastly improved testing for `JsonApiController`** (will add more for `GetPackageOwners` later)
> [Organizations] Improvements to Manage Package Owners page for organizations

- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/Services/DeleteAccountService.cs
- src/NuGetGallery/Services/IPackageService.cs
- src/NuGetGallery/Services/PackageService.cs
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
- tests/NuGetGallery.Facts/Services/DeleteAccountServiceFacts.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
Renaming `FindPackagesByOwner` to `FindPackagesByAnyMatchingOwner`, so it's more obvious how this differs from the `FindPackageRegistrationsByOwner` which will continue to only look for direct ownership.
@scottbommarito @shishirx34 - based on our discussion of PR #5022 feedback.
> Rename FindPackagesByOwner API

- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/Views/Users/Account.cshtml
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
Fix for #4984 - Password reset for accounts created with MSA login is broken
Also, added a redundant server side check which would send invalid password reset links. 
use `?w=1` to ignore whitespace changes.
[UPDATE]
Before confirmation:
After confirmation:
> Hide enable password login flow until user verification

- src/NuGetGallery.Core/CredentialTypes.cs
- src/NuGetGallery/Authentication/AuthenticationService.cs
- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/Scripts/gallery/page-api-keys.js
- src/NuGetGallery/ViewModels/AccountViewModel.cs
- src/NuGetGallery/ViewModels/ApiKeyViewModel.cs
- src/NuGetGallery/Views/Users/ApiKeys.cshtml
- tests/NuGetGallery.Facts/Authentication/TestCredentialHelper.cs
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
- tests/NuGetGallery.Facts/Framework/Fakes.cs
- tests/NuGetGallery.Facts/Services/MessageServiceFacts.cs
This is a preparation step for this work: https://github.com/NuGet/Engineering/issues/927
Since we are going to have V3, V4 ApiKeys doesn't make sense using ApiKey type (V1/V2) to distinguish between scoped/non-scopedm keys.
> Remove usage of ApiKey Type for distinguishing between Scoped/non-scoped ApiKeys

- src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs
- tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceFacts.cs
With @joelverhagen's help found a nasty issue with SAS tokens for blob storage: if expiration time is not specified generated SAS token is invalid and causes HTTP 403 when blob is accessed with that token *even* in public container (which is accessible without any tokens).
It is unclear from documentation whether expiration time should be specified or not and the class that is used to pass that information uses `Nullable<DateTimeOffset>` for the expiration time, which assumes that it's optional. It isn't.
> Not using SAS tokens for public containers read URIs

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/RequestModels/EditPackageRequest.cs
- src/NuGetGallery/RequestModels/EditPackageVersionRequest.cs
- src/NuGetGallery/RequestModels/VerifyPackageRequest.cs
- src/NuGetGallery/Services/EditPackageService.cs
- src/NuGetGallery/Services/IReadMeService.cs
- src/NuGetGallery/Services/ReadMeService.cs
- src/NuGetGallery/Views/Packages/UploadPackage.cshtml
- src/NuGetGallery/Views/Packages/_VerifyForm.cshtml
- src/NuGetGallery/Views/Packages/_VerifyMetadata.cshtml
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
PR into feature branch for pkg immutability.
This PR focuses on the verify-upload experience, which now only allows toggling Listed/Unlisted and modifying Readme/Documentation.
The verify form is now a separate view from the edit form as they provide both different views and experience.
> Split up edit/verify views and make verify upload metadata read-only.

- src/NuGetGallery/Scripts/gallery/page-manage-owners.js
(This is a bug in master that's on dev but not yet deployed to int or prod.)
We want to redirect you back to the package details page after removing a package owner if you removed the last owner that granted you ownership of the package.
Currently, it will always redirect you back after removing any package owner, regardless of whether or not you are still an owner. This fixes this behavior.
> Quick hotfix to removing package owners from the manage package owners page

- src/NuGetGallery/Controllers/PackagesController.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Framework/TestExtensionMethods.cs
- tests/NuGetGallery.Facts/TestUtils/TestUtility.cs
This adds some permissions tests to `DisplayPackage`
More specifically, these test that
1 - Packages with pending edits show the pending edit only to users that own them.
2 - Packages in the validating/failed validation state only appear for users that own them.
Note that I caught a change in behavior from before--with the addition of the permissions service, admins could no longer see pending edits on package. This change returns that functionality (which will rewritten with the "Permissions Service 2.0" PR).
> Permissions tests for DisplayPackage

- src/NuGetGallery/Scripts/gallery/page-manage-packages.js
- src/NuGetGallery/Views/Users/Packages.cshtml
Fixes #5133, originally intended for PR #5060
> ManagePackages: hide filter if not in organization

- src/NuGetGallery/Services/PackageUploadService.cs
- tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs
Moved the validation message enqueuing to the `CommitPackageAsync` method of the `PackageUploadService` to prevent sending said message before package metadata is validated.
Partially addresses https://github.com/NuGet/Engineering/issues/1023.
> Hotfix early validation message sending

- src/NuGetGallery/Scripts/gallery/common.js
Issue #4604 - Fixes client side hang during ApiKey creation callback due to resetFormValidation including all package checkboxes. Tested with test account on DEV, which had >8K package registrations.
Note, there are more perf issues on this page - may open separate issues when I have more time.
> [Perf][ApiKeys]Fix hang due to resetFormValidation including all fields

- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Previous fix was too narrowly targeted at "not validating" state, while it should have been "only for available pacakges"
Addresses https://github.com/NuGet/Engineering/issues/1027
> Displaying "package not indexed yet" alert only if package is available.

- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
For Edit, SetLicenseReportVisibility, and Delete I parametrized the tests so that they now run with every test user.
For Manage Package Owners I added two simple tests to guarantee it displays the form when expected.
> Permissions tests for Edit, Delete, Manage Package Owners, and SetLicenseReportVisibility (UI)

- src/NuGetGallery/Helpers/PermissionsHelpers.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/ActionOnNewPackageContext.cs
- src/NuGetGallery/Services/ActionRequiringAccountPermissions.cs
- src/NuGetGallery/Services/ActionRequiringEntityPermissions.cs
- src/NuGetGallery/Services/ActionRequiringPackagePermissions.cs
- src/NuGetGallery/Services/ActionRequiringReservedNamespacePermissions.cs
- src/NuGetGallery/Services/ActionsRequiringPermissions.cs
- src/NuGetGallery/Services/IActionRequiringEntityPermissions.cs
- src/NuGetGallery/Services/PermissionsCheckResult.cs
- src/NuGetGallery/Services/PermissionsFailure.cs
- src/NuGetGallery/Services/PermissionsRequirement.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/Services/ActionRequiringEntityPermissionsFacts.cs
- tests/NuGetGallery.Facts/Services/PermissionsHelpersFacts.cs
This is the implementation of the new version of the Permissions Service, without changes to the existing code.
You may have seen this code before in https://github.com/NuGet/NuGetGallery/pull/5097
> PermissionsService 2.0 (just implementation)

- src/NuGetGallery.Core/Services/CoreMessageService.cs
- src/NuGetGallery.Core/Services/ICoreMessageService.cs
- src/NuGetGallery/Services/MessageService.cs
- tests/NuGetGallery.Facts/Services/MessageServiceFacts.cs
Addresses https://github.com/NuGet/NuGetGallery/issues/5194.
These APIs will be consumed by the orchestrator.
> Update failed validation message to allow a specify email for package signing failure

- src/NuGetGallery/Filters/ApiAuthorizeAttribute.cs
https://github.com/NuGet/NuGetGallery/issues/4900
When UI redesign happened, we started sending the wrong address because we changed the URL that the API keys could be set from.
By using the `UrlHelper` extension for navigating to the API keys page we should guarantee that the address is always correct.
> Fix API expiry notification email to use the correct URL

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Services/IMessageService.cs
- src/NuGetGallery/Services/MessageService.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Services/MessageServiceFacts.cs
https://github.com/NuGet/NuGetGallery/issues/5087
> Add link to package in Contact Owners email

- src/NuGetGallery/Services/ActionRequiringEntityPermissions.cs
- src/NuGetGallery/Services/ActionRequiringPackagePermissions.cs
- src/NuGetGallery/Services/ActionRequiringReservedNamespacePermissions.cs
- src/NuGetGallery/Services/IActionRequiringEntityPermissions.cs
- src/NuGetGallery/Services/PermissionsCheckResult.cs
- tests/NuGetGallery.Facts/Services/ActionRequiringEntityPermissionsFacts.cs
Per discussion with @chenriksson:
`TryGetAccountsIsAllowedOnBehalfOf` is now `CheckPermissionsOnBehalfOfAnyAccount` and returns `PermissionsCheckResult` instead of `bool` to mimic the existing `CheckPermissions` method. It also has an override without the `out` parameter for cases in which the `out` parameter is not desired.
> Change Permissions Service 2.0 GetAccountsAllowedOnBehalfOf API

- tests/NuGetGallery.FunctionalTests.Core/EnvironmentSettings.cs
- tests/NuGetGallery.FunctionalTests.Core/NuGetGallery.FunctionalTests.Core.csproj
- tests/NuGetGallery.FunctionalTests.Core/XunitExtensions/DefaultSecurityPoliciesEnforcedFactAttribute.cs
- tests/NuGetGallery.FunctionalTests.Core/XunitExtensions/PackageLockFactAttribute.cs
- tests/NuGetGallery.FunctionalTests/Commandline/NuGetCommandLineTests.cs
The test requires a locked package to exist on the feed, hence it will be disabled by default.
> Functional test for package locking

- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/Configuration/ConfigurationService.cs
- src/NuGetGallery/Configuration/IPackageDeleteConfiguration.cs
- src/NuGetGallery/Configuration/PackageDeleteConfiguration.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/PackageDeleteService.cs
- src/NuGetGallery/Web.config
- tests/NuGetGallery.Facts/Services/PackageDeleteServiceFacts.cs
Progress on https://github.com/NuGet/Engineering/issues/921.
This PR has no functional impact on the gallery but should give a good picture of what the user package delete feature looks like.
NuGet.org's will probably look like this:
```xml
<add key="PackageDelete.AllowUsersToDeletePackages" value="true" />
<add key="PackageDelete.MaximumDownloadsForPackageId" value="125000" />
<add key="PackageDelete.StatisticsUpdateFrequencyInHours" value="24" />
<add key="PackageDelete.HourLimitWithMaximumDownloads" value="72" />
<add key="PackageDelete.MaximumDownloadsForPackageVersion" value="100" />
```
The 125,000 is a value that Karan and I agreed upon based off of the number of downloads in the first 24 hours for the top 500 latest packages in the past 6 months. It is a protective measure we can …
> Add configuration for user package deletes

- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Validation issues are currently escaped on the display package page. Unfortunately, some validation issues have HTML within the message (like the [package is signed issue](https://dev.nugettest.org/packages/Loshar.NuGet.Server/3.1.5)). This change removes escaping so that validation issues are properly formatted.
> [Validation Issues] Display the raw validation message

- src/NuGetGallery/ExtensionMethods.cs
- tests/NuGetGallery.Facts/ExtensionMethodsFacts.cs
`GetCurrentUser` had a bug where if `self.Request.User` was non-null (e.g. with a default `IPrincipal` that was unauthenticated) it would throw a 401 error.
> Fix GetCurrentUser for unauthenticated scenarios

- src/NuGetGallery/App_Start/Routes.cs
- tests/NuGetGallery.Facts/Telemetry/ClientTelemetryPIIProcessorTests.cs
Fixing unit test failure. Obfuscation and test from PR #5236 didn't account for new route added in PR #5228.
> Obfuscate new transform account route

- src/NuGetGallery/Telemetry/ClientTelemetryPIIProcessor.cs
Due to null ref exception in ClientTelemetryPIIProcessor.
> Fix issue: [DEV] Images missing from Dev environment

- src/NuGetGallery/Configuration/AppConfiguration.cs
- src/NuGetGallery/Configuration/IAppConfiguration.cs
- tests/NuGetGallery.Facts/Configuration/ConfigurationServiceFacts.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
Added support to update date dynamically from the app for the formatted branding message. Sending config updates to NuGet Deployment.
Fixes #5233
> Update copyright for NuGet Gallery

- src/NuGetGallery/Authentication/AuthenticationService.cs
- src/NuGetGallery/Security/SecurePushSubscription.cs
- src/NuGetGallery/Security/SecurityPolicyService.cs
Remove usernames and emails from AI traces.
> Remove usernames and emails from AI traces.

- src/NuGetGallery.Core/Infrastructure/MigrateUserToOrganization.sql
- src/NuGetGallery/Constants.cs
- src/NuGetGallery/Controllers/AuthenticationController.cs
- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- src/NuGetGallery/UrlExtensions.cs
- src/NuGetGallery/ViewModels/TransformAccountFailedViewModel.cs
- src/NuGetGallery/Views/Authentication/SignIn.cshtml
- src/NuGetGallery/Views/Users/Transform.cshtml
- src/NuGetGallery/Views/Users/TransformFailed.cshtml
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
Includes the following, with screenshots:
- Update SQL to return and not migrate when no request match
- Add informational hint on transform page to indicate what is expected for administrator:
- Add informational message when prompting for new admin sign in:
- Adjust transformation error formatting to align with header:
//cc @anangaur , @karann-msft
> SQL fix and addressing feedback from demo

- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/Services/IUserService.cs
- src/NuGetGallery/Services/UserService.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- src/NuGetGallery/Views/Authentication/SignIn.cshtml
- src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
- src/NuGetGallery/Views/Users/Transform.cshtml
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
- tests/NuGetGallery.Facts/Services/UserServiceFacts.cs
Fixes for the following:
- #5311: Transform should fail if admin is same as transformed account
- #5309: Transform should fail if admin is an organization
- #5317: Transform error not formatted correctly for unconfirmed admin
**Update 1/23**: Also incorporating feedback from @anangaur, including:
- #5308 and other transform error messages
- UI: Change admin info message to tooltip
- UI: Add transform confirmation
- UI: Formatting of sign-in returnUrl message
> Bug bash: fix transform issues

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/dist/js/bootstrap.js
- src/Bootstrap/less/theme/all.less
- src/Bootstrap/less/theme/page-manage-packages.less
- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/Scripts/gallery/page-api-keys.js
- src/NuGetGallery/Scripts/gallery/page-manage-packages.js
- src/NuGetGallery/ViewModels/OwnerRequestsViewModel.cs
- src/NuGetGallery/Views/Users/ApiKeys.cshtml
- src/NuGetGallery/Views/Users/Packages.cshtml
- src/NuGetGallery/Web.config
Fixes the following bug bash issues:
- #5299 comma separators for package and download counts
- #5304 flash of empty containers
- #5310 Layout issues (except binding filter to namespaces / requests will be separate PR)
- #5298 Org icon too high
- #5306 Owner link whitespace fix
- #5307 Visual separation between owners
Page Screenshot:
Package row w/ owners screenshot:
> Organization bug bash: Manage Packages page

- src/NuGetGallery/Controllers/AuthenticationController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Extensions/OrganizationExtensions.cs
- src/NuGetGallery/ViewModels/PackageOwnersResultViewModel.cs
- tests/NuGetGallery.Facts/Controllers/JsonApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- https://github.com/NuGet/NuGetGallery/issues/5301
We have configured our MVC so that if a 401 is returned by an endpoint, the app will redirect you to the sign in page.
If you are signed in when this happens, the sign-in page will redirect you back to the page you were initially on that gave you the 401. This leads to an infinite redirect loop.
To fix this, we can return 403 instead. Edit already does this.
We should potentially monitor our other endpoints to see if this is possible elsewhere--any endpoint that returns 401 when the user is logged in will have this behavior.
- https://github.com/NuGet/NuGetGallery/issues/5318
Simple fix that I added unit tests to.
> [Organizations] Fix Manage Package Owners issues

- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/ViewModels/AccountViewModel.cs
- src/NuGetGallery/ViewModels/ChangeEmailViewModel.cs
- src/NuGetGallery/ViewModels/ChangeNotificationsViewModel.cs
- src/NuGetGallery/ViewModels/ChangePasswordViewModel.cs
- src/NuGetGallery/ViewModels/CredentialKind.cs
- src/NuGetGallery/ViewModels/CredentialViewModel.cs
- src/NuGetGallery/ViewModels/UserAccountViewModel.cs
- src/NuGetGallery/Views/Users/Account.cshtml
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
Preparation for #4990.
Refactoring to create base AccountViewModel, to be used by both UserAccountViewModel and OrganizationAccountViewModel (coming w/ Manage Organization).
> Create derived UserAccountViewModel for User (non-Organization) accounts

- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/Services/IPackageService.cs
- src/NuGetGallery/Services/PackageService.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
> Do not show organization packages on profile

- src/NuGetGallery.Core/Auditing/AuditedDeleteAccountAction.cs
- src/NuGetGallery.Core/Auditing/DeleteAccountAuditRecord.cs
- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery/Areas/Admin/Services/ISupportRequestService.cs
- src/NuGetGallery/Areas/Admin/Services/SupportRequestService.cs
- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/Services/DeleteAccountService.cs
- tests/NuGetGallery.Core.Facts/Auditing/AuditRecordTests.cs
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
- tests/NuGetGallery.Facts/Services/DeleteAccountServiceFacts.cs
- tests/NuGetGallery.Facts/Services/SupportRequestServiceFacts.cs
Add audit for DeleteAccount. Changes in the IFX shim will be in a different PR.
> Audit for DeleteAccount

- src/NuGetGallery/Controllers/UsersController.cs
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
https://github.com/NuGet/NuGetGallery/issues/5340
Was accidentally passing in the owner of the page instead of the current user.
> Profile page should only show "Edit", "Manage Package Owners", and "Delete" links when the current user has permission

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/RequestModels/VerifyPackageRequest.cs
- src/NuGetGallery/Views/Packages/_VerifyMetadata.cshtml
https://github.com/NuGet/NuGetGallery/issues/5312
(same behavior as before for new package IDs)
> Only show "Owner" dropdown in upload flow for new packages

- src/NuGetGallery/Controllers/ApiController.cs
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
- tests/NuGetGallery.FunctionalTests/DistIntegrationTests.cs
- tests/NuGetGallery.FunctionalTests/NuGetGallery.FunctionalTests.csproj
Fix https://github.com/NuGet/NuGetGallery/issues/4558.
I will not merge this until @anangaur has posted about this on the announcements repo.
> Redirect /nuget.exe endpoint to dist.nuget.org, nuget.exe 2.8.6

- src/NuGetGallery/Configuration/IPackageDeleteConfiguration.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/IPackageDeleteService.cs
- src/NuGetGallery/Services/ITelemetryClient.cs
- src/NuGetGallery/Services/ITelemetryService.cs
- src/NuGetGallery/Services/PackageDeleteService.cs
- src/NuGetGallery/Services/TelemetryClientWrapper.cs
- src/NuGetGallery/Services/TelemetryService.cs
- src/NuGetGallery/Telemetry/AppInsightsHealthIndicatorLogger.cs
- src/NuGetGallery/Telemetry/UserPackageDeleteEvent.cs
- src/NuGetGallery/Telemetry/UserPackageDeleteOutcome.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Services/PackageDeleteServiceFacts.cs
- tests/NuGetGallery.Facts/Services/TelemetryServiceFacts.cs
Address https://github.com/NuGet/Engineering/issues/921.
Could I get some crazy nitpick 👀s on this PR? There is risk associated with this change as it allows users to delete their own packages in some cases.
I check both the DB and the statistics reports for download counts. This is to improve resiliency as separate jobs write these two artifacts.
> Add logic for respecting the package auto-delete configuration

- src/NuGetGallery.Core/Auditing/AuditedSecurityPolicyAction.cs
- src/NuGetGallery.Core/CredentialTypes.cs
- src/NuGetGallery/App_Start/Routes.cs
- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Security/ISecurityPolicyService.cs
- src/NuGetGallery/Security/IUserSecurityPolicySubscription.cs
- src/NuGetGallery/Security/RequireOrganizationTenantPolicy.cs
- src/NuGetGallery/Security/SecurityPolicyAction.cs
- src/NuGetGallery/Security/SecurityPolicyService.cs
- src/NuGetGallery/Security/UserSecurityPolicyEvaluationContext.cs
- src/NuGetGallery/Services/UserService.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- src/NuGetGallery/Telemetry/Obfuscator.cs
- src/NuGetGallery/UrlExtensions.cs
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/Security/RequireMinClientVersionForPushPolicyFacts.cs
- tests/NuGetGallery.Facts/Security/RequireMinProtocolVersionForPushPolicyFacts.cs
- tests/NuGetGallery.Facts/Security/RequireOrganizationTenantPolicyFacts.cs
- tests/NuGetGallery.Facts/Security/RequirePackageVerifyScopePolicyFacts.cs
- tests/NuGetGallery.Facts/Security/SecurityPolicyServiceFacts.cs
- tests/NuGetGallery.Facts/Services/UserServiceFacts.cs
- tests/NuGetGallery.Facts/TestUtils/TestServiceUtility.cs
Addresses issue #5261
- Create organization policy requiring AAD credential with matching tenant
- On transform: adds policy to organization, using tenant from initial admin's AAD credential
- On add member: evaluates organization policy for new member
Will also require a small shims change for the new security policy action... separate PR coming.
> Add organization tenant policy

- src/NuGetGallery.Core/Auditing/CloudAuditingService.cs
- src/NuGetGallery.Core/Infrastructure/AzureEntityList.cs
- src/NuGetGallery.Core/Infrastructure/TableErrorLog.cs
- src/NuGetGallery.Core/Services/CloudBlobContainerWrapper.cs
- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
Configure the Azure services to use secondary storage if the primary is not available. For a set of resources this setting was already in place but not for all. One sample is audit storage (that is used for api/stats) .
> USSC gallery api/status should use secondary storage.

- src/NuGetGallery/UrlExtensions.cs
https://github.com/NuGet/NuGetGallery/issues/5453
When `interceptReturnUrl` is true, `GetActionLink` turns the `returnUrl` into an absolute URL. This causes the `SafeRedirectResult` to redirect to the home page instead of the transform organization URL. By turning off `interceptReturnUrl`, the return url now gets passed in correctly.
We do this for some of the other external authentication `UrlHelper` methods, so this seemed like an appropriate fix.
> dont intercept authenticate returnurl

- src/NuGetGallery.Core/Entities/Organization.cs
- src/NuGetGallery/Helpers/PermissionsHelpers.cs
- src/NuGetGallery/Services/UserService.cs
Issue #5461, optimization 2.
Caches and separates admin/collaborators lookups for current user during permissions checks so duplicate checks don't hit the DB.
Originally saw response go from 37.8s -> 35.1s, but now seeing it go from 59.1s -> 42.5s
> Cache admins and collaborators for permissions

- src/NuGetGallery.Core/CoreConstants.cs
- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery.Core/Services/CryptographyService.cs
- src/NuGetGallery/Constants.cs
- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/ReflowPackageService.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
Per feedback from @cristinamanum.
Progress on https://github.com/NuGet/Engineering/issues/1168
> Move CryptographyService to NuGetGallery.Core so it can be used in the hash checker

- src/NuGetGallery/Controllers/AuthenticationController.cs
- src/NuGetGallery/Controllers/UsersController.cs
- tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
Fixes: https://github.com/NuGet/NuGetGallery/issues/5445. Simple refactoring.
> [BugBash] Prevent AAD to MSA account transformation

- src/NuGetGallery/Services/UserService.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- tests/NuGetGallery.Facts/Services/UserServiceFacts.cs
Issue #5463, messaging per @anangaur 
Scenario is current user (org admin) as only admin deleting their membership or changing self to collaborator... which we block.
> Error message for removal of last org admin

- src/NuGetGallery.Core/Packaging/ManifestValidator.cs
- src/NuGetGallery.Core/Packaging/PackageMetadata.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Services/PackageService.cs
- src/NuGetGallery/Services/ReflowPackageService.cs
- tests/NuGetGallery.Core.Facts/Packaging/PackageMetadataFacts.cs
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
- tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs
- tests/NuGetGallery.Facts/Services/ReflowPackageServiceFacts.cs
Fix https://github.com/NuGet/NuGetGallery/issues/5522
> Enable reflowing of packages that don't pass the valid version range rule

- src/NuGetGallery.Core/Services/CorePackageService.cs
- src/NuGetGallery.Core/Services/ICorePackageService.cs
- tests/NuGetGallery.Core.Facts/Services/CorePackageServiceFacts.cs
Address https://github.com/NuGet/Engineering/issues/1191
> Add UpdatePackageStreamMetadataAsync to keep the package stream details up to date

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Services/ITelemetryClient.cs
- src/NuGetGallery/Services/ITelemetryService.cs
- src/NuGetGallery/Services/PackageDeleteService.cs
- src/NuGetGallery/Services/PackageService.cs
- src/NuGetGallery/Services/ReflowPackageService.cs
- src/NuGetGallery/Services/TelemetryClientWrapper.cs
- src/NuGetGallery/Services/TelemetryService.cs
- src/NuGetGallery/Services/ValidationService.cs
- tests/NuGetGallery.Facts/Services/PackageDeleteServiceFacts.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
- tests/NuGetGallery.Facts/Services/ReflowPackageServiceFacts.cs
- tests/NuGetGallery.Facts/Services/TelemetryServiceFacts.cs
- tests/NuGetGallery.Facts/Services/ValidationServiceFacts.cs
- tests/NuGetGallery.Facts/TestUtils/TestServiceUtility.cs
Progress on https://github.com/NuGet/NuGetGallery/issues/5378.
I chose not to pass down `User` and `IIdentity` for now. I wanted to emit telemetry from the service layer and not the controller layer so that we would not need to duplicate emits in `ApiController` vs. `PackagesController` and we would not emit telemetry when the service call no-ops (e.g. unlisting an already unlisted package).
> Add telemetry for unlist, list, delete, reflow, and revalidate

- tests/NuGetGallery.FunctionalTests.Core/EnvironmentSettings.cs
So functional tests can run against *.cloudapp.net hosts.
> Added new DEV environment cert to the list of accepted.

- src/NuGetGallery/Scripts/gallery/page-add-organization.js
- src/NuGetGallery/Services/UserService.cs
- src/NuGetGallery/Views/NuGetViewBase.cs
- src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
1 - Fetch the image immediately for the text box on the add page if the form is already filled (e.g. if form submission fails, show the image from the email already.
2 - Don't use `string.Equals` in EF queryables because it throws on Azure SQL lol.
3 - Show the `Manage Organizations` page for users who are allowed to create an org.
> [Organizations] Minor bug fixes from dev

- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/Services/PackageService.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
First optimization for #5461, which covers 2 fixes:
1. Regression from d8371bd
In **UsersController**, fix sent to query off the request table instead of the large list of packages. Performance was hard to measure, as it was hanging due to the regression.
2. Optimize packages query to only sort in DB, based on IsLatest columns
In **PackageService**, modified the EF query to sort and select based on IsLatest state in DB. Previously we'd read all rows and sort in memory (on NuGetVersion as last resort) to handle cases where IsLatest wasn't set due to concurrency issues.
The second optimization helps mostly in scenarios with many versions, as opposed to many registrations. Results below:
**Scenario 1:  59K registrations, 59K versions (NuGetStagingTest on DEV)**
- BEFORE: 48.54, 49.41, 60, …
> Improve query performance for Manage Packages

- src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs
- src/NuGetGallery.Core/Services/CloudBlobWrapper.cs
- src/NuGetGallery.Core/Services/ICoreFileStorageService.cs
- src/NuGetGallery.Core/Services/ISimpleCloudBlob.cs
- src/NuGetGallery/Services/FileSystemFileStorageService.cs
- src/NuGetGallery/Services/FileSystemService.cs
- src/NuGetGallery/Services/IFileSystemService.cs
- tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceFacts.cs
- tests/NuGetGallery.Facts/Services/FileSystemFileStorageServiceFacts.cs
Progress on https://github.com/NuGet/Engineering/issues/1190
Progress on https://github.com/NuGet/Engineering/issues/1203
> Add CopyFileAsync to ICoreFileStorageService

- src/NuGetGallery/Services/IUserService.cs
- src/NuGetGallery/Services/UserService.cs
- tests/NuGetGallery.Facts/Services/UserServiceFacts.cs
With this PR, when an account is transformed into an organization, its API keys are now cloned to the new admin.
This prevents breaking existing CI scenarios upon organization transformation.
> [Organizations] Clone existing API keys to org admin on account transform

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/modals.less
- src/NuGetGallery/App_Data/Files/Content/Login-Discontinuation-Configuration.json
- src/NuGetGallery/Controllers/PagesController.cs
- src/NuGetGallery/Extensions/ClaimsExtensions.cs
- src/NuGetGallery/Filters/UiAuthorizeAttribute.cs
- src/NuGetGallery/Services/ContentObjectService.cs
- src/NuGetGallery/Services/LoginDiscontinuationConfiguration.cs
- src/NuGetGallery/ViewModels/GalleryHomeViewModel.cs
- src/NuGetGallery/Views/Pages/Home.cshtml
- src/NuGetGallery/Views/Pages/_TransformOrLink.cshtml
- tests/NuGetGallery.Facts/Services/ContentObjectServiceFacts.cs
- tests/NuGetGallery.Facts/Services/LoginDiscontinuationConfigurationFacts.cs
https://github.com/NuGet/NuGetGallery/issues/5584
Added a new field to the existing `LoginDiscontinuationConfiguration` for the accounts that should be asked to transform.
Individual account:
Organization account:
> [Organizations] Use a configurable list to determine what users should be asked to transform to an organization with a deprecated password

- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery.Core/Services/AccessConditionWrapper.cs
- src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs
- src/NuGetGallery.Core/Services/IAccessCondition.cs
- src/NuGetGallery.Core/Services/ICoreFileStorageService.cs
- src/NuGetGallery/Services/FileSystemFileStorageService.cs
- tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceFacts.cs
- tests/NuGetGallery.Facts/Services/FileSystemFileStorageServiceFacts.cs
This is used during revalidate to verify the destination package has not changed.
If a processor has mutated a package, the copy that replaces the destination package should fail if the destination has changed.
Progress on https://github.com/NuGet/Engineering/issues/1190
> Add destination access condition parameter to CopyFileAsync

- src/NuGetGallery.Core/Services/AccessConditionWrapper.cs
- tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj
- tests/NuGetGallery.Core.Facts/Services/AccessConditionWrapperFacts.cs
- tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceFacts.cs
Note to self, add unit tests even on wrapper classes...
Progress on https://github.com/NuGet/Engineering/issues/1190.
> Add GenerateEmptyCondition and fix AccessConditionWrapper bug

- src/NuGetGallery.Core/Services/CloudBlobClientWrapper.cs
- src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs
- src/NuGetGallery.Core/Services/ICloudBlobClient.cs
- src/NuGetGallery.Core/Services/ICoreFileStorageService.cs
- src/NuGetGallery/Services/FileSystemFileStorageService.cs
- tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj
- tests/NuGetGallery.Core.Facts/Services/CloudBlobClientWrapperFacts.cs
- tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceFacts.cs
Progress on https://github.com/NuGet/Engineering/issues/1190
This is needed because `IProcessor` returns a `NupkgUrl`. Per Blob Storage's implementation of server-side copy, this URL must point to an Blob Storage location and must either be a public blob or authenticated with a SAS token:
https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob#request-headers
I could have chosen to make `IProcessor` return a container name and file name, but I think this is the wrong abstraction as it forces `IProcessor` nupkgs to be in the same region and account as the destination.
> Add overload to CopyFileAsync which supports a source URI

- src/NuGetGallery/Views/Authentication/SignIn.cshtml
Fixes:
- https://github.com/NuGet/NuGetGallery/issues/5606 - Show password login for local login.
- https://github.com/NuGet/NuGetGallery/issues/5040 - Simplify password login when no external providers present.
Now if there is no external provider configured, we will see password login on the first sign in page itself. 
Note: use `?w=1`(https://github.com/NuGet/NuGetGallery/pull/5613/files?w=1) to ignore whitespace changes
> Fix login page for local debugging.

- src/NuGetGallery/Configuration/AppConfiguration.cs
- src/NuGetGallery/Configuration/IAppConfiguration.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Services/IValidationService.cs
- src/NuGetGallery/Services/ValidationService.cs
- src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- src/NuGetGallery/Views/Shared/Gallery/Footer.cshtml
- src/NuGetGallery/Web.config
- tests/NuGetGallery.Facts/Services/ValidationServiceFacts.cs
Displays a notice on the Display Package page if the validation is taking longer than expected.
Progress on https://github.com/NuGet/Engineering/issues/1144
> [Validation] Display notice if package validation exceeds expectation

- src/NuGetGallery.Core/Services/CorePackageFileService.cs
- src/NuGetGallery.Core/Services/CryptographyService.cs
- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Services/ReflowPackageService.cs
- tests/NuGetGallery.Core.Facts/Services/CorePackageFileServiceFacts.cs
Progress on https://github.com/NuGet/Engineering/issues/1190.
Since we can now mutate packages via processors, it is possible for the hash in the DB to mismatch the hash of the actual package. Therefore, we should calculate the hash from the backed up stream.
I chose not to change the backup method to use `CopyFileAsync` (i.e. server-side copy) because this would have it's own race conditions and requires a `srcAccessCondition`. We have to download the package anyway to calculate the hash. We can revisit this later if we want to improve the performance.
Also, make the hash algorithm a required parameter to `CryptographyService.GenerateHash`. It's silly for the caller to not care about the hash algorithm, especially since you have to put the hash algorithm name in the database record …
> Get the package hash from the stream when backing up

- src/NuGetGallery/Controllers/ODataV2CuratedFeedController.cs
- src/NuGetGallery/Controllers/ODataV2FeedController.cs
- src/NuGetGallery/OData/SearchService/SearchAdaptor.cs
- tests/NuGetGallery.Facts/Services/SearchAdaptorFacts.cs
This reverts commit 24256775e2c34c767f863bf3ff1036eccc7f9fa7.
We determined the issue with the commit was not actually caused by the commit but instead was an existing issue. As such, we are re-including it in the deployment.
> Hotfix: Revert "Hotfix: Revert "Fix SemVerLevel propagation in Odata Next links. (#5582)" (#5623)"

- tests/Scripts/RunP0Tests.bat
- tests/Scripts/RunP1Tests.bat
- tests/Scripts/RunP2Tests.bat
Today, since we delete the Web UI test results, only the P2 Web UI results are available.
We can depend on the CI build configurations "Clean all build directories" setting to do the clean-up.
> Don't delete Web UI test results and only delete minimal functional test results

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Services/IReadMeService.cs
- src/NuGetGallery/Services/ReadMeService.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Services/ReadMeServiceFacts.cs
Fix https://github.com/NuGet/NuGetGallery/issues/5625.
28 packages were affected by this bug. The symptom was that validation failed due to broken .nupkg URL passed to the validator. This happened because I made a change to orchestrator to use the `Package.PackageStatusKey` to determine where the .nupkg should be (`packages` container vs. `validation` container). Because of this gallery bug, there was a short window of time that the package was in the `Available` state but the package was _not_ in the `packages` container.
All 28 packages were UI uploads and all has readmes added on upload.
> Don't immediately commit readme changes during UI upload

- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/RouteName.cs
- src/NuGetGallery/Services/IMessageService.cs
- src/NuGetGallery/Services/IUserService.cs
- src/NuGetGallery/Services/MessageService.cs
- src/NuGetGallery/Services/UserService.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- src/NuGetGallery/UrlExtensions.cs
- tests/NuGetGallery.Facts/Controllers/ControllerTests.cs
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
- tests/NuGetGallery.Facts/Services/MessageServiceFacts.cs
- tests/NuGetGallery.Facts/Services/UserServiceFacts.cs
https://github.com/NuGet/NuGetGallery/issues/5263
This PR adds email notifications to transforming users into organizations.
1 - Asking a user to become the admin of your transformed account
2 - Accepting a request to become an admin of a transformed account
3 - Rejecting a request to become the admin of a transformed account
4 - Cancelling a request for a user to become the admin of your transformed account
It also adds the ability to reject and cancel organization migration requests, to make it consistent with how the package ownership requests work.
Email text looks like:
1:
2:
3:
4:
> [Organizations] Transform User to Organization Notifications

- src/NuGetGallery/Controllers/AuthenticationController.cs
- src/NuGetGallery/Controllers/JsonApiController.cs
- src/NuGetGallery/Controllers/OrganizationsController.cs
- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/Services/IMessageService.cs
- src/NuGetGallery/Services/MessageService.cs
- tests/NuGetGallery.Facts/Controllers/AccountsControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/JsonApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/OrganizationsControllerFacts.cs
- tests/NuGetGallery.Facts/Services/MessageServiceFacts.cs
1 - If the target of the email is an organization, updated any reference of `you` or `your account` with `your organization`
2 - If the target of a package ownership email is an organization, the email sends to the admins of the organization and not the organization DL (because org admins are the only users who can handle these requests)
Messaging pending review with @anangaur
> [Organization] Update existing email notifications for organizations

- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs
- src/NuGetGallery.Core/Services/CloudBlobWrapper.cs
- src/NuGetGallery.Core/Services/FileUriPermissions.cs
- src/NuGetGallery.Core/Services/ICoreFileStorageService.cs
- src/NuGetGallery.Core/Services/ISimpleCloudBlob.cs
- src/NuGetGallery/Services/FileSystemFileStorageService.cs
- tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj
- tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceFacts.cs
- tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceIntegrationTests.cs
- tests/NuGetGallery.Core.Facts/Services/FileUriPermissionsFacts.cs
Progress on https://github.com/NuGet/Engineering/issues/1207.
Currently we only have `GetFileReadUriAsync` which allows downloading but nothing else. I am adding `GetPriviledgedFileUriAsync` which accepts arbitrary permissions. 
I am adding this method so that `IProcessor` running in the orchestrator processor can use this URL to both read and delete (for clean up) a temporary .nupkg, a la `FileUriPermissions.Read | FileUriPermissions.Delete`.
> Add GetPriviledgedFileUriAsync to create SAS enabled URLs

- src/NuGetGallery/NuGetGallery.csproj
Somehow, this got by and didn't fail NuGetGallery CI and instead only NuGetDeployment CI.
> Fix DEV build

- src/NuGetGallery/Views/Shared/_AccountConfirmationNotices.cshtml
https://github.com/NuGet/NuGetGallery/issues/5654
New organization as collaborator:
Existing organization as collaborator:
> [Organizations] Hide organization confirmation link when user is a collaborator

- src/NuGetGallery/Services/PackageService.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
Extend query performance from PR #5573 to the profiles page. See that PR for more details.
Scenario: View profile for user with 107 registrations, 52,289 versions
- Before: 1.8m, 2.0m, 2.0m => AVG=116s
- After: 4.39s, 4.32s, 4.36s => AVG=4.36s (-96%)
*This is after dropping outliers. Saw up to 6.4m for before on cold load.
Another optimization we should do is only select the current page... opened #5658 to track this.
> Improve profiles page query performance

- src/NuGetGallery.Core/CoreStrings.Designer.cs
- src/NuGetGallery.Core/CoreStrings.resx
- src/NuGetGallery.Core/Packaging/PackageMetadata.cs
- tests/NuGetGallery.Core.Facts/Packaging/PackageMetadataFacts.cs
Progress on https://github.com/NuGet/NuGetGallery/issues/5119.
There will be another PR to make `catalog2lucene` resilient to such catalog leaves.
> Reject duplicate metadata elements during upload

- src/NuGetGallery.Core/CoreStrings.Designer.cs
- src/NuGetGallery.Core/CoreStrings.resx
- src/NuGetGallery.Core/Packaging/PackageMetadata.cs
- tests/NuGetGallery.Core.Facts/Packaging/PackageMetadataFacts.cs
Address on https://github.com/NuGet/Engineering/issues/1308.
Address on https://github.com/NuGet/Engineering/issues/1309.
Address on https://github.com/NuGet/Engineering/issues/1310.
In short, two validations on upload or revalidate are being added:
1. Reject metadata element names that collide with those generated by feed2catalog.
1. Reject non-boolean values for boolean metadata fields.
Instead of overhauling .nuspec/.nupkg validation in gallery with XSD or some other strict approach, I am taking a minimal-ish approach that is least likely to break existing package authors. The goal here is to reject .nuspec metadata child elements that break V3. See the aforementioned issues for what is breaking. I don't want to tackle the problem of rejecting anything but the most perfect .nuspecs 😄. …
> Reject invalid boolean values and properties generated by feed2catalog

- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/Scripts/gallery/page-api-keys.js
- src/NuGetGallery/Services/ActionRequiringEntityPermissions.cs
- src/NuGetGallery/Services/ActionsRequiringPermissions.cs
- src/NuGetGallery/Services/IActionRequiringEntityPermissions.cs
- src/NuGetGallery/ViewModels/ApiKeyOwnerViewModel.cs
- src/NuGetGallery/Views/Users/ApiKeys.cshtml
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
We decided that allowing collaborators not to push new IDs and contact support was a weird experience.
This PR includes making that permissions change and also updating the API keys page to use the permissions service correctly.
https://github.com/NuGet/NuGetGallery/issues/5731
https://github.com/nuget/nugetgallery/issues/5104
> [Organizations] Give organization collaborators the same permissions on packages as administrators

- src/NuGetGallery/packages.config
- tests/NuGetGallery.Facts/App.config
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/packages.config
SDL: OSS reg automation can't locate this System.Net.Http beta version. Since these projects target net46, we should just use the version of System.Net.Http that is part of the framework.
Notes:
- NuGetGallery.Core still targets 4.5.2, so still needs the 4.1.0 reference
- NuGetGallery.Facts was updated to use the [beta version](https://github.com/NuGet/NuGetGallery/commit/c0fc2d6256a6b9abbf0a31d829f935cf3c0ee01f#diff-a193ba314cd03d77ec62c470e7006d83) in order to fix [MediaTypeHeaderValue errors](https://stackoverflow.com/questions/38355544/type-argument-system-net-http-headers-mediatypeheadervalue-violates-the-constr) from tests.
> Use System.Net.Http from net46

- src/NuGetGallery/Controllers/AccountsController.cs
- src/NuGetGallery/Controllers/OrganizationsController.cs
- src/NuGetGallery/Extensions/OrganizationExtensions.cs
- src/NuGetGallery/Services/ActionsRequiringPermissions.cs
- src/NuGetGallery/ViewModels/AccountViewModel.cs
- src/NuGetGallery/ViewModels/OrganizationAccountViewModel.cs
- src/NuGetGallery/ViewModels/UserAccountViewModel.cs
- src/NuGetGallery/Views/Organizations/ManageOrganization.cshtml
- src/NuGetGallery/Views/Organizations/_OrganizationAccountManageMembers.cshtml
- src/NuGetGallery/Views/Shared/_AccountConfirmationNotices.cshtml
- src/NuGetGallery/Views/Shared/_AccountProfilePicture.cshtml
- src/NuGetGallery/Views/Users/Profiles.cshtml
- tests/NuGetGallery.Facts/Controllers/AccountsControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/OrganizationsControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
https://github.com/NuGet/NuGetGallery/issues/5557
Site admins can now see the `Manage Organization` page for any user on the site and make changes to its membership.
In terms of UI, the only change is text on the manage organizations page that explains the permissions the current user has.
> Site admins should be able to modify organization membership

- src/NuGetGallery/Services/CloudDownloadCountService.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/Services/CloudDownloadCountServiceFacts.cs
Had some free time so I wanted to fix some intermittent 500s related to getting download counts on an ID. This PR addresses #5779.
Things done:
1. Use `ConcurrentDictionary` in CloudDownloadCountService instead of `Dictionary`. This allows concurrent reads (via HTTP requests) and writes (via a background refresh every 15 minutes)
1. Don't lowercase. Using `StringComparer.OrdinalIgnoreCase`. This should reduce allocations (not measured though).
1. Add unit tests, in particular one that repro'd the race condition on `Dictionary`.
Performance analysis:
Version | Operation | Duration
-- | -- | --
`Dictionary` | `Refresh` | 17.13 seconds
`Dictionary` | `TryGetDownloadCountForPackageRegistration` | 0.0009 ms
`ConcurrentDictionary` | `Refresh` | 17.70 seconds
`ConcurrentDictionary` | …
> Fix collection modified exception which causes rare HTTP 500s

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/page-manage-packages.less
- src/NuGetGallery/Views/Users/Packages.cshtml
https://github.com/NuGet/NuGetGallery/issues/5734
Remove extra padding below each table:
Show a message inside an empty section:
> Manage packages page minor UI fixes

- tests/NuGetGallery.Facts/Controllers/OrganizationsControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
Add more tests specifically covering mutation-based controller actions when the current user is not multi-factor authenticated.
> Certificates:  add more tests

- src/NuGetGallery/ViewModels/ListPackageItemRequiredSignerViewModel.cs
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- tests/NuGetGallery.Facts/ViewModels/ListPackageItemRequiredSignerViewModelFacts.cs
Fix https://github.com/NuGet/NuGetGallery/issues/5882.
Should display text instead of a disabled dropdown when the current user lacks permission to set the signing owner on a package with one owner.
> Certificates:  fix https://github.com/NuGet/NuGetGallery/issues/5882

- tests/NuGetGallery.Facts/SearchClient/RetryingHttpClientWrapperFacts.cs
The test NuGetGallery.SearchClient.RetryingHttpClientWrapperFacts.LoadBalancesBetweenValidUrisForGetAsync uses the random comparer to direct the requests. This makes it to be non-deterministic. Change the Assert to make it deterministic.
> Fix nondeterministic test.

- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/App_Start/OwinStartup.cs
There was a bug which would prevent content refresh on app start due to `NullReferenceException`, `DependencyResolver` cannot resolve a dependency in the `Autofac` builder, the resolver is set after the `load` method. Moving the code to OwinStartup fixes this issue.
> Refresh content on app start

- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/Services/DeleteAccountService.cs
- tests/NuGetGallery.Facts/Services/DeleteAccountServiceFacts.cs
https://github.com/NuGet/NuGetGallery/issues/5924
We must delete these API keys because
- they are no longer valid when the owner that they are scoped to is deleted
- there is a DB constraint that the user in the owner scope exists
> Delete API keys scoped to a user when that user is deleted

- src/NuGetGallery/Services/ReadMeService.cs
- tests/NuGetGallery.Facts/Services/ReadMeServiceFacts.cs
Fixes https://github.com/NuGet/NuGetGallery/issues/5778
> Handle ArgumentNullException and HTTP 500 when readme host is invalid.

- src/NuGetGallery/Services/MessageService.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- tests/NuGetGallery.Facts/Services/MessageServiceFacts.cs
- incorrect account name in the delete account email message body.
[Issue 6035](https://github.com/NuGet/NuGetGallery/issues/6035)
> Fix issue 6035 

- src/NuGetGallery/Services/ReservedNamespaceService.cs
- tests/NuGetGallery.Facts/Services/ReservedNamespaceServiceFacts.cs
https://github.com/NuGet/NuGetGallery/issues/6039
(also see https://github.com/NuGet/NuGetGallery/pull/6043)
> Correctly unverify packages when they are removed from their reserved namespaces (HOTFIX)

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Scripts/gallery/async-file-upload.js
This addresses most of https://github.com/NuGet/NuGetGallery/issues/5850
* Adds AI logging for any failure fed back to gallery during validation flow.
* Scrolls error message container into view on Upload page when Submit is pressed (if there are any errors to show). scrollIntoView tested on IE, Edge, Firefox, Chrome.
> Minor fixes for verify page.

- tools/Update-Databases.ps1
Fixes setup script by using the global packages cache, which PackageRef restore uses.
> Setup: packageRef migration fix

- src/GalleryTools/GalleryTools.csproj
- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/Areas/Admin/AdminAreaRegistration.cs
- src/NuGetGallery/Areas/Admin/DynamicData/DynamicDataManager.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/SqlAggregateStatsService.cs
- src/NuGetGallery/Web.config
- tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
- tests/NuGetGallery.Facts/Framework/TestContainer.cs
Addresses feedback from #6011 
- Removed `ISqlConnectionFactory` keyed registration (registration actually only needed for Gallery DB)
- Upgrade to Autofac v4.6.2
- aligns with version from NuGet.Jobs
- supports attribute-based keyed registrations, if we eventually need it
- deprecates `Container.Update` which is discouraged
- Test updates related to Autofac v4.6.2 deprecation of `Container.Update`
> Autofac upgrade and cleanup

- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/Services/ValidationService.cs
- tests/NuGetGallery.Facts/Services/ValidationServiceFacts.cs
Regression: The SQL AAD work changed EF context behavior by creating/opening DB connections upfront at EF context construction... instead of passing in connectionString and deferring the connection until EF execution. This caused a dependency on the validation DB when creating the `ValidationService`, which isn't done behind a feature flag. Note that the `ValidationAdminService` is used by `ValidationController`, which is behind the feature flag... so I left it alone.
Fix: make the `IEntityRepository<PackageValidationSet>` an optional argument to the ValidationService.
Also opened the following to investigate deferring connections when I have more time:
- https://github.com/NuGet/Engineering/issues/1472
> Regression fix: validation db dependency

- src/NuGetGallery/NuGetGallery.csproj
Depends on https://github.com/NuGet/ServerCommon/pull/162
Fixes https://github.com/NuGet/Engineering/issues/1472
Alternative to https://github.com/NuGet/NuGetGallery/pull/6063, but I think we should do both:
- Don't connect to validation DB unless feature flag is enabled
- Defer DB connection open to the EF context
> Defer open of DB connection to EF context

- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery/NuGetGallery.csproj
Updating our references to NuGet.Client libraries in preparation to consume an upcoming change.
All tests pass. Manual scenario pass doesn't seem to indicate any obvious scenario failures.
> Update client library references

- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/IPackageService.cs
- src/NuGetGallery/Services/PackageService.cs
Adds an additional nupkg validation that will fail if a package contains any entries that would result in extraction outside of the target extraction directory.
See https://github.com/NuGet/NuGet.Client/pull/2296 and https://github.com/NuGet/NuGet.Client/pull/2302 for client change details
NuGet Client:
NuGet Website:
> Add Zip Entry restriction

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/page-display-package.less
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- src/NuGetGallery/Views/Packages/_ValidationIssue.cshtml
- tests/NuGetGallery.Facts/Views/Packages/ValidationIssueFacts.cs
In other words:
- show all errors in a single display
- explain that you can reupload the package once you've fixed the issues (or to contact support if validation failed for an unknown reason)
> Improve gallery user experience for package reupload

- src/NuGetGallery/Services/MessageService.cs
https://github.com/NuGet/NuGetGallery/issues/6022
```
The user 'requestor' has requested that user 'pending' be added as an administrator of organization 'org'. A confirmation mail has been sent to user 'pending' to accept the membership request. This mail is to inform you of the membership changes to organization 'org' and there is no action required from you.
```
> Fix the mail template for the addition of a member to an org

- src/NuGetGallery.Core/Extensions/PackageValidationSetExtensions.cs
- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery.Core/Services/CoreMessageService.cs
- src/NuGetGallery.Core/Services/ICoreMessageService.cs
- src/NuGetGallery/Services/ValidationService.cs
- tests/NuGetGallery.Facts/Services/MessageServiceFacts.cs
https://github.com/NuGet/NuGetGallery/issues/6098
Example:
The package [MyPackage 1.0.0]({packageUrl}) failed validation because of the following reason(s):
- *NU3007:* Package signatures must have format version 1.
- This package must be signed with a registered certificate. [Read more...](https://aka.ms/nuget-signed-ref)
Your package was not published on NuGet Gallery and is not available for consumption.
Once you've fixed all the issues with your package, you can reupload it with the same ID and version.
> Include failure reasons in email sent when package validation fails

- src/NuGetGallery/Views/Shared/_AccountProfilePicture.cshtml
Current wording:
> We use the verified email address for your organization and gravatar.com to get the publicly visible profile picture. gravatar.com to change the profile picture for your organization.
Fixed wording:
> We use the verified email address for your organization and gravatar.com to get the publicly visible profile picture. Go to gravatar.com to change the profile picture for your organization.
Fixes https://github.com/NuGet/NuGetGallery/issues/6096
> Fix organization's profile picture wording

- src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs
Issue #https://github.com/NuGet/NuGetGallery/issues/6081
Was unable to reproduce the NullRefException, and don't see more instances in AI. Originating source from the stack is
https://github.com/NuGet/NuGetGallery/blob/a171bd1a86fad6950e1d0c6531a3c286e9276812/src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs#L408
Per https://github.com/Azure/azure-storage-net/issues/271, looks like the Storage SDK can generate `StorageException`'s with `ExtendedErrorInformation` set to null.
Note that WebJobs found the root cause for their null `StorageException.ExtendedErrorInformation` to be a missing binding redirect. I'm doubtful that it's the case here, as there's only 4 instances of this seen in AI. This fix will result in throwing the original exception instead of a …
> Fix NullRef from StorageException.ExtendedErrorInformation

- tests/NuGetGallery.FunctionalTests/ApiManagement/CachingTests.cs
- tests/NuGetGallery.FunctionalTests/NuGetGallery.FunctionalTests.csproj
- tests/NuGetGallery.FunctionalTests/packages.config
- tests/Scripts/BuildTests.ps1
- tests/Scripts/RunTests.ps1
1. APIM behavior:
- If a request meets the criteria it will be cached
- If a request meets the criteria and it's a cache miss we add header x-cache: MISS
- If a request meets the criteria and it's a cache hit we add header x-cache: HIT
2. The tests belong to a new Category (ApiManagement) and will NOT run normaly. In the future, when we automate APIM config deployment we can use them for verification. Until then, we will run them from VSTS manually during config deployment.
3. Changed the build to use MSBuild 15.0. Tested in VSTS for all tests.
> Functional tests for OData API api/v2/packages() caching 

- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Extensions/HttpExceptionExtensions.cs
- src/NuGetGallery/Extensions/HttpRequestExtensions.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Scripts/gallery/async-file-upload.js
- src/NuGetGallery/Services/TelemetryService.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
Fixes https://github.com/NuGet/NuGetGallery/issues/6143
**API push**
Hits `maxRequestLength` (ASP.NET) limit which throws HttpException.
We now handle this to return status 413 with better error message, and client no longer retries.
```
NuGet Version: 4.6.2.5055
Pushing chenriks252.nupkg to 'https://localhost/api/v2/package/'...
PUT https://localhost/api/v2/package/
RequestEntityTooLarge https://localhost/api/v2/package/ 8448ms
Response status code does not indicate success: 413 (The package file exceeds the size limit of 250MB.).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 413 (The package file exceeds the
size limit of 250MB.).
at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
at …
```
> Improve experience when users hit package size limit

- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery.Core/Services/CorePackageFileService.cs
- src/NuGetGallery.Core/Services/IFileMetadataService.cs
- src/NuGetGallery.Core/Services/IMetadataFileService.cs
- src/NuGetGallery.Core/Services/PackageFileServiceMetadata.cs
- src/NuGetGallery/Services/PackageFileService.cs
- tests/NuGetGallery.Core.Facts/Services/CorePackageFileServiceFacts.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/Services/PackageFileServiceMetadataFacts.cs
Refactor CorePackageFileService to allow the file metadata to be passed at construction time instead to use directly the CoreConstants values. This will allow the same logic for file manipulation to be used for packages and symbols.
> Refactor CorePackageFileService 

- src/NuGetGallery/Scripts/gallery/async-file-upload.js
The error messages are not displayed correclty. 
Example:
With this change the error is displayed:
> Display errors fix.

- src/NuGetGallery.Core/CoreConstants.cs
- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery.Core/Services/CorePackageService.cs
- src/NuGetGallery.Core/Services/CoreSymbolPackageService.cs
- src/NuGetGallery.Core/Services/ICoreSymbolPackageService.cs
- src/NuGetGallery.Core/Services/SymbolPackageFileServiceMetadata.cs
- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/ISymbolPackageService.cs
- tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj
- tests/NuGetGallery.Core.Facts/Services/CoreSymbolPackageServiceFacts.cs
Adds the entity and definitions required by gallery, jobs and orchestrator. Also added tests.
> [NuGet Symbol Server] Add core symbol package service

- src/NuGetGallery/Controllers/PackagesController.cs
There was a bug introduced by #6038 that caused FileStorage uploads to behave incorrectly.
The behaviour is detailed by #6175 
This PR moves the delete outside of the Using statement and swallows if it fails.
Behaviour can change from swallow if we decide this is not how we want to handle this.
> Move delete outside of using so FileStorage can delete the file.

- tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedExtendedTests.cs
Fixes #6168 (functional test failure when <10 distinct packages in feed)
> Fix PackageFeedSortingTest functional test

- src/NuGetGallery.Core/Extensions/PackageRegistrationExtensions.cs
- tests/NuGetGallery.Core.Facts/Extensions/PackageRegistrationExtensionsFacts.cs
Progress on https://github.com/NuGet/NuGetGallery/issues/6181.
The fast check (not in this PR) will reject the package if any of these conditions are true:
- Signing is required on the ID and there is no signature file
- signing is required if all signers have at least one certificate
- Signing is not allowed on the ID and there is a signature file
- signing is not allowed if all signers have no certificates
It is possible for signing to be allowed but not required if there are two owners on a package: one with certificates and one without certificates. In this case we can't do a fast check based off of the presence of a signature file.
I chose to name the method `IsSigningAllowed` instead of `IsSigningNotAllowed` so the call sign can negate the behavior without a double negative. The …
> Add IsSigningAllowed method

- src/NuGetGallery/App_Data/Files/Content/Symbols-Configuration.json
- src/NuGetGallery/Constants.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/ContentObjectService.cs
- src/NuGetGallery/Services/ISymbolsConfiguration.cs
- src/NuGetGallery/Services/SymbolsConfiguration.cs
- tests/NuGetGallery.Facts/Services/ContentObjectServiceFacts.cs
Addresses https://github.com/NuGet/NuGetGallery/issues/6169 
Also, I have reduced the reload duration to 5 minutes for configuration, it was 1 hour. This feature flag will be used in subsequent PRs to allow/prevent symbols upload until we go live with this feature.
> Add Symbols Feature flag

- src/Bootstrap/package-lock.json
- src/Bootstrap/package.json
Should fix https://github.com/NuGet/Engineering/issues/1565
Recommended updates, per https://github.com/NuGet/NuGetGallery/network/dependencies
- fresh, 0.5.0 (recommend >= 0.5.2)
- mime, 1.3.4 (recommend >= 1.4.1)
- no-case, 2.3.1 (recommend >= 2.3.2)
- tough-cookie, 2.3.2 (recommend >= 2.3.3)
Applied updates with the following commands, from .\src\Bootstrap (npm version 6.1.0). Note that there were no changes to the generated files under .\dist
```
npm install tough-cookie@2.3.3
npm install no-case@2.3.2
npm install mime@1.4.1
npm install fresh@0.5.2
rm .\dist\css\*
rm .\dist\js\*.js
grunt
```
> Update bootstrap dependency versions

- src/NuGetGallery/App_Data/Files/Content/Symbols-Configuration.json
This typo means that anybody running the gallery locally will get an exception at https://github.com/NuGet/NuGetGallery/blob/dev/src/NuGetGallery/Services/SymbolsConfiguration.cs#L30
> Fix Symbols-Configuration.json

- src/NuGetGallery/Configuration/AppConfiguration.cs
- src/NuGetGallery/Configuration/IAppConfiguration.cs
- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Scripts/gallery/async-file-upload.js
- src/NuGetGallery/Services/IPackageUploadService.cs
- src/NuGetGallery/Services/PackageCommitResult.cs
- src/NuGetGallery/Services/PackageService.cs
- src/NuGetGallery/Services/PackageUploadService.cs
- src/NuGetGallery/Services/PackageValidationResult.cs
- src/NuGetGallery/Services/PackageValidationResultType.cs
- src/NuGetGallery/Services/SearchExtensionMethods.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- src/NuGetGallery/Views/Packages/UploadPackage.cshtml
- src/NuGetGallery/Web.config
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
- tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs
- tests/NuGetGallery.Facts/TestUtils/TestServiceUtility.cs
Address https://github.com/NuGet/NuGetGallery/issues/6181.
Pushing an unsigned package when a signed one is required.
```
> nuget.exe push .\testunsigned.1.0.0.nupkg -apikey FOO -source https://localhost
Pushing testunsigned.1.0.0.nupkg to 'https://localhost'...
PUT https://localhost/api/v2/package/
BadRequest https://localhost/api/v2/package/ 387ms
Response status code does not indicate success: 400 (This package must be signed with a registered certificate.).
```
Pushing a signed package when an unsigned one is required.
```
> nuget.exe push .\system.rido.1.0.1.nupkg -apikey FOO -source https://localhost
Pushing system.rido.1.0.1.nupkg to 'https://localhost'...
PUT https://localhost/api/v2/package/
BadRequest https://localhost/api/v2/package/ 974ms
Response status code does not indicate …
```
> Fail fast when package signing status does not match owner/ID requirements

- src/NuGetGallery.Core/CoreConstants.cs
- src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs
This will be needed by the revalidation job to determine the health of the ingestion pipeline (the revalidation job uses the Gallery's storage APIs).
Part of https://github.com/NuGet/Engineering/issues/1441
> [Status] Add the status folder

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/page-account-settings.less
- src/NuGetGallery/App_Code/ViewHelpers.cshtml
- src/NuGetGallery/Scripts/gallery/certificates.js
- src/NuGetGallery/ViewModels/ListCertificateItemViewModel.cs
- src/NuGetGallery/Views/CuratedFeeds/CuratedFeed.cshtml
- src/NuGetGallery/Views/Packages/UploadPackage.cshtml
- src/NuGetGallery/Views/Shared/_AccountCertificates.cshtml
- src/NuGetGallery/Views/Users/Account.cshtml
- src/NuGetGallery/Views/Users/ApiKeys.cshtml
The process signature job (part of package push validation) populates the certificate details when a package is first pushed with that author signing certificate.
Progress on https://github.com/NuGet/NuGetGallery/issues/6183.
> Add gallery UI to display new certificate information

- src/NuGetGallery/Views/Shared/_ListPackage.cshtml
Fix the "NuGet/NuGetGallery#6136 Owner info missing for a package" issue.
> Fix owner info missing issue

- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Infrastructure/HttpStatusCodeWithServerWarningResult.cs
- src/NuGetGallery/RequestModels/SubmitPackageRequest.cs
- src/NuGetGallery/RequestModels/VerifyPackageRequest.cs
- src/NuGetGallery/Services/IPackageUploadService.cs
- src/NuGetGallery/Services/PackageUploadService.cs
- src/NuGetGallery/Services/PackageValidationResult.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- src/NuGetGallery/Views/Packages/UploadPackage.cshtml
- src/NuGetGallery/Views/Packages/_VerifyMetadata.cshtml
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs
Address https://github.com/NuGet/NuGetGallery/issues/6184.
Address https://github.com/NuGet/NuGetGallery/issues/6253.
```
> nuget.exe push "system.rido.1.0.3 (unsigned).nupkg" -source https://localhost/api/v2/package -apikey myapikey
Pushing system.rido.1.0.3 (unsigned).nupkg to 'https://localhost/api/v2/package'...
PUT https://localhost/api/v2/package/
WARNING: The previous package version '1.0.1' is signed but the uploaded package is unsigned. To avoid this warning, sign the package before uploading.
Created https://localhost/api/v2/package/ 38504ms
Your package was pushed.
> Warn when an unsigned package is pushed after a signed one

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/page-manage-packages.less
- src/NuGetGallery/Views/Users/Packages.cshtml
Fixes #5909 
Explanation of fix: https://stackoverflow.com/questions/10672586/how-to-make-select-elements-shrink-to-max-width-percent-style-within-fieldset
Screenshot:
> Signing owner selection box on Manage Packages page can cause table to overflow

- src/NuGetGallery/Services/BackgroundMessageService.cs
- src/NuGetGallery/Telemetry/QuietLog.cs
QuietLog uses Elmah, which uses DI resolving at log time, rather than being contructed at HTTP request time. Autofac MVC's lifetime manager requires a HttpContext, which is null in a background thread, so there was no good/easy way to resolve the Elmah logger in a background thread. Logging only to app insights instead.
> Fix logging exceptions from background thread

- src/GalleryTools/App.config
- src/GalleryTools/Commands/BackfillRepositoryMetadataCommand.cs
- src/GalleryTools/GalleryTools.csproj
- src/GalleryTools/Program.cs
- src/GalleryTools/Readme.md
/// This tool collect repository metadata for all packages in the DB from nuspec files in V3 flat container and updates DB with this data.
/// Usage:
/// 1. To collect repository metadata:
///     a. Configure app.config with DB information and service index url
///     b. Run this tool with: GalleryTools.exe -c
/// This will create a file repositoryMetadata.txt with all collected data. You can stop the job anytime and restart. cursor.txt contains current position.    
/// 
/// 2. To update DB:
///     a. Run GalleryTools.exe -u  
/// This will update DB from file repositoryMetadata.txt. You can stop the job anytime and restart.
> Backfill repo metadata tool

- src/NuGetGallery.Core/Entities/User.cs
- src/NuGetGallery/Controllers/AccountsController.cs
- src/NuGetGallery/Services/UserService.cs
- tests/NuGetGallery.Facts/Controllers/AccountsControllerFacts.cs
- tests/NuGetGallery.Facts/Services/UserServiceFacts.cs
https://github.com/NuGet/NuGetGallery/issues/5509
> If ConfirmEmailAddresses config is false, users should not be required to confirm changing their email

- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Fixes #6247.
As discussed offline with @anangaur, remove bold and (current) text, and use a background colour instead of simply removing bold from non-current versions as asked in original issue.
Viewing most recent version:
Viewing older version:
package with only a single version:
hover link:
> Package history current version highlight

- src/NuGetGallery.Core/Services/CoreMessageService.cs
- src/NuGetGallery.Core/Services/ICoreMessageService.cs
- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/Controllers/AccountsController.cs
- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/AuthenticationController.cs
- src/NuGetGallery/Controllers/JsonApiController.cs
- src/NuGetGallery/Controllers/OrganizationsController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Controllers/PagesController.cs
- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/BackgroundMessageService.cs
- src/NuGetGallery/Services/IMessageService.cs
- src/NuGetGallery/Services/ITelemetryClient.cs
- src/NuGetGallery/Services/ITelemetryService.cs
- src/NuGetGallery/Services/MessageService.cs
- src/NuGetGallery/Services/TelemetryClientWrapper.cs
- src/NuGetGallery/Services/TelemetryService.cs
- src/NuGetGallery/Telemetry/QuietLog.cs
- tests/NuGetGallery.Facts/Controllers/AccountsControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/JsonApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/OrganizationsControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/PagesControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
- tests/NuGetGallery.Facts/Services/MessageServiceFacts.cs
The first commit is just a revert of what was previously reviewed and merged in dev. So, you can save yourself some time by just looking at the second commit's changes.
The problem with the previous PR that needed to be reverted was that previously emails are sent synchronously, so only one email being sent at a time. In order to prevent users waiting a long time for HTTP responses, emails now are sent in the background. However, when a single MVC action sends two or more messages, only the first would be sent and the others would throw an exception because the SmtpClient couldn't start sending a new message while an async operation was already in progress.
This PR fixes that issue by creating a BackgroundMessageServiceFactory. When an instance of BackgroundMessageService detects that it …
> Retry failed emails

- src/NuGetGallery/App_Start/Routes.cs
- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/RouteName.cs
- src/NuGetGallery/Services/FileSystemFileStorageService.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- src/NuGetGallery/UrlExtensions.cs
- src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
- tests/NuGetGallery.Facts/Services/FileSystemFileStorageServiceFacts.cs
- tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs
This PR adds support to download the snupkg from the package details page.
Addresses #5978  and #5970, also added tests.
The idea is to allow downloading a snupkg if the latest uploaded snupkg is "Available". If there is a newer uploaded snupkg that failed validations or still validating, no download allowed. This is taken care of in the download API and in the package details page view.
> [NuGet Symbol Server] Add download symbols support to Package details page

- src/NuGetGallery.Core/CoreConstants.cs
- src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs
- tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceFacts.cs
This sets the `CacheControl` property on all blobs to 2 minutes. This affects all uploaded blobs for all blob containers.
Fixes https://github.com/NuGet/NuGetGallery/issues/6285
> Set the CacheControl property on stored blobs

- src/NuGetGallery/Views/Shared/_AccountCertificates.cshtml
fixes #6208 
user's account setting unchanged:
organisation settings page changed:
> Improve manage certificates message

- src/Bootstrap/package-lock.json
- src/Bootstrap/package.json
Recommended updates, per https://github.com/NuGet/NuGetGallery/network/dependencies
- debug, 2.6.9 (recommend >= 2.6.9)
- hoek, 4.2.1. (recommend >= 4.2.1)
Applied updates with the following commands, from .\src\Bootstrap (npm version 6.2.0). Note that there were no changes to the generated files under .\dist
```
npm install debug@2.6.9
npm install hoek@4.2.1
rm .\dist\css\*
rm .\dist\js\*.js
grunt
```
Addresses https://github.com/NuGet/Engineering/issues/1634
> Update bootstrap dependencies

- src/NuGetGallery/Constants.cs
- src/NuGetGallery/Controllers/JsonApiController.cs
- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/Services/UserService.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- tests/NuGetGallery.Facts/Controllers/JsonApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
- tests/NuGetGallery.Facts/Services/UserServiceFacts.cs
https://github.com/NuGet/NuGetGallery/issues/6133
For add member/add owner/transform to org, if an email address is input instead of a username, fail with a specific message telling the user to type in a username instead of "account not found".
> Add member/add owner/transform to org fails with specific message if email is input instead of username

- src/NuGet.Services.Search.Client/Client/SearchClient.cs
- src/NuGet.Services.Search.Client/Client/ServiceResponse.cs
- src/NuGet.Services.Search.Client/NuGet.Services.Search.Client.csproj
- src/NuGetGallery/NuGetGallery.csproj
I've created a strong name version of all dependencies that are not already strong named. These packages are on `nuget-build`. The same SNK was used for all of these packages and is stored in our KeyVault.
This is the same process taken over a year ago to enable strong naming on NuGetGallery.Core, with:
- elmah.corelibrary.strongname
- elmah.sqlserver.strongname
- elmah.strongname
Progress on https://github.com/NuGet/Engineering/issues/1577.
> Use strong name version of third party dependencies

- src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs
- tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceFacts.cs
Set the same max-age for the symbol packages blobs as for the packages.
> Symbol-packages cache control

- src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
JAWS has a bug where they do not read our nav bar's tabs correctly.
After more analysis, it appears that we are using roles incorrectly, and we can avoid the bug by fixing our usage of roles.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/643637
> Accessibility - Fix nav roles

- src/NuGet.Services.Search.Client/Client/RetryingHttpClientWrapper.cs
- src/NuGet.Services.Search.Client/Client/SearchClient.cs
- src/NuGetGallery/Infrastructure/Lucene/ExternalSearchService.cs
- src/NuGetGallery/Queries/AutoCompleteServiceQuery.cs
- tests/NuGetGallery.Facts/SearchClient/RetryingHttpClientWrapperFacts.cs
https://github.com/NuGet/NuGetGallery/issues/6229
Unfortunately we can't use `QuietLog` directly because `NuGet.Services.Search.Client` doesn't have a dependency on `NuGetGallery`, so I've added an `Action` parameter.
> Log search service exceptions encountered during retry

- src/GalleryTools/Commands/VerifyApiKeyCommand.cs
- src/GalleryTools/GalleryTools.csproj
- src/GalleryTools/Program.cs
I had a support request where I had to verify the identity of a nuget.org account with a lost email. Part of this verification process was comparing an expired API key against what we have in the database.
I wrote this tool to support this.
> Add tool to verify the clear-text of an API key

- src/NuGetGallery/Views/Packages/_ImportReadMe.cshtml
- src/NuGetGallery/Views/Users/ApiKeys.cshtml
- src/NuGetGallery/Views/Users/PasswordSent.cshtml
Address https://github.com/NuGet/NuGetGallery/issues/6318. This problem happens when the legacy API key was used more than 365 days ago but has not been used for an API call. This leads to the `HasExpired` boolean to be `true` but the `Expires` nullable `DateTime` to be null. The product code sets `HasExpired` but leaves `Expires` as null since this is set to `DateTime.UtcNow` at API call time.
The server side code is here:
https://github.com/NuGet/NuGetGallery/blob/1b9875706fb5fda0313de0e7c235603946ef3856/src/NuGetGallery/Authentication/AuthenticationService.cs#L591-L593
Also, fix some cases where we say "url" instead of "URL", because it bothered me.
The aka.ms link in the PR goes here:
https://blog.nuget.org/20170202/introducing-scoped-api-keys.html#faqs
Eventually, this should go to a …
> Fix inconsistent messaging around expired legacy API key

- src/NuGetGallery/Configuration/AppConfiguration.cs
- src/NuGetGallery/Configuration/IAppConfiguration.cs
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- src/NuGetGallery/Views/Shared/Gallery/Layout.cshtml
- src/NuGetGallery/Web.config
Progress on https://github.com/NuGet/NuGetGallery/issues/6381. I will set this to `true` on DEV and INT.
Setting `ViewBag.BlockSearchEngineIndexing` to `true` allows you block search engines _only_ when the site-wide configuration is `false`. There is currently no scenario where an individual page needs to be indexed but the site in general is not.
> Add BlockSearchEngineIndexing to allow site-wide search engine indexing

- src/NuGetGallery/Controllers/ApiController.cs
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
- tests/NuGetGallery.Facts/Framework/MemberDataHelper.cs
If `VerifyPackageKeyAsync`, `DeletePackage`, or `PublishPackage` were called without a valid version string, they could throw because the `NuGetVersion.Parse` used in `GetHttpResultFromFailedApiScopeEvaluation` would throw. This fixes that issue.
> ApiController actions should not throw exceptions when called with an unparseable version

- src/NuGetGallery/Authentication/Providers/AzureActiveDirectoryV2/AzureActiveDirectoryV2Authenticator.cs
This fixes https://github.com/NuGet/NuGetGallery/issues/5150 
The new token option enforces Azure AD auth to show the multiple options for account selection.
> Fix MSA/AAD login account selection

- src/NuGetGallery/Views/Packages/Delete.cshtml
https://github.com/NuGet/NuGetGallery/commit/b1ba68e5d4a17d8c87b7686fbc6acd85f38185aa has a bug where if you try to delete a package through the package details page (id/version/delete) and not the admin flow, it fails.
Didn't catch this earlier because I forgot to verify on DEV/INT that the package page delete still worked in addition to verifying that the admin page delete worked.
> Hotfix: fix package delete through package details page

- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery.Core/PackageMetadataExtensions.cs
- src/NuGetGallery.Core/StreamExtensions.cs
- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Helpers/ZipArchiveHelpers.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/ISymbolPackageUploadService.cs
- src/NuGetGallery/Services/PackageCommitResult.cs
- src/NuGetGallery/Services/SymbolPackageService.cs
- src/NuGetGallery/Services/SymbolPackageUploadService.cs
- src/NuGetGallery/Services/SymbolPackageValidationResult.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- src/NuGetGallery/Views/Packages/UploadPackage.cshtml
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
- tests/NuGetGallery.Facts/Services/SymbolPackageUploadServiceFacts.cs
This is a preparation PR for adding support to gallery for symbols package upload.
I have refactored code out from the `ApiController` for the symbols upload, so that we can reuse the code in `PackagesController` and keep common code in single place. Also, as part of this I had to refactor/re-write some tests for the coverage. I do not touch the Package upload flow(which should also be refactored) as part of this PR, since its a lot more refactor and out of scope for the symbol upload flow. 
Also, refactored some part of `PackagesController` to reuse upload page in gallery. In subsequent PRs I will be doing additive changes to enhance this controller for symbols upload.
Apologies for the big PR(refactoring is a pain)
> [NuGet Symbol Server] Gallery upload - Refactoring

- src/NuGetGallery.Core/Entities/DatabaseWrapper.cs
- src/NuGetGallery.Core/Entities/DbContextTransactionWrapper.cs
- src/NuGetGallery.Core/Entities/IDatabase.cs
- src/NuGetGallery.Core/Entities/IDbContextTransaction.cs
- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- tests/NuGetGallery.Facts/Services/DeleteAccountServiceFacts.cs
- tests/NuGetGallery.Facts/Services/PackageDeleteServiceFacts.cs
- tests/NuGetGallery.Facts/Services/PackageOwnershipManagementServiceFacts.cs
- tests/NuGetGallery.Facts/Services/ReflowPackageServiceFacts.cs
- tests/NuGetGallery.Facts/TestUtils/TestServiceUtility.cs
Fix https://github.com/NuGet/Engineering/issues/1745. This uses a mocked `IDatabase` instead of LocalDB. 
Services that only use `IDatabase` for a transaction:
- `DeleteAccountService`
- `PackageOwnershipManagementService`
- `ReflowPackageService`
- `ReservedNamespaceService`
Services that run SQL, but don't unit test the outcome:
- `PackageDeleteService`
In other words, the concrete database was being connected to but never used for test assertions.
> Use mock IDbContextTransaction instead of concrete transaction object

- src/NuGetGallery/Configuration/AppConfiguration.cs
- src/NuGetGallery/Configuration/IAppConfiguration.cs
- src/NuGetGallery/Controllers/ODataV2CuratedFeedController.cs
- src/NuGetGallery/Services/CuratedFeedService.cs
- src/NuGetGallery/Services/ICuratedFeedService.cs
- tests/NuGetGallery.Facts/Controllers/ODataV2CuratedFeedControllerFacts.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/Services/CuratedFeedServiceFacts.cs
Progress on https://github.com/NuGet/NuGetGallery/issues/6470. Depends on https://github.com/NuGet/NuGetGallery/pull/6483.
This will allow us to disable the 'webmatrix', 'windows8-packages', and 'dotnetframework' feeds before completely deleting them.
The 'microsoftdotnet' feed will eventually redirect to the main feed. This work is not yet done but is tracked here: https://github.com/NuGet/NuGetGallery/issues/6472.
> Add configuration value to disable specific curated feeds

- src/NuGetGallery/Configuration/AppConfiguration.cs
- src/NuGetGallery/Configuration/IAppConfiguration.cs
- src/NuGetGallery/Controllers/ODataV2CuratedFeedController.cs
- tests/NuGetGallery.Facts/Controllers/ODataFeedControllerFactsBase.cs
- tests/NuGetGallery.Facts/Controllers/ODataV2CuratedFeedControllerFacts.cs
Progress on https://github.com/NuGet/NuGetGallery/issues/6472. Depends on https://github.com/NuGet/NuGetGallery/pull/6486.
If a curated feed name is in this new list, it will not even be checked for existence in the DB. It will just use all packages. I considered an HTTP redirect or calling the `ODataV2FeedController` but chose to take this approach since it has the best change of not breaking existing clients.
> Add configuration value to redirect specific curated feeds to main feed

- src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs
- src/NuGetGallery.Core/Services/CloudFileReference.cs
- tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceIntegrationTests.cs
This is preventing the reliable pattern:
1. Read
1. Business logic,
1. Write, if etag still matches
Added an integration test that catches the problem.
> Fix potential race condition with etags returned by GetFileReferenceAsync

- tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs
- tests/NuGetGallery.FunctionalTests.Core/GalleryConfiguration.cs
- tests/NuGetGallery.FunctionalTests.Core/NuGetGallery.FunctionalTests.Core.csproj
- tests/NuGetGallery.FunctionalTests.Core/XunitExtensions/TyposquattingTestFactAttribute.cs
- tests/NuGetGallery.FunctionalTests/NuGetGallery.FunctionalTests.csproj
- tests/NuGetGallery.FunctionalTests/TyposquattingCheck/TyposquattingCheckForUploadPackageTests.cs
Finish the basic typo-squatting functional tests. 
Fix: https://github.com/NuGet/Engineering/issues/1595
> Typo-squatting: finish functional tests

- src/NuGetGallery.Core/Auditing/PackageAuditReasons.cs
- src/NuGetGallery.Core/Auditing/PackageCreatedVia.cs
- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Scripts/gallery/page-delete-package.js
- src/NuGetGallery/Services/ActionsRequiringPermissions.cs
- src/NuGetGallery/Services/ISymbolPackageUploadService.cs
- src/NuGetGallery/Services/ITelemetryService.cs
- src/NuGetGallery/Services/SymbolPackageUploadService.cs
- src/NuGetGallery/Services/TelemetryService.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- src/NuGetGallery/UrlHelperExtensions.cs
- src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
- src/NuGetGallery/ViewModels/ListPackageItemViewModel.cs
- src/NuGetGallery/Views/Packages/DeleteSymbols.cshtml
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Services/SymbolPackageUploadServiceFacts.cs
- tests/NuGetGallery.Facts/Services/TelemetryServiceFacts.cs
This PR adds delete support based on the spec: https://github.com/NuGet/Home/wiki/Symbols-Package-Upload-and-Delete-Workflow 
Also, added tests. 
Screenshot:
Signed in Owner:
Everyone else;
Delete page;
Confirm:
Symbols deleted! Yay!! no more option to delete the symbols package/or download symbols
> [NuGet Symbol Server] Add symbols delete support to gallery

- src/NuGetGallery/Authentication/AuthenticateExternalLoginResult.cs
- src/NuGetGallery/Authentication/AuthenticationService.cs
- src/NuGetGallery/Controllers/AuthenticationController.cs
- tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs
- tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
Fix issue https://github.com/NuGet/NuGetGallery/issues/6389
If the user registers using the MSA/AAD account, we will confirm the account and set up the email address automatically without sending any confirmation email. 
When the user changes email address, we will send the confirmation email as before.
> Fix email verification issue for AAD/MSA registration

- src/NuGetGallery/Configuration/AppConfiguration.cs
- src/NuGetGallery/Configuration/IAppConfiguration.cs
- src/NuGetGallery/Services/PackageUploadService.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- src/NuGetGallery/Web.config
- tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs
- tests/NuGetGallery.Facts/TestPackage.cs
- tests/NuGetGallery.Facts/TestUtils/TestServiceUtility.cs
Addresses https://github.com/NuGet/NuGetGallery/issues/6558
Added configuration option to reject the packages that have <license> metadata node in them in preparation for proper implementation of license metadata processing, so we don't create a backlog of packages to reprocess.
> Configurable rejection of packages with <license>

- src/NuGetGallery/Web.config
Fixes #6557
Added configuration option to web.config for the default value of [`AppConfiguration.FileStorageDirectory`](https://github.com/NuGet/NuGetGallery/blob/619bede5c0580cd553d4b5332f35454a12ebebbf/src/NuGetGallery/Configuration/AppConfiguration.cs#L111)
> Add setting 'Gallery.FileStorageDirectory' to web.config

- src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs
- src/NuGetGallery.Core/Services/ICoreFileStorageService.cs
- src/NuGetGallery/Services/FileSystemFileStorageService.cs
- tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceFacts.cs
Add an api for reading the etag for an azure blob.
> GetEtagAsync

- src/NuGetGallery/Authentication/Providers/AzureActiveDirectoryV2/AzureActiveDirectoryV2Authenticator.cs
- src/NuGetGallery/Controllers/AuthenticationController.cs
- src/NuGetGallery/Helpers/UriExtensions.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/UriExtensionsFacts.cs
Addresses #6100 - It is likely that the users were seeing 500 due to unhandled exceptions in AADv2 OIDC middleware. With this change, we will handle all the exceptions/failures that might occur during authentication and surface the received error message to the user for easier analysis and debugging.
> [MSA] Pass the error messages from AADv2 to gallery

- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery/NuGetGallery.csproj
Noticed assembly version loading issues in e2e tests.
Figured aligning these dependencies to the same version (`2.30.0-master-42731`) should fix these.
Message:
```
Could not load file or assembly 'NuGet.Versioning, Version=4.8.0.4, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. 
The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) 
Could not load file or assembly 'NuGet.Versioning, Version=4.3.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. 
The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) 
```
Stacktrace:
```
System.IO.FileLoadException:
at …
```
> Align all ServerCommon dependencies

- src/NuGetGallery/Web.config
Fixes the versioning issue with dev.
> Fix versioning issue in Gallery for NuGet.Versioning

- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery/NuGetGallery.csproj
This PR upgrades the gallery to rely on the latest stable ServerCommon dependencies.
This way, it is also in sync with the email publisher job.
> Upgrade gallery to stable ServerCommon v2.30 dependencies

- src/NuGetGallery/Web.config
Address https://github.com/NuGet/NuGetGallery/issues/6601.
Currently, HTTP 400s produced by IIS (unsafe character validation for URL path) get redirected to the HTTP 500 error page.
> Redirect HTTP 400 to a specific error page instead of the default for HTTP 500

- src/NuGetGallery/Controllers/ODataV1FeedController.cs
- src/NuGetGallery/Controllers/ODataV2CuratedFeedController.cs
- src/NuGetGallery/Controllers/ODataV2FeedController.cs
- src/NuGetGallery/GalleryConstants.cs
- src/NuGetGallery/OData/NuGetODataController.cs
- src/NuGetGallery/Services/ITelemetryService.cs
- src/NuGetGallery/Services/TelemetryService.cs
- src/NuGetGallery/WebApi/QueryResult.cs
- tests/NuGetGallery.Facts/Controllers/ODataFeedControllerFactsBase.cs
- tests/NuGetGallery.Facts/Controllers/ODataV1FeedControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/ODataV2CuratedFeedControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/ODataV2FeedControllerFacts.cs
- tests/NuGetGallery.Facts/Services/FeedServiceFacts.cs
- tests/NuGetGallery.Facts/Services/TelemetryServiceFacts.cs
- tests/NuGetGallery.Facts/TestUtils/Infrastructure/TestableV1Feed.cs
- tests/NuGetGallery.Facts/TestUtils/Infrastructure/TestableV2Feed.cs
Progress on https://github.com/NuGet/Engineering/issues/1798.
This PR does two things:
1. Add custom metric `ODataCustomQuery` to OData queries.
- This has a property `IsCustomQuery = True | False | Unknown`
1. Add a response header `X-NuGet-CustomQuery: true | false`
- This can be used by APIM
The telemetry will allow us to verify that official clients are not doing custom queries. Note that "custom query" does not necessarily mean executed without the database. I chose to make this distinction for the `GetUpdates` OData function. This can be called by official client (2.x for many cases, 3.x+ for `nuget.exe update -self`) so it should not be throttled like custom OData queries.
~Another case: when search hijack throws an exception, some (maybe all?) codepaths fall back to DB. This …
>  Add custom query telemetry and response header to OData endpoint

- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery.Core/Services/PackageAlreadyExistsException.cs
- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Services/PackageService.cs
- src/NuGetGallery/Services/PackageUploadService.cs
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
- tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs
Fixes https://github.com/NuGet/Engineering/issues/1817. Mostly affects the functional test failures, kind of hard to test but I will deploy this change to dev and run functional tests couple of times to verify.
> Fix concurrency/consistency issues in Gallery API push

- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Infrastructure/HttpStatusCodeWithServerWarningResult.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/RequestModels/VerifyPackageRequest.cs
- src/NuGetGallery/Services/IValidationMessage.cs
- src/NuGetGallery/Services/JsonValidationMessage.cs
- src/NuGetGallery/Services/PackageShouldNotBeSignedUserFixableValidationMessage.cs
- src/NuGetGallery/Services/PackageUploadService.cs
- src/NuGetGallery/Services/PackageValidationResult.cs
- src/NuGetGallery/Services/PackageValidationResultType.cs
- src/NuGetGallery/Services/PlainTextOnlyValidationMessage.cs
- src/NuGetGallery/Views/Packages/_VerifyMetadata.cshtml
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs
Progress on #6545.
I needed a way to enhance the errors and warning produced on a package upload and verify pages to allow passing raw HTML as an error, so I could include links in an error or warning message.
The gist of the change is that validation code now instead of returning errors and warnings as strings returns objects (implementing the `IValidationMessage` interface). Those object provide a way to render the message in either plain text or optional HTML. If object chooses not to provide HTML, its plain text representation is used instead. For API purposes plain text representation is always used. Errors passed through `TempData["Message"]` are also always plain text (that's a bit more global change that I don't want to touch right now).
Errors and warnings were passed as an array …
> Validation message enhancements

- src/NuGetGallery/Services/TyposquattingConfiguration.cs
- tests/NuGetGallery.Facts/Services/ContentObjectServiceFacts.cs
The default value for typo-squatting checklist length and cache expire time doesn't work as expected in Dev. Fix this issue and add more test cases for content service. 
Fix https://github.com/NuGet/Engineering/issues/1881
> Fix default value issue and add more tests. 

- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery/NuGetGallery.csproj
Aligns Gallery with NuGet/ServerCommon#222
> Hotfix: Don't attempt to send emails if they have no recipients

- src/NuGetGallery.Core/NuGetGallery.Core.csproj
The package pulled in via the other PR included changes in `NuGet.Services.Entity` that did not have a corresponding DB migration. This caused the change to fail.
This pulls in a package from [a private branch](https://github.com/NuGet/ServerCommon/compare/master...sb-noemailrecipients) that is based off `master` `ServerCommon` BEFORE the `NuGet.Services.Entity` changes.
> Hotfix: Hotfix: Don't attempt to send emails if they have no recipients

- src/NuGetGallery.Core/CoreConstants.cs
- src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs
- src/NuGetGallery.Core/Services/PackageFileServiceMetadata.cs
- src/NuGetGallery.Core/Services/RevalidationStateService.cs
- src/NuGetGallery.Core/Services/SymbolPackageFileServiceMetadata.cs
- src/NuGetGallery/Services/CertificateService.cs
- src/NuGetGallery/Services/CloudBlobFileStorageService.cs
- src/NuGetGallery/Services/ContentService.cs
- src/NuGetGallery/Services/FileSystemFileStorageService.cs
- src/NuGetGallery/Services/PackageFileService.cs
- src/NuGetGallery/Services/SymbolPackageFileService.cs
- src/NuGetGallery/Services/UploadFileService.cs
- tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceFacts.cs
- tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceIntegrationTests.cs
- tests/NuGetGallery.Core.Facts/Services/CorePackageFileServiceFacts.cs
- tests/NuGetGallery.Core.Facts/Services/RevalidationStateServiceFacts.cs
- tests/NuGetGallery.Facts/Services/CertificateServiceFacts.cs
- tests/NuGetGallery.Facts/Services/CloudBlobFileStorageServiceFacts.cs
- tests/NuGetGallery.Facts/Services/ContentServiceFacts.cs
- tests/NuGetGallery.Facts/Services/FileSystemFileStorageServiceFacts.cs
- tests/NuGetGallery.Facts/Services/PackageFileServiceFacts.cs
- tests/NuGetGallery.Facts/Services/UploadFileServiceFacts.cs
Added new folder to a list of known private folders.
Changed the default cache control to be not set.
Updated tests to include the new folder.
To prevent the issue in the future all folders were moved into their own class and added a test that makes sure `CloudBlobCoreFileStorageServiceFacts` have all of them covered.
> Fix for broken package delete

- src/NuGetGallery/Helpers/LicenseExpressionRedirectUrlHelper.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/PackageUploadService.cs
- src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
Given valid license expression, we want that the "License Info" link in package page redirects to the license content page at "licenses.nuget.org".
Fix:  https://github.com/NuGet/Engineering/issues/1855
> Upload license expression redirect url logic

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
- tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs
Addresses #6650 
The fix is basically to avoid setting the `LatestSymbolPackage` on all the package versions, and only set on the main package for the display view. The perf gain would be reduced dependency calls. I verified this locally and was able to see the reduced dependency calls. I will analyze the performance over the week after merging and deploying this change in DEV.
The problem is we are reusing the same view model for two different views(which happen to be on the same page), details view and package versions history. Ideally we should have a completely different view model for the package versions list(history) which should only have the required data populated rather than using same `DisplayPackageViewModel`. However, that is overall a bigger change that I do not want to …
> Fix DisplayPackage Perf regression

- src/NuGetGallery/App_Start/OwinStartup.cs
https://github.com/NuGet/NuGetGallery/issues/6651
Wasn't able to find any unit tests that verify that our `RequestTelemetryProcessor` considers 400, 404, and 405 successful, but I verified locally that they are.
> Mark 405 response code as "success" for AI

- src/NuGetGallery/Helpers/LicenseExpressionRedirectUrlHelper.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/InvalidLicenseUrlValidationMessage.cs
- src/NuGetGallery/Services/InvalidUrlEncodingForLicenseUrlValidationMessage.cs
- src/NuGetGallery/Services/LicenseUrlDeprecationValidationMessage.cs
- src/NuGetGallery/Services/PackageUploadService.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs
> Targeted block for invalidly URL encoded license URLs for license expressions

- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
The second word should start with lowercase. See other texts on a package's page. `Source Code` renamed to `Source repository`.
> Fix casing and rewording of left nav items

- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery/NuGetGallery.csproj
- tests/NuGetGallery.Facts/Infrastructure/Mail/MarkdownMessageServiceFacts.cs
- tests/NuGetGallery.Facts/Infrastructure/Mail/TestMailSender.cs
- tests/NuGetGallery.Facts/Infrastructure/Mail/TestableMarkdownMessageService.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
Whilst at it, refactored the `MarkdownMessageServiceTests` a bit and moved them next to the other email tests. The hotfix is within the ServerCommon dependency upgrade.
> Hotfix copy-sender

- src/GalleryTools/Commands/UpdateIsLatestCommand.cs
- src/GalleryTools/Commands/VerifyApiKeyCommand.cs
- src/GalleryTools/GalleryTools.csproj
- src/GalleryTools/Program.cs
This adds a command to `GalleryTools.exe` to `updateIsLatest` on a target gallery database.
Main use case:
Properly set `IsLatest(Stable)SemVer2` after running the EF migrations against a gallery database that did not have SemVer2 support yet.
Usage:
```
gallerytools.exe updateIsLatest --connectionstring "value"
```
Screenshot:
> Add tool to upgrade gallery deployments to support SemVer2 feature

- src/NuGetGallery/Helpers/PackageHelper.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
Address https://github.com/NuGet/Engineering/issues/1953.
35000 was picked by looking at the length of release notes on the most recently pushed package per ID. This number will not break users and protect us until we have further perf/UX information.
```sql
SELECT TOP 10
pr.Id,
p.NormalizedVersion,
LEN(p.ReleaseNotes) AS ReleaseNotesLength,
pr.LatestCreated,
pr.TotalDownloadCount,
p.DownloadCount AS LatestDownloadCount
FROM (
SELECT pr.[Key], MAX(pr.[Id]) AS [Id], MAX(pr.DownloadCount) AS [TotalDownloadCount], MAX(p.Created) AS [LatestCreated]
FROM Packages p
INNER JOIN PackageRegistrations pr ON p.PackageRegistrationKey = pr.[Key]
WHERE p.Listed = 1
GROUP BY pr.[Key]
) pr
INNER JOIN Packages p ON p.Created = pr.LatestCreated AND p.PackageRegistrationKey = pr.[Key]
WHERE …
```
> Limit release notes field to 35000 characters

- src/NuGetGallery/Controllers/JsonApiController.cs
- tests/NuGetGallery.Facts/Controllers/JsonApiControllerFacts.cs
https://github.com/NuGet/NuGetGallery/issues/6683
We don't have a `try`-`catch` around this statement, so it bubbles up to a 500.
This change just returns a JSON result directly instead.
> Properly return a 400 JSON result instead of 500 when trying to remove the last owner of a package

- src/NuGetGallery/App_Code/ViewHelpers.cshtml
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
> Remove ‘deprecated’ text from the username/password login page

- src/NuGetGallery/Controllers/PackagesController.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
Controller should redirect to licenses.nuget.org with license expression.
> Controller should redirect to licenses.nuget.org with license expression

- src/NuGetGallery/UrlHelperExtensions.cs
- src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- tests/NuGetGallery.Facts/UrlHelperExtensionsFacts.cs
License info link for package with license file should appear only after validation job, and it should redirect to the correct Url in Gallery.
Fix: https://github.com/NuGet/NuGetGallery/issues/6734
> License file package - License info should appear only after validation job and redirect to correct Url. 

- src/NuGetGallery.Core/Services/CoreLicenseFileService.cs
- src/NuGetGallery.Core/Services/FIleNameHelper.cs
- src/NuGetGallery/Services/PackageUploadService.cs
- tests/NuGetGallery.Core.Facts/Services/CoreLicenseFileServiceFacts.cs
- tests/NuGetGallery.Core.Facts/TestUtils/TestPackage.cs
- tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs
Fixes https://github.com/NuGet/NuGetGallery/issues/6737.
Per zip file format [specification](http://www.pkware.com/documents/casestudies/APPNOTE.TXT) (4.4.17.1), only forward slashes can be used in paths inside zip file, but paths in nuspec can contain both forward and back slashes. So added code that fixes the paths before they are passed into `PackageArchiveReader`.
On the other hand, `ZipArchive` implementation in .net does not enforce forward slashes and allows to create zip files with backslashes in paths, so alternative pack implementations might exist that produce technically invalid zip files, not sure we want to support those though.
> Fix for the Gallery unable to find license file if paths with backslashes are used

- src/NuGetGallery/Services/ActionRequiringEntityPermissions.cs
- src/NuGetGallery/Services/PackageService.cs
https://github.com/NuGet/NuGetGallery/issues/6755
These fixes drastically improve the performance of the Manage Packages page.
1) Include `RequiredSigners` in the initial request for packages. Previously, the page was making a SQL request for every package in `ListPackageItemRequiredSignerViewModel`.
2) Exit the `ChecksPermissionsOnBehalfOfAnyAccount` call early. `ChecksPermissionsOnBehalfOfAnyAccount` has two implementations-- both return whether or not the action can be done on behalf of any owner, but one returns the list of owners the action can be done on behalf as well. To get the full list of owners the action can be done on behalf of, we were enumerating the full list of possible owners every time, even if we didn't care about which owners the action can be done on behalf of. By …
> Server-side performance fixes for Manage Packages page

- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Updated fix for issue #6741 from PR #6742.
Displays the latest listed package download count, or no package download count if there are no listed packages.
> Fix latest download count, re: issue #6741

- src/NuGetGallery.Core/Services/CoreLicenseFileService.cs
- tests/NuGetGallery.Core.Facts/Services/CoreLicenseFileServiceFacts.cs
Internally, we don't care about content type since we store type in DB, I just wanted to be nice and store markdown files with proper content type, unfortunately, at least Edge and Firefox try to save it when pointed to it instead of rendering as plain text, so we'll save as `text/plain` to provide better experience for users of those browsers.
Later, when we stop pointing to a blob directly, but render it inside Gallery, we can put proper content types back.
> Not saving markdown files with "text/markdown" anymore

- src/NuGetGallery.Core/Services/CloudBlobWrapper.cs
- src/NuGetGallery.Core/Services/ISimpleCloudBlob.cs
- tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceIntegrationTests.cs
This will allow me to use `If-None-Match: "old-etag"` in the search service to only download auxiliary files when they have changed.
I am using this storage abstraction because it has etags exposed.
> Add OpenReadAsync to ISimpleCloudBlob wrapper

- src/NuGetGallery.Core/Services/AccessConditionWrapper.cs
- tests/NuGetGallery.Core.Facts/Services/AccessConditionWrapperFacts.cs
Progress on https://github.com/NuGet/NuGetGallery/issues/6449.
This supports no-oping by specifying `If-None-Match: (previous etag)` and reacting to HTTP 304 Not Modified.
> Add AccessConditionWrapper.GenerateIfNoneMatchCondition

- src/NuGetGallery/Areas/Admin/Services/SupportRequestService.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/Services/SupportRequestServiceFacts.cs
- tests/NuGetGallery.Facts/UsernameValidationRegex.cs
On delete account the issue. createdby field will be obfuscated but not changed to null . The issues will be marked as resolved and still be visible on the support page.
> Not null the createdby on delete account

- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- src/NuGetGallery/Web.config
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
Addresses NuGet/NuGetGallery#6721
Will update PR once https://github.com/NuGet/ServerCommon/pull/234 is merged and non-private builds of a new library are available.
Worse case:
Should we put `<nobr>` (or set up css accordingly) around license names, so they are not split between lines?
> License expression display in Gallery

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/ViewModels/DeletePackageViewModel.cs
- src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
- src/NuGetGallery/ViewModels/ManagePackageViewModel.cs
- tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs
https://github.com/NuGet/NuGetGallery/issues/6845
This PR adds a `ToList` to `DisplayPackageViewModel.PackageVersions`, which prevents it from be enumerated multiple times. Without this change, it is recalculated every time it is called, which is very expensive with many versions.
I also simplified the constructor by getting rid of the `packageHistory` parameter that was continually set to the same expression by all of our app code and by making the other constructor, which was only intended to be used by the other constructor, private.
> DisplayPackageViewModel.PackageVersions should not be enumerated multiple times

- src/NuGetGallery/App_Start/NuGetODataV2CuratedFeedConfig.cs
- src/NuGetGallery/App_Start/Routes.cs
- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/Controllers/ODataV2CuratedFeedController.cs
- src/NuGetGallery/Controllers/PagesController.cs
- src/NuGetGallery/Extensions/SimulatedErrorTypeExtensions.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/RequestModels/SimulatedErrorType.cs
- src/NuGetGallery/RouteName.cs
This proposal is in regards to issue https://github.com/NuGet/NuGetGallery/issues/6601. We have seen strange behavior when it comes to how exceptions and non-success status codes are dealt with in the gallery. Right now we have very high Application Insights noise around HTTP 500s since some HTTP 400s get mapped to HTTP 500. This is bad since it is potentially hiding really HTTP 500s that we need to handle.
Also, we have certain experiences built around error cases. For example, in descending order of importance:
1. **Critical:** HTTP 400 reason phrase is used by to pass an error message to client. If these reason phrase or status stops working as expected, `nuget.exe push` experience is significantly degraded.
1. **Important:** Non-HTML response when …
> [PROPOSAL] Add "simulate error" endpoints to gallery for testing

- src/GalleryTools/Commands/ApplyTenantPolicyCommand.cs
- src/GalleryTools/Commands/ReflowCommand.cs
- src/GalleryTools/GalleryTools.csproj
- src/GalleryTools/Program.cs
This tool applies the `RequireOrganizationTenantPolicy` to a list of organizations specified in a file.
I intend to use it for https://github.com/NuGet/Engineering/issues/2092
> Add tool to apply organization tenant policy to a list of organizations

- src/NuGetGallery/Controllers/PackagesController.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
https://github.com/NuGet/NuGetGallery/issues/6843
For some context, `FindPackageByIdAndVersion` is intended to be used when the consumer wants a package, but if the package does not exist, wants the latest version instead. If the consumer REQUIRES the exact package they are asking for, they should use `FindPackageByIdAndVersionStrict` instead.
Unfortunately, our endpoints here are not using these methods properly, and I've fixed two classes of issues here, including the issue above.
1. `FindPackageByIdAndVersion` only returns the latest semver 2.0 package if `SemVer2` is passed in. It defaults to returning only semver 1 packages. The gallery is a semver 2 client, and should always show semver 2 packages in its UI. Unfortunately, several of our `PackagesController` endpoints were not …
> PackagesController methods should handle SemVer2 and missing packages properly

- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/App_Start/StorageDependent.cs
- src/NuGetGallery/Configuration/AppConfiguration.cs
- src/NuGetGallery/Configuration/IAppConfiguration.cs
- tests/NuGetGallery.Facts/App_Start/StorageDependentFacts.cs
For DEV blob storage, we have separate locations as "nugetdev0" and "nugetdevlegacy". V3 job will put the package with license file at "nugetdev0". However, gallery will go to "nugetdevlegacy" to fetch the license file, which is not there. So there is a need to let the gallery get the license file from "nugetdev0" in DEV.
Fix: https://github.com/NuGet/Engineering/issues/2119
> Need to fetch the license file from Dev0 rather than Devlegacy for DEV. 

- src/NuGetGallery/Controllers/PackagesController.cs
Customers should check the license page without login. 
Fix: https://github.com/NuGet/Engineering/issues/2134
> Open license page for anyone. 

- src/NuGetGallery/App_Code/ViewHelpers.cshtml
- src/NuGetGallery/Controllers/AuthenticationController.cs
- src/NuGetGallery/GalleryConstants.cs
- src/NuGetGallery/Helpers/UriExtensions.cs
- src/NuGetGallery/Infrastructure/CookieTempDataProvider.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- src/NuGetGallery/Views/Authentication/LinkExternal.cshtml
- src/NuGetGallery/Views/Pages/Contact.cshtml
- src/NuGetGallery/Views/Pages/_TransformOrLink.cshtml
- src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
- tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
- tests/NuGetGallery.Facts/Infrastructure/CookieTempDataProviderFacts.cs
Addresses https://github.com/NuGet/NuGetGallery/issues/6777 https://github.com/NuGet/Engineering/issues/2071 https://github.com/NuGet/Engineering/issues/2066, I ended up dropping the idea that @agr used for validation messages, it is not straight forward to integrate it with `TempData`, main issue being `TempData` is stored in cookies and it can only be stored as strings. The full fledged support would include JSON serialization and Deserialization with cookie support which is a much larger change for addressing this issue. 
This PR introduces a new property `RawErrorMessage` in `TempData` which would be rendered as a RawHtml on the view side. We have to be careful when using this property for showing error messages making sure we do not format user data in this property. It is fine to be …
> Add FAQ links to account login error messages

- src/NuGetGallery/App_Data/Files/Content/flags.json
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Services/FeatureFlagService.cs
- src/NuGetGallery/Services/IFeatureFlagService.cs
- src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
Progress on https://github.com/NuGet/NuGetGallery/issues/2992
If there is unexpected performance issues, we can use this as an escape hatch. Also plumb through the `prerel` parameter and give it a name consistent with the package search page.
> Add a feature flag for the atom feed and enable prerelease filtering

- src/NuGetGallery.Core/NuGetVersionExtensions.cs
- src/NuGetGallery/Scripts/gallery/page-edit-readme.js
- src/NuGetGallery/ViewModels/ManagePackageViewModel.cs
- src/NuGetGallery/ViewModels/PackageViewModel.cs
- src/NuGetGallery/Views/Packages/Manage.cshtml
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
precursor to https://github.com/NuGet/NuGetGallery/issues/6773
We decided that it was a bad idea to make the `ManagePackageViewModel` dependent on `DisplayPackageViewModel` as it forces `DisplayPackageViewModel` to store all information necessary to build the `ManagePackageViewModel`, which complicates the performance of the page.
`ManagePackageViewModel` will need deprecation information for all versions, but `DisplayPackageViewModel` only needs the selected package's deprecation information.
I have kept the dependency on `ListItemPackageViewModel` because it needs some of the fields on it, and I felt the model was lightweight enough for it not to be a big deal to reuse it.
> ManagePackageViewModel should not be dependent on DisplayPackageViewModel

- tests/NuGetGallery.FunctionalTests/AtomFeed/AtomFeedTests.cs
- tests/NuGetGallery.FunctionalTests/NuGetGallery.FunctionalTests.csproj
Address https://github.com/NuGet/NuGetGallery/issues/6898.
Many of our other functional tests use Newtonsoft.Json as a pre-existing package. Technically this should probably be an explicit test package but this is out of scope. The benefit of using an pre-existing package is that the run time of the functional test is very low.
> Add functional tests for the packages Atom feed

- src/NuGetGallery/Scripts/gallery/common.js
When exploring custom keyboard controls for the Deprecation form, I discovered this as a substantially simpler implementation than what I had implemented in https://github.com/NuGet/NuGetGallery/pull/6215.
Basically, instead of having to traverse the DOM manually, I am now leveraging JQuery to do this heavy-lifting for me by defining a "this element can be tabbed to" selector. I also added `focusable` in case we need it.
This also fixes a bug in the previous implementation. If an element has a `tabindex` of `-1`, its children can still be tabbed to. In the previous implementation, children of elements with `tabindex="-1"` were not considered `tabbable`.
I also got rid of all the ESLint issues in the file.
> Improve implementation of "Skip To Content" link

- src/NuGetGallery.Core/Services/CorePackageService.cs
- src/NuGetGallery/Controllers/JsonApiController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Services/IPackageService.cs
- src/NuGetGallery/Services/PackageService.cs
- tests/NuGetGallery.Facts/Controllers/JsonApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
precursor to https://github.com/NuGet/NuGetGallery/issues/6773
Both `PackagesController.DisplayPackage` and `PackagesController.Manage` require all versions of a package.
Previously, this was done either implicitly or lazily, specifically:
- if a version isn't specified or is missing, `FindPackageByIdAndVersion` must fetch all versions to calculate the latest one
- if a version was specified and found, the remaining versions would be loaded lazily
This is bad because our perf for these endpoints are relying on a hidden behavior of one of our services, and when this hidden behavior doesn't go our way, lazy loading is **very very very very** slow, and adding the deprecation entities associated with this feature makes it *even* worse.
So, to remedy this
- add `FindPackagesById` to get all …
> Restructure PackageService to better support endpoints requiring all versions of an ID

- src/NuGetGallery/Controllers/PackagesController.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
Addresses https://github.com/NuGet/NuGetGallery/issues/6570
Moved package contents processing (opening package, validating metadata, getting the license data) into separate method `ValidateAndProcessPackageContents`. Added code that if that method returns error the package is deleted from the upload container, preventing the situation when Gallery tries to resume package upload for a package that was deemed invalid.
> Cleaning up upload container on failed sync validation

- tests/NuGetGallery.FunctionalTests/AtomFeed/AtomFeedTests.cs
This behavior is asserted by unit tests so a functional test is not strictly necessary.
Unit tests:
https://github.com/NuGet/NuGetGallery/blob/651381b1506a8c29eb879831f592514bcee5a8fa/tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs#L1178
https://github.com/NuGet/NuGetGallery/blob/651381b1506a8c29eb879831f592514bcee5a8fa/tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs#L1253
> Remove Atom feed functional tests that depend on 3rd party package

- tests/NuGetGallery.FunctionalTests/ErrorHandling/EndpointType.cs
- tests/NuGetGallery.FunctionalTests/ErrorHandling/ErrorHandlingTests.cs
- tests/NuGetGallery.FunctionalTests/ErrorHandling/SimulatedErrorRequest.cs
- tests/NuGetGallery.FunctionalTests/ErrorHandling/SimulatedErrorType.cs
- tests/NuGetGallery.FunctionalTests/ErrorHandling/TestResponse.cs
- tests/NuGetGallery.FunctionalTests/ErrorHandling/Validator.cs
- tests/NuGetGallery.FunctionalTests/NuGetGallery.FunctionalTests.csproj
This just adds test coverage of current behavior. Cases asserted:
1. Bad cookie
1. Missing route (simple 404)
1. Nasty URLs that IIS does not like.
1. All possible inputs for the "simulate error" endpoints.
Progress on https://github.com/NuGet/NuGetGallery/issues/6601.
> Add functional tests for error cases in gallery

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/page-profile.less
- src/NuGetGallery/Views/Users/Profiles.cshtml
This is currently already possible with the database admin view, but this makes it much more convenient. If the user is not a site admin, this information will remain private -- as it should be!
Address https://github.com/NuGet/Engineering/issues/609.
Looks like this:
> Site admins can see email address on profile page

- tests/NuGetGallery.FunctionalTests.Core/Helpers/ClientSdkHelper.cs
- tests/NuGetGallery.WebUITests.P1/BasicPages/PackagesPageTest.cs
Address https://github.com/NuGet/Engineering/issues/1952.
This is broken since stats don't sync between search and gallery simultaneously.
> Remove flaky download count assertion

- src/NuGetGallery/Services/PackageDeprecationService.cs
- tests/NuGetGallery.Facts/Services/PackageDeprecationServiceFacts.cs
https://github.com/NuGet/Engineering/issues/2082
This is a bug fix for the behavior of the deprecation form on the manage package page. Without setting `LastEdited`, the change is not pushed to V3.
In the future, when deprecation information is pushed to V3 as well, this route should always set `LastEdited`, but right now, because deprecation information is not push to V3, it only needs to update `LastEdited` when we are unlisting.
> Unlisting a package when deprecating it should update LastEdited

- src/NuGetGallery/Controllers/PackagesController.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
A couple fixes that were done while working on https://github.com/NuGet/NuGetGallery/pull/6912 but moved to here because they are separate to it
Two issues fixed here:
1. [`DeleteSymbols` requires all versions of the package but doesn't call `FindPackagesById`](https://github.com/NuGet/NuGetGallery/pull/6905)
2. `DeleteSymbols` uses `SelectList` (which uses reflection and dynamic objects) instead of `IEnumerable<SelectListItem>`
> Minor fixes to the GET DeleteSymbols endpoint

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/page-display-package.less
- src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
- src/NuGetGallery/Views/Packages/_DisplayPackageDeprecation.cshtml
- tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs
@anangaur had some additional feedback for https://github.com/nuget/nugetgallery/issues/6774
If you remember before, we merged a single string for the reason text and then had text/icons centered with the reason text. We now have separate text for each reason and text/icons aligned with the top line.
We also changed the text for legacy only.
> Improve deprecation information UI on Display Package page with multiple reasons

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/page-manage-deprecation.less
- src/NuGetGallery/Controllers/ManageDeprecationJsonApiController.cs
- src/NuGetGallery/Scripts/gallery/page-manage-deprecation.js
- src/NuGetGallery/Services/IPackageDeprecationService.cs
- src/NuGetGallery/Services/PackageDeprecationService.cs
- src/NuGetGallery/ViewModels/ManagePackageViewModel.cs
- src/NuGetGallery/Views/Packages/_ManageDeprecation.cshtml
- tests/NuGetGallery.Facts/Controllers/ManageDeprecationJsonApiControllerFacts.cs
- tests/NuGetGallery.Facts/Services/PackageDeprecationServiceFacts.cs
We have decided to remove the "should unlist" checkbox from the Manage Deprecation form. This PR removes it from the form.
Because this PR was also small, I also made a small UI fix that @anangaur asked for--the CVSS rating in the deprecation form should be bolded.
If we leave "should unlist" in the form, we'd need to do testing on whether or not bulk unlisting works. This is non-trivial and may require large V3 changes.
Additionally, we decided to separate "deprecation" and "listing" in the UI, and having a checkbox that bridges the two is confusing, especially when multiple versions are selected.
> Remove unlist checkbox from Manage Deprecation form

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/page-display-package.less
- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery.Core/Services/CorePackageService.cs
- src/NuGetGallery.Core/Services/PackageDeprecationFieldsToInclude.cs
- src/NuGetGallery/Controllers/ManageDeprecationJsonApiController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Services/IPackageService.cs
- src/NuGetGallery/Services/PackageService.cs
- src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- tests/NuGetGallery.Facts/Controllers/ManageDeprecationJsonApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs
https://github.com/NuGet/NuGetGallery/issues/6954
Current implementation: icons on right with row border between
Regarding SQL performance, the `DisplayPackage` endpoint now loads the `PackageDeprecation`s associated with each `Package` as well, but not any entities linked to those deprecations (like the CVEs, CWEs, alternate packages, etc). In my testing, this added load seemed entirely insignificant. I am continuing to look into potential impact but I think I'm not sure what else we could do to decrease the risk of impact.
with certs
> Mark deprecated versions in Display Package page's version history

- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/Configuration/AppConfiguration.cs
- src/NuGetGallery/Configuration/IAppConfiguration.cs
- src/NuGetGallery/Infrastructure/Lucene/SearchClientConfiguration.cs
- src/NuGetGallery/Infrastructure/Lucene/SearchClientPolicies.cs
- src/NuGetGallery/Web.config
- tests/NuGetGallery.Facts/Infrastructure/Lucene/SearchPolicyFacts.cs
Two changes in this PR:
1. Move configurations in web.config.
2. Fix a potential issue with a case like:
- one single query will return 500+
- multiple queries will be fine
The circuit breaker will not be closed and the failing query will keep retrying until timing out. 
With this change only a certain amount of retries will be allowed.
> Upper bound individual retries, move configurations in web config.

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/ViewModels/ContactOwnersViewModel.cs
- src/NuGetGallery/Views/Packages/ContactOwners.cshtml
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
https://github.com/NuGet/Engineering/issues/2250
Two issues here
- `ContactOwnersViewModel.Owners` uses `User` entity
- `PackagesController.VerifyPackageInternal` and `PackagesController.VerifySymbolsPackageInternal` are `public` so [they can be hit using a REST API](https://www.nuget.org/packages/woah/VerifyPackageInternal?formData=hi&uploadFile=hi&packageArchiveReader=ho&packageMetadata=haah&currentUser=hi&owner=ho)
> Use separate model binding classes

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/common-multi-select-dropdown.less
- src/NuGetGallery/Scripts/gallery/common.js
- src/NuGetGallery/Scripts/gallery/page-manage-deprecation.js
- src/NuGetGallery/Views/Packages/Manage.cshtml
- src/NuGetGallery/Views/Packages/_DisplayPackageDeprecation.cshtml
- src/NuGetGallery/Views/Packages/_ManageDeprecation.cshtml
- src/NuGetGallery/Views/Packages/_ManageDocumentation.cshtml
- src/NuGetGallery/Views/Packages/_ManageListing.cshtml
Some quick bugs found in https://github.com/nuget/engineering/issues/2168
- multi-select dropdown should not be larger than content
- "skip to content" does not tab to the deprecation warning on the package details page (non-focusable elements with `tabIndex` set should be considered `:focusable` and `:tabbable`)
- Fixed page when package is locked or feature flag is disabled
site admin:
owner:
- deprecation warning on package details page should show pointer cursor
- custom message in deprecation warning on package details page should have better text
- alternate package text in deprecation warning on package details page should be shorter
> Fix minor bugs in Deprecation UI found in bug bash

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Scripts/gallery/page-display-package.js
- src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
(also fixed a minor bug with the deprecation expander being clickable when it's empty)
> Hotfix: Deprecation UI should be hidden when feature flag is disabled

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Services/FeatureFlagService.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
Unfortunately, https://github.com/NuGet/NuGetGallery/pull/7016 throws when the user is null (e.g. logged out)
This is a temporary fix--https://github.com/NuGet/ServerCommon/pull/290 is the long-term fix
> Hotfix: ManageDeprecation is not enabled for logged out users

- src/NuGetGallery/Scripts/gallery/page-manage-deprecation.js
- src/NuGetGallery/Views/Packages/_ManageDeprecation.cshtml
Found during https://github.com/NuGet/Engineering/issues/2168
Currently, if you enter in CVEs, CWEs, or a CVSS rating and then uncheck "is vulnerable", the CVEs, CWEs, and CVSS you entered will be submitted with the form (even though the package is not marked vulnerable). This fixes the issue.
> Deprecation - CVEs, CWEs, and CVSS should not be submitted with the form if unchecked

- src/NuGetGallery/Areas/Admin/Controllers/ReservedNamespaceController.cs
- src/NuGetGallery/Authentication/AuthenticationService.cs
- src/NuGetGallery/Controllers/JsonApiController.cs
- src/NuGetGallery/Controllers/OrganizationsController.cs
- src/NuGetGallery/Controllers/UsersController.cs
- src/NuGetGallery/Security/ISecurityPolicyService.cs
- src/NuGetGallery/Security/SecurityPolicyService.cs
- src/NuGetGallery/Services/DeleteAccountService.cs
- src/NuGetGallery/Services/IDeleteAccountService.cs
- src/NuGetGallery/Services/IPackageOwnershipManagementService.cs
- src/NuGetGallery/Services/IReservedNamespaceService.cs
- src/NuGetGallery/Services/PackageOwnershipManagementService.cs
- src/NuGetGallery/Services/ReservedNamespaceService.cs
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/OrganizationsControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
- tests/NuGetGallery.Facts/Services/DeleteAccountServiceFacts.cs
- tests/NuGetGallery.Facts/Services/ReservedNamespaceServiceFacts.cs
https://github.com/nuget/engineering/issues/2264
`DeleteAccountService.DeleteAccountAsync` was so slow because it calls a lot of other services, most of which internally called `EntitiesContext.SaveChangesAsync`. Because the entire method is wrapped in a transaction, none of these calls are necessary and thus slow down the process substantially. Each call to `EntitiesContext.SaveChangesAsync` forces EF to do a lot of work behind the scenes--even if the transaction isn't going to be committed to the DB yet.
This was fixed by
- passing `commitChanges: false` to services that already supported it
- modifying services so that they allow `commitChanges: false`
We had a couple services with a `commitAsTransaction` parameter, which committed regardless of whether or not it was in a transaction …
> Only commit once in DeleteAccountService.DeleteAccountAsync

- src/NuGetGallery.Core/Services/CloudBlobWrapper.cs
- src/NuGetGallery.Core/Services/ISimpleCloudBlob.cs
- tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceIntegrationTests.cs
Progress on https://github.com/NuGet/NuGetGallery/issues/6475.
This method is the buddy of the already plumbed through `OpenReadAsync`. `StreamWriter` and `JsonTextWriter` can be used on top of this stream to incrementally write to a blob.
> Add OpenWriteAsync to ISimpleCloudBlob to allow streaming writes

- src/NuGetGallery/Services/AsynchronousPackageValidationInitiator.cs
- src/NuGetGallery/Services/IPackageValidationInitiator.cs
- src/NuGetGallery/Services/IValidationService.cs
- src/NuGetGallery/Services/ImmediatePackageValidator.cs
- src/NuGetGallery/Services/PackageUploadService.cs
- src/NuGetGallery/Services/SymbolPackageUploadService.cs
- src/NuGetGallery/Services/ValidationService.cs
- tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs
- tests/NuGetGallery.Facts/Services/SymbolPackageUploadServiceFacts.cs
- tests/NuGetGallery.Facts/Services/ValidationServiceFacts.cs
Related to #6624 
Targeted fix for the "DuplicatePushesAreRejectedAndNotDeleted" tests causing deadlettering in validation pipeline. Validation request ServiceBus message now sent right before committing changes to DB, which in case of that test means there will be no surge of validation request for the same package.
Since the post validation request package status is used in `PackageUploadService` to determine the course of action, updating the package status was extracted into separate method, so it can be done without sending the validation request. It, of course, introduces an issue that we can forget to call the actual method that sends the message, but the exposure is very limited (one call for regular packages and another one for the symbol packages), and we are likely to notice …
> Sending validation request right before committing changes to DB

- src/NuGetGallery/Areas/Admin/ViewModels/IModifyFeatureFlagsViewModel.cs
- tests/NuGetGallery.Facts/Controllers/FeaturesControllerFacts.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
https://github.com/nuget/nugetgallery/issues/7078
It seems that FXCop has a bug that causes that generic to fail to load.
I had to refactor the code to remove the generic to get FXCop to run successfully.
See https://github.com/NuGet/NuGetGallery/commit/90eb3cfa9a525d674187d9da2b3843651796d084 for the changes that resolved the issue.
[I also filed a bug with the team that maintains FXCop so they can hopefully fix this in the future.](https://github.com/dotnet/roslyn-analyzers/issues/2390)
> Add back FeaturesControllerFacts

- src/NuGet.Services.Entities/Package.cs
- src/NuGet.Services.Entities/PackageDeprecation.cs
- src/NuGetGallery.Core/Entities/EntitiesContext.cs
- src/NuGetGallery.Core/Entities/IEntitiesContext.cs
- src/NuGetGallery/Services/DeleteAccountService.cs
- src/NuGetGallery/Services/PackageService.cs
- tests/NuGetGallery.Facts/Services/DeleteAccountServiceFacts.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
https://github.com/nuget/engineering/issues/2358
These relationships aren't being cleaned up.
We also aren't cleaning up `AccountDelete.DeletedBy` and `PackageDelete.DeletedBy`, but I'm not doing them as part of this change as fixing them will require a DB migration.
> DeleteAccountService should clean up Package.User and PackageDeprecation.DeprecatedBy

- src/NuGetGallery/Authentication/AuthenticationService.cs
Addresses #7080 - This will persist the session cookie even after the browser is closed, until the session expires. Verified with local sessions.
> [NuGet Gallery Login] Add isPersistent flag to cookie

- src/NuGetGallery/Controllers/JsonApiController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/ViewModels/AddPackageOwnerViewModel.cs
- tests/NuGetGallery.Facts/Controllers/JsonApiControllerFacts.cs
Since we encode the incoming message on our side before we send the message, there is no reason to reject the message from the client based on that alone.
Adds a new object type for the parameters to AddOwners so we can restricted the relaxing of verification to the message field only.
> Allow HTML in owner request messages.

- src/DatabaseMigrationTools/MigrationTargetDatabaseArgumentNames.cs
- tests/NuGet.Services.DatabaseMigration.Facts/NuGet.Services.DatabaseMigration.Facts.csproj
- tests/NuGet.Services.DatabaseMigration.Facts/PendingMigrationsFacts.cs
- tests/NuGet.Services.DatabaseMigration.Facts/Properties/AssemblyInfo.cs
This adds a unit test that fails if there are any pending changes in the entity model. It asserts that if someone was to run `Add-Migration`, an empty migration would be added (indicating the latest migration matches the entity model).
Found with https://github.com/NuGet/NuGetGallery/issues/7140.
Addresses https://github.com/NuGet/NuGetGallery/issues/4934.
> Add pending migration test

- src/NuGetGallery/Scripts/gallery/common.js
- src/NuGetGallery/Views/Shared/ListPackages.cshtml
- src/NuGetGallery/Views/Shared/_ListPackage.cshtml
Address https://github.com/NuGet/NuGetGallery/issues/6803.
Adds two new events to Google Analytics:
1. `search-selection`. This is emitted when someone clicks a search result. This includes the absolute index of the selection. In other words, with page size 20 and you click the 4th result on the 3rd page, the index will be `(20 * (3 - 1)) + (4 - 1) = 43`.
1. `search-page`. This is emitted when someone navigates to a page of search results. The page index is emitted with this event.
There is parity between these events and the client event where appropriate.
These events are only emitted when there is a search term. Our main search ranking efforts are going into relevancy towards the search query, not to the default page of popular packages. I would rather not add noise to the events …
> Add Google Analytics events for search

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Scripts/gallery/async-file-upload.js
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
Quick fix for https://github.com/NuGet/NuGetGallery/issues/6956 that I encountered previously and while working on https://github.com/nuget/nugetgallery/issues/7154
Basically, because we are returning `401` (unauthorized) in a UI request, MVC automatically redirects the request to the authentication middleware which returns `200` because the user is logged in. As a result, the Javascript on the upload page thinks the request succeeded and shows some weird behavior.
I did not change this for the API symbols push path because I'm not sure of the impact it will have on NuGet clients. I also don't think the authentication middleware redirect happens for API symbols push because API controller methods use different authentication middleware and [we already have another flow that returns …
> UI should return Forbidden when symbols feature flag is disabled

- src/NuGetGallery/Services/PackageUploadService.cs
- tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs
Addresses #7147.
The issue was that the `_coreLicenseFileService.ExtractAndSaveLicenseFileAsync` call in `PackageUploadService` left the package stream with `Position` pointing to the middle of the stream, so `_packageFileService.SavePackageFileAsync` saved the package starting from that position.
> Fix for the package corruption when license file is extracted by Gallery

- src/NuGetGallery.Core/Entities/IEntitiesContext.cs
- tests/NuGetGallery.Facts/TestUtils/FakeEntitiesContext.cs
Related to https://github.com/NuGet/NuGet.Services.Metadata/pull/518#discussion_r284468321.
This allows `IEntitiesContext` to be provided by DI and still disposed via a factory pattern.
> Make IEntitiesContext implement IDisposable

- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/Configuration/AppConfiguration.cs
- src/NuGetGallery/Configuration/IAppConfiguration.cs
- src/NuGetGallery/Infrastructure/Lucene/ExternalSearchService.cs
- src/NuGetGallery/Infrastructure/Lucene/SearchClientConfiguration.cs
- tests/NuGetGallery.Facts/Services/FeedServiceFacts.cs
Progress on https://github.com/NuGet/NuGetGallery/issues/7152.
- Add config for two "preview" search endpoints.
- Add an `ISearchService` instance that hits these preview endpoints
- This is available with a binding key. The default `ISearchService` has not changed.
This basic infrastructure is for the side-by-side search page and can be adapted for https://github.com/NuGet/NuGetGallery/issues/7166 later.
To do this, I needed to move the DI wire-up of `ISearchService` to Autofac, which has binding key support.
> Add capability of a preview ISearchService

- src/NuGetGallery/App_Data/Files/Content/flags.json
- src/NuGetGallery/Infrastructure/Mail/Messages/SearchSideBySideMessage.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/FeatureFlagService.cs
- src/NuGetGallery/Services/IFeatureFlagService.cs
- src/NuGetGallery/Services/ITelemetryService.cs
- src/NuGetGallery/Services/SearchResults.cs
- src/NuGetGallery/Services/TelemetryService.cs
- src/NuGetGallery/ViewModels/SearchSideBySideViewModel.cs
- src/NuGetGallery/Web.config
- tests/NuGet.Services.DatabaseMigration.Facts/ValidateMigrationsFacts.cs
- tests/NuGetGallery.Facts/Infrastructure/Mail/Messages/SearchSideBySideMessageFacts.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/Services/TelemetryServiceFacts.cs
Progress on https://github.com/NuGet/NuGetGallery/issues/7152.
- Add feature flag
- Add an email message that will be sent when people leave feedback
- Email address and comments should not be recorded in AI and therefore take a path like support requests.
- Add telemetry to record SxS search and feedback in AI
- Just "metadata" not comments or email address
- Minor style issues in existing code (VS was nagging me)
This is what the email looks like:
Look at the view model for an idea of the kind of data we are going to pass to the view and get back from the feedback form. Here's a sneak-peak of the UI (PR forthcoming) to help you understand the goal. Please leave UI comments to a future PR.
> [SxS 1] Add initial infrastructure for search side-by-side (SxS) page

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/base.less
Related to https://github.com/microsoft/accessibility-insights-web/issues/692
Related to https://bugs.chromium.org/p/chromium/issues/detail?id=647594
This is a workaround suggested by the Accessibility Insights team (the tool formerly known as Keros). This means there is less noise in our accessibility passes using this tool.
> Work around Chromium bug that gives false positives during accessibility pass

- src/DatabaseMigrationTools/DatabaseMigrationTools.csproj
- src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj
- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery/NuGetGallery.csproj
Related to https://github.com/NuGet/NuGet.Jobs/pull/759.
Bringing in version parity between repos.
Difference between 2.46 and 2.48: https://github.com/NuGet/ServerCommon/compare/a827b73d00bf971c631149461d2afcaa862a9382...172a0f385dec8b90f5efb889d1d6f0996a3f9b0e?expand=1
> Aligning ServerCommon versions with NuGet.Jobs

- src/DatabaseMigrationTools/DatabaseMigrationTools.csproj
- src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj
- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery.Services/NuGetGallery.Services.csproj
- src/NuGetGallery/Areas/Admin/Controllers/ValidationController.cs
- src/NuGetGallery/Areas/Admin/Views/Validation/Index.cshtml
- src/NuGetGallery/NuGetGallery.csproj
The new DB migration in validation DB adds a status column to validation sets. Also, polish the validation page a little bit.
Progress on https://github.com/NuGet/NuGetGallery/issues/7185.
> Update ServerCommon version to pull in latest validation DB migration

- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Views/Api/HealthProbeApi.cshtml
Applying the HealthProbe changes as part of https://github.com/NuGet/NuGetGallery/pull/7198 as a hotfix.
> Hotfix: Wrap HealthProbe endpoint in a Razor view

- src/NuGetGallery/App_Start/OwinStartup.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Telemetry/DeploymentIdTelemetryEnricher.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/Telemetry/DeploymentIdTelemetryEnricherFacts.cs
This can help us distinguish between USNC-USSC, production-staging slot. This is the same value we see in our internal telemetry system for "tenant".
The actual name of the slot and cloud service resource is not directly available. See:
https://stackoverflow.com/questions/24522781/get-cloud-service-name-in-a-web-role
I am in the process of confirming this on DEV.
> Add deployment ID value to Application Insights telemetry

- src/NuGetGallery/Scripts/gallery/common.js
Discovered when testing out search click index telemetry. With this change, we now emit our "click" event when someone uses the middle-mouse click on a tracked link.
I left the existing logic for left-click.
Address https://github.com/NuGet/NuGetGallery/issues/7248
> Emit Google Analytics click event on middle-mouse click

- src/NuGet.Services.Entities/Extensions/PackageExtensions.cs
- src/NuGetGallery/Controllers/ApiController.cs
- src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
- tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
Allow the pre-published symbols to be downloaded after newer symbols are being published/failed validation.
See https://github.com/NuGet/NuGetGallery/issues/7222#issuecomment-499686460 snapshots
Also, updated the link for "Blog" header to point to new blogs pages.
> Allow published symbols to be downloaded after re-upload failures and Blog updates

- src/NuGetGallery/Views/Users/ApiKeys.cshtml
https://github.com/nuget/nugetgallery/issues/7032
This bug prevents me from creating new API keys on my DEV account so I decided to fix it.
It also affects DEV's NuGetTestAccount.
> Use JsonConvert for API keys list

- src/NuGetGallery/Extensions/NumberExtensions.cs
Currently the int.ToKiloFormat() is Culture sensitive. This PR fixes that.
(See [Build #57489](https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=57489))
> Fixing ToKiloFormat method

- src/NuGetGallery/Scripts/gallery/page-display-package.js
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
This PR adds analytics for the GitHub Usage section. 
The 2 metrics are:
- Clicks on the GitHub Usage section (show/hide)
- Clicks on the GitHub repo links (which index was clicked/how many total clicks)
> [GH Usage] Added analytics

- src/NuGetGallery/Controllers/ManageDeprecationJsonApiController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Services/FeatureFlagService.cs
- src/NuGetGallery/Services/IFeatureFlagService.cs
- tests/NuGetGallery.Facts/Controllers/ManageDeprecationJsonApiControllerFacts.cs
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
- tests/NuGetGallery.Facts/Services/FeatureFlagServiceFacts.cs
https://github.com/nuget/nugetgallery/issues/7159
Basically, if the feature goes haywire, we want to be able to turn it off for packages with many versions while not affecting people with few versions.
Right now I've set the cut-off at 500. I think this is sufficiently low given the performance I've seen on DEV--even doing a bulk update on a thousand versions doesn't seem to have a large effect.
Also, if the existing feature flag is enabled but the "many versions" flag is not configured, I have it returning true. This means that if the existing flag is enabled, we would need to explicitly disable it for many versions to turn it off for many versions. I think this is ideal because it will make it harder for us to not notice when it's turned on for few versions and turned off for many …
> Add feature flag for deprecating a package with many versions

- src/NuGetGallery/Controllers/ManageDeprecationJsonApiController.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/RequestModels/DeprecatePackageRequest.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- src/NuGetGallery/Views/Packages/_DisplayPackageDeprecation.cshtml
- tests/NuGetGallery.Facts/Controllers/ManageDeprecationJsonApiControllerFacts.cs
https://github.com/NuGet/NuGetGallery/issues/7277
https://github.com/NuGet/NuGetGallery/issues/7278
https://github.com/NuGet/NuGetGallery/issues/7279
https://github.com/NuGet/NuGetGallery/issues/7280
https://github.com/NuGet/NuGetGallery/issues/7281
The bulk of these changes were to move the deprecation request parameters to a model so I can add `[AllowHtml]` to the custom message. Otherwise, the changes were fairly trivial.
> Fix deprecation custom message issues

- src/NuGetGallery/Scripts/gallery/common.js
- src/NuGetGallery/Views/Shared/ListPackages.cshtml
- src/NuGetGallery/Views/Shared/_ListPackage.cshtml
- src/NuGetGallery/Web.config
Address https://github.com/NuGet/NuGetGallery/issues/7287
I will keep it side-by-side with Google Analytics so we can understand if we are missing data. I think this is a better model overall and works great for click events performed within our site.
For outgoing links we would probably need to investigate the beacon API in AI to avoid events dropped during page transition.
Issue https://github.com/NuGet/NuGetGallery/issues/7289 tracks removing GA later.
> Emit Application Insights metric from browser for search selection

- src/NuGetGallery.Services/Configuration/AppConfiguration.cs
- src/NuGetGallery.Services/Configuration/IAppConfiguration.cs
- src/NuGetGallery.Services/ServicesStrings.Designer.cs
- src/NuGetGallery.Services/ServicesStrings.resx
- src/NuGetGallery/Services/PackageUploadService.cs
- src/NuGetGallery/Strings.Designer.cs
- src/NuGetGallery/Strings.resx
- src/NuGetGallery/Web.config
- tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs
Addresses #7083 
Don't need it anymore as license implementation is live for quite some time now.
There is an accompanying configuration update PR.
> Removed the "RejectPackagesWithLicense" configuration option.

- src/NuGetGallery.Services/PackageManagement/PackageHelper.cs
- src/NuGetGallery.Services/ServicesStrings.Designer.cs
- src/NuGetGallery.Services/ServicesStrings.resx
- tests/NuGetGallery.Facts/Helpers/PackageHelperTests.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
User friendly mitigation for https://github.com/NuGet/Engineering/issues/2481
> Limiting the id + version length to 160 characters.

- src/NuGetGallery.Services/AccountManagement/DeleteAccountService.cs
- src/NuGetGallery.Services/PackageManagement/PackageService.cs
- tests/NuGetGallery.Facts/Services/DeleteAccountServiceFacts.cs
- tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
Remove orphan registrations on user delete. 
Addresses [Deleting a user does not remove their ownership from package registrations without packages](https://github.com/NuGet/NuGetGallery/issues/7197)
> Clean orphan package registration on user delete

- src/AccountDeleter/Telemetry/GalleryTelemetryService.cs
- src/NuGetGallery.Services/Configuration/ABTestConfiguration.cs
- src/NuGetGallery.Services/Configuration/IABTestConfiguration.cs
- src/NuGetGallery.Services/NuGetGallery.Services.csproj
- src/NuGetGallery.Services/ServicesConstants.cs
- src/NuGetGallery.Services/Storage/ContentObjectService.cs
- src/NuGetGallery.Services/Storage/IContentObjectService.cs
- src/NuGetGallery.Services/Telemetry/ITelemetryService.cs
- src/NuGetGallery/App_Data/Files/Content/AB-Test-Configuration.json
- src/NuGetGallery/App_Data/Files/Content/flags.json
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/FeatureFlagService.cs
- src/NuGetGallery/Services/IFeatureFlagService.cs
- src/NuGetGallery/Services/TelemetryService.cs
- tests/NuGetGallery.Facts/Services/ContentObjectServiceFacts.cs
- tests/NuGetGallery.Facts/Services/TelemetryServiceFacts.cs
Progress on https://github.com/NuGet/NuGetGallery/issues/7166
1. Add a config type to content object service to define test percentage
1. Add a flight to turn the whole thing off if necessary
1. Add telemetry when A/B tests are evaluated and when users are enrolled
More PRs to come.
> [A/B Test 1] Add A/B test content file, flight, and telemetry

- src/AccountDeleter/Telemetry/GalleryTelemetryService.cs
- src/NuGetGallery.Services/Telemetry/ITelemetryService.cs
- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/Services/CloudDownloadCountService.cs
- src/NuGetGallery/Services/DownloadCountObjectMaterializedInterceptor.cs
- src/NuGetGallery/Services/TelemetryService.cs
- tests/NuGetGallery.Facts/Services/CloudDownloadCountServiceFacts.cs
- tests/NuGetGallery.Facts/Services/TelemetryServiceFacts.cs
Adding additional telemetry around statistics in gallery.
Adds metrics for the following:
Interceptor replaces a gallery values with a smaller values from downloads for package
Interceptor replaces a gallery values with a smaller values from downloads for package registration
Request to get stats for package fails
Request to get stats for package registration fails
Duration of downloads.v1.json refresh
Update of downloads.v1.json causes a decrease in download count.
Also rejects updates to internal download count in service if it would lower the download count of a package.
@cristinamanum
> Additional Statistics Telemetry

- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/Infrastructure/ABTestEnrollment.cs
- src/NuGetGallery/Infrastructure/ABTestEnrollmentFactory.cs
- src/NuGetGallery/Infrastructure/ABTestEnrollmentState.cs
- src/NuGetGallery/Infrastructure/CookieBasedABTestService.cs
- src/NuGetGallery/Infrastructure/IABTestEnrollmentFactory.cs
- src/NuGetGallery/Infrastructure/IABTestService.cs
- src/NuGetGallery/NuGetGallery.csproj
- tests/NuGetGallery.Facts/Infrastructure/ABTestEnrollmentFactoryFacts.cs
- tests/NuGetGallery.Facts/Infrastructure/CookieBasedABTestServiceFacts.cs
- tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
Progress on https://github.com/NuGet/NuGetGallery/issues/7166
Depends on https://github.com/NuGet/NuGetGallery/pull/7310
This is the meat of the assignment logic for A/B testing.
> [A/B Test 2] Add A/B test enrollment service and cookie

- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/ViewModels/PackageListViewModel.cs
- src/NuGetGallery/Views/Shared/ListPackages.cshtml
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
Depends on https://github.com/NuGet/NuGetGallery/pull/7311
Address https://github.com/NuGet/NuGetGallery/issues/7166
This toggles the search client used for package search based on the user's cookie. This also toggles the telemetry emitted.
> [A/B Test 3] Integrate A/B test service with package search

- src/NuGetGallery/Controllers/AccountsController.cs
- tests/NuGetGallery.Facts/Controllers/OrganizationsControllerFacts.cs
Attempt to address https://github.com/NuGet/Engineering/issues/2512
> Fix for "Resend confirmation email" button to use the correct email address

- src/NuGetGallery/Views/Shared/ListPackages.cshtml
Address https://github.com/NuGet/NuGetGallery/issues/7187
The one place I think we should index is the base search results page so `nuget.org search` Google search still works:
> Don't index search results pages

- src/AccountDeleter/Configuration/GalleryConfiguration.cs
- src/NuGetGallery.Services/Configuration/AppConfiguration.cs
- src/NuGetGallery.Services/Configuration/IAppConfiguration.cs
- src/NuGetGallery.Services/Telemetry/ITelemetryService.cs
- src/NuGetGallery.Services/Telemetry/TelemetryService.cs
- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/Infrastructure/Lucene/HttpClientBuilderExtensions.cs
- src/NuGetGallery/Infrastructure/Lucene/SearchClientPolicies.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Web.config
- tests/NuGetGallery.Facts/Infrastructure/Lucene/SearchPolicyFacts.cs
- tests/NuGetGallery.Facts/Services/TelemetryServiceFacts.cs
When a timeout occurs, consider this as an error for the circuit breaker.
Progress on https://github.com/NuGet/NuGetGallery/issues/7119
Previously everyone would always encounter the timeout case on USNC and the circuit breaker would never open.
> Move search timeout from HttpClient to Polly timeout policy

- src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs
At some point the method signature diverged from the documentation, this brings back the parity and the ability to navigate to method definition in VS.
> Small documentation fix

- src/AccountDeleter/AccountDeleteUserService.cs
- src/AccountDeleter/EmptyUserService.cs
- src/NuGet.Services.Entities/Extensions/RoleExtensions.cs
- src/NuGet.Services.Entities/NuGet.Services.Entities.csproj
- src/NuGet.Services.Entities/Role.cs
- src/NuGet.Services.Entities/User.cs
- src/NuGetGallery.Services/UserManagement/IUserService.cs
- src/NuGetGallery.Services/UserManagement/UserService.cs
- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/Areas/Admin/Controllers/SiteAdminsController.cs
- src/NuGetGallery/Areas/Admin/ViewModels/SiteAdminsViewModel.cs
- src/NuGetGallery/Areas/Admin/Views/Home/Index.cshtml
- src/NuGetGallery/Areas/Admin/Views/SiteAdmins/Index.cshtml
- src/NuGetGallery/NuGetGallery.csproj
- tests/NuGetGallery.Facts/Services/UserServiceFacts.cs
- tests/NuGetGallery.Facts/TestUtils/TestServiceUtility.cs
Currently, we don't have a UI that allows us to manage site admins. Previously, we had the database editor, which we would use to do this, but we recently removed it. As a result, now, whenever we need to onboard someone to the team, we have to gain database access and make a SQL query to make them a site admin.
This PR adds a simple UI to the admin section of the site that allows us to easily and quickly manage site admins.
> Add page for managing site admins

- src/AccountDeleter/AccountDeleter.csproj
- src/DatabaseMigrationTools/DatabaseMigrationTools.csproj
- src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj
- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery.Services/NuGetGallery.Services.csproj
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/AsynchronousPackageValidationInitiator.cs
- tests/NuGetGallery.Facts/Services/AsynchronousPackageValidationInitiatorFacts.cs
React to the breaking API changes in https://github.com/NuGet/ServerCommon/pull/303, which blocks testing https://github.com/NuGet/ServerCommon/pull/297. This does not change any existing functionality.
Addresses https://github.com/NuGet/NuGetGallery/issues/7411
> Upgrade ServerCommon dependency

- src/NuGetGallery/Scripts/gallery/page-home.js
jQuery3.x has fully removed the $(document).on("ready") binding for binding events to page ready (see https://api.jquery.com/ready/ for details).
This caused the modal dialog "show" method to never actually get called.
This appears to be the only place we use the document.on('ready') pattern, so update it to the proper, non-deprecated jQuery3.x ready binding.
Thanks to @adamjcooper for catching and reporting this (https://github.com/NuGet/NuGetGallery/issues/7415)
> [Hotfix]Update modal dialog show binding.

- src/NuGetGallery/Views/Shared/ListPackages.cshtml
Currently, it is a checkbox that refreshes the page upon checking/unchecking, which is very confusing for screen readers. Functionally, it behaves like a link, so we have changed it to a link.
Alternatively, we considered changing the form to ajax, but ultimately that is a very nontrivial change.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/910827
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/905602
> "Include prerelease" checkbox should be a link

- src/NuGetGallery.Core/Services/CloudBlobClientWrapper.cs
- tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceIntegrationTests.cs
Related to https://github.com/NuGet/Engineering/issues/2633
See https://github.com/Azure/azure-storage-net/issues/470#issuecomment-306245417 for more information.
There is no timeout by default. This API change will allow Azure Search Service to set a reasonable timeout instead of being unbounded.
> Add support for custom default request options in CloudBlobClientWrapper

- tests/NuGetGallery.FunctionalTests.Core/Helpers/ClientSdkHelper.cs
- tests/NuGetGallery.FunctionalTests.Core/Helpers/ODataHelper.cs
- tests/NuGetGallery.FunctionalTests.Core/Helpers/UploadHelper.cs
- tests/NuGetGallery.FunctionalTests.Core/XunitExtensions/GalleryTestBase.cs
- tests/NuGetGallery.FunctionalTests/Commandline/NuGetCommandLineTests.cs
- tests/NuGetGallery.FunctionalTests/License/LicenseTests.cs
- tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedExtendedTests.cs
- tests/NuGetGallery.FunctionalTests/PackageCreation/ApiPushTests.cs
- tests/NuGetGallery.FunctionalTests/PackageCreation/SecurityPolicyTests.cs
This fixes two issues observed:
- `PackagesAppearInFeedInOrderTest` sometimes failed because too many pushes happened from other caller during the test. This causes it to not be able to find a package in the first 100 packages after an arbitrary timestamp.
- `DateTime.[Utc]Now.Ticks` is not a good way to generate unique identifiers. I've observed some 409s. See https://stackoverflow.com/a/2143163. As a side note, I think we had an SDL task about this but perhaps missed/skipped this test code.
> Reduce flakiness of functional tests

- src/NuGetGallery/Scripts/gallery/common.js
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/905677
When the jQuery Validation plugin finds an issue with an input field, it adds a `span` containing the error message to a `span` that has `role=alert`. As a result, Narrator reads `alert group <the error message>`. This is because Narrator thinks the `div` is a `group` containing multiple elements instead of just one. Furthermore, [the jQuery Validation plugin only supports a single error message for every field](https://github.com/jquery-validation/jquery-validation/issues/2146), so there will never be more than one error message anyway, so wrapping the error message in a container is invalid.
To fix this, I have added some post-processing logic that gets rid of the nested `span` and moves the error message to the parent span. …
> Unwrap error messages generated by jQuery Validation

- src/NuGetGallery/App_Code/ViewHelpers.cshtml
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/917879
For some reason, the last nodes in our breadcrumbs do not read aloud to screen readers. I was not able to figure out why narrator was refusing to read the span, but it appears that, [according to accessibility guidance available online](https://www.w3.org/TR/wai-aria-practices/examples/breadcrumb/index.html), breadcrumbs should be represented as lists. When I added the roles to the HTML, the screen reader began to properly read the breadcrumbs.
I started by rewriting the HTML into `<ol>` and `<ul>`, but doing so started a fight against the default CSS, so I felt that adding the roles, given that it is functionally equivalent to a screen reader, was a better choice.
> Breadcrumbs should be represented as lists to screenreaders

- tests/NuGetGallery.FunctionalTests.Core/Helpers/ClientSdkHelper.cs
- tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedExtendedTests.cs
A recent backend change has made this test flaky, because listing changes are not immediately available in OData. This causes a race condition between the unlist becoming available in OData and the timestamp comparison.
> [Hotfix] PackagesAppearInFeedInOrderTest should wait for unlisted packages to be unlisted in feed before checking timestamps

- src/NuGetGallery/Views/Users/TransformToOrganization.cshtml
https://github.com/nuget/nugetgallery/issues/7325
We shouldn't ask for user confirmation if the form is invalid--e.g. the username is empty or contains disallowed characters.
> Transform form shouldn't ask for confirmation if form is invalid

- tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedExtendedTests.cs
Resolution of a merge conflict ended up causing a build issue. This patch fixes the error.
> [Hotfix]Pass through version on a timestamp check.

- src/AccountDeleter/AccountDeleter.csproj
- src/AccountDeleter/Job.cs
- src/DatabaseMigrationTools/DatabaseMigrationTools.csproj
- src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj
- src/NuGetGallery.Core/Features/EditableFeatureFlagFileStorageService.cs
- src/NuGetGallery.Core/Features/FeatureFlagFileStorageService.cs
- src/NuGetGallery.Core/Features/FeatureFlagSaveResult.cs
- src/NuGetGallery.Core/NuGetGallery.Core.csproj
- src/NuGetGallery.Services/NuGetGallery.Services.csproj
- src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
- src/NuGetGallery/App_Start/StorageDependent.cs
- src/NuGetGallery/NuGetGallery.csproj
- tests/NuGetGallery.Core.Facts/Features/EditableFeatureFlagFileStorageServiceFacts.cs
- tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj
- tests/NuGetGallery.Facts/App_Start/StorageDependentFacts.cs
Update to latest server common to pull in https://github.com/NuGet/ServerCommon/pull/306
Progress on https://github.com/NuGet/NuGetGallery/issues/7439
This will allow other components (e.g. NuGet.Jobs) to use feature flags without needing the "write" feature flag method. In particular, the "write" feature flag service (`EditableFeatureFlagFileStorageService`) needs an `IAuditingService` which shouldn't be needed in a background job context where only "read" feature flag operations are performed.
The NuGet.Services.FeatureFlags update makes app shutdown much faster. I was able to trigger the cancellation token provided by `HostingEnvironment.QueueBackgroundWorkItem` getting to a cancelled state by stopping the site in IIS Express. It seems like the shutdown before this change triggered …
> [Queue-Back 1] Split read vs. read/write feature flag storage services

- src/Bootstrap/dist/css/bootstrap-theme.css
- src/Bootstrap/less/theme/all.less
- src/Bootstrap/less/theme/page-admin-index.less
- src/NuGetGallery/Areas/Admin/Views/Home/Index.cshtml
The `<ul>` dots before the icons look bad. Also it's too spaced out.
> Make the admin index page a little better looking

- src/NuGetGallery/Views/Organizations/Add.cshtml
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/904941
I misread this bug--turns out they were talking about the organization image's tooltip and not the logo icon's tooltip (which we've removed).
> Add aria-label to Add Organization page logo

- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
https://github.com/nuget/nugetgallery/issues/7452
This was the only difference between the other expanders on the page and this one.
> GitHub Usage expander should be tabbable

- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Views/Shared/ListPackages.cshtml
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
Address https://github.com/NuGet/NuGetGallery/issues/7455
Also, add a GUID to correlate clicks and searches more precisely than search term.
> [Azure Search] Allow default searches to go to preview search

- src/NuGetGallery.Core/CoreConstants.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Extensions/ImageExtensions.cs
- src/NuGetGallery/Helpers/ViewModelExtensions/DisplayPackageViewModelFactory.cs
- src/NuGetGallery/NuGetGallery.csproj
- src/NuGetGallery/Services/PackageUploadService.cs
- src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
- src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- src/NuGetGallery/Views/Packages/_VerifyMetadata.cshtml
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
Addresses #7239, #7093.
Moved the image type identification bits to the `ImageExtensions` to be shared between controllers and services.
Updated `PackagesController` to identify the image type from the image signature and generate data: url with proper content type.
On a verify package page it looks like this:
(the icon in this case is 1024x1024 reduced by browser to our "regular size")
> Embedded icon display on verify package page and indexing message

- src/NuGetGallery/Controllers/JsonApiController.cs
- src/NuGetGallery/Controllers/OrganizationsController.cs
- src/NuGetGallery/Controllers/PackagesController.cs
- src/NuGetGallery/Infrastructure/Mail/Messages/OrganizationMembershipRequestInitiatedMessage.cs
- src/NuGetGallery/Infrastructure/Mail/Messages/PackageOwnershipRequestInitiatedMessage.cs
- src/NuGetGallery/Scripts/gallery/common.js
- src/NuGetGallery/Scripts/gallery/page-manage-packages.js
- src/NuGetGallery/UrlHelperExtensions.cs
- src/NuGetGallery/Views/Users/Packages.cshtml
- tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
- tests/NuGetGallery.Facts/Infrastructure/Mail/MarkdownMessageServiceFacts.cs
- tests/NuGetGallery.Facts/Infrastructure/Mail/Messages/OrganizationMembershipRequestInitiatedMessageFacts.cs
Progress on https://github.com/NuGet/Engineering/issues/2679
Depends on https://github.com/NuGet/NuGetGallery/pull/7497.
The `CancelPendingOwnershipRequest` endpoint was a GET without a token but it performed an action. This is against CSRF rules. The fix was to make the endpoint redirect the existing URL to the manage package page with the owners section auto-expanded. This is so existing links in the email are not broken.
The new UI on the Packages page is this (a pencil instead of an "x"):
The old UI looked like this:
I considered the word "Manage" instead of a pencil but I thought this was more consistent with the rest of the page. Note that this adds an additional hope to cancel an ownership request from the packages page. I could do a POST on click here but this would take some …
> Make the cancel ownership request endpoint just redirect to Manage Owners

- src/NuGetGallery/Infrastructure/Lucene/GallerySearchClient.cs
- src/NuGetGallery/Infrastructure/Lucene/Models/SortOrder.cs
- src/NuGetGallery/OData/SearchService/SearchAdaptor.cs
- tests/NuGetGallery.Facts/Infrastructure/Lucene/GallerySearchServiceFacts.cs
- tests/NuGetGallery.Facts/Services/SearchAdaptorFacts.cs
Progress on https://github.com/NuGet/NuGetGallery/issues/5432.
For `/api/v2/FindPackagesById()`, if no `$orderby` is specified, use order by Created timestamp (ascending) by default. The previous behavior was to use relevance ordering which makes no sense on such an API. This code can ship immediately because both old search and Azure Search default unrecognized sort orders to `Relevance`. In other words, this will begin to work when both a) we move hijack queries over to Azure Search and b) Azure Search supports order by created.
The `/api/v2/Search()` endpoint still defaults to ordering by relevance.
> Order by created ascending by default in FindPackagesById()

- src/NuGetGallery/Scripts/gallery/page-display-package.js
This reverts commit 8c5b4e8836f57b050dff8ef98d458cb82fb4379a.
This causes the documentation of more than 10 lines to stay collapsed even if you click "Show more"
/cc @304NotModified, I'll look into the root cause later. For now we are reverting it to unblock our deployment.
> [Hotfix] Revert "Click on "show more" should not scroll page to top (#7420)"

- src/NuGetGallery/Scripts/gallery/page-display-package.js
As mentioned on https://github.com/NuGet/NuGetGallery/pull/7516#issuecomment-529023098. Thanks for the top, @304NotModified. Worked like a charm.
> Make the readme show more link not jump to the top of the page
