src/NuGetGallery/Content/Site.css

Adjusted height of actionlist-item

---

src/NuGetGallery/Views/Shared/Layout.cshtml

Because I got tired of that extra click all the time...

Add autofocus to search input

---

src/NuGetGallery.Core/Packaging/Nupkg.cs
src/NuGetGallery/Controllers/PackagesController.cs

Show error for invalid packages instead of 500

---

src/NuGetGallery/Infrastructure/Jobs/NuGetJobCoordinator.cs

To fix download counter.
https://github.com/NuGet/NuGetGallery/issues/2306

Issue 2306: Allow for jobs with a TaskStatus of 'Created' to be started.

---

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

Fixes https://github.com/NuGet/NuGetGallery/issues/2491

Add permalink to current version in version history

---

tests/NuGetGallery.FunctionalTests.Fluent/AccountManagement/ContactEmailTest.cs
tests/NuGetGallery.FunctionalTests.Fluent/EditableMetadata/EditAndSearchTest.cs
tests/NuGetGallery.FunctionalTests.Fluent/EditableMetadata/EditPackageAsPartOfUploadTest.cs
tests/NuGetGallery.FunctionalTests.Fluent/ExtensionMethods.cs
tests/NuGetGallery.FunctionalTests.Fluent/NuGetGallery.FunctionalTests.Fluent.csproj
tests/NuGetGallery.FunctionalTests.Fluent/PackageManagement/PackageManagementTest.cs
tests/NuGetGallery.FunctionalTests.Fluent/SearchTests/SearchUITest.cs
tests/NuGetGallery.FunctionalTests.Fluent/Statistics/StatisticsPageTest.cs
tests/NuGetGallery.FunctionalTests.Fluent/Statistics/StatsInHomePageTest.cs
tests/NuGetGallery.FunctionalTests.Fluent/UploadAndDownload/1826RegressionTest.cs
tests/NuGetGallery.FunctionalTests.Fluent/packages.config
tests/NuGetGallery.FunctionalTests.Helpers/AssertAndValidationHelper.cs
tests/NuGetGallery.FunctionalTests.Helpers/CmdLineHelper.cs
tests/NuGetGallery.FunctionalTests.Helpers/Constants.cs
tests/NuGetGallery.FunctionalTests.Helpers/MetricsServiceHelper.cs
tests/NuGetGallery.FunctionalTests.Helpers/NuspecHelper.cs
tests/NuGetGallery.FunctionalTests.Helpers/ODataHelper.cs
tests/NuGetGallery.FunctionalTests.Helpers/PackageCreationHelper.cs
tests/NuGetGallery.FunctionalTests/ClientIntegrationTests/UploadAndDownload/NuGetCommandLineTests.cs
tests/NuGetGallery.FunctionalTests/GalleryTestBase.cs
tests/NuGetGallery.FunctionalTests/ODataTests/FeedTests/CuratedFeedTest.cs
tests/NuGetGallery.FunctionalTests/ODataTests/FeedTests/SearchTest.cs
tests/NuGetGallery.FunctionalTests/ODataTests/FeedTests/V2FeedExtendedTest.cs
tests/NuGetGallery.FunctionalTests/ODataTests/FeedTests/V2FeedTest.cs
tests/NuGetGallery.FunctionalTests/ODataTests/LoadTests/LoadTests.cs
tests/NuGetGallery.FunctionalTests/ODataTests/Statistics/PackageStatsTests.cs
tests/NuGetGallery.FunctionalTests/WebUITests/AccountManagement/LogonTest.cs
tests/NuGetGallery.FunctionalTests/WebUITests/ReadOnlyMode/UploadPackageFromInUIInReadOnlyMode.cs
tests/NuGetGallery.FunctionalTests/WebUITests/UploadAndDownload/UploadPackageFromUI.cs

Also upgraded selenium dependencies to latest available.

Converted functional tests to async model

---

src/NuGetGallery/Areas/Admin/Views/Web.config
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Views/web.config
src/NuGetGallery/Web.config
src/NuGetGallery/packages.config
tests/NuGetGallery.Facts/App.config
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
tests/NuGetGallery.Facts/packages.config

Follow #2488, only upgrade MVC to 5.2.3.

upgrade MVC to 5.2.3

---

src/NuGetGallery/DataServices/SearchAdaptor.cs
src/NuGetGallery/DataServices/V2Feed.svc.cs
tests/NuGetGallery.Facts/Services/FeedServiceFacts.cs

Don't merge it just yet.
* Fixed OData feed (FindPackagesById())
* Package details page pending.

Don't hit the database for retrieving packages #2527

---

src/NuGetGallery/Constants.cs
src/NuGetGallery/Controllers/ApiController.cs
src/NuGetGallery/Controllers/PackagesController.cs

fixes #2697 - MinClientVersion support for v3.2

---

appveyor.yml

supersedes #2707
Addition of a config file to build successful with [AppVeyor CI](https://ci.appveyor.com). 
This is not meant as a replacement of the current build server, TeamCity CI.
Building with AppVeyor, next to TeamCity gives the following benefits:
- In a PR it's clear if the submitted code compiles and won't break any unit tests
- The build and test status is clear en public visible
- It looks professional IMO ;)
downsides:
- None
Example output: 
https://ci.appveyor.com/project/304NotModified/nugetgallery/build/1.0.6
This PR only creates a config file. To add the AppVeyor webhook to GitHub, AppVeyor should be integrated to this repository. This can be done by the following (simple) steps: 
1. Sign in to AppVeyor (https://ci.appveyor.com)
1. Click button "new project"
1. GitHub / …

Add AppVeyor CI config

---

src/NuGetGallery/Controllers/UsersController.cs
src/NuGetGallery/ViewModels/ConfirmationViewModel.cs
src/NuGetGallery/Views/Users/Confirm.cshtml
src/NuGetGallery/Views/Users/ConfirmationRequired.cshtml

fixes #2731.
And maybe #2199. 
Supersedes #2732 (which was PR to master)

Handle already confirmed email

---

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

show exact date and time when you hover over the package date

---

src/NuGetGallery.Core/Entities/EntitiesContext.cs
src/NuGetGallery.Core/Entities/IEntitiesContext.cs
src/NuGetGallery/Areas/Admin/Views/Delete/Index.cshtml
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/RequestModels/DeletePackagesRequest.cs
src/NuGetGallery/Services/IPackageDeleteService.cs
src/NuGetGallery/Services/PackageDeleteService.cs
src/NuGetGallery/Views/Packages/Delete.cshtml
tests/NuGetGallery.Facts/Services/PackageDeleteServiceFacts.cs
tests/NuGetGallery.Facts/TestUtils/FakeEntitiesContext.cs

Delete feature should remove package registration when no packages are left #2791 
/cc @xavierdecoster @joyhui

Delete feature should remove package registration when no packages are left

---

README.md

Pointing to the new NuGet GitHub Home.

Link to home repo & link patch

---

src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Public/opensearch.xml
src/NuGetGallery/Views/Shared/Layout.cshtml

new PR for opensearch, as described in #2832
this one is made against `dev` branch and is composed of only 1 commit, as requested

add OpenSearch feature for easy in-browser search of packages

---

src/NuGetGallery.Operations/Infrastructure/ImportExportHelper.cs
src/NuGetGallery.Operations/Tasks/CreateWarehouseReportsTask.cs
src/NuGetGallery.Operations/Tasks/ReplicatePackageStatisticsTask.cs
src/NuGetGallery/Filters/CacheFilter.cs
src/NuGetGallery/Services/FormsAuthenticationService.cs
tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs

Changing all occurences of DateTime.Now to DateTime.UtcNow as per issue #2860

Fix for issue #2860

---

src/NuGetGallery/App_Start/Routes.cs
src/NuGetGallery/Controllers/JsonApiController.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/RouteNames.cs
src/NuGetGallery/Views/Packages/ConfirmOwner.cshtml
src/NuGetGallery/Views/Packages/ManagePackageOwners.cshtml
src/NuGetGallery/packages.config
tests/NuGetGallery.Facts/Controllers/JsonApiControllerFacts.cs

Fix broken jsonapi controller

---

src/NuGetGallery.Cloud/ServiceConfiguration.Cloud.cscfg
src/NuGetGallery.Cloud/ServiceConfiguration.Local.cscfg
src/NuGetGallery.Cloud/ServiceDefinition.csdef
src/NuGetGallery/Configuration/AppConfiguration.cs
src/NuGetGallery/Configuration/IAppConfiguration.cs
src/NuGetGallery/Controllers/ApiController.cs
src/NuGetGallery/Services/StatusService.cs

Fixes #2931
@maartenba @skofman1 @joyhui

Remove obsolete metrics service code from gallery

---

src/NuGetGallery/OData/SearchService/SearchHijacker.cs

Avoid an unhandled exception for `The 'substringof' function cannot be applied to an enumeration-typed argument`
Related to https://github.com/NuGet/NuGetGallery/issues/2916
@maartenba

Handle ODataException: return 400 BadRequest instead of 500 InternalServerError

---

content/PROD/Home.html
src/NuGetGallery/Views/Pages/About.cshtml
src/NuGetGallery/Views/Users/Account.cshtml

https://github.com/NuGet/Home/issues/2504#issuecomment-216063943 opening in reference to this issue

Update to accounts page to take into account the need for -Source parameter

---

tools/Enable-LocalTestMe.ps1

Quotes were erroneously placed before.

Fixing typo in makecert path

---

src/NuGetGallery.Core/Auditing/CloudAuditingService.cs
src/NuGetGallery.Core/Auditing/FileSystemAuditingService.cs

Fixes issue: https://github.com/NuGet/NuGetGallery/issues/3099

Use guid instead of timestamp in auditing files

---

src/NuGetGallery.Core/Packaging/ManifestValidator.cs
src/NuGetGallery/Helpers/PackageHelper.cs
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
src/NuGetGallery/Views/Shared/_ListPackage.cshtml
tests/NuGetGallery.Core.Facts/Packaging/ManifestValidatorFacts.cs

Validate on upload + when rendering view.
@blowdart @skofman1 @xavierdecoster

Ensure ProjectUrl, IconUrl and LicenseUrl properties link to http or https URL

---

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

Cosmetic change. Details here https://github.com/NuGet/NuGetGallery/pull/3143
(due to some Git-shell "problems" I closed the other PR ;))

NewLine for Prerelease Info Box

---

build.cmd

Added variable to build.cmd to capture the script path.

---

.vs/config/applicationhost.config
src/NuGetGallery/Views/Users/Account.cshtml

Adding a simple survey link to gauge Customer Effort Score. Starting small as a experiment to see if we can get folks to give us feedback. Will look into expanding more and redesigning if we are getting less responses.

CES Experiment

---

README.md
tools/Update-Databases.ps1

Solves Issue #3148.
I had to create a new PR because PR #3149 was including more changes than it should.
@anurse @robertmuehsig

Added Update-Databases.ps1. Updates the databases on the configuration connection string to the latest migration.

---

src/NuGetGallery/Services/CloudBlobFileStorageService.cs

Partial fix for https://github.com/NuGet/NuGetGallery/issues/3168
Forwards query string parameters to the package binary CDN download so
we fetch a fresh cache version from the CDN.
@scottbommarito @skofman1 @ryuyu

Append querystring to package binary download to bust CDN cache

---

build.msbuild

Run BinSkim as part of the build

---

src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/OData/SearchService/SearchAdaptor.cs

@skofman1 @xavierdecoster @scottbommarito

Package with Unicode characters is not searched correctly using the gallery #3186

---

src/NuGetGallery/Configuration/AppConfiguration.cs
src/NuGetGallery/Configuration/IAppConfiguration.cs
src/NuGetGallery/Services/MessageService.cs
src/NuGetGallery/Web.config
tests/NuGetGallery.Facts/Services/MessageServiceFacts.cs

All e-mail that are not support/need a reply address are now sent from a
noreply address.
@shishirx34 @ryuyu @xavierdecoster @skofman1

Send "package uploaded" notifications from a noreply e-mail address #3190

---

src/NuGetGallery/Authentication/AuthenticationService.cs
src/NuGetGallery/Controllers/UsersController.cs
src/NuGetGallery/ViewModels/AccountViewModel.cs
src/NuGetGallery/Views/Users/Account.cshtml
tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs
tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs

@harikmenon @skofman1 @xavierdecoster

Make resetting API key when changing password optional

---

src/NuGetGallery/Web.config
tests/NuGetGallery.Facts/Infrastructure/LuceneSearchServiceFacts.cs

Reopening https://github.com/NuGet/NuGetGallery/pull/3202 against the right branch.
Address the issues that scanning for credentials on our repository found.
@skofman1 @maartenba

Remove Secrets

---

src/NuGetGallery/Controllers/ODataV2FeedController.cs
src/NuGetGallery/OData/SearchService/SearchHijacker.cs

Fixes https://github.com/NuGet/NuGetGallery/issues/3207 and returns a
proper 400 (handled by OData framework).
@xavierdecoster @ryuyu  @shishirx34 @skofman1

Gallery throws exception on search requests that contain "toLower" #3207

---

src/NuGetGallery/Controllers/ErrorsController.cs

Fixes https://github.com/NuGet/NuGetGallery/issues/3228.

Accept both HTTP GET and HEAD requests on Errors/NotFound action

---

src/NuGetGallery/Controllers/StatisticsController.cs

Fixes #3229
@scottbommarito @xavierdecoster @skofman1 @shishirx34

Invalid stats report request causes 500 return code

---

src/NuGetGallery/Controllers/UsersController.cs
src/NuGetGallery/Views/Users/ResetPassword.cshtml
tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs

Also fixed text on page (copy paste issue from "Forgot Password" view.
@maartenba @xavierdecoster @shishirx34 @scottbommarito @ryuyu

Fix password reset page: validate model correctness

---

src/NuGetGallery/Authentication/Providers/LocalUser/LocalUserAuthenticator.cs

Change cookie expiration time from 14 days to 6 hours

---

src/NuGetGallery/Web.config

Fixes exceptions seen by #3194

Fix Failing requests

---

src/NuGetGallery/Views/Statistics/_PivotTable.cshtml

Fixes https://github.com/NuGet/NuGetGallery/issues/3297

Fix footer overlapping content on package statistics page

---

.gitignore
README.md

Based on the discussion from this PR https://github.com/NuGet/NuGetGallery/pull/3335 I added a couple of line to describe the current situation.
Hope this helps.

applicationhost.config documentation & readme enhancements

---

src/NuGetGallery/Web.config
tests/NuGetGallery.FunctionalTests/Commandline/NuGetCommandLineTests.cs
tests/Scripts/DownloadLatestNuGetExeRelease.ps1
tests/Scripts/RunEverything.cmd
tests/Scripts/RunP0Tests.bat
tests/Scripts/RunP1Tests.bat
tests/Scripts/RunP2Tests.bat
tests/Scripts/RunReadonlyModeTests.bat
tests/Scripts/TestRunSetupScript.cmd

1. Set nuget.exe to be downloaded from the correct URI
2. Added html output for xunit tests

Func tests

---

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

For issue https://github.com/NuGet/NuGetGallery/issues/3344 
I hope I did understand the issue correctly.

Add no follow rel

---

.nuget/packages.config

@skofman1 @scottbommarito @ryuyu @shishirx34 fyi

Upgrade to latest version of bin-skim utility

---

src/NuGetGallery/Areas/Admin/ViewModels/SupportRequestViewModel.cs
src/NuGetGallery/Areas/Admin/Views/SupportRequest/Index.cshtml
src/NuGetGallery/Scripts/supportrequests.js

When applicable.
@skofman1 @scottbommarito @shishirx34 @ryuyu @mishra14
Preview in test environment:

Add link to package details page on support requests view

---

tests/NuGetGallery.FunctionalTests.Core/EnvironmentSettings.cs

Until https://github.com/NuGet/NuGetGallery/issues/3516 is done.

Add certificate fingerprint (thumbprint) for new nuget.org SSL certificate

---

build.ps1

See https://github.com/NuGet/ServerCommon/pull/21

Fix $Branch overwriting in build script

---

src/NuGetGallery.Core/NuGetGallery.Core.csproj

Revert the line that broke things until I can iron the issue out in a non-breaking way 😄

Don't sign NuGetGallery.Core quite yet (NuGetDeployment is broken)

---

src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery.Core/packages.config

Also remove unnecessary dependency.

Import sign.targets only if it exists

---

src/NuGetGallery/Authentication/AuthenticationService.cs
src/NuGetGallery/Content/PageStylings.css
src/NuGetGallery/Content/Site.css
src/NuGetGallery/Controllers/UsersController.cs
src/NuGetGallery/Views/Users/ApiKeys.cshtml
tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs
tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs

There are 3 fixes in this PR (did them as one PR to avoid merge conflicts):
1. SetApiKey command should have source as part of it:
2. Copying a key provides no indication of success: added a popup that disappears after 1 second/
3. Should remove code related to 'expire api key' option

Scoped api keys - bug fixes

---

src/NuGetGallery/Views/Users/Account.cshtml
tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs

A simple fix for #3556. Added test coverage for the issue.

Fix Microsoft Account removal

---

src/NuGetGallery/Authentication/AuthenticationService.cs

This information is necessary for internal auditing.

Add credential to Register and RequestPasswordReset audits

---

tests/NuGetGallery.Core.Facts/Auditing/AuditRecordTests.cs
tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj

Add unit test for audit record types

---

tests/NuGetGallery.FunctionalTests/Statistics/PackageStatisticsTests.cs
tests/NuGetGallery.FunctionalTests/WebPages/LinksTests.cs

Fix SSL errors in functional tests when running against staging slot

---

src/NuGetGallery/Web.config

Fixes https://github.com/NuGet/NuGetGallery/issues/3713

Update default localdb connection strings in gallery web.config

---

tests/Scripts/RunTestScripts.ps1

Will configure VSTS to call this script shortly after this merges.
https://github.com/NuGet/Engineering/issues/316

Add script to run a semicolon-delimited list of functional test scripts

---

src/NuGetGallery.Core/Auditing/AuditedEntities/AuditedPackage.cs
src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery.Core/app.config
src/NuGetGallery.Core/packages.config
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Services/PackageService.cs
src/NuGetGallery/Web.config
src/NuGetGallery/packages.config
tests/NuGetGallery.Core.Facts/Auditing/AuditedPackageFacts.cs
tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj
tests/NuGetGallery.Core.Facts/Packaging/ManifestValidatorFacts.cs
tests/NuGetGallery.Core.Facts/app.config
tests/NuGetGallery.Core.Facts/packages.config
tests/NuGetGallery.Facts/App.config
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
tests/NuGetGallery.Facts/packages.config

Fix gallery audit trail does not show full version string

---

src/NuGetGallery/App_Start/AppActivator.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Telemetry/QuietExceptionLogger.cs

Fixes this: https://github.com/NuGet/NuGetGallery/issues/3825

Log all unhandled exceptions in AI and Elmah

---

src/NuGetGallery/Controllers/ApiController.cs
src/NuGetGallery/ExtensionMethods.cs
src/NuGetGallery/Services/TelemetryService.cs
tests/NuGetGallery.Facts/ExtensionMethodsFacts.cs

Per @anangaur, additional telemetry necessary to track temp key usage

Key creation telemetry

---

src/NuGetGallery.Core/Auditing/PackageAuditRecord.cs
src/NuGetGallery.Core/NuGetVersionExtensions.cs
src/NuGetGallery/Controllers/ApiController.cs
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Infrastructure/PackageIndexEntity.cs
src/NuGetGallery/OData/QueryInterceptors/NormalizeVersionInterceptor.cs
src/NuGetGallery/OData/SearchService/SearchHijacker.cs
src/NuGetGallery/OData/Serializers/V2FeedPackageAnnotationStrategy.cs
src/NuGetGallery/Services/DownloadCountObjectMaterializedInterceptor.cs
src/NuGetGallery/Services/PackageFileService.cs
src/NuGetGallery/Services/PackageService.cs
src/NuGetGallery/ViewModels/PackageViewModel.cs
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
tests/NuGetGallery.Facts/Services/PackageFileServiceFacts.cs

Only display the full version in the title.
Use NormalizedVersion anywhere else.

Show full version on package details page

---

src/NuGetGallery/ViewModels/PackageViewModel.cs
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

Client version to be confirmed.
Preview:

Highlight semver2 packages on package details view

---

src/NuGetGallery/Infrastructure/Lucene/LuceneIndexingService.cs
src/NuGetGallery/Services/PackageService.cs
tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs

Discovered this whilst testing the `feature/semver2` branch, added more unit tests to assert behavior.

Fix bug in IsLatest(Stable)SemVer2

---

src/NuGetGallery/UrlExtensions.cs
tests/NuGetGallery.Facts/UrlExtensionsFacts.cs

UrlHelper extension for Package should use NormalizedVersion

---

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

Addresses inconsistent UI behavior experienced in https://github.com/NuGet/NuGetGallery/issues/3912

Default to latest stable semver2 on package details page

---

src/NuGetGallery/Services/PackageService.cs
src/NuGetGallery/Views/Users/Profiles.cshtml
tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs

User profile page does not show SemVer 2.0.0 packages

---

src/NuGetGallery/OData/Serializers/V2FeedPackageAnnotationStrategy.cs
tests/NuGetGallery.Facts/OData/Serializers/V2FeedPackageAnnotationStrategyFacts.cs

Fix functional test failure SearchMicrosoftDotNetCuratedFeed

---

src/NuGetGallery/Services/PackageService.cs

Fix System.NotSupportedException on User profile page

---

src/NuGetGallery/OData/Serializers/V2FeedPackageAnnotationStrategy.cs
tests/NuGetGallery.Facts/OData/Serializers/V2FeedPackageAnnotationStrategyFacts.cs

Fix Functional Test failure for ODataFeeds.V2FeedExtendedTests.FindPackagesByIdTest

---

src/NuGetGallery/Migrations/201705032101231_SecurityPoliciesFix.cs

Fix SecurityPoliciesFix migration rollback

---

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

Update Semver2 package details message with final nuget client version

---

src/NuGetGallery/Controllers/PackagesController.cs
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs

Parse tags list before comparing on package validation completion

---

content/PROD/Home.html

Currently the link isn't a link, but plain text.
Defeats the purpose of html ;)

Fix link in home

---

src/NuGetGallery/App_Start/OwinStartup.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Telemetry/Telemetry.cs
src/NuGetGallery/packages.config

Update telemetry processors

---

src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs

Fixes https://github.com/NuGet/NuGetGallery/issues/4039

Average download shown incorrectly when its 1.x #4039

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/dist/css/bootstrap.css
src/Bootstrap/less/theme/base.less
src/Bootstrap/less/type.less
src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
src/NuGetGallery/Content/gallery/css/bootstrap.css
src/NuGetGallery/Controllers/PagesController.cs
src/NuGetGallery/Views/Pages/Contact.cshtml
src/NuGetGallery/Views/Shared/Gallery/Footer.cshtml

1. Add contact page.
1. Add new HTML helper for checkbox.
1. Add common heading and subheading CSS. Copied from https://github.com/NuGet/NuGetGallery/pull/4048.
Address https://github.com/NuGet/NuGetGallery/issues/4007.
/cc @microsoftsam

[Redesign] Add contact page

---

src/NuGetGallery/Queries/AutoCompleteDatabasePackageVersionsQuery.cs

Package-Versions autocomplete endpoint does not properly handle semVerLevel when using the db

---

src/NuGetGallery/Queries/AutoCompleteDatabasePackageVersionsQuery.cs

v2 package-versions auto-complete endpoint should exclude deleted versions

---

src/NuGetGallery/Scripts/stats.js

Remove auto-refresh AJAX call for total stats on home page

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/all.less
src/Bootstrap/less/theme/page-downloads.less
src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
src/NuGetGallery/Controllers/PagesController.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Scripts/gallery/page-home.js
src/NuGetGallery/Views/Pages/Downloads.cshtml

/cc @microsoftsam
Address https://github.com/nuget/nugetgallery/issues/4009.

[Redesign] Downloads page

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/base.less
src/NuGetGallery/Content/gallery/css/bootstrap-theme.css

Darken tags' font color by 5% so that Keros no longer complains.

[Redesign] Tag Contrast is too low

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/base.less
src/Bootstrap/less/theme/page-display-package.less
src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
src/NuGetGallery/Scripts/gallery/common.js
src/NuGetGallery/Scripts/gallery/page-display-package.js
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
src/NuGetGallery/Views/Shared/Gallery/Header.cshtml

1. Banner should have the alert icon
1. Transient message should not fill the width of the screen
1. Update correct icons for display package
1. Move dependencies below versions
1. Hide dependencies by default (with expander)

Update banner, transient message, and package details page

---

src/NuGetGallery/App_Code/ViewHelpers.cshtml
src/NuGetGallery/Scripts/gallery/common.js
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

Fix https://github.com/NuGet/NuGetGallery/issues/4114
Three events. When the following outbound links are clicked:
1. License URL
1. Project URL
1. Direct download

[Redesign] Add more Google Analytics events for outbound clicks

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/base.less
src/Bootstrap/less/theme/page-display-package.less
src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
src/NuGetGallery/Scripts/gallery/common.js
src/NuGetGallery/Scripts/gallery/page-display-package.js
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

Also, use plus/minus icons for expanding the version list.
https://github.com/NuGet/NuGetGallery/issues/4116

Make Dependencies and Version History headings collapsable

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/all.less
src/Bootstrap/less/theme/page-pages.less
src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
src/NuGetGallery/Views/Pages/_PagesView.cshtml

Use main-container on terms and privacy pages

---

src/NuGetGallery/Infrastructure/CookieTempDataProvider.cs
tests/NuGetGallery.Facts/Infrastructure/CookieTempDataProviderFacts.cs

Fix System.ArgumentNullException on GET packages/DisplayPackage

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/base.less
src/Bootstrap/less/theme/page-display-package.less
src/Bootstrap/less/theme/page-home.less
src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
src/NuGetGallery/Views/Pages/Home.cshtml
src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
src/NuGetGallery/Views/Shared/_ListPackage.cshtml

- https://github.com/NuGet/NuGetGallery/issues/4197 - Make install command wrap better on small screen and have a border on high contrast
- https://github.com/NuGet/NuGetGallery/issues/4195 - Give transient message on home page the right background color
- https://github.com/NuGet/NuGetGallery/issues/4178 - Hide circuit board triangles on high contrast
- https://github.com/NuGet/NuGetGallery/issues/4162 - Don't wrap package versions on package details and list page
- https://github.com/NuGet/NuGetGallery/issues/4147 - Make the hamburger icon visible on high contrast

[Redesign] Fix up some high contrast and small screen bugs

---

src/NuGetGallery/Views/Pages/Downloads.cshtml

Fix https://github.com/NuGet/NuGetGallery/issues/4171.

Move VS 2017 to the front and center

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-statistics-per-package.less
src/NuGetGallery/Scripts/gallery/common.js
src/NuGetGallery/Scripts/gallery/page-display-package.js
src/NuGetGallery/Scripts/gallery/stats-dimensions.js
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
src/NuGetGallery/Views/Statistics/_PivotTable.cshtml

Addresses https://github.com/NuGet/NuGetGallery/issues/4172
Switch to collapsing tbody instead of individual rows.
@joelverhagen @skofman1

[Redesign]Improve performance of expand/collapse large number of rows.

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/all.less
src/Bootstrap/less/theme/common-slider.less
src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
src/NuGetGallery/ExtensionMethods.cs
src/NuGetGallery/ViewModels/ReportAbuseViewModel.cs
src/NuGetGallery/Views/Packages/ReportAbuse.cshtml

100% CSS!
This is on the report abuse page (`https://localhost/packages/<id>/<version>/ReportAbuse`)
@microsoftsam

[Redesign] Toggle "slider"

---

src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Scripts/gallery/common.js
src/NuGetGallery/ViewModels/ReportAbuseViewModel.cs
src/NuGetGallery/ViewModels/ReportMyPackageViewModel.cs
src/NuGetGallery/Views/Packages/ReportAbuse.cshtml
src/NuGetGallery/Views/Packages/ReportMyPackage.cshtml
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs

Couple notes:
- Fixed some broken Javascript validation behavior by copying some code from the old common Javascript file (`nugetgallery.js`) to `common.js`
- Made some minor unifications to the `Report Abuse` page, most notably resizing to 10 columns.

[Redesign] Contact Support page

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/all.less
src/Bootstrap/less/theme/page-manage-owners.less
src/NuGetGallery/App_Code/ViewHelpers.cshtml
src/NuGetGallery/App_Start/AppActivator.cs
src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
src/NuGetGallery/Controllers/JsonApiController.cs
src/NuGetGallery/Helpers/GravatarHelper.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Scripts/gallery/page-manage-owners.js
src/NuGetGallery/UrlExtensions.cs
src/NuGetGallery/Views/Packages/ManagePackageOwners.cshtml

[Redesign] Manage Package Owners

---

src/NuGetGallery/ViewModels/DependencySetsViewModel.cs
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs

This is a quick PR to fix up some of the tests we have caused to fail with redesign work so far.
* Removes some dead tests
* Minimal fixes to existing test to get them to pass.
@joelverhagen @scottbommarito @loic-sharma

[Redesign]Some Test Fixes

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/all.less
src/Bootstrap/less/theme/page-reset-password.less
src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
src/NuGetGallery/Views/Users/PasswordChanged.cshtml
src/NuGetGallery/Views/Users/ResetPassword.cshtml

[Redesign] Reset password

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/all.less
src/Bootstrap/less/theme/page-delete-package.less
src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
src/NuGetGallery/ExtensionMethods.cs
src/NuGetGallery/RequestModels/DeletePackagesRequest.cs
src/NuGetGallery/ViewModels/PackageViewModel.cs
src/NuGetGallery/Views/Packages/Delete.cshtml

[Redesign] Unlist/Delete Package Page

---

src/NuGetGallery/Views/Packages/ConfirmOwner.cshtml

[Redesign] Confirm Package Ownership

---

src/Bootstrap/.gitignore
src/Bootstrap/package-lock.json
src/NuGetGallery/App_Start/AppActivator.cs
src/NuGetGallery/Scripts/gallery/common.js
src/NuGetGallery/Scripts/gallery/page-account.js
src/NuGetGallery/Scripts/gallery/page-api-keys.js
src/NuGetGallery/Views/Users/Account.cshtml

Also, move account JS to external file.
This PR will go in after the API keys PR (thus the base branch).

[Redesign] Share form reset logic between account and API keys page

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/dist/css/bootstrap.css
src/Bootstrap/less/buttons.less
src/Bootstrap/less/theme/base.less
src/Bootstrap/less/theme/page-home.less
src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
src/NuGetGallery/Content/gallery/css/bootstrap.css
src/NuGetGallery/Views/Users/ApiKeys.cshtml

Fix the opacity of disabled state so that contrast ratio is high enough.
Add border around home page stats on high contrast

[Redesign] Fix some contrast issues

---

src/NuGetGallery/Views/Packages/ReportAbuse.cshtml

[Redesign] Improve Wording on Report Abuse Page

---

src/NuGetGallery/Scripts/gallery/page-about.js
src/NuGetGallery/Views/CuratedFeeds/CuratedFeed.cshtml
src/NuGetGallery/Views/Pages/About.cshtml
src/NuGetGallery/Views/Statistics/PackageVersions.cshtml
src/NuGetGallery/Views/Statistics/Packages.cshtml
src/NuGetGallery/Web.config

https://github.com/NuGet/NuGetGallery/issues/4191
https://github.com/NuGet/NuGetGallery/issues/4179
https://github.com/NuGet/NuGetGallery/issues/4141
https://github.com/NuGet/NuGetGallery/issues/4135
https://github.com/NuGet/NuGetGallery/issues/4314

[Redesign] Minor bugfixes

---

src/NuGetGallery/Scripts/gallery/stats-dimensions.js
src/NuGetGallery/Scripts/gallery/stats-perpackagestatsgraphs.js
src/NuGetGallery/Views/Statistics/PackageDownloadsByVersion.cshtml
src/NuGetGallery/Views/Statistics/PackageDownloadsDetail.cshtml
src/NuGetGallery/Views/Statistics/_PivotTable.cshtml

* [Redesign] Stats Label is Truncated on OS X Chrome #4170
* [Redesign] Package Statistics / Package Version Statistics page looks odd with small window #4190
@joelverhagen @scottbommarito @loic-sharma

[Redesign] Some Miscellaneous bug fixes

---

src/NuGetGallery/Views/Packages/Delete.cshtml

Mirror of #4341, fixes #4323 on redesign.

[Redesign] Ensure package version is provided in Unlist/Delete form

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/dist/css/bootstrap.css
src/Bootstrap/less/dropdowns.less
src/Bootstrap/less/navbar.less
src/Bootstrap/less/theme/base.less
src/Bootstrap/less/variables.less
src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
src/NuGetGallery/Content/gallery/css/bootstrap.css
src/NuGetGallery/Scripts/gallery/common.js
src/NuGetGallery/UrlExtensions.cs
src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
src/NuGetGallery/Views/Users/Profiles.cshtml

[Redesign] Add Dropdown Menu

---

src/NuGetGallery/App_Start/AppActivator.cs
src/NuGetGallery/Configuration/AppConfiguration.cs
src/NuGetGallery/Configuration/IAppConfiguration.cs
src/NuGetGallery/Content/Layout.css
src/NuGetGallery/Content/fabric.css
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Views/Shared/Layout.cshtml
src/NuGetGallery/Web.config

[Redesign] Added redesign banner

---

src/NuGetGallery/Views/Shared/Gallery/Header.cshtml

[Redesign] Add Admin link to dropdown

---

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

Address https://github.com/NuGet/NuGetGallery/issues/4313.

Format description just like release notes

---

tests/NuGetGallery.FunctionalTests.Core/Constants.cs
tests/NuGetGallery.WebUITests.P0/AccountManagement/LogonTest.cs
tests/NuGetGallery.WebUITests.P0/BasicPages/NetFoundationBrandingValidationTest.cs
tests/NuGetGallery.WebUITests.P1/BasicPages/StatisticsPageTest.cs

[Redesign] Fix functional tests
- NuGetGallery.FunctionalTests.WebUITests.AccountManagement.LogonTest
- NuGetGallery.FunctionalTests.WebUITests.BasicPages.NetFoundationBrandingValidationTest
- NuGetGallery.FunctionalTests.WebUITests.BasicPages.StatisticsPageTest
Still not fixed:
- NuGetGallery.FunctionalTests.WebUITests.UploadAndDownload.UploadPackageFromUI

[Redesign] Fix functional tests

---

src/NuGetGallery/Scripts/gallery/async-file-upload.js

When we went from a regular file input to a masked file input, we lost the ability to drag and drop files to select a package.
This PR re-enables this feature through javascript.
@joelverhagen @jonwchu @scottbommarito @loic-sharma

[Redesign]Enable drag and drop file upload.

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/base.less
src/NuGetGallery/Content/gallery/css/bootstrap-theme.css

Fix https://github.com/NuGet/NuGetGallery/issues/4371

[Redesign] Increase heading line-height of dependency headings

---

src/NuGetGallery/Constants.cs
src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
src/NuGetGallery/Views/Users/Confirm.cshtml
src/NuGetGallery/Views/Users/Thanks.cshtml

* Made Confirm Email page be wider to properly accommodate long emails (this follows the Thanks for Registering page)
* Shorted the maximum email length displayed on  dropdown to ensure there isn't overflow.

[Redeisgn] Fixed display issues caused by long emails

---

src/NuGetGallery/Controllers/StatisticsController.cs

Fix https://github.com/NuGet/NuGetGallery/issues/4118

Increase cache time of stats/totals to 1 hour

---

tests/NuGetGallery.FunctionalTests.Core/Helpers/UrlHelper.cs
tests/NuGetGallery.WebUITests.P0/AssertAndValidationHelper.cs
tests/NuGetGallery.WebUITests.P0/UploadAndDownload/UploadPackageFromUI.cs

Addresses https://github.com/NuGet/NuGetGallery/issues/4364
@joelverhagen

[Redesign]Update UploadPackageFromUI test for redesign upload flow.

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/base.less
src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
src/NuGetGallery/Views/Shared/Gallery/Header.cshtml

Also, merge `dev` into `feature-redesign`.
Fix https://github.com/NuGet/NuGetGallery/issues/4387.

[Redesign] Link back to main site

---

src/NuGetGallery/Scripts/gallery/common.js
src/NuGetGallery/Scripts/gallery/page-display-package.js

Collect data for https://github.com/NuGet/NuGetGallery/issues/4422

[Redesign] Emit an event when the dependencies section is expanded or collapsed

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/base.less
src/Bootstrap/less/theme/common-list-packages.less
src/Bootstrap/less/theme/page-account-settings.less
src/Bootstrap/less/theme/page-home.less
src/Bootstrap/less/theme/page-list-packages.less
src/Bootstrap/less/theme/page-profile.less
src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
src/NuGetGallery/Controllers/StatisticsController.cs
src/NuGetGallery/ExtensionMethods.cs
src/NuGetGallery/Helpers/HtmlExtensions.cs
src/NuGetGallery/Scripts/gallery/page-home.js
src/NuGetGallery/Views/Authentication/_Register.cshtml
src/NuGetGallery/Views/Shared/Gallery/Footer.cshtml
src/NuGetGallery/Views/Shared/ListPackages.cshtml
src/NuGetGallery/Views/Shared/_ListPackage.cshtml
src/NuGetGallery/Views/Statistics/Index.cshtml
src/NuGetGallery/Views/Users/_UserPackagesList.cshtml

https://github.com/NuGet/NuGetGallery/issues/4432
https://github.com/NuGet/NuGetGallery/issues/4419
https://github.com/NuGet/NuGetGallery/issues/4440
https://github.com/NuGet/NuGetGallery/issues/4441
https://github.com/NuGet/NuGetGallery/issues/4443
Observe the bugs and each commit separately.

[Redesign] Address various points of feedback from the community

---

src/NuGetGallery/ExtensionMethods.cs
src/NuGetGallery/Scripts/gallery/common.js
src/NuGetGallery/Scripts/gallery/page-api-keys.js
src/NuGetGallery/Scripts/gallery/page-display-package.js
src/NuGetGallery/Views/Pages/Home.cshtml

#467716
#467720
#467727
Observe each individual commit.

[Redesign] Address three accessibility issues

---

src/NuGetGallery/App_Code/ViewHelpers.cshtml
src/NuGetGallery/Extensions/DateTimeExtensions.cs
src/NuGetGallery/Scripts/gallery/common.js
src/NuGetGallery/Services/TelemetryService.cs
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
src/NuGetGallery/Views/Shared/_ListPackage.cshtml
src/NuGetGallery/Views/Statistics/_LastUpdated.cshtml

Also, never show relative years -- show full dates at that point
Fix https://github.com/NuGet/NuGetGallery/issues/4280
Fix https://github.com/NuGet/NuGetGallery/issues/4424

[Redesign] Assume dates are UTC (even though their DateTimeKind is Unspecified)

---

src/NuGetGallery/Scripts/gallery/common.js

If no element has focus (or body has focus), typing will jump to search box.
As suggested in https://github.com/NuGet/NuGetGallery/issues/4458
@joelverhagen @microsoftsam

[Redesign]Autofocus search

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/base.less
src/Bootstrap/less/theme/page-report-abuse.less
src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/ViewModels/PackageHeadingModel.cs
src/NuGetGallery/Views/Packages/ContactOwners.cshtml
src/NuGetGallery/Views/Packages/Delete.cshtml
src/NuGetGallery/Views/Packages/Edit.cshtml
src/NuGetGallery/Views/Packages/ManagePackageOwners.cshtml
src/NuGetGallery/Views/Packages/ReportAbuse.cshtml
src/NuGetGallery/Views/Packages/ReportMyPackage.cshtml
src/NuGetGallery/Views/Shared/_PackageHeading.cshtml

Addresses https://github.com/NuGet/NuGetGallery/issues/4433
@joelverhagen @jonwchu 
Screenshots:

[Redesign]Make Page headings Consistent

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-display-package.less
src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

Fix issue https://github.com/NuGet/NuGetGallery/issues/4470

[Redesign] Wrap long IDs and titles on the display package page

---

src/NuGetGallery/Views/Users/Packages.cshtml
src/NuGetGallery/Views/Users/_UserPackagesList.cshtml

https://github.com/NuGet/NuGetGallery/issues/4431

[Redesign] Minor polish on the manage packages page

---

src/NuGetGallery/App_Start/DefaultDependenciesModule.cs

Fixes https://github.com/NuGet/NuGetGallery/issues/4486

CookieComplianceService initialization fix

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/base.less
src/Bootstrap/less/theme/common-list-packages.less
src/Bootstrap/less/theme/page-list-packages.less
src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
src/NuGetGallery/Controllers/CuratedFeedsController.cs
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/OData/SearchService/SearchAdaptor.cs
src/NuGetGallery/UrlExtensions.cs
src/NuGetGallery/ViewModels/PackageListSearchViewModel.cs
src/NuGetGallery/ViewModels/PackageListViewModel.cs
src/NuGetGallery/Views/Shared/ListPackages.cshtml
src/NuGetGallery/Views/Shared/_ListPackage.cshtml
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs

Fix https://github.com/NuGet/NuGetGallery/issues/4491
Fix https://github.com/NuGet/NuGetGallery/issues/4492

[Redesign] Add "include prerelease" checkbox and polish search results

---

content/DEV/Home.html
content/INT/Home.html

Finish https://github.com/NuGet/NuGetGallery/issues/4508.

DEV and INT, point to the new index.json locations

---

src/NuGetGallery/Web.config

Fix https://github.com/NuGet/NuGetGallery/issues/4515

Redirect to HTTPS when using packages.nuget.org

---

src/NuGetGallery/Helpers/HtmlExtensions.cs
src/NuGetGallery/Helpers/RegexEx.cs
src/NuGetGallery/NuGetGallery.csproj
tests/NuGetGallery.Facts/Helpers/HtmlExtensionsFacts.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj

Fix https://github.com/NuGet/NuGetGallery/issues/4492

[Redesign] Make links clickable in description and release notes.

---

src/NuGetGallery/Authentication/AuthenticationService.cs
src/NuGetGallery/Controllers/UsersController.cs
tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs
tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs

Gracefully handle unconfirmed email addresses in password reset

---

src/NuGetGallery/Authentication/AuthenticationService.cs
src/NuGetGallery/Controllers/UsersController.cs
tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs
tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs

Reverts NuGet/NuGetGallery#4556
This wasn't supposed to go this cycle, we already have a release for gallery deployed to INT.

Revert "[Release Prep][2017.08.14] RI of dev to Master"

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/base.less
src/Bootstrap/less/theme/common-list-packages.less
src/Bootstrap/less/theme/common-user-package-list.less
src/Bootstrap/less/theme/page-display-package.less
src/Bootstrap/less/theme/page-list-packages.less
src/NuGetGallery/Content/gallery/css/bootstrap-theme.css
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

Use a common `.break-word` class.
Fix https://github.com/NuGet/NuGetGallery/issues/4564.

Break long lines in the package details page

---

src/NuGetGallery/Views/Packages/Delete.cshtml

Regressed in https://github.com/NuGet/NuGetGallery/commit/257c61df1d6aff8b312af55cd7dfb891668dce88.
Fix https://github.com/NuGet/NuGetGallery/issues/4577

Enumerate the package ID and versions to be deleted as hidden fields

---

src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
src/NuGetGallery/Configuration/AppConfiguration.cs
src/NuGetGallery/Configuration/IAppConfiguration.cs
src/NuGetGallery/Web.config

No longer necessary, as we've verified the service behaves as expected.

Remove CookieComplianceEnabled flag

---

src/NuGetGallery/Controllers/StatisticsController.cs
src/NuGetGallery/Scripts/gallery/stats-dimensions.js
src/NuGetGallery/ViewModels/StatisticsPackagesReport.cs
src/NuGetGallery/ViewModels/StatisticsPivot.cs
src/NuGetGallery/Views/Statistics/_PivotTable.cshtml
tests/NuGetGallery.Facts/Controllers/StatisticsControllerFacts.cs

Addresses https://github.com/NuGet/NuGetGallery/issues/4571
@joelverhagen @jonwchu

Update Number display to clientside formatting.

---

src/NuGetGallery/App_Code/ViewHelpers.cshtml
src/NuGetGallery/ViewModels/PackageViewModel.cs
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

Package details page warning for SemVer is inconsistent with other places

---

src/NuGetGallery/Views/Users/_UserPackagesList.cshtml

Fix https://github.com/NuGet/NuGetGallery/issues/4607

Use TotalDownloadCount sum for total on user packages list instead of DownloadCount

---

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

As proposed by @loic-sharma and @anangaur in https://github.com/NuGet/NuGetGallery/pull/4638/files#r138423374

Link to new contact page for Paket

---

src/NuGetGallery/Configuration/AppConfiguration.cs
src/NuGetGallery/Configuration/IAppConfiguration.cs
src/NuGetGallery/Views/Shared/Gallery/Footer.cshtml
src/NuGetGallery/Web.config

Adds ability to configure and display a trademark Url.

---

src/NuGetGallery/Filters/ApiAuthorizeAttribute.cs

Pretty-print API key expiration time.

---

src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
src/NuGetGallery/ViewModels/PackageViewModel.cs
tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs

Fix DisplayPackageViewModel.HasNewerPrerelease

---

src/NuGetGallery/Areas/Admin/Views/SecurityPolicy/Index.cshtml

Fix sec policy undefined addAjaxAntiForgeryToken

---

src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Services/ReservedNamespaceService.cs
tests/NuGetGallery.Facts/Services/ReservedNamespaceServiceFacts.cs

Merge a bug fix for the deployment

RI Dev to Master(bug fix)

---

src/NuGetGallery.Core/Auditing/AuditedEntities/AuditedPackage.cs
src/NuGetGallery.Core/Entities/Package.cs
src/NuGetGallery.Core/SemVerLevelKey.cs
src/NuGetGallery/Areas/Admin/Controllers/DeleteController.cs
src/NuGetGallery/Controllers/ODataV1FeedController.cs
src/NuGetGallery/Controllers/ODataV2CuratedFeedController.cs
src/NuGetGallery/Controllers/ODataV2FeedController.cs
src/NuGetGallery/Infrastructure/Lucene/LuceneIndexingService.cs
src/NuGetGallery/OData/SearchService/SearchAdaptor.cs
src/NuGetGallery/Queries/AutoCompleteDatabasePackageVersionsQuery.cs
src/NuGetGallery/Services/PackageDeleteService.cs
src/NuGetGallery/Services/PackageNamingConflictValidator.cs
src/NuGetGallery/Services/PackageService.cs
src/NuGetGallery/ViewModels/PackageViewModel.cs
tests/NuGetGallery.Core.Facts/Auditing/AuditingServiceTests.cs
tests/NuGetGallery.Core.Facts/SemVerLevelKeyFacts.cs
tests/NuGetGallery.Facts/Services/FeedServiceFacts.cs
tests/NuGetGallery.Facts/Services/PackageDeleteServiceFacts.cs
tests/NuGetGallery.Facts/Services/PackageNamingConflictValidatorFacts.cs
tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
tests/NuGetGallery.Facts/TestUtils/Infrastructure/FeedServiceHelpers.cs

Address https://github.com/NuGet/NuGetGallery/issues/4645.
Depends on https://github.com/NuGet/NuGetGallery/pull/4664. I will change the base branch once that one goes in.

Use package status instead of deleted bit

---

src/NuGetGallery/Scripts/gallery/async-file-upload.js
src/NuGetGallery/Scripts/gallery/page-edit-readme.js
src/NuGetGallery/Scripts/gallery/page-edit.js
src/NuGetGallery/Views/Packages/_EditMetadata.cshtml

-Update bindData to call bindReadMeData when model is null
-Update bindReadMeData to hide form when model is null
-Remove unmatched ending form tag

Hide readme form on validation errors

---

src/NuGetGallery/Migrations/201709111714021_AddPackageStatusKey.cs

Fix https://github.com/NuGet/Engineering/issues/781
I will merge this after we get this migration to PROD.

Remove WITH (ONLINE = ON) from queries so all SQL Servers are happy

---

src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
src/NuGetGallery/Views/Packages/_EditForm.cshtml
src/NuGetGallery/Views/Packages/_ImportReadMe.cshtml

Use 'documentation' wording instead of 'readme'

---

src/NuGetGallery/Configuration/AppConfiguration.cs
src/NuGetGallery/Configuration/IAppConfiguration.cs
src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
src/NuGetGallery/Views/Shared/Layout.cshtml
src/NuGetGallery/Web.config

https://github.com/NuGet/NuGetGallery/issues/4691

Remove redesign banner

---

src/NuGetGallery/Controllers/ODataV2CuratedFeedController.cs
tests/NuGetGallery.Facts/Controllers/ODataFeedControllerFactsBase.cs
tests/NuGetGallery.Facts/Controllers/ODataV2CuratedFeedControllerFacts.cs
tests/NuGetGallery.Facts/Controllers/ODataV2FeedControllerFacts.cs

Fix https://github.com/NuGet/NuGetGallery/issues/4750. Depends on https://github.com/NuGet/NuGetGallery/pull/4677.

Filter out unavailable packages in curated feed controller

---

src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Services/IValidationService.cs
src/NuGetGallery/Services/ValidationService.cs
src/NuGetGallery/UrlExtensions.cs
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
tests/NuGetGallery.Facts/Services/ValidationServiceFacts.cs
tests/NuGetGallery.Facts/TestUtils/TestUtility.cs

Depends on https://github.com/NuGet/NuGetGallery/pull/4677. Address https://github.com/NuGet/Engineering/issues/765.

Implement "revalidate" gesture for asynchronous validation

---

src/NuGetGallery/Views/Users/ApiKeys.cshtml

Add text to API Keys page

---

src/NuGetGallery/Services/PackageUploadService.cs
tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs

Depends on https://github.com/NuGet/NuGetGallery/pull/4764. Progress on https://github.com/NuGet/NuGetGallery/issues/4646.
This writes the new .nupkg to the `validation` container if the package is starting in the `Validating` status instead of the `Available` status. No product code actually sets the `Validating` status, but eventually the `AsynchronousPackageValidationInitiator` will do it .
https://github.com/NuGet/NuGetGallery/blob/d6b55e7f15f2d7963f382d4e9719ce6ede5eed1f/src/NuGetGallery/Services/AsynchronousPackageValidationInitiator.cs#L59

Write to the validation container if the package starts in the Validating status

---

src/NuGetGallery/Areas/Admin/Controllers/DeleteController.cs
src/NuGetGallery/Areas/Admin/ViewModels/DeleteSearchResult.cs
src/NuGetGallery/Areas/Admin/ViewModels/UserViewModel.cs
src/NuGetGallery/Areas/Admin/Views/Delete/Index.cshtml
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Services/PackageDeleteService.cs
src/NuGetGallery/UrlExtensions.cs
src/NuGetGallery/Web.config
tests/NuGetGallery.Facts/Areas/Admin/Controllers/DeleteControllerFacts.cs
tests/NuGetGallery.Facts/Areas/Admin/Controllers/ReservedNamespaceControllerFacts.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
tests/NuGetGallery.Facts/Services/PackageDeleteServiceFacts.cs

... and some little polishes that are low hanging fruit.
Address https://github.com/NuGet/NuGetGallery/issues/3856, https://github.com/NuGet/NuGetGallery/issues/4230, https://github.com/NuGet/NuGetGallery/issues/4648, and https://github.com/NuGet/NuGetGallery/issues/4683.
Many results:
No results:

Backup package in validation package container during delete flow (and other little fixes)

---

src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Services/ITelemetryService.cs
src/NuGetGallery/Services/TelemetryService.cs
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

see: https://github.com/NuGet/Engineering/issues/827

Package documentation telemetry

---

src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/OData/QueryAllowed/ODataQueryVerifier.cs
src/NuGetGallery/Services/ITelemetryService.cs
src/NuGetGallery/Services/TelemetryService.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
tests/NuGetGallery.Facts/Services/TelemetryServiceFacts.cs

Fix for: https://github.com/NuGet/Engineering/issues/809

Log user safe exceptions

---

src/NuGetGallery/Views/Users/_UserPackagesList.cshtml

Latest Version on Manage Packages does not show SemVer 2.0.0 packages

---

src/NuGetGallery/UrlExtensions.cs
src/NuGetGallery/Views/Authentication/_Register.cshtml
src/NuGetGallery/Views/Shared/Gallery/Footer.cshtml

Updates the Terms of Use and Privacy Policy links on register page to use the links provided by the customization.
@joelverhagen @skofman1 @karann-msft

Update links to docs on register page to use new configuration

---

src/NuGetGallery/Helpers/HtmlExtensions.cs
src/NuGetGallery/Services/ReadMeService.cs
tests/NuGetGallery.Facts/Helpers/HtmlExtensionsFacts.cs

This PR adds rel="nofollow" attribute to text that contains links that we format into anchor tags.
Addresses https://github.com/NuGet/NuGetGallery/issues/4839
@joelverhagen @skofman1 @xavierdecoster

Add nofollow to links

---

tests/NuGetGallery.Facts/Services/ReadMeServiceFacts.cs

Fix readme test that broke with nofollow change.

---

src/NuGetGallery/Web.config

There was an issue with this allowing large package pushes from CLI.
Change the default value to be more restrictive.
@skofman1 @shishirx34 @joelverhagen

Change maxRequestLength to 250MB

---

src/NuGetGallery/Services/PackageDeleteService.cs

https://github.com/NuGet/NuGetGallery/issues/4807

Hard delete of package should delete package owner requests

---

src/NuGetGallery.Core/Auditing/AuditedAuthenticatedOperationAction.cs
src/NuGetGallery/Authentication/AuthenticationService.cs
src/NuGetGallery/ExtensionMethods.cs
src/NuGetGallery/Extensions/UserExtensions.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
tests/NuGetGallery.Core.Facts/Auditing/AuditedAuthenticatedOperationActionTests.cs
tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs
tests/NuGetGallery.Facts/Framework/Fakes.cs

Issue #4871 , Depends on PR #4904
Adds checks to AuthenticationService to prevent authentication and credential creation for Organization accounts.

Gallery constraints to prevent Organization authentication

---

src/NuGetGallery/Extensions/PrincipalExtensions.cs
tests/NuGetGallery.Facts/Extensions/PrincipalExtensionsFacts.cs

This was a regression from #4945

Hotfix for legacy api keys

---

src/NuGetGallery/Views/NuGetViewBase.cs
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
src/NuGetGallery/Web.config
tests/NuGetGallery.FunctionalTests/PackageCreation/SecurityPolicyTests.cs

There's a functional test that was fixed in dev. Would like to merge to avoid cherry picking. Please review your changes.

Merge dev to master

---

tests/NuGetGallery.FunctionalTests.Core/Helpers/UrlHelper.cs

Broken by my previous change for logon flow change.

Fix web UI test for signin flow

---

src/NuGetGallery/Views/Packages/ReportMyPackage.cshtml

Addresses issue introduced by fix for https://github.com/NuGet/NuGetGallery/issues/4716
@skofman1 @joelverhagen

Remove extra copyright text from owner support request page.

---

src/NuGetGallery/Configuration/AppConfiguration.cs
src/NuGetGallery/Web.config

The impact here is that validation DB admin panel is broken.
There will be a subsequent .cscfg PR.

Add the required prefix to the validation DB connection string

---

src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Scripts/gallery/async-file-upload.js

Accidentally merged into master, welp

Revert "Show VerifyPackage errors correctly in UI (#5029)" from master

---

tests/NuGetGallery.FunctionalTests.Core/Helpers/ClientSdkHelper.cs
tests/NuGetGallery.FunctionalTests.Core/NuGetGallery.FunctionalTests.Core.csproj
tests/NuGetGallery.FunctionalTests.Core/packages.config
tests/NuGetGallery.FunctionalTests.Fluent/NuGetFluentTest.cs
tests/NuGetGallery.FunctionalTests/Commandline/NuGetCommandLineTests.cs
tests/NuGetGallery.FunctionalTests/Commandline/PackageVersionTest.cs
tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedExtendedTests.cs
tests/NuGetGallery.FunctionalTests/PackageCreation/ApiPushTests.cs
tests/NuGetGallery.WebUITests.P0/UploadAndDownload/UploadPackageFromUI.cs

Addresses https://github.com/NuGet/Engineering/issues/946.

Fix functional tests that started failing when async validation was turned on 

---

tests/NuGetGallery.Facts/Controllers/JsonApiControllerFacts.cs

Near the end of the PR, I changed some "!" to "." but did not update the related tests.

Fix broken JsonApiControllerFacts

---

tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
tests/NuGetGallery.Facts/Framework/Fakes.cs
tests/NuGetGallery.Facts/Services/DeleteAccountServiceFacts.cs
tests/NuGetGallery.Facts/ViewModels/DeleteAccountViewModelFacts.cs

Caused by conflict between these commits:
- https://github.com/NuGet/NuGetGallery/commit/2df96487c3e97e1120b82715627ea73cc68363d1
- https://github.com/NuGet/NuGetGallery/commit/651bd24b471335ed89c6917de07960cfcf128e96

Unit test fixes

---

src/NuGetGallery/Services/PackageUploadService.cs
tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs

Addresses https://github.com/NuGet/NuGetGallery/issues/5039.

Handle race condition caused by fast asynchronous validation

---

tests/NuGetGallery.Facts/Controllers/StatisticsControllerFacts.cs

Fixes: https://github.com/NuGet/NuGetGallery/issues/5061

Fix StatisticsControllerFacts failures

---

src/NuGetGallery/Infrastructure/Authentication/ApiKeyV4.cs
src/NuGetGallery/Infrastructure/Authentication/Base32Encoder.cs
src/NuGetGallery/Infrastructure/Authentication/V3Hasher.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Web.config
tests/NuGetGallery.Facts/App.config
tests/NuGetGallery.Facts/Infrastructure/Authentication/ApiKeyV4Facts.cs
tests/NuGetGallery.Facts/Infrastructure/Authentication/Base32EncoderTests.cs
tests/NuGetGallery.Facts/Infrastructure/Authentication/V3HasherTests.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj

This PR introduces ApiKeyV4 implementation without integrating it into the exiting scenarios. This will be done in a future PR. 
/cc @blowdart

ApiKeyV4 implementation

---

src/NuGetGallery/Web.config

Temporary increase to 350MB, based on earlier change here:
https://github.com/NuGet/NuGetGallery/pull/4848
Issue: https://github.com/NuGet/Engineering/issues/984

Temporary package size workaround

---

src/NuGetGallery/Infrastructure/Authentication/ApiKeyV4.cs
src/NuGetGallery/Infrastructure/Authentication/Base32Encoder.cs
src/NuGetGallery/Infrastructure/Authentication/V3Hasher.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Web.config
tests/NuGetGallery.Facts/App.config
tests/NuGetGallery.Facts/Infrastructure/Authentication/ApiKeyV4Facts.cs
tests/NuGetGallery.Facts/Infrastructure/Authentication/Base32EncoderTests.cs
tests/NuGetGallery.Facts/Infrastructure/Authentication/V3HasherTests.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj

Please note the earlier RI attempt and rollback:
- https://github.com/NuGet/NuGetGallery/pull/5068
- https://github.com/NuGet/NuGetGallery/pull/5076
- https://github.com/NuGet/NuGetGallery/pull/5078
Initial PR was closed as we investigated issue with FI/RI and CI checks. Rollback was necessary due to need for a hotfix in the current PROD deployment which hadn't completed.
GitHub diff only shows the 2 commits since the original RI (rolled back). I will verify on merge that the rollback was really undone.

[ReleasePrep][2017.12.04] RI dev to master (redo)

---

src/NuGetGallery/Areas/Admin/Services/ISupportRequestService.cs
src/NuGetGallery/Areas/Admin/Services/SupportRequestService.cs
src/NuGetGallery/Controllers/UsersController.cs
src/NuGetGallery/Services/DeleteAccountService.cs
tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
tests/NuGetGallery.Facts/Services/DeleteAccountServiceFacts.cs
tests/NuGetGallery.Facts/Services/SupportRequestServiceFacts.cs

Clean support requests on account delete action.

Clean support requests

---

src/NuGetGallery/Controllers/ApiController.cs
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Services/IMessageService.cs
src/NuGetGallery/Services/MessageService.cs
tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
tests/NuGetGallery.Facts/Services/MessageServiceFacts.cs

Replaced calls to SendPackageAddedNotice with SendPackageUploadedNotice.
Added tests for the new method.

Added SendPackageUploadedNotice method to MessageService.

---

src/NuGetGallery/Controllers/ApiController.cs
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Services/IMessageService.cs
src/NuGetGallery/Services/MessageService.cs
tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
tests/NuGetGallery.Facts/Services/MessageServiceFacts.cs

Same as #5100, but against master branch

Cherry-picking email message fix to master

---

tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj
tests/NuGetGallery.Core.Facts/packages.config
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
tests/NuGetGallery.Facts/packages.config

This should fix the VS feedback issue reported here:
https://developercommunity.visualstudio.com/content/problem/157928/test-explorer-trying-to-debug-one-test-but-debugs.html

Update Xunit version

---

tests/NuGetGallery.Core.Facts/PackageStatusFacts.cs

Fix https://github.com/NuGet/NuGetGallery/issues/5122

Mark PackageStatusFacts facts as [Fact] and improve testing

---

src/NuGetGallery/Scripts/gallery/page-manage-packages.js

Fix ManagePackages icon fallback

---

tests/NuGetGallery.Facts/Controllers/JsonApiControllerFacts.cs
tests/NuGetGallery.Facts/Framework/Fakes.cs

(logged out means current user is null)

Add logged out tests for Manage Package Owners

---

src/NuGetGallery/Telemetry/Obfuscator.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
tests/NuGetGallery.Facts/Telemetry/ObfuscatorFacts.cs

Address one comment missed in previous PR.

Make ObfuscatedAction collection case insensitive

---

src/NuGetGallery/Areas/Admin/Controllers/SupportRequestController.cs
tests/NuGetGallery.Facts/Controllers/SupportControllerFacts.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj

Do not pull in the Support page the support requests for the deleted accounts.

Fix issue 5140

---

src/NuGetGallery/Controllers/ApiController.cs
src/NuGetGallery/Controllers/PackagesController.cs
tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs

Conditional on no blocking async validation.
Related to https://github.com/NuGet/NuGetGallery/issues/4659 and https://github.com/NuGet/Engineering/issues/998 - Gallery side update.

Reverting back to "package published" email

---

src/NuGetGallery/Scripts/gallery/common.js

Improved data-val filtering

---

src/NuGetGallery/Services/ReadMeService.cs
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
tests/NuGetGallery.Facts/Services/ReadMeServiceFacts.cs

Fix for: https://github.com/NuGet/NuGetGallery/issues/5184

Hide Documentation when it's empty

---

src/NuGetGallery/Views/Users/Packages.cshtml

Switch to Json.NET serializer which has no max length limit and better perf

---

src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/RequestModels/EditPackageRequest.cs
src/NuGetGallery/ViewModels/DeletePackageViewModel.cs
src/NuGetGallery/Views/Packages/Delete.cshtml
src/NuGetGallery/Views/Packages/Edit.cshtml
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs

Message example from list/unlist:

Lock UI upload/edit/unlist

---

src/NuGetGallery.Core/Auditing/AuditActor.cs

Issue #5209 - estimated to improve api push by 18.5%

Cache AuditActor.GetLocalIpAddressAsync

---

src/NuGetGallery/Views/Authentication/SignIn.cshtml

Note: using right now to test organization migration confirmation workflow

Pass returnUrl for NuGet sign in

---

src/NuGetGallery/Areas/Admin/Controllers/LockPackageController.cs
src/NuGetGallery/Areas/Admin/Helpers.cs
src/NuGetGallery/Areas/Admin/Services/ValidationAdminService.cs
src/NuGetGallery/Areas/Admin/ViewModels/LockPackageViewModel.cs
src/NuGetGallery/Areas/Admin/Views/Home/Index.cshtml
src/NuGetGallery/Areas/Admin/Views/LockPackage/Index.cshtml
src/NuGetGallery/NuGetGallery.csproj
tests/NuGetGallery.Facts/Areas/Admin/Controllers/LockPackageControllerFacts.cs
tests/NuGetGallery.Facts/Areas/Admin/HelperFacts.cs
tests/NuGetGallery.Facts/Areas/Admin/Services/ValidationAdminServiceFacts.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj

Screenshot: 
Yes, it's ugly on purpose 😆

Admin UI for package locking

---

src/NuGetGallery/Scripts/gallery/async-file-upload.js
src/NuGetGallery/Views/Packages/_VerifyForm.cshtml
src/NuGetGallery/Views/Packages/_VerifyMetadata.cshtml

Fixes https://github.com/NuGet/NuGetGallery/issues/5234

Fix expander for verify-metadata section package upload page

---

src/NuGetGallery/Web.config

Reverts changes made in https://github.com/NuGet/NuGetGallery/pull/5080
Addresses https://github.com/NuGet/Engineering/issues/985
@xavierdecoster @skofman1 @chenriksson

Reduce package size limit back to 250MB

---

src/NuGetGallery/Controllers/ApiController.cs
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/RequestModels/VerifyPackageRequest.cs
src/NuGetGallery/Services/IPackageService.cs
src/NuGetGallery/Services/IPackageUploadService.cs
src/NuGetGallery/Services/PackageService.cs
src/NuGetGallery/Services/PackageUploadService.cs
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
src/NuGetGallery/Views/Packages/_VerifyMetadata.cshtml
tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs

This PR allows organization members to upload on behalf of their organizations using the UI.
(had some git issues--same as https://github.com/NuGet/NuGetGallery/pull/5192)

[Organizations] Fixes and unit tests for UI upload for organizations

---

src/NuGetGallery/App_Code/ViewHelpers.cshtml
src/NuGetGallery/Scripts/gallery/page-account.js
src/NuGetGallery/Scripts/gallery/page-manage-packages.js
src/NuGetGallery/Views/NuGetViewBase.cs
src/NuGetGallery/Views/Users/Account.cshtml
src/NuGetGallery/Views/Users/ApiKeys.cshtml
src/NuGetGallery/Views/Users/Packages.cshtml

Refactoring in preparation for adding new page with sections (Edit Organization).
Opened #5270 to finish the refactoring.

Refactor section helpers into common ViewHelpers

---

src/NuGetGallery/Authentication/Providers/AzureActiveDirectory/AzureActiveDirectoryAuthenticator.cs

This was broken due to my refactor work for AADv2 login support. I have tested this locally with AAD and it looks good. Will deploy these changes on DEV and test.

[AAD]Fix admin logins issue.

---

tests/NuGetGallery.FunctionalTests.Core/EnvironmentSettings.cs
tests/NuGetGallery.FunctionalTests.Fluent/AccountManagement/ContactEmailTest.cs
tests/NuGetGallery.FunctionalTests.Fluent/AccountManagement/LogonTest.cs
tests/NuGetGallery.FunctionalTests.Fluent/AccountManagement/MailHelper.cs
tests/NuGetGallery.FunctionalTests.Fluent/AccountManagement/ResendConfirmationTest.cs
tests/NuGetGallery.FunctionalTests.Fluent/BasicPages/CSExtensionTest.cs
tests/NuGetGallery.FunctionalTests.Fluent/BasicPages/LicenseReportUITest.cs
tests/NuGetGallery.FunctionalTests.Fluent/EditableMetadata/EditAndSearchTest.cs
tests/NuGetGallery.FunctionalTests.Fluent/EditableMetadata/EditPackageAsPartOfUploadTest.cs
tests/NuGetGallery.FunctionalTests.Fluent/EditableMetadata/EditPackageTest.cs
tests/NuGetGallery.FunctionalTests.Fluent/ExtensionMethods.cs
tests/NuGetGallery.FunctionalTests.Fluent/PackageManagement/PackageManagementTest.cs
tests/NuGetGallery.FunctionalTests.Fluent/UploadAndDownload/1826RegressionTest.cs
tests/NuGetGallery.WebUITests.P0/AssertAndValidationHelper.cs
tests/NuGetGallery.WebUITests.P0/UploadAndDownload/UploadPackageFromUI.cs

Fix functional test: UploadPackageFromUI

FixUploadPackageFromUI

---

src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
src/NuGetGallery/Controllers/ApiController.cs
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Services/PackageService.cs
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs

Fixes to:
https://github.com/NuGet/NuGetGallery/issues/5314
https://github.com/NuGet/NuGetGallery/issues/5316
https://github.com/NuGet/NuGetGallery/issues/5323
https://github.com/NuGet/NuGetGallery/issues/5324
https://github.com/NuGet/NuGetGallery/issues/5325
https://github.com/NuGet/NuGetGallery/issues/5334

[Organizations] Fix bugs with upload scenarios

---

src/NuGetGallery/Services/PackageService.cs
tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs

See [this comment](https://github.com/NuGet/NuGetGallery/issues/4782#issuecomment-359814380)

Rewrite functionality that gets latest package versions for package owners

---

src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Services/ValidationService.cs
src/NuGetGallery/Views/Packages/_ValidationIssue.cshtml
src/NuGetGallery/packages.config
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
tests/NuGetGallery.Facts/Services/ValidationServiceFacts.cs
tests/NuGetGallery.Facts/Views/Packages/ValidationIssueFacts.cs
tests/NuGetGallery.Facts/packages.config

Progress on https://github.com/NuGet/Engineering/issues/785 and https://github.com/NuGet/Engineering/issues/1047.
The look n' feel of the message is exactly like the existing issues:
https://github.com/NuGet/NuGetGallery/pull/5271#issuecomment-357089131

Add messages for new validation issue codes

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/dist/js/bootstrap.js
src/Bootstrap/less/theme/page-api-keys.less
src/NuGetGallery/Scripts/gallery/page-api-keys.js
src/NuGetGallery/Views/Users/ApiKeys.cshtml

Fixes the following issues:
- #5170: JS exception from ApiKeys page (edit)
- #5320: pointless nested container
- #5322: horizontal rule is ugly
- #5313: partial validation
- #5315: Edit doesn't show org packages
Screenshot of no nested container, partial validation gone:
Screenshot of removed bottom border at end:

Fix ApiKeys page issues from bug bash

---

src/NuGetGallery/ViewModels/UserProfileModel.cs
src/NuGetGallery/Views/Users/Profiles.cshtml

Hide DeleteUser link for organizations

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-forgot-password.less
src/Bootstrap/less/theme/page-sign-in.less
src/NuGetGallery/App_Code/ViewHelpers.cshtml
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
src/NuGetGallery/Views/Authentication/Register.cshtml
src/NuGetGallery/Views/Authentication/SignInNugetAccount.cshtml
src/NuGetGallery/Views/Users/ForgotPassword.cshtml

Add deprecate warning on the forgot password page, also update the forgot password email with the warning message.

[MSA/AAD] Deprecate password warnings

---

src/NuGetGallery/App_Start/AppActivator.cs
src/NuGetGallery/Controllers/OrganizationsController.cs
src/NuGetGallery/Helpers/RouteUrlTemplate.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Scripts/gallery/page-manage-organization.js
src/NuGetGallery/Services/IUserService.cs
src/NuGetGallery/Services/UserService.cs
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
src/NuGetGallery/UrlExtensions.cs
src/NuGetGallery/ViewModels/OrganizationMemberViewModel.cs
src/NuGetGallery/Views/Organizations/ManageOrganization.cshtml
src/NuGetGallery/Views/Organizations/_OrganizationAccountManageMembers.cshtml
src/NuGetGallery/Views/Users/Organizations.cshtml
tests/NuGetGallery.Facts/Controllers/OrganizationsControllerFacts.cs
tests/NuGetGallery.Facts/Framework/Fakes.cs
tests/NuGetGallery.Facts/Services/UserServiceFacts.cs

Issue #4990 
- Adds Members section on Manage Organization view
- Can add, remove, or edit (toggle admin/collaborator)
Screenshot (UPDATED per demo feedback):
see screen capture here: \\\\sollentuna\Public\5383_AddRemoveMembers

Add/remove members UI

---

src/NuGetGallery/App_Code/ViewHelpers.cshtml
src/NuGetGallery/Views/Authentication/LinkExternal.cshtml

Nit fixes for strings. Fixes #5389

String fixes, address feedback from demo

---

src/NuGetGallery/Authentication/AuthenticationService.cs
tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs

Remove copy api key option for non-scoped api keys

---

src/NuGetGallery/Scripts/gallery/page-manage-organization.js
src/NuGetGallery/Views/Organizations/ManageOrganization.cshtml
src/NuGetGallery/Views/Organizations/_OrganizationAccountManageMembers.cshtml
src/NuGetGallery/Views/Shared/_AccountChangeEmail.cshtml
src/NuGetGallery/Views/Shared/_AccountChangeNotifications.cshtml
src/NuGetGallery/Views/Shared/_AccountCuratedFeeds.cshtml
src/NuGetGallery/Views/Shared/_AccountProfilePicture.cshtml
src/NuGetGallery/Views/Users/Account.cshtml
src/NuGetGallery/Views/Users/Organizations.cshtml
src/NuGetGallery/Views/Users/Transform.cshtml
src/NuGetGallery/Views/Users/_UserAccountChangeExternalCredential.cshtml
src/NuGetGallery/Views/Users/_UserAccountChangePassword.cshtml
src/NuGetGallery/Views/Users/_UserAccountLinkExternalCredential.cshtml

Fixes the following issues:
- #5379 : Cancel buttons on Manage Organization page
- #5379 : Account drop-down on Manage Organizations page
- Expander icons for Account, Manage Organization pages (regression from partials)
- Breadcrumb fix, per @anangaur

UI fixes for AAD+Organizations bug bash

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/modals.less
src/NuGetGallery/Authentication/AuthenticationService.cs
src/NuGetGallery/Authentication/Providers/AzureActiveDirectory/AzureActiveDirectoryAuthenticator.cs
src/NuGetGallery/Authentication/Providers/MicrosoftAccount/MicrosoftAccountAuthenticator.cs
src/NuGetGallery/Authentication/Providers/Utils/ClaimsExtentions.cs
src/NuGetGallery/Controllers/AuthenticationController.cs
src/NuGetGallery/Controllers/PagesController.cs
src/NuGetGallery/Controllers/UsersController.cs
src/NuGetGallery/Extensions/ClaimsExtensions.cs
src/NuGetGallery/Extensions/CredentialExtensions.cs
src/NuGetGallery/Extensions/UserExtensions.cs
src/NuGetGallery/Filters/UiAuthorizeAttribute.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Scripts/gallery/page-home.js
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
src/NuGetGallery/UrlExtensions.cs
src/NuGetGallery/ViewModels/GalleryHomeViewModel.cs
src/NuGetGallery/Views/Pages/Home.cshtml
src/NuGetGallery/Views/Pages/_TransformOrLink.cshtml
tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs
tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs

This PR addresses #5387 and #5412 
- Allows popup dialog dismissal.
- Shows the transform popup dialog for whitelisted accounts.
- Refactored code for reusability with signing/linking MSA/AAD accounts.
I will add tests as I go along.

[Org/AAD] Transform Dialog integration for certain accounts

---

src/GalleryTools/App.config
src/GalleryTools/Commands/HashCommand.cs
src/GalleryTools/Commands/ReflowCommand.cs
src/GalleryTools/GalleryTools.csproj
src/GalleryTools/Program.cs
src/GalleryTools/packages.config
src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
src/NuGetGallery/Configuration/AppConfiguration.cs
src/NuGetGallery/Configuration/IAppConfiguration.cs

Progress on https://github.com/NuGet/Engineering/issues/1094.
Also, refactor the `hash` tool to use DI, app.config, and KeyVault.

Add tool to bulk reflow packages

---

src/NuGetGallery/Scripts/gallery/page-api-keys.js
src/NuGetGallery/Views/Organizations/_OrganizationAccountManageMembers.cshtml
src/NuGetGallery/Views/Packages/_ImportReadMe.cshtml
src/NuGetGallery/Views/Packages/_VerifyForm.cshtml
src/NuGetGallery/Views/Pages/Home.cshtml
src/NuGetGallery/Views/Shared/_AccountChangeNotifications.cshtml
src/NuGetGallery/Views/Shared/_SearchBar.cshtml
src/NuGetGallery/Views/Users/ApiKeys.cshtml
src/NuGetGallery/Views/Users/Packages.cshtml
src/NuGetGallery/Views/Users/_OwnerRequestsList.cshtml
src/NuGetGallery/Views/Users/_ReservedNamespacesList.cshtml
src/NuGetGallery/Views/Users/_UserPackagesList.cshtml
src/NuGetGallery/Views/Users/_UserPackagesListForDeletedAccount.cshtml

Accessibility fixes from organizations, documentation and other work... based on testing with the Keros chrome extension.

Accessibility fixes

---

src/NuGetGallery/Services/TelemetryService.cs
src/NuGetGallery/Telemetry/ClientInformationTelemetryEnricher.cs
tests/NuGetGallery.Facts/Telemetry/ClientInformationTelemetryEnricherTests.cs

Validating a hypothesis around customer browsing behavior.

Add IsAuthenticated property to RequestsTelemetry

---

src/NuGetGallery.Core/CoreConstants.cs
src/NuGetGallery.Core/Entities/User.cs
src/NuGetGallery/Constants.cs
src/NuGetGallery/Controllers/AuthenticationController.cs
src/NuGetGallery/Extensions/PrincipalExtensions.cs
src/NuGetGallery/Extensions/UserExtensions.cs
src/NuGetGallery/Helpers/PermissionsHelpers.cs
src/NuGetGallery/Migrations/MigrationsConfiguration.cs
src/NuGetGallery/Services/PackageOwnershipManagementService.cs
src/NuGetGallery/ViewModels/ManagePackageOwnersViewModel.cs
src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
src/NuGetGallery/Views/Shared/SiteMenu.cshtml
tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
tests/NuGetGallery.Facts/Controllers/SupportControllerFacts.cs
tests/NuGetGallery.Facts/Framework/Fakes.cs
tests/NuGetGallery.Facts/PolicyFacts.cs
tests/NuGetGallery.Facts/Services/PackageOwnershipManagementServiceFacts.cs
tests/NuGetGallery.Facts/Services/PermissionsHelpersFacts.cs
tests/NuGetGallery.Facts/TestUtils/TestUtility.cs

Issue #5461 - addresses issue 1 (11.9% incl from isAdmin checks, which increased with permissions helpers)
Server response went from 39.4s to 37.8s.

Cache IsAdmin check

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/modals.less
src/NuGetGallery/Constants.cs
src/NuGetGallery/Views/Pages/_TransformOrLink.cshtml

Addresses fixes for #5447 
The text has been changed as per @anangaur's request. New changes:

[BugBash] UI fixes for Link/Transform dialog

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/all.less
src/Bootstrap/less/theme/page-manage-organizations.less
src/NuGetGallery/Views/Organizations/ManageOrganization.cshtml
src/NuGetGallery/Views/Organizations/_OrganizationAccountManageMembers.cshtml

Fixes bug bash issues:
- #5458: Can click 'Add' member when no input
- #5460: Manage Org / Members list has big blank areas and unnecessary lines
Screenshot:
Before (for comparison):

Manage Org UI fixes

---

src/NuGetGallery/Scripts/gallery/autocomplete.js

Doing a minimal disable of autocomplete.

Minimal disable of autocomplete.

---

src/NuGetGallery/Controllers/AccountsController.cs
src/NuGetGallery/Controllers/OrganizationsController.cs
src/NuGetGallery/Controllers/UsersController.cs
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
tests/NuGetGallery.Facts/Controllers/AccountsControllerFacts.cs

https://github.com/NuGet/NuGetGallery/issues/5456
New:
Old:

[BugBash] Remove redundant message when changing email

---

src/NuGetGallery/NuGetGallery.csproj

Fixes NuGetDeployment build. Verifying with [VSTS build #25146](https://nuget.visualstudio.com/NuGetBuild/_build/index?buildId=25146&_a=summary)

Remove Content include of clientaccesspolicy.xml

---

src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs
tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj
tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceIntegrationTests.cs
tests/NuGetGallery.Core.Facts/TestUtils/BlobStorageCollection.cs
tests/NuGetGallery.Core.Facts/TestUtils/BlobStorageFact.cs
tests/NuGetGallery.Core.Facts/TestUtils/BlobStorageFixture.cs

Progress on https://github.com/NuGet/Engineering/issues/1190.

 Add integration tests for Azure Blob Storage testing CopyFileAsync

---

tests/NuGetGallery.Core.Facts/Auditing/FileSystemAuditingServiceTests.cs
tests/NuGetGallery.Core.Facts/Auditing/ObfuscatorJsonConverterTests.cs

Fix culture assumptions in tests

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-manage-organizations.less
src/NuGetGallery/Scripts/gallery/page-manage-organization.js
src/NuGetGallery/Views/Organizations/_OrganizationAccountManageMembers.cshtml

https://github.com/NuGet/NuGetGallery/issues/5630
Adding collaborator:
Adding admin:
Error:

[Organizations] Add UI to explain admin vs. collaborator

---

src/NuGetGallery/Constants.cs
src/NuGetGallery/ViewModels/AddOrganizationViewModel.cs
src/NuGetGallery/ViewModels/ChangeEmailViewModel.cs
src/NuGetGallery/ViewModels/LogOnViewModel.cs

https://github.com/NuGet/NuGetGallery/issues/5693
Reusing the regex from `RegisterViewModel`.

[Organizations] Fix username validation for Add Organization

---

src/NuGetGallery/Services/LoginDiscontinuationConfiguration.cs
tests/NuGetGallery.Facts/Services/LoginDiscontinuationConfigurationFacts.cs

https://github.com/NuGet/NuGetGallery/issues/5686

Login Discontinuation Configuration should be case-insensitive

---

src/NuGetGallery/PackageCurators/WebMatrixPackageCurator.cs
tests/NuGetGallery.Facts/PackageCurators/WebMatrixPackageCuratorFacts.cs

Issue #5049 - optimize upload submit by not querying `CuratedFeedService.GetFeedByName` unless necessary. Profile showed 46% inclusive in submit due to this query.
Scenario: upload of package that won't be curated
- Before: 11.52s, 10.61s, 12.71s => 11.61s
- After: 2.74s, 2.36s, 2.31s => 2.47s (-78.73%)

Perf: optimize VerifyPackage by not querying WM feed unless necessary

---

src/NuGetGallery/Views/Users/Account.cshtml

Remove feedback from the account page.

Remove feedback from the account page.

---

src/NuGet.Services.Search.Client/Client/RetryingHttpClientWrapper.cs
src/NuGet.Services.Search.Client/Client/ThreadSafeRandom.cs
src/NuGet.Services.Search.Client/NuGet.Services.Search.Client.csproj
tests/NuGetGallery.Facts/SearchClient/RetryingHttpClientWrapperFacts.cs

Fix for the infinite loop due to bad comparer. 
With this change add the equality in the comparer and add a thread safe random.

Fix for the infinite loop due to bad comparer

---

src/NuGetGallery/Scripts/gallery/page-manage-organization.js
src/NuGetGallery/Views/Organizations/_OrganizationAccountManageMembers.cshtml

Fixes to a couple tab-related accessibility issues I found.

[Organizations] Small accessibility fixes

---

src/NuGetGallery/Views/Users/Account.cshtml

https://github.com/NuGet/NuGetGallery/issues/5724

Account settings page header improvements

---

src/NuGetGallery/Authentication/ApiScopeEvaluationResult.cs
src/NuGetGallery/Controllers/ApiController.cs
src/NuGetGallery/Controllers/AppController.cs
src/NuGetGallery/Controllers/OrganizationsController.cs
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Controllers/StatisticsController.cs
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
tests/NuGetGallery.Facts/Authentication/ApiScopeEvaluationResultFacts.cs
tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
tests/NuGetGallery.Facts/Controllers/AppControllerFacts.cs
tests/NuGetGallery.Facts/Controllers/OrganizationsControllerFacts.cs

https://github.com/NuGet/NuGetGallery/issues/5712

[Organizations] Restrict unconfirmed organizations from pushing and changing membership

---

src/NuGetGallery.Core/Packaging/PackageMetadata.cs
tests/NuGetGallery.Core.Facts/Packaging/PackageMetadataFacts.cs

The validation I added missed the following bad cases:
```xml
<listed />
<requireLicenseAcceptance />
```

Reject empty values for restricted and boolean metadata

---

src/NuGetGallery/Controllers/OrganizationsController.cs
src/NuGetGallery/Scripts/gallery/page-add-organization.js
src/NuGetGallery/Views/Organizations/Add.cshtml
tests/NuGetGallery.Facts/Controllers/OrganizationsControllerFacts.cs

https://github.com/NuGet/NuGetGallery/issues/5725
(work to fix the breadcrumb at the top will be done in a separate PR with other breadcrumb work)

[Organizations] Add new organization page improvements

---

src/NuGetGallery/Scripts/gallery/page-manage-organization.js
src/NuGetGallery/Views/Organizations/ManageOrganization.cshtml

https://github.com/NuGet/NuGetGallery/issues/5730:
https://github.com/NuGet/NuGetGallery/issues/5736

[Organizations] Edit organization UI fixes

---

src/NuGetGallery/Views/Users/TransformToOrganizationFailed.cshtml

https://github.com/NuGet/NuGetGallery/issues/5740
I didn't add an error icon to the title because it's inconsistent with the rest of our error pages.

[Organizations] Transform error UI fixes

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-manage-packages.less
src/Bootstrap/less/theme/page-transform-account.less
src/NuGetGallery/ExtensionMethods.cs
src/NuGetGallery/Views/Users/Organizations.cshtml
src/NuGetGallery/Views/Users/TransformToOrganization.cshtml

https://github.com/NuGet/NuGetGallery/issues/5691
Also some small UI fixes to the transform page
Manage organizations page:
Transform page:

[Organizations] Link empty Manage Organizations page to the Transform flow

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/base.less
src/NuGetGallery/App_Code/ViewHelpers.cshtml
src/NuGetGallery/Areas/Admin/Views/DeleteAccount/DeleteUserAccount.cshtml
src/NuGetGallery/Services/ActionsRequiringPermissions.cs
src/NuGetGallery/ViewModels/ListPackageItemViewModel.cs
src/NuGetGallery/ViewModels/PackageHeadingModel.cs
src/NuGetGallery/Views/Organizations/Add.cshtml
src/NuGetGallery/Views/Organizations/ManageOrganization.cshtml
src/NuGetGallery/Views/Packages/ContactOwners.cshtml
src/NuGetGallery/Views/Packages/Delete.cshtml
src/NuGetGallery/Views/Packages/Edit.cshtml
src/NuGetGallery/Views/Packages/ManagePackageOwners.cshtml
src/NuGetGallery/Views/Packages/ReportAbuse.cshtml
src/NuGetGallery/Views/Packages/ReportMyPackage.cshtml
src/NuGetGallery/Views/Packages/UploadPackage.cshtml
src/NuGetGallery/Views/Shared/_PackageHeading.cshtml
src/NuGetGallery/Views/Users/Account.cshtml
src/NuGetGallery/Views/Users/ApiKeys.cshtml
src/NuGetGallery/Views/Users/DeleteAccount.cshtml
src/NuGetGallery/Views/Users/Organizations.cshtml
src/NuGetGallery/Views/Users/Packages.cshtml
src/NuGetGallery/Views/Users/TransformToOrganization.cshtml

Too many to show--here's a subset:

Improve breadcrumbs across site

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-profile.less
src/NuGetGallery/Views/Users/Profiles.cshtml

https://github.com/NuGet/NuGetGallery/issues/5737
1 - Improved the breadcrumb to the manage organizations / edit organization page
2 - Added edit link
User:
Organization:

Improve profile page UI

---

src/NuGetGallery/Controllers/AccountsController.cs
src/NuGetGallery/Controllers/OrganizationsController.cs
src/NuGetGallery/Controllers/UsersController.cs
src/NuGetGallery/Extensions/OrganizationExtensions.cs
src/NuGetGallery/Extensions/UserExtensions.cs
src/NuGetGallery/Services/ITelemetryService.cs
src/NuGetGallery/Services/TelemetryService.cs
tests/NuGetGallery.Facts/Controllers/OrganizationsControllerFacts.cs
tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
tests/NuGetGallery.Facts/Services/TelemetryServiceFacts.cs

https://github.com/NuGet/NuGetGallery/issues/5711
Also added message service validation to Transform unit tests.

[Organizations] Telemetry for organizations

---

src/NuGetGallery/Services/LoginDiscontinuationConfiguration.cs
src/NuGetGallery/Services/UserService.cs
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
tests/NuGetGallery.Facts/Services/ContentObjectServiceFacts.cs
tests/NuGetGallery.Facts/Services/LoginDiscontinuationConfigurationFacts.cs
tests/NuGetGallery.Facts/Services/UserServiceFacts.cs

https://github.com/NuGet/NuGetGallery/issues/5769
also made some improvements to the unit testing

[Organizations] Add feature flag

---

tests/NuGetGallery.FunctionalTests/Commandline/NuGetCommandLineTests.cs
tests/NuGetGallery.WebUITests.P0/UploadAndDownload/UploadPackageToOrganizationAsCollaboratorFromUI.cs

https://github.com/NuGet/NuGetGallery/issues/5781

[Organizations] Functional tests should verify that collaborators can push new IDs

---

src/NuGetGallery/Controllers/UsersController.cs
src/NuGetGallery/Services/IActionRequiringEntityPermissions.cs
tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs

Unfortunately missed this bug when fixing https://github.com/NuGet/NuGetGallery/issues/5731

[Organizations] Allow collaborators to create API keys scoped to an organization with the ability to push new IDs

---

src/NuGetGallery/Web.config

Correct a typo in CSP header value.

[Hotfix]Correct a typo in the CSP header.

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-manage-organizations.less
src/Bootstrap/less/theme/page-manage-packages.less
src/NuGetGallery/Views/Organizations/Add.cshtml
src/NuGetGallery/Views/Organizations/_OrganizationAccountManageMembers.cshtml
src/NuGetGallery/Views/Users/Organizations.cshtml

https://github.com/NuGet/NuGetGallery/issues/5783
**Manage Organizations:**
with organizations
without organizations
**Edit Organization:**
**Add Organization:**
without validation erros
with validation errors

[Organizations] More UI fixes

---

src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/packages.config

SDL: remove old, unused dependency flagged by automation that has no license

Remove unused dependency

---

src/NuGetGallery/Services/LoginDiscontinuationConfiguration.cs
src/NuGetGallery/Services/UserService.cs
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
tests/NuGetGallery.Facts/Services/ContentObjectServiceFacts.cs
tests/NuGetGallery.Facts/Services/LoginDiscontinuationConfigurationFacts.cs
tests/NuGetGallery.Facts/Services/UserServiceFacts.cs

We don't need it anymore now that orgs has gone GA!

Remove organizations feature flag

---

src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/RequestModels/EditPackageRequest.cs
src/NuGetGallery/ViewModels/PackageHeadingModel.cs
src/NuGetGallery/Views/Packages/Edit.cshtml

https://github.com/NuGet/Engineering/issues/1389

Package Edit page throws on Locked Packages

---

src/NuGetGallery/Controllers/AccountsController.cs
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Controllers/UsersController.cs
src/NuGetGallery/ViewModels/AccountViewModel.cs
src/NuGetGallery/ViewModels/ListPackageItemRequiredSignerViewModel.cs
src/NuGetGallery/ViewModels/ManagePackagesViewModel.cs
src/NuGetGallery/Views/Shared/_AccountCertificates.cshtml
src/NuGetGallery/Views/Users/Packages.cshtml
tests/NuGetGallery.Facts/Controllers/OrganizationsControllerFacts.cs
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
tests/NuGetGallery.Facts/ViewModels/ListPackageItemRequiredSignerViewModelFacts.cs

Resolve https://github.com/NuGet/NuGetGallery/issues/5775

Certificates:  add 2FA requirement for signing

---

src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Controllers/UsersController.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Scripts/gallery/page-manage-packages.js
src/NuGetGallery/Services/PackageService.cs
src/NuGetGallery/ViewModels/ManagePackagesViewModel.cs
src/NuGetGallery/Views/Packages/_ValidationIssue.cshtml
src/NuGetGallery/Views/Shared/_AccountCertificates.cshtml
src/NuGetGallery/Views/Users/Packages.cshtml
src/NuGetGallery/packages.config
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
tests/NuGetGallery.Facts/Services/ReflowPackageServiceFacts.cs
tests/NuGetGallery.Facts/TestUtils/TestServiceUtility.cs
tests/NuGetGallery.Facts/Views/Packages/ValidationIssueFacts.cs
tests/NuGetGallery.Facts/packages.config

Resolve https://github.com/NuGet/NuGetGallery/issues/5873.

Certificates:  fix bug bash bugs

---

src/NuGetGallery/Services/PackageUploadService.cs
tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs

Fix a regression from https://github.com/NuGet/NuGetGallery/pull/5833.

Fix HTTP 500 on storage conflict

---

tests/NuGetGallery.Facts/SearchClient/RetryingHttpClientWrapperFacts.cs

FI Master to Dev through local branch.

Gallery FI master to dev

---

src/NuGetGallery.Core/Auditing/CloudAuditingService.cs
tests/NuGetGallery.Core.Facts/Auditing/CloudAuditingServiceTests.cs

Resolve https://github.com/NuGet/NuGetGallery/issues/5925.

Cloud auditing: stop persisting package audit records for non-deletion events

---

src/NuGetGallery.Core/CoreConstants.cs
src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs
tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceFacts.cs

Resolve https://github.com/NuGet/NuGetGallery/issues/5927.

Certificates:  fix exception setting content type for certificate

---

src/NuGetGallery/Views/Organizations/ManageOrganization.cshtml

https://github.com/NuGet/NuGetGallery/issues/5878
https://github.com/NuGet/NuGetGallery/issues/5866

UI fixes for Manage Organization

---

src/NuGetGallery/Infrastructure/Lucene/ExternalSearchService.cs
tests/NuGetGallery.Facts/Infrastructure/Lucene/ExternalSearchServiceFacts.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj

Update external search to set semVer2 isLatest props

---

src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs
src/NuGetGallery.Core/Services/CloudBlobWrapper.cs
src/NuGetGallery.Core/Services/ICoreFileStorageService.cs
src/NuGetGallery.Core/Services/ISimpleCloudBlob.cs
src/NuGetGallery/Services/FileSystemFileStorageService.cs
tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceFacts.cs
tests/NuGetGallery.Facts/Services/FileSystemFileStorageServiceFacts.cs

Resolve https://github.com/NuGet/NuGetGallery/issues/6000.

Storage:  enable setting blob metadata

---

src/NuGetGallery/App_Code/ViewHelpers.cshtml
src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
src/NuGetGallery/Configuration/AppConfiguration.cs
src/NuGetGallery/Configuration/ConfigurationService.cs
src/NuGetGallery/Configuration/IAppConfiguration.cs
src/NuGetGallery/Content/Site.css
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Filters/ValidateRecaptchaResponse.cs
src/NuGetGallery/Filters/ValidateRecaptchaResponseAttribute.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
src/NuGetGallery/Views/Packages/ContactOwners.cshtml
src/NuGetGallery/Views/Packages/ReportAbuse.cshtml
src/NuGetGallery/Views/Packages/ReportMyPackage.cshtml
src/NuGetGallery/Web.config
src/NuGetGallery/packages.config

Replacing old, unmaintained PoliteCaptcha reference with invisible recaptcha v2.
This is required for moving to PackageRefs. I'm prioritizing the move to PackageRefs as part of the SQL AAD work, since I need to touch all dependencies as a result of retargeting projects.

Replace PoliteCaptcha

---

src/Bootstrap/less/theme/page-manage-packages.less
src/NuGetGallery/Views/Users/Organizations.cshtml
src/NuGetGallery/Views/Users/Packages.cshtml

Add a "Add new (upload)" link to the Manage Packages view breadcrumb navigation

---

src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs

Fix confusing "There is a newer prerelease version of this package available"

---

src/NuGetGallery/Extensions/NumberExtensions.cs
src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
tests/NuGetGallery.Facts/Extensions/NumberExtensionsFacts.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj

Addresses #5471
Preview Screenshot:
If there's a better icon let me know.

Show package size in Gallery UI Package Page

---

src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
src/NuGetGallery/ViewModels/PackageViewModel.cs

Fixes https://github.com/NuGet/Engineering/issues/1453

Fix DisplayPackage perf regression

---

src/NuGetGallery/Helpers/HtmlExtensions.cs
tests/NuGetGallery.Facts/Helpers/HtmlExtensionsFacts.cs

Package summary with URL in quotes is parsed incorrectly

---

src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
src/NuGetGallery/NuGetGallery.csproj

Depends on #6011 and https://github.com/NuGet/ServerCommon/pull/160

Update validation db to support AAD authentication

---

src/NuGetGallery/Views/Shared/_AccountCertificates.cshtml

Resolve https://github.com/NuGet/NuGetGallery/issues/6036.
<br /><br />
User account settings:
Organization account settings:

Certificates:  disallow certificate management if email unconfirmed

---

src/NuGetGallery/Controllers/AuthenticationController.cs
tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs

Fix Null ref on Signin assistance

---

src/NuGetGallery/Services/SqlAggregateStatsService.cs

Fixes https://github.com/NuGet/NuGetGallery/issues/6026

Add missing statistics data when using SQL storage (#6026)

---

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

Package view table is not properly aligned after version deleted

---

src/NuGetGallery/Controllers/UsersController.cs

Fixes #5375
Note: [assumption](https://github.com/NuGet/NuGetGallery/issues/5375#issuecomment-397386972)

Package that failed validation is visible under "Published Packages" heading

---

src/NuGetGallery/Services/PackageService.cs
src/NuGetGallery/Views/Packages/Delete.cshtml
tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs

Don't show "list/unlist" options for packages that failed validation

---

src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs

Progress on https://github.com/NuGet/Engineering/issues/1482.

Add logging if blob does not exist before calling FetchAttributesAsync()

---

src/NuGetGallery/Controllers/UsersController.cs
tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs

Failed Validation packages should not be shown in the account page

---

src/NuGetGallery/Views/Shared/_AccountCertificates.cshtml

Banner to let users know where to manage certificate for an org, on the account settings page

---

src/NuGetGallery/Filters/ValidateRecaptchaResponseAttribute.cs

https://github.com/NuGet/Engineering/issues/1480

Fail ReCaptcha when no response

---

src/NuGetGallery/Controllers/PagesController.cs
tests/NuGetGallery.Facts/Controllers/ControllerTests.cs
tools/Update-Databases.ps1

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/640117
Example FxCop results: https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=34347&view=logs
Part of https://github.com/NuGet/Engineering/issues/1345

Make acceptable verbs explicit on PagesController

---

src/NuGetGallery.Core/Diagnostics/IDiagnosticsSource.cs
src/NuGetGallery.Core/Diagnostics/NullDiagnosticsSource.cs
src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
src/NuGetGallery/Diagnostics/DiagnosticsService.cs
src/NuGetGallery/Diagnostics/TraceDiagnosticsSource.cs
src/NuGetGallery/Diagnostics/TraceDiagnosticsSourceScope.cs
src/NuGetGallery/NuGetGallery.csproj

Along with the following PRs, would update Gallery to use SQL AAD authentication... will update to master build before merge. DEV only for now.
- https://github.com/NuGet/ServerCommon/pull/172
- [NuGetDeployment#516](https://nuget.visualstudio.com/NuGetMicrosoft/_git/NuGetDeployment/pullrequest/516?_a=overview)
Planning DEV deployment today to verify changes before merging.

Update to latest NuGet.Services.Sql

---

tests/NuGetGallery.FunctionalTests/NuGetGallery.FunctionalTests.csproj
tests/NuGetGallery.FunctionalTests/PackageCreation/ApiPushTests.cs
tests/NuGetGallery.FunctionalTests/packages.config

This assertion is wrong now given repository signing.

Assert package ID and version instead of file size

---

src/NuGetGallery/Views/Shared/Gallery/Header.cshtml

Part of https://github.com/NuGet/Engineering/issues/1512

[WebScout] Use HTTPS for blog navigation link

---

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

Use (short) version string in package version history

---

src/NuGetGallery/Controllers/PackagesController.cs
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs

Screenshot of metadata validation failure upon verifying the uploaded package.

Added package compliance policy checks when uploading through NuGet.org UI

---

src/NuGetGallery/Services/ActionsRequiringPermissions.cs
tests/NuGetGallery.Facts/Controllers/OrganizationsControllerFacts.cs

This reverts commit fdeb46a59871a68fae5ffe458f46a9a60712b0c4.
This is related to https://github.com/NuGet/NuGetGallery/issues/6071

Revert "Admin should have permissions to manage certificates for an org (#6274)"

---

src/NuGetGallery/Infrastructure/HttpStatusCodeWithBodyResult.cs
tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
tests/NuGetGallery.Facts/Infrastructure/HttpStatusCodeWithBodyResultFacts.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj

Address https://github.com/NuGet/NuGetGallery/issues/6279.

Collapse multi-line reason phrases in HttpStatusCodeWithBodyResult

---

src/NuGetGallery/Views/NuGetViewBase.cs
src/NuGetGallery/Views/Shared/Gallery/Layout.cshtml

https://github.com/NuGet/Engineering/issues/1606

Add ViewBase field to hide opensearch.xml link

---

src/NuGetGallery/Scripts/gallery/async-file-upload.js

Addresses https://github.com/NuGet/NuGetGallery/issues/6085

Make the upload progress bar resilient to slow uploads

---

build.ps1

https://github.com/NuGet/NuGetGallery/issues/6334

Set-StrictMode in build script

---

build.ps1
src/NuGet.Services.Search.Client/NuGet.Services.Search.Client.csproj
src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Properties/AssemblyInfo.cs
tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj

Progress on https://github.com/NuGet/Engineering/issues/1577
Like this https://github.com/NuGet/NuGet.Services.Metadata/pull/345 but for gallery instead of search.

Add MicroBuild dependency and signing of output DLLs

---

src/NuGetGallery/Configuration/AppConfiguration.cs
src/NuGetGallery/Configuration/IAppConfiguration.cs
src/NuGetGallery/Services/PackageUploadService.cs
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
src/NuGetGallery/Web.config
tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs
tests/NuGetGallery.Facts/TestPackage.cs
tests/NuGetGallery.Facts/TestUtils/TestServiceUtility.cs

Progress on https://github.com/NuGet/NuGetGallery/issues/6357.

Gallery:  enable blocking packages with too many package entries

---

src/NuGetGallery/Areas/Admin/Services/RevalidationAdminService.cs

Fixes https://github.com/NuGet/NuGetGallery/issues/6362
Depends on https://github.com/NuGet/ServerCommon/pull/190

[Revalidation] Fix incorrect pending revalidation count

---

src/NuGetGallery/Controllers/ApiController.cs
src/NuGetGallery/Services/ITelemetryService.cs
src/NuGetGallery/Services/TelemetryService.cs
tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
tests/NuGetGallery.Facts/Services/TelemetryServiceFacts.cs

Add 3 telemetry metrics for symbol push flow.
TrackSymbolPackagePushEvent
TrackSymbolPackagePushFailureEvent
TrackSymbolPackageFailedGalleryValidationEvent

Telemetry metrics for symbol push.

---

src/NuGetGallery/App_Data/Files/Content/Typosquatting-Configuration.json
src/NuGetGallery/App_Start/OwinStartup.cs
src/NuGetGallery/Constants.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Services/ContentObjectService.cs
src/NuGetGallery/Services/IContentObjectService.cs
src/NuGetGallery/Services/ITyposquattingConfiguration.cs
src/NuGetGallery/Services/TyposquattingCheckService.cs
src/NuGetGallery/Services/TyposquattingConfiguration.cs
tests/NuGetGallery.Facts/Services/TyposquattingCheckServiceFacts.cs

Finish the typo-squatting configuration file and feature flags. 
Fix: https://github.com/NuGet/Engineering/issues/1596

Typosquatting: finish configuration file and feature flags

---

src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Services/IValidationService.cs
src/NuGetGallery/Services/ValidationService.cs
src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
src/NuGetGallery/Views/Packages/_ValidationIssue.cshtml
src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
tests/NuGetGallery.Facts/Services/ValidationServiceFacts.cs
tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs
tests/NuGetGallery.Facts/Views/Packages/ValidationIssueFacts.cs

This PR adds the support to see the validation status of uploaded symbols. 
Pending validation:
Failed Validations:

[NuGet Symbol Server]Symbols validation status view

---

src/NuGetGallery/App_Start/Routes.cs
src/NuGetGallery/Extensions/RouteExtensions.cs
src/NuGetGallery/Telemetry/ClientTelemetryPIIProcessor.cs
src/NuGetGallery/Telemetry/Obfuscator.cs
tests/NuGetGallery.Facts/Extensions/RouteExtensionsFacts.cs
tests/NuGetGallery.Facts/Telemetry/ClientTelemetryPIIProcessorTests.cs

Obfuscate secret tokens in logging

---

src/NuGetGallery.Core/Infrastructure/TableErrorLog.cs

More cleanup of Elmah

---

src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery/NuGetGallery.csproj

Updating references to strongnamed packages to NuGet.* namespaced copies.

update strongname package references.

---

src/NuGetGallery.Core/Services/CoreMessageService.cs
src/NuGetGallery.Core/Services/ICoreMessageService.cs
tests/NuGetGallery.Facts/Services/MessageServiceFacts.cs

Add the Send email for symbol apis.

Add the Send email for symbol apis.

---

src/NuGetGallery/Security/RequirePackageMetadataCompliancePolicy.cs
tests/NuGetGallery.Facts/Security/RequirePackageMetadataCompliancePolicyFacts.cs

Non compliant package didn't fail validation

---

src/NuGetGallery/Services/ITelemetryService.cs
src/NuGetGallery/Services/TelemetryService.cs
src/NuGetGallery/Services/TyposquattingService.cs
tests/NuGetGallery.Facts/Services/TelemetryServiceFacts.cs
tests/NuGetGallery.Facts/Services/TyposquattingServiceFacts.cs

Finish the log metrics for typo-squatting.
Fix: https://github.com/NuGet/Engineering/issues/1537

Typo-squatting: Log metrics

---

src/NuGetGallery/Views/Packages/Edit.cshtml
src/NuGetGallery/Views/Packages/UploadPackage.cshtml
src/NuGetGallery/Views/Packages/_EditForm.cshtml
src/NuGetGallery/Views/Packages/_VerifyForm.cshtml

https://github.com/NuGet/NuGetGallery/issues/6405
Corrects an issue with some expanders having incorrect default aria-expanded values.

Fix default expanders

---

build.ps1

Tracking: https://github.com/NuGet/Engineering/issues/822

FxCop tools update

---

src/NuGetGallery/Areas/Admin/DynamicData/Content/Images/web.config
src/NuGetGallery/Areas/Admin/DynamicData/web.config
src/NuGetGallery/Areas/Admin/Views/Web.config
src/NuGetGallery/Branding/Views/web.config
src/NuGetGallery/Views/web.config
src/NuGetGallery/Web.config
src/NuGetGallery/api/Web.config

1. Set enableVersionHeader to 'false' everywhere - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/704083
2. Avoid enabling debug attribute in <compilation> element - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/704127

Fix TSA issues

---

src/NuGetGallery.Core/Infrastructure/mail/CoreMarkdownMessageService.cs
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Infrastructure/Mail/BackgroundMarkdownMessageService.cs
src/NuGetGallery/Infrastructure/Mail/Messages/ContactOwnersMessage.cs
tests/NuGetGallery.Facts/Infrastructure/Mail/Messages/ContactOwnersMessageFacts.cs
tests/NuGetGallery.Facts/Services/MessageServiceFacts.cs

https://github.com/NuGet/Engineering/issues/1825

Hotfix: Do not CC sender for Contact Owners emails

---

build.ps1

Tracking: https://github.com/NuGet/Engineering/issues/1757

Integrate with FxCop exclusions

---

src/NuGet.Services.Search.Client/NuGet.Services.Search.Client.csproj
src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Infrastructure/Mail/BackgroundMarkdownMessageService.cs
src/NuGetGallery/Infrastructure/Mail/Messages/ContactOwnersMessage.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Views/Users/Thanks.cshtml
tests/NuGetGallery.Facts/Infrastructure/Mail/Messages/ContactOwnersMessageFacts.cs
tests/NuGetGallery.Facts/Services/MessageServiceFacts.cs

This brings the hotfix from last week to dev.
Note: see commit `c6e3c47` for some changes that had to be made to pull in the updated server common packages.

Hotfixes (do not CC sender for contact owners) to dev

---

src/NuGetGallery/Services/SymbolPackageUploadService.cs
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
tests/NuGetGallery.Facts/Services/SymbolPackageUploadServiceFacts.cs

[Symbol server]Address UI fixes and fix re-upload on failed validation issues for Symbol Server

---

src/NuGetGallery/Helpers/UriExtensions.cs
tests/NuGetGallery.Facts/Helpers/HtmlExtensionsFacts.cs
tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs

fixes https://github.com/NuGet/NuGetGallery/issues/6606

Http to https translation for GitHub pages urls

---

src/NuGetGallery/Web.config

This reverts commit 64f5a36609de9efb53cb6aaea079169af43fc159.
Address https://github.com/NuGet/NuGetGallery/issues/6655.

Revert "Redirect HTTP 400 to a specific error page instead of default or 500"

---

src/NuGetGallery/NuGetGallery.csproj

Tracking: https://github.com/NuGet/Engineering/issues/1880
Note that last reference was removed by @scottbommarito  here: https://github.com/NuGet/NuGetGallery/commit/b1ba68e5d4a17d8c87b7686fbc6acd85f38185aa#diff-8110fe0d3615d286a6788c2f19f51e54

Remove FontAwesome dependency

---

tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs

This is a follow-up PR to #6680. 
Introducing a test that verifies proper response to `PreviewReadMe` request.
Tests will fail unless hotfix from master branch is merged.

Tests for PackagesController.PreviewReadMe to produce proper JSON responses

---

src/NuGetGallery/Services/ReadMeService.cs
tests/NuGetGallery.Facts/Services/ReadMeServiceFacts.cs

Fixes: https://github.com/NuGet/NuGetGallery/issues/6681

Transform HTTP to HTTPS for known domains in readme.md

---

src/NuGetGallery/Security/MicrosoftTeamSubscription.cs
tests/NuGetGallery.Facts/Security/MicrosoftTeamSubscriptionFacts.cs

Additional copyright values for auto-add MSFT feature

---

src/NuGetGallery/Security/MicrosoftTeamSubscription.cs
src/NuGetGallery/Security/RequirePackageMetadataCompliancePolicy.cs
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
tests/NuGetGallery.Facts/Security/MicrosoftTeamSubscriptionFacts.cs
tests/NuGetGallery.Facts/Security/RequirePackageMetadataCompliancePolicyFacts.cs

Fixes NuGet/Engineering#1955, NuGet/Engineering#1954

RequirePackageMetadataCompliancePolicy: allow exceptions for authors

---

src/NuGetGallery/Security/SecurityPolicyService.cs
tests/NuGetGallery.Facts/Areas/Admin/Controllers/SecurityPolicyControllerFacts.cs

SecurityPolicyService.IsSubscribed should ignore state

---

src/NuGetGallery/Services/PackageService.cs
src/NuGetGallery/Services/ReservedNamespaceService.cs
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
tests/NuGetGallery.Core.Facts/TestUtils/PackageServiceUtility.cs
tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
tests/NuGetGallery.Facts/Services/ReservedNamespaceServiceFacts.cs
tests/NuGetGallery.Facts/Services/SymbolPackageServiceFacts.cs

Addresses https://github.com/NuGet/NuGetGallery/issues/6647 and https://github.com/NuGet/Engineering/issues/1983. Also, added tests.

Fix bug with namespace reservation and snupkg push with older clients

---

tests/NuGetGallery.FunctionalTests.Core/Helpers/NuspecHelper.cs
tests/NuGetGallery.FunctionalTests.Core/Helpers/PackageCreationHelper.cs
tests/NuGetGallery.FunctionalTests.Core/NuGetGallery.FunctionalTests.Core.csproj
tests/NuGetGallery.FunctionalTests/License/LicenseTests.cs
tests/NuGetGallery.FunctionalTests/NuGetGallery.FunctionalTests.csproj
tests/NuGetGallery.FunctionalTests/TyposquattingCheck/TyposquattingCheckForUploadPackageTests.cs

Add the functional tests for license expression/file. 
Fix: https://github.com/NuGet/NuGetGallery/issues/6534

Functional tests for license expression/file and reasoning phrase. 

---

src/NuGetGallery.Core/Services/CloudBlobContainerWrapper.cs
src/NuGetGallery.Core/Services/ICloudBlobContainer.cs

Progress on https://github.com/nuget/nugetgallery/issues/6766

Add DeleteIfExistsAsync and CreateAsync container APIs

---

src/NuGetGallery/Services/UserService.cs
tests/NuGetGallery.Facts/TestUtils/TestServiceUtility.cs

Need to do this because of https://github.com/NuGet/Engineering/issues/2109

Use IDiagnosticsSource for automatic RequireOrganizationTenantPolicy logs

---

src/NuGetGallery.Core/Features/FeatureFlagFileStorageService.cs
src/NuGetGallery.Core/Features/IEditableFeatureFlagStorageService.cs
src/NuGetGallery/Services/DeleteAccountService.cs
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
tests/NuGetGallery.Core.Facts/Features/FeatureFlagFileStorageServiceFacts.cs
tests/NuGetGallery.Facts/Services/DeleteAccountServiceFacts.cs

Part of https://github.com/NuGet/NuGetGallery/issues/6787
Build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2407655

[Feature Flags] On account deletion, remove user from flights

---

src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery/Areas/Admin/Controllers/FeaturesController.cs
src/NuGetGallery/Areas/Admin/ViewModels/FeatureFlagsViewModel.cs
src/NuGetGallery/Areas/Admin/Views/Features/Index.cshtml
src/NuGetGallery/Extensions/DateTimeExtensions.cs
src/NuGetGallery/NuGetGallery.csproj

Does the following improvements to the feature flags admin panel:
* Adds more debugging information
* Refreshes the gallery's feature flags immediately after saving the flags
Depends on https://github.com/NuGet/ServerCommon/pull/275
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2429570
https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=261286

[Feature Flags] Admin panel improvements

---

src/NuGetGallery/Infrastructure/Lucene/ExternalSearchService.cs
src/NuGetGallery/Queries/AutocompleteServicePackageIdsQuery.cs
src/NuGetGallery/Queries/AutocompleteServicePackageVersionsQuery.cs
src/NuGetGallery/Queries/AutocompleteServiceQuery.cs
src/NuGetGallery/Services/FeatureFlagService.cs
src/NuGetGallery/Services/IFeatureFlagService.cs
tests/NuGetGallery.Facts/AutocompleteServicePackageIdsQueryFacts.cs
tests/NuGetGallery.Facts/AutocompleteServicePackageVersionsQueryFacts.cs
tests/NuGetGallery.Facts/AutocompleteServiceQueryFacts.cs
tests/NuGetGallery.Facts/Infrastructure/Lucene/ExternalSearchServiceFacts.cs

Add the circuit breaker search behind the feature flag.

Add the feature flag for the GallerySearch

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-manage-deprecation.less
src/NuGetGallery/ActionName.cs
src/NuGetGallery/Controllers/ManageDeprecationJsonApiController.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Scripts/gallery/common-multi-select-dropdown.js
src/NuGetGallery/Scripts/gallery/common.js
src/NuGetGallery/Scripts/gallery/page-manage-deprecation.js
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
src/NuGetGallery/UrlHelperExtensions.cs
src/NuGetGallery/ViewModels/ManagePackageViewModel.cs
src/NuGetGallery/Views/Packages/Manage.cshtml
src/NuGetGallery/Views/Packages/_ManageDeprecation.cshtml

Integrate Deprecate form with CVE/CWE autocomplete

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-display-package.less
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Scripts/gallery/page-display-package.js
src/NuGetGallery/Services/IPackageDeprecationService.cs
src/NuGetGallery/Services/PackageDeprecationService.cs
src/NuGetGallery/ViewModels/DeletePackageViewModel.cs
src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
src/NuGetGallery/ViewModels/ManagePackageViewModel.cs
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
src/NuGetGallery/Views/Packages/_DisplayPackageDeprecation.cshtml
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
tests/NuGetGallery.Facts/Framework/MemberDataHelper.cs
tests/NuGetGallery.Facts/Services/PackageDeprecationServiceFacts.cs
tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs

https://github.com/NuGet/NuGetGallery/issues/6774

Show deprecation information for current package on the Display Package page

---

src/NuGetGallery/Services/SymbolPackageService.cs
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
tests/NuGetGallery.Facts/Services/SymbolPackageServiceFacts.cs

Snupkgs without symbols will be rejected.

Snupkgs without symbols will be rejected.

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/common-multi-select-dropdown.less
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Scripts/gallery/common.js
src/NuGetGallery/Scripts/gallery/page-manage-deprecation.js
src/NuGetGallery/ViewModels/ContactOwnersViewModel.cs
src/NuGetGallery/Views/Packages/ContactOwners.cshtml
src/NuGetGallery/Views/Packages/Manage.cshtml
src/NuGetGallery/Views/Packages/_DisplayPackageDeprecation.cshtml
src/NuGetGallery/Views/Packages/_ManageDeprecation.cshtml
src/NuGetGallery/Views/Packages/_ManageDocumentation.cshtml
src/NuGetGallery/Views/Packages/_ManageListing.cshtml
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs

Need to include #6994 in deployment because Manage page is broken without one of its fixes.

[2019.03.13] FI NuGetGallery DEV into MASTER

---

.nuget/packages.config
build.ps1

Progress on https://github.com/NuGet/Engineering/issues/2244

Sign the NuGet packages produced by the build

---

src/Bootstrap/dist/css/bootstrap.css
src/Bootstrap/package-lock.json
src/Bootstrap/package.json

Resulting minimized CSS and JS unchanged.
Also ran `npm audit fix`.

Upgrade devDependencies for Bootstrap

---

src/NuGetGallery.Core/Features/FeatureFlagClientExtensions.cs
src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery/NuGetGallery.csproj
tests/NuGetGallery.Core.Facts/Features/FeatureFlagClientExtensionsFacts.cs

See: https://github.com/NuGet/NuGetGallery/issues/7019

[Feature Flags] Handle anonymous users

---

src/NuGetGallery/Migrations/201811291758016_RemoveCuratedFeedEntities.cs

Progress on https://github.com/NuGet/Engineering/issues/2353

Fix curated feed delete script

---

src/NuGetGallery/App_Start/DefaultDependenciesModule.cs

Same PR as https://github.com/NuGet/NuGetGallery/pull/7043 but directly on master.

Reduce the Search related telemetry.

---

src/NuGetGallery/Web.config
tests/NuGetGallery.FunctionalTests/ErrorHandling/ErrorHandlingTests.cs

Fix for: https://github.com/NuGet/NuGetGallery/issues/6601

400 errors shouln't show 500 page

---

src/NuGetGallery/Controllers/PackagesController.cs
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs

Resolving the hack from https://github.com/NuGet/NuGetGallery/pull/7020 that was required until https://github.com/NuGet/NuGetGallery/pull/7021

Pass anonymous users to FeatureFlagService in Manage

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-display-package.less
src/NuGetGallery/ViewModels/PackageManagerViewModel.cs
src/NuGetGallery/ViewModels/ThirdPartyPackageManagerViewModel.cs
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

Just a suggestion :wink:
This will allow you to easily copy `PackageReference` tags directly from the gallery and paste them into the project file 😄 
Closes #5670

Add tab for PackageReference

---

src/Bootstrap/package-lock.json
src/Bootstrap/package.json

fixes https://github.com/nuget/engineering/issues/2386

Upgrade grunt devDependency from 1.0.3 to 1.0.4

---

src/NuGetGallery.Core/Auditing/AuditedEntities/AuditedFeatureFlagFeature.cs
src/NuGetGallery.Core/Auditing/AuditedEntities/AuditedFeatureFlagFlight.cs
src/NuGetGallery.Core/Auditing/AuditedFeatureFlagsAction.cs
src/NuGetGallery.Core/Auditing/FeatureFlagsAuditRecord.cs
src/NuGetGallery.Core/Features/FeatureFlagFileStorageService.cs
src/NuGetGallery.Core/NuGetGallery.Core.csproj
tests/NuGetGallery.Core.Facts/Auditing/AuditRecordTests.cs
tests/NuGetGallery.Core.Facts/Features/FeatureFlagFileStorageServiceFacts.cs

Gallery side portion of https://github.com/nuget/engineering/issues/2333

Add auditing to feature flags

---

src/NuGetGallery/Controllers/ManageDeprecationJsonApiController.cs
src/NuGetGallery/Scripts/gallery/page-manage-deprecation.js
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
src/NuGetGallery/Views/Packages/_ManageDeprecation.cshtml
tests/NuGetGallery.Facts/Controllers/ManageDeprecationJsonApiControllerFacts.cs

Part of https://github.com/NuGet/Engineering/issues/2382

Custom message should be required if deprecating package due to "Other" reason

---

src/NuGetGallery/Scripts/gallery/page-display-package.js
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

Closes https://github.com/NuGet/NuGetGallery/issues/7097

Store users preferred tab in localStorage

---

src/NuGetGallery/Areas/Admin/AdminAreaRegistration.cs
src/NuGetGallery/Areas/Admin/Controllers/HomeController.cs
src/NuGetGallery/Areas/Admin/ViewModels/HomeViewModel.cs
src/NuGetGallery/Areas/Admin/Views/Home/Index.cshtml
src/NuGetGallery/Configuration/AppConfiguration.cs
src/NuGetGallery/Configuration/IAppConfiguration.cs
src/NuGetGallery/Web.config

Adds a new flag to enable/disable the DB administration access from the Admin UI.

Add flag to enable/disable UI DB access

---

src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Services/IPackageService.cs
src/NuGetGallery/Services/PackageService.cs
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs

https://github.com/nuget/nugetgallery/issues/7154

DisplayPackage, Manage, and DeleteSymbols pages should find exact version case-insensitively

---

src/NuGetGallery.Core/Auditing/CloudAuditingService.cs
src/NuGetGallery.Core/ICloudStorageStatusDependency.cs
src/NuGetGallery.Core/Services/CloudBlobContainerWrapper.cs
src/NuGetGallery.Core/Services/ICloudBlobContainer.cs
src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
src/NuGetGallery/Services/CloudBlobFileStorageService.cs
src/NuGetGallery/Services/CloudReportService.cs
src/NuGetGallery/Services/StatusService.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
tests/NuGetGallery.Facts/Services/StatusServiceFacts.cs

Address issue https://github.com/NuGet/Engineering/issues/1980. Gallery status service will verify the storage status for primary or secondary depending on the read only mode.

StorageStatusService

---

src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Services/ISearchSideBySideService.cs
src/NuGetGallery/Services/SearchSideBySideService.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
tests/NuGetGallery.Facts/Services/SearchSideBySideServiceFacts.cs

Progress on https://github.com/NuGet/NuGetGallery/issues/7152.
Depends on https://github.com/NuGet/NuGetGallery/pull/7175.
This is the service layer code to actually perform the search against the two search services.

[SxS 2] Add SearchSideBySideService to do the two searches

---

src/Bootstrap/Gruntfile.js
src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/all.less
src/Bootstrap/less/theme/page-search-sxs.less
src/NuGetGallery/App_Start/Routes.cs
src/NuGetGallery/Controllers/ExperimentsController.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/RouteName.cs
src/NuGetGallery/UrlHelperExtensions.cs
src/NuGetGallery/ViewModels/SearchSideBySideViewModel.cs
src/NuGetGallery/Views/Experiments/SearchSideBySide.cshtml
src/NuGetGallery/Views/Shared/_ListPackage.cshtml
tests/NuGetGallery.Facts/Controllers/ExperimentsControllerFacts.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj

Address https://github.com/NuGet/NuGetGallery/issues/7152.
Depends on https://github.com/NuGet/NuGetGallery/pull/7176.
1. Add .cshtml for the SxS page and associated CSS
1. Make minimally invasive changes to `_ListPackage.cshtml` to support SxS better
1. Add `ExperimentsController` to serve up the page and connect to the service layer
This is what it looks like:

[SxS 3] Add search side-by-side web page

---

src/NuGetGallery/Controllers/ApiController.cs
src/NuGetGallery/Migrations/201904292139301_RemoveVulnerabilityDataFromPackageDeprecationModel.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Views/Api/HealthProbeApi.cshtml

FI master to dev. Use this approach to fix merge issues.

FI master to dev

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-status.less
src/Bootstrap/package-lock.json

https://github.com/NuGet/NuGetGallery/issues/7130
There will be a corresponding change on the status repo to switch the submodule branch to include these changes.
After:
The `package-lock.json` changes were made when I `npm install`'d the project.

Status page degraded icon should be orange for subcomponents

---

src/NuGetGallery.Services/Telemetry/ITelemetryService.cs
src/NuGetGallery/Controllers/ManageDeprecationJsonApiController.cs
src/NuGetGallery/Services/PackageDeprecationService.cs
src/NuGetGallery/Services/TelemetryService.cs
tests/NuGetGallery.Facts/Controllers/ManageDeprecationJsonApiControllerFacts.cs
tests/NuGetGallery.Facts/Services/PackageDeprecationServiceFacts.cs
tests/NuGetGallery.Facts/Services/TelemetryServiceFacts.cs

https://github.com/nuget/nugetgallery/issues/6854
We need to emit a new event so that it can show in the PackageEvents dashboard (https://github.com/nuget/engineering/issues/2477).

Add "PackageDeprecate" telemetry event

---

src/NuGetGallery/Views/Shared/Gallery/Header.cshtml

Undoing the changes unnecessary at this time.

Update blog link

---

src/DatabaseMigrationTools/DatabaseMigrationTools.csproj
src/GalleryTools/GalleryTools.csproj
src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj
src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery.Services/NuGetGallery.Services.csproj
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Web.config
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj

Update our ServerCommon and other C# dependencies to mitigate potential vulnerabilities.
Waiting on testing and "official" release of ServerCommon packages.

Update CS Dependencies

---

sign.thirdparty.targets
src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery.Services/NuGetGallery.Services.csproj
src/NuGetGallery/ApplicationInsights.config
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Telemetry/ClientInformationTelemetryEnricher.cs
src/NuGetGallery/Telemetry/ClientTelemetryPIIProcessor.cs
src/NuGetGallery/Web.config
tests/NuGetGallery.Facts/Telemetry/ClientInformationTelemetryEnricherTests.cs

Update the App Insights version to 2.10.

Update the App Insights version.

---

src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery.Services/NuGetGallery.Services.csproj
src/NuGetGallery/ApplicationInsights.config
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Telemetry/ClientInformationTelemetryEnricher.cs
src/NuGetGallery/Telemetry/ClientTelemetryPIIProcessor.cs
src/NuGetGallery/Web.config
tests/NuGetGallery.Facts/Telemetry/ClientInformationTelemetryEnricherTests.cs

Reverts NuGet/NuGetGallery#7253

Revert "Update the App Insights version."

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-statistics-per-package.less
src/NuGetGallery/Scripts/gallery/stats-perpackagestatsgraphs.js

Address https://github.com/NuGet/NuGetGallery/issues/7286

Fix overlap in stats chart title

---

src/AccountDeleter/Configuration/GalleryConfiguration.cs

Update AccountDeleter implementation of IAppConfiguration to include latest fields that were added in dev.

Fix GalleryConfiguration

---

src/NuGetGallery/Controllers/PagesController.cs
src/NuGetGallery/Views/Pages/Contact.cshtml

Title
@loic-sharma @joelverhagen @skofman1

Add recaptcha to Contact page.

---

src/DatabaseMigrationTools/DatabaseMigrationTools.csproj
src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj
src/NuGet.Services.Entities/NuGet.Services.Entities.csproj
src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery.Services/NuGetGallery.Services.csproj
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Telemetry/ClientInformationTelemetryEnricher.cs
src/NuGetGallery/Web.config

Address https://github.com/NuGet/Engineering/issues/2527.
This is a version of https://github.com/NuGet/NuGetGallery/pull/7307. I think it is more prudent to deploy this as a hotfix. Deploying this change along with product changes bit us last time. It would be foolish to not be cautious given that experience.
Additionally, this will allow us to get this change out sooner.

[Hotfix] Update to Application Insights 2.3.0

---

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

Addresses https://github.com/NuGet/NuGetGallery/issues/6616

Fix 'Download symbols' casing

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-display-package.less
src/NuGetGallery.Core/GitHub/RepositoryInformation.cs
src/NuGetGallery/Scripts/gallery/page-display-package.js
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
tests/NuGetGallery.Core.Facts/GitHub/GitHubUsageConfigurationFacts.cs

This PR adds the final UI for the GitHub Usage section on the Gallery

Added final UI for the GitHub Usage section

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-display-package.less
src/NuGetGallery/Controllers/ManageDeprecationJsonApiController.cs
src/NuGetGallery/Scripts/gallery/page-manage-deprecation.js
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
src/NuGetGallery/Views/Packages/_DisplayPackageDeprecation.cshtml
src/NuGetGallery/Views/Packages/_ManageDeprecation.cshtml
tests/NuGetGallery.Facts/Controllers/ManageDeprecationJsonApiControllerFacts.cs

https://github.com/nuget/engineering/issues/2541
https://github.com/nuget/engineering/issues/2536
https://github.com/nuget/nugetgallery/issues/7305
https://github.com/nuget/engineering/issues/2542
https://github.com/nuget/engineering/issues/2540
The new error message for having a package the alternate of itself looks like

Small Deprecation fixes

---

tests/NuGetGallery.Facts/Controllers/ManageDeprecationJsonApiControllerFacts.cs

https://github.com/NuGet/NuGetGallery/pull/7326#discussion_r301925255

Add test that asserts success when deprecating a package and choosing an alternate package with the ID

---

src/NuGetGallery/Web.config

The AsyncFileUploadModule moved assemblies from NuGetGallery to NuGetGallery.Services.
Update the web.config to reflect this change.

Update web.config for httpmodules

---

src/Bootstrap/package-lock.json
src/Bootstrap/package.json

Lifts our lodash dependency so we can reference the latest security fixes.

Pull lodash up so we can use the latest.

---

src/NuGetGallery/Infrastructure/Lucene/SearchClientPolicies.cs
tests/NuGetGallery.Facts/Infrastructure/Lucene/SearchPolicyFacts.cs

Stopped Azure web apps return HTTP 403. We should consider this case for the circuit breaker configuration in light of moving search to web app (for Azure Search).
Note that we do not retry in 403 case as we do with HTTP 500+.
Progress on https://github.com/NuGet/NuGetGallery/issues/7119.

Consider a 403 from search in the circuit breaker configuration

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-search-sxs.less
src/NuGetGallery/ViewModels/PackageViewModel.cs
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
src/NuGetGallery/Views/Shared/_ListPackage.cshtml
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs

Package title was eliminated from
* DisplayPackage.cshtml
* _ListPackage.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/7149

Eliminate package title

---

src/NuGetGallery/Controllers/JsonApiController.cs
src/NuGetGallery/Infrastructure/Mail/Messages/PackageOwnershipRequestMessage.cs
tests/NuGetGallery.Facts/Infrastructure/Mail/Messages/PackageOwnershipRequestMessageFacts.cs

https://github.com/NuGet/NuGetGallery/issues/7382

[Hotfix] Don't throw when adding a package owner without a message

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/dist/css/bootstrap.css
src/Bootstrap/less/theme/all.less
src/Bootstrap/less/theme/page-add-organization.less
src/Bootstrap/less/variables.less
src/NuGetGallery/Views/Organizations/Add.cshtml
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
src/NuGetGallery/Views/Packages/_ImportReadMe.cshtml
src/NuGetGallery/Views/Packages/_ManageOwners.cshtml
src/NuGetGallery/Views/Pages/Home.cshtml
src/NuGetGallery/Views/Shared/Gallery/Footer.cshtml
src/NuGetGallery/Views/Shared/_AccountCertificates.cshtml

These changes fix the following accessibility issues:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/904918
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/904930
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/904941
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/905541
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/910823
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/910473
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/910459
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/905573
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/905742
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/904912
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/917909

Fix minor accessibility issues found in recent scan

---

src/NuGetGallery/Scripts/gallery/jquery-ui-1.10.3.js

Address issue #7397 
This was caused by the upgrade to jQuery 3.x and a known incompatibility with jqueryUI < 1.12
see https://github.com/vanderlee/colorpicker/issues/132 and https://github.com/jquery/jquery/issues/3193 for details.

Fix Support Request Dialog box

---

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

Beautiful new UI:
Addresses https://github.com/nuget/nugetgallery/issues/7346

[GitHub Usage] Trim whitespace

---

src/NuGetGallery/Helpers/TextHelper.cs
tests/NuGetGallery.Facts/Helpers/TextHelperFacts.cs
tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs

Addresses https://github.com/NuGet/NuGetGallery/issues/7405.

Allow form feed character to be used in license files

---

src/NuGetGallery/App_Code/ViewHelpers.cshtml
src/NuGetGallery/ExtensionMethods.cs
src/NuGetGallery/Views/Packages/ContactOwners.cshtml
src/NuGetGallery/Views/Packages/ReportAbuse.cshtml
src/NuGetGallery/Views/Packages/ReportMyPackage.cshtml
src/NuGetGallery/Views/Packages/_ManageOwners.cshtml
src/NuGetGallery/Views/Pages/Contact.cshtml

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/910474
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/917900
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/910502

Some more accessibility issues found in last scan

---

src/NuGetGallery.Services/Configuration/ABTestConfiguration.cs
src/NuGetGallery.Services/Configuration/FeatureFlagService.cs
src/NuGetGallery.Services/Configuration/IABTestConfiguration.cs
src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs
src/NuGetGallery/App_Data/Files/Content/AB-Test-Configuration.json
src/NuGetGallery/App_Data/Files/Content/flags.json
src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
src/NuGetGallery/Controllers/ODataV1FeedController.cs
src/NuGetGallery/Controllers/ODataV2FeedController.cs
src/NuGetGallery/Infrastructure/HijackSearchServiceFactory.cs
src/NuGetGallery/Infrastructure/IHijackSearchServiceFactory.cs
src/NuGetGallery/Infrastructure/Lucene/ExternalSearchService.cs
src/NuGetGallery/NuGetGallery.csproj
tests/NuGetGallery.Facts/Controllers/ODataV1FeedControllerFacts.cs
tests/NuGetGallery.Facts/Controllers/ODataV2FeedControllerFacts.cs
tests/NuGetGallery.Facts/Infrastructure/HijackSearchServiceFactoryFacts.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
tests/NuGetGallery.Facts/Services/ContentObjectServiceFacts.cs
tests/NuGetGallery.Facts/Services/FeedServiceFacts.cs
tests/NuGetGallery.Facts/TestUtils/Infrastructure/TestableV1Feed.cs
tests/NuGetGallery.Facts/TestUtils/Infrastructure/TestableV2Feed.cs

Addresses https://github.com/nuget/nugetgallery/issues/7400
Test build: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=2936530
Test release: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=413946

[Azure Search] Split traffic for hijack by percentage

---

src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Infrastructure/ISearchServiceFactory.cs
src/NuGetGallery/Infrastructure/SearchServiceFactory.cs
src/NuGetGallery/NuGetGallery.csproj
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
tests/NuGetGallery.Facts/Infrastructure/SearchServiceFactoryFacts.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj

Address https://github.com/NuGet/NuGetGallery/issues/7461
Regressed in https://github.com/NuGet/NuGetGallery/pull/7313

[Hotfix] Fix bug causing TempData messages to not work

---

src/NuGetGallery.Services/Extensions/UriExtensions.cs
tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs

Fixed https://github.com/NuGet/Engineering/issues/2658

Add 2 URLs to HTTP->HTTPS translation list

---

src/NuGetGallery/Views/Shared/Gallery/Header.cshtml

Update Documentation link at the top of the page to the new docs landing page (https://docs.microsoft.com/en-us/nuget)
@karann-msft

Update docs link.

---

src/NuGetGallery/App_Code/ViewHelpers.cshtml
src/NuGetGallery/App_Start/Routes.cs
src/NuGetGallery/Areas/Admin/Controllers/HomeController.cs
src/NuGetGallery/Areas/Admin/Views/Home/Index.cshtml
src/NuGetGallery/Areas/Admin/Views/Validation/Index.cshtml
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/RouteName.cs
src/NuGetGallery/UrlHelperExtensions.cs
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
tests/NuGetGallery.Facts/UrlHelperExtensionsFacts.cs

Progress on https://github.com/NuGet/Engineering/issues/2679

Use POST for admin actions

---

tests/NuGetGallery.FunctionalTests.Core/Helpers/ODataHelper.cs
tests/NuGetGallery.FunctionalTests/ODataFeeds/CuratedFeedTest.cs
tests/NuGetGallery.FunctionalTests/ODataFeeds/SearchTest.cs
tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedExtendedTests.cs
tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedTests.cs
tests/NuGetGallery.FunctionalTests/PackageCreation/SecurityPolicyTests.cs
tests/NuGetGallery.FunctionalTests/Statistics/PackageStatisticsTests.cs
tests/NuGetGallery.LoadTests/LoadTests.cs

Functional test run: https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=61456
Part of https://github.com/nuget/engineering/issues/2686

[SDL] Use HttpClient instead of HttpWebRequest

---

src/AccountDeleter/AccountDeleter.csproj
src/DatabaseMigrationTools/DatabaseMigrationTools.csproj
src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj
src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery.Services/NuGetGallery.Services.csproj
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Services/AsynchronousPackageValidationInitiator.cs
tests/NuGetGallery.Facts/Services/AsynchronousPackageValidationInitiatorFacts.cs

Progress on https://github.com/NuGet/NuGetGallery/issues/7490

Update to latest ServerCommon to react to method rename

---

src/NuGetGallery/Infrastructure/HttpStatusCodeWithBodyResult.cs
tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs

`HttpStatusCodeResult` throws if the `StatusDescription` property is longer than 512 characters (see [this documentation](https://docs.microsoft.com/en-us/dotnet/api/system.web.httpresponse.statusdescription?redirectedfrom=MSDN&view=netframework-4.8#exceptions)), which results in a HTTP 500 response. I wasn't able to determine which code path affected the user as a few suspicious paths append an exception message to the description.
This change mitigates the issue by truncating HTTP Status Descriptions if they are longer than 512 characters.
Addresses https://github.com/NuGet/NuGetGallery/issues/7536

Mitigate "Internal Server Error" on package uploads

---

.github/CODEOWNERS
src/NuGetGallery.Services/Telemetry/UserPackageDeleteEvent.cs
src/NuGetGallery/Controllers/StatisticsController.cs
src/NuGetGallery/Services/JsonStatisticsService.cs
src/NuGetGallery/ViewModels/StatisticsFact.cs
src/NuGetGallery/ViewModels/StatisticsNuGetUsageItem.cs
src/NuGetGallery/ViewModels/StatisticsPackagesItemViewModel.cs
src/NuGetGallery/ViewModels/StatisticsPackagesReport.cs
src/NuGetGallery/ViewModels/StatisticsPackagesViewModel.cs
src/NuGetGallery/ViewModels/StatisticsPivot.cs
src/NuGetGallery/ViewModels/StatisticsWeeklyUsageItem.cs
src/NuGetGallery/Views/Statistics/Index.cshtml
tests/NuGetGallery.Facts/Controllers/StatisticsControllerFacts.cs

I'm waiting until the master build completes before merging this: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3042836

[ReleasePrep][2019.09.11]FI of master into dev

---

src/AccountDeleter/AccountDeleteMessageHandler.cs

Re-enables sending out mail to users.

Enable sending mails to users.

---

src/NuGetGallery.Services/PackageManagement/PackageHelper.cs
src/NuGetGallery/Services/ReadMeService.cs
tests/NuGetGallery.Facts/Helpers/PackageHelperTests.cs
tests/NuGetGallery.Facts/Services/ReadMeServiceFacts.cs

Rewrites all http images to https at display time.
Does not affect text in the actual md file; this is only a display time rewrite.

Rewrite http images to https.

---

src/NuGetGallery.Services/NuGetGallery.Services.csproj
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Telemetry/ClientInformationTelemetryEnricher.cs
src/NuGetGallery/Telemetry/DeploymentIdTelemetryEnricher.cs
src/NuGetGallery/Web.config
tests/NuGetGallery.Facts/Telemetry/ClientInformationTelemetryEnricherTests.cs
tests/NuGetGallery.Facts/Telemetry/DeploymentIdTelemetryEnricherFacts.cs

This reverts commit d199584d61d92757081f2f4be3fe39d6aa65860d.

Revert "Upgrade to AppInsights v2.10 (#7499)"

---

src/NuGetGallery/ApplicationInsights.config
src/NuGetGallery/Web.config

Fixes the missing request telemetry as a result of missing configuration changes that go with the AppInsights upgrade.

Fix AppInsights request telemetry

---

src/NuGetGallery.Services/NuGetGallery.Services.csproj
src/NuGetGallery/ApplicationInsights.config
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Telemetry/ClientInformationTelemetryEnricher.cs
src/NuGetGallery/Telemetry/DeploymentIdTelemetryEnricher.cs
src/NuGetGallery/Web.config
tests/NuGetGallery.Facts/Telemetry/ClientInformationTelemetryEnricherTests.cs
tests/NuGetGallery.Facts/Telemetry/DeploymentIdTelemetryEnricherFacts.cs

This PR reverts https://github.com/NuGet/NuGetGallery/pull/7596 and cherry picks https://github.com/NuGet/NuGetGallery/pull/7599. 
When https://github.com/NuGet/NuGetGallery/pull/7599 is merged in `dev`, this PR ensures `master` and `dev` are in sync and won't have merge conflicts.

Re-align AppInsights with dev branch

---

src/NuGetGallery/Telemetry/ClientTelemetryPIIProcessor.cs
src/NuGetGallery/Views/Organizations/Add.cshtml
src/NuGetGallery/Views/Shared/_AccountProfilePicture.cshtml
tests/NuGetGallery.Facts/Telemetry/ClientTelemetryPIIProcessorTests.cs

I suggest enabling `Hide whitespace changes` before reviewing this change.
Also see [NuGetDeployment#1166](https://nuget.visualstudio.com/NuGetMicrosoft/_git/NuGetDeployment/pullrequest/1166?_a=overview)
Test build 2: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3127150
Test release 2: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=473075
~~Test build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3124426
Test release: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=472071~~

[Gravatar Proxy] Address legal and privacy concerns

---

src/AccountDeleter/AccountDeleter.csproj
src/AccountDeleter/Configuration/GalleryConfiguration.cs
src/DatabaseMigrationTools/DatabaseMigrationTools.csproj
src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj
src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery.Services/Configuration/AppConfiguration.cs
src/NuGetGallery.Services/Configuration/IAppConfiguration.cs
src/NuGetGallery.Services/NuGetGallery.Services.csproj
src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
src/NuGetGallery/App_Start/OwinStartup.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Web.config

NuGetGallery AI heartbeats currently emit every 15 minutes (default since AI upgrade to v2.10). This PR makes the interval configurable.

Add configuration support for heartbeat interval to NuGetGallery

---

tests/NuGetGallery.FunctionalTests.Core/Helpers/UrlHelper.cs
tests/NuGetGallery.FunctionalTests/License/LicenseTests.cs
tests/NuGetGallery.FunctionalTests/NuGetGallery.FunctionalTests.csproj
tests/NuGetGallery.FunctionalTests/ProfileTests.cs

Test run: https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=63423
Test run 2: https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=63525
Addresses https://github.com/NuGet/NuGetGallery/issues/7588

[Gravatar Proxy] Add functional test

---

src/AccountDeleter/AccountDeleter.csproj
src/DatabaseMigrationTools/DatabaseMigrationTools.csproj
src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj

Follow up to https://github.com/NuGet/NuGetGallery/pull/7634
Finishing pulling in updated jobs packages.

Update Jobs Packages

---

src/NuGetGallery/Controllers/ExperimentsController.cs
src/NuGetGallery/ViewModels/SearchSideBySideViewModel.cs
src/NuGetGallery/Views/Experiments/SearchSideBySide.cshtml
tests/NuGetGallery.Facts/Controllers/ExperimentsControllerFacts.cs

Address https://github.com/NuGet/NuGetGallery/issues/7638
When the side-by-side page is turned off, anyone hitting the URL will see:

Add better messaging when SxS page is disabled

---

src/NuGetGallery.Services/Extensions/UriExtensions.cs
tests/NuGetGallery.Facts/Helpers/PackageHelperTests.cs

Addresses https://github.com/nuget/engineering/issues/2804

Add odata.org to Microsoft domains

---

src/NuGetGallery.Services/NuGetGallery.Services.csproj
src/NuGetGallery.Services/PackageManagement/IPackageUpdateService.cs
src/NuGetGallery.Services/PackageManagement/IPackageVulnerabilityService.cs
src/NuGetGallery.Services/PackageManagement/PackageUpdateService.cs
src/NuGetGallery.Services/PackageManagement/PackageVulnerabilityService.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
tests/NuGetGallery.Facts/Services/PackageUpdateServiceFacts.cs
tests/NuGetGallery.Facts/Services/PackageVulnerabilityServiceFacts.cs

Part of https://github.com/nuget/nugetgallery/issues/7648
This PR adds the PackageVulnerabilityService, which will be used directly by the GitHub ingestion job (GitHubVulnerabilities2Db) to update the vulnerabilities in the DB.

Add PackageVulnerabilityService

---

src/NuGetGallery.Core/Auditing/AuditedUserAction.cs
src/NuGetGallery.Core/Auditing/CredentialAuditRecord.cs
src/NuGetGallery.Services/Authentication/AuthenticationService.cs
src/NuGetGallery.Services/Extensions/UriExtensions.cs
tests/NuGetGallery.Core.Facts/Auditing/AuditedUserActionTests.cs
tests/NuGetGallery.Core.Facts/Auditing/CredentialAuditRecordTests.cs
tests/NuGetGallery.Facts/Helpers/PackageHelperTests.cs

Cherry picking the auditing changes, since we do not want @scottbommarito's package vulnerabilities changes to go to PROD.

RI dev-merge to master

---

src/NuGetGallery.Services/Configuration/FeatureFlagService.cs
src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs
src/NuGetGallery/App_Data/Files/Content/flags.json
src/NuGetGallery/Helpers/GravatarHelper.cs
src/NuGetGallery/Services/GravatarProxyService.cs
tests/NuGetGallery.Facts/Services/GravatarProxyServiceFacts.cs

Addresses https://github.com/nuget/nugetgallery/issues/7646
Build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3201746
Release: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=497282

[Gravatar] Proxy the en.gravatar.com subdomain

---

src/NuGetGallery.Services/Authentication/AuthenticationService.cs
src/NuGetGallery.Services/Authentication/IAuthenticationService.cs
src/NuGetGallery/Areas/Admin/Controllers/ApiKeysController.cs
src/NuGetGallery/Areas/Admin/ViewModels/ApiKeyRevokeViewModel.cs
src/NuGetGallery/Areas/Admin/Views/ApiKeys/Index.cshtml
src/NuGetGallery/Areas/Admin/Views/Home/Index.cshtml
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/ViewModels/ApiKeyViewModel.cs
tests/NuGetGallery.Facts/Areas/Admin/Controllers/ApiKeysControllerFacts.cs
tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj

[Token scanning-Phase 1-1] Admin page to verify the token.
1. Verify multiple tokens:
2. Invalid Input:
3. Not found tokens:

[Token scanning-Phase 1-1] Admin page to verify the token

---

src/NuGetGallery/GalleryConstants.cs
tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs

Fixes https://github.com/NuGet/NuGetGallery/issues/7674

Update minClientVersion to 5.3.0

---

src/NuGetGallery.Services/Configuration/SecretReader/SecretReaderFactory.cs

Progress on https://github.com/NuGet/Engineering/issues/1912.
Added two new optional configuration settings:
* KeyVault.StoreName
* KeyVault.StoreLocation
Allows to override the default LocalMachine/My store for keyvault cert.

Allow to specify KeyVault cert store and location.

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-api-keys.less
src/NuGetGallery/Areas/Admin/Views/ApiKeys/Index.cshtml
src/NuGetGallery/Scripts/gallery/page-api-keys.js
src/NuGetGallery/Views/Users/ApiKeys.cshtml

- API keys profile page shows the revoked API keys info.
Or
- The page to verify API keys shows "Link" rather than the original URL.

[Token scanning-Phase 1-3] API keys profile page

---

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

Part of https://github.com/NuGet/Engineering/issues/2763

Link to 'evaluate packages' documentation

---

src/NuGetGallery/App_Start/AppActivator.cs

Progress on https://github.com/NuGet/Engineering/issues/1912
Removed some dead code. `DiagnosticMonitorTraceListener` needs to be configured, we don't have any configuration code in the project (or in web.config).

Dropped the `DiagnosticMonitorTraceListener` usage.

---

src/NuGetGallery.Services/Storage/ContentObjectService.cs
tests/NuGetGallery.Facts/Services/ContentObjectServiceFacts.cs

/cc @zhhyu - this is what caused the exceptions you saw in AI.
Address https://github.com/NuGet/NuGetGallery/issues/7726.

Fix null reference exception when GitHub usage is not yet initialized

---

src/NuGetGallery/Controllers/PackagesController.cs
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs

Address https://github.com/NuGet/NuGetGallery/issues/7716
[Hide whitespace changes](https://github.com/NuGet/NuGetGallery/pull/7729/files?utf8=%E2%9C%93&diff=unified&w=1)

Only check "is indexed" for a day

---

src/NuGetGallery/Controllers/AuthenticationController.cs
src/NuGetGallery/Filters/UiAuthorizeAttribute.cs
src/NuGetGallery/GalleryConstants.cs
tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
tests/NuGetGallery.Facts/Filters/UiAuthorizeAttributeFacts.cs

Addressing a minor fix for redirecting to home page(for redirected pages after authentication) for encouraging 2FA.

[MSA] Redirect to home page for enabling 2FA

---

src/NuGetGallery.Core/Infrastructure/Mail/Messages/CredentialRevokedMessage.cs
src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery/Areas/Admin/Controllers/ApiKeysController.cs
tests/NuGetGallery.Core.Facts/Infrastructure/Mail/Messages/MarkdownMessageBuilderFacts.cs
tests/NuGetGallery.Facts/Areas/Admin/Controllers/ApiKeysControllerFacts.cs
tests/NuGetGallery.Facts/Infrastructure/Mail/Messages/CredentialRevokedMessageFacts.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj

Send the email to the customer about the revocation. 
Lack test coverage and test the recommended ways among Windows/Linux/Mac. 
Send email -> Audit -> Commit to DB
If anything goes wrong, just click the button and try again. If we send the email at the last step, the email will not be able to send automatically once the DB commit is done. Because the UI only provides the choice to do the revocation if it has not be revoked. 
Handle: https://github.com/nuget/engineering/issues/2831
Sample email: @karann-msft

[Token scanning-Phase 1-5] Email

---

src/NuGetGallery.Core/Infrastructure/Mail/Messages/CredentialRevokedMessage.cs
tests/NuGetGallery.Core.Facts/Infrastructure/Mail/Messages/CredentialRevokedMessageFacts.cs
tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj

We want to cc the email to Gallery Owner (Support) to track the messages. 
Handle: https://github.com/nuget/engineering/issues/2898

[Token scanning-Phase 1] Email should cc to Gallery Owner. 

---

src/NuGetGallery.Core/CoreStrings.Designer.cs
src/NuGetGallery.Core/CoreStrings.resx
src/NuGetGallery.Core/Packaging/PackageMetadata.cs
src/NuGetGallery/Services/ReflowPackageService.cs
tests/NuGetGallery.Core.Facts/Packaging/PackageMetadataFacts.cs
tests/NuGetGallery.Facts/Services/ReflowPackageServiceFacts.cs

Clear previous package types during reflow: https://github.com/NuGet/NuGetGallery/issues/7780
Reject invalid package type names: https://github.com/NuGet/NuGetGallery/issues/7766

Fix two package type related bugs

---

src/NuGetGallery/NuGetGallery.csproj

Progress on https://github.com/NuGet/Engineering/issues/2883
This adds an optional point to insert targets file during the build.

Build extensions targets file for build pipelines

---

src/NuGetGallery/Views/Packages/Manage.cshtml

All required documentation is on the following issue:
Addresses https://github.com/NuGet/Engineering/issues/2911

Use Json.Encode to avoid js injection

---

src/AccountDeleter/AccountDeleter.csproj
src/DatabaseMigrationTools/DatabaseMigrationTools.csproj
src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj
src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj
src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery.Services/NuGetGallery.Services.csproj
src/NuGetGallery/NuGetGallery.csproj

Consumes latest ServerCommon and NuGet.Jobs dependencies to align repositories

Upgrade ServerCommon and NuGet.Jobs dependencies to latest

---

src/NuGetGallery.Services/PackageManagement/PackageHelper.cs
src/NuGetGallery.Services/ServicesStrings.Designer.cs
src/NuGetGallery.Services/ServicesStrings.resx
tests/NuGetGallery.Facts/Helpers/PackageHelperTests.cs
tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs

Addresses https://github.com/NuGet/NuGetGallery/issues/7714

Reject packages with duplicate dependency groups

---

src/NuGetGallery.Core/Services/CorePackageService.cs
src/NuGetGallery.Services/Configuration/FeatureFlagService.cs
src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs
src/NuGetGallery.Services/PackageManagement/IPackageService.cs
src/NuGetGallery.Services/PackageManagement/PackageHelper.cs
src/NuGetGallery.Services/PackageManagement/PackageService.cs
src/NuGetGallery.Services/Permissions/ActionRequiringEntityPermissions.cs
src/NuGetGallery.Services/ServicesStrings.Designer.cs
src/NuGetGallery.Services/ServicesStrings.resx
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Helpers/ViewModelExtensions/DeletePackageViewModelFactory.cs
src/NuGetGallery/Helpers/ViewModelExtensions/DisplayPackageViewModelFactory.cs
src/NuGetGallery/Services/IPackageDeprecationService.cs
src/NuGetGallery/Services/PackageDeprecationService.cs
src/NuGetGallery/Views/Packages/_ManageDeprecation.cshtml
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
tests/NuGetGallery.Facts/Helpers/PackageHelperTests.cs
tests/NuGetGallery.Facts/Services/FeatureFlagServiceFacts.cs
tests/NuGetGallery.Facts/Services/PackageDeprecationServiceFacts.cs
tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs

Pulling in display package page performance improvements.

[ReleasePrep][2020.01.21]RI dev to master

---

src/NuGetGallery.Services/Authentication/Providers/AzureActiveDirectory/AzureActiveDirectoryAuthenticator.cs
src/NuGetGallery.Services/Authentication/Providers/AzureActiveDirectoryV2/AzureActiveDirectoryV2Authenticator.cs
src/NuGetGallery.Services/NuGetGallery.Services.csproj
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Web.config

Updating to accommodate upcoming chrome change for SameSite cookie.

Update owin 3.x->4.x

---

src/AccountDeleter/AccountDeleter.csproj
src/DatabaseMigrationTools/DatabaseMigrationTools.csproj
src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj
src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj
src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery.Services/Configuration/SecretReader/SecretReaderFactory.cs
src/NuGetGallery.Services/NuGetGallery.Services.csproj
src/NuGetGallery/NuGetGallery.csproj

Progress on https://github.com/NuGet/Engineering/issues/2970

Enable using managed identities for KeyVault

---

src/GalleryTools/App.config
src/NuGetGallery/Web.config

Minor fix for easy local development against keyvault environment.

Add empty config for managed identity

---

sign.thirdparty.props

The new version of the verification tools found this.
Address https://github.com/NuGet/Engineering/issues/2997

Sign Owin.dll

---

sign.thirdparty.props
src/AccountDeleter/Job.cs

This job threw exception when deleting a user due to DI issues. 
@ryuyu provided the fix, I am going to deploy it.
This was tested on DEV with the private branch.

[HOTFIX] Fix GalleryAccount deleter job DI issue

---

src/NuGetGallery/App_Start/DefaultDependenciesModule.cs

Progress on https://github.com/NuGet/Engineering/issues/2980
This adds about 23 seconds to start-up time.

Initialize cookie compliance service during startup

---

src/AccountDeleter/AccountDeleter.csproj
src/AccountDeleter/Job.cs
src/DatabaseMigrationTools/DatabaseMigrationTools.csproj
src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj
src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj
src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery.Services/Configuration/ConfigurationService.cs
src/NuGetGallery.Services/Configuration/SecretReader/SecretReaderFactory.cs
src/NuGetGallery.Services/NuGetGallery.Services.csproj
src/NuGetGallery/NuGetGallery.csproj

Shrink Gallery secret caching to 6 hours and update dependencies.

Shrink Gallery secret caching to 6 hours and update dependencies. 

---

src/NuGetGallery/Web.config

This helps with addressing Component Governance issues.

Add missing binding redirects

---

src/NuGetGallery/GalleryConstants.cs

Bringing parity with https://github.com/NuGet/NuGet.Services.Index/pull/161

Updated MaxSupportedMinClientVersion

---

src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
tests/NuGetGallery.Facts/App_Start/DefaultDependenciesModuleFacts.cs

Address https://github.com/NuGet/Engineering/issues/3105

Remove "-staging" suffix from cloud role name

---

src/NuGetGallery.Core/Authentication/MicrosoftClaims.cs
src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery.Services/Extensions/HttpContextBaseExtensions.cs
src/NuGetGallery.Services/Extensions/IOwinContextExtensions.cs
src/NuGetGallery.Services/Extensions/PrincipalExtensions.cs
src/NuGetGallery.Services/Telemetry/TelemetryService.cs
src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Telemetry/ClientInformationTelemetryEnricher.cs
src/NuGetGallery/Telemetry/CustomerResourceIdEnricher.cs
tests/NuGetGallery.Facts/App_Start/DefaultDependenciesModuleFacts.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
tests/NuGetGallery.Facts/Telemetry/CustomerResourceIdEnricherFacts.cs

Progress on https://github.com/NuGet/Engineering/issues/3106

Add CustomerResourceId to enrich push metrics with tenant ID

---

src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
src/NuGetGallery/Controllers/PagesController.cs
src/NuGetGallery/Extensions/SimulatedErrorTypeExtensions.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/RequestModels/SimulatedErrorType.cs
src/NuGetGallery/Views/Errors/InternalError.cshtml
src/NuGetGallery/Views/Pages/SimulateError.cshtml
tests/NuGetGallery.FunctionalTests/ErrorHandling/ErrorHandlingTests.cs
tests/NuGetGallery.FunctionalTests/ErrorHandling/SimulatedErrorRequest.cs
tests/NuGetGallery.FunctionalTests/ErrorHandling/SimulatedErrorType.cs

Progress on https://github.com/NuGet/NuGetGallery/issues/7868.
Also switched from diagnostics service to logger factory to aid in debugging.

Add simulated error for exceptions in view and error page

---

src/AccountDeleter/AccountDeleter.csproj
src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj

Progress on https://github.com/NuGet/Engineering/issues/2891

Add build hook to AccountDeleter and GitHubVulnerabilities2Db

---

src/NuGetGallery/GalleryConstants.cs

Brings parity with: https://github.com/NuGet/NuGet.Services.Index/pull/166
Addresses https://github.com/nuget/nugetgallery/issues/7984

Update max supported nuget client version

---

src/NuGetGallery/Web.config

Progress on https://github.com/NuGet/Engineering/issues/3128

Remove unnecessary binding redirect

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/base.less
src/Bootstrap/less/theme/modals.less
src/Bootstrap/less/theme/page-status.less
src/Bootstrap/less/variables.less
src/NuGetGallery/Views/Shared/Gallery/Header.cshtml

Added variable with the background color and put it in all places the verbatim value was used.

Banner about the upcoming TLS 1.2 enforcement

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/base.less
src/NuGetGallery/Views/Shared/Gallery/Header.cshtml

[Hotfix] Black Lives Matter

---

src/Bootstrap/dist/css/bootstrap.css
src/Bootstrap/less/input-groups.less

Updates some css so the input row on upload page doesn't get read out as a table.

[A11y]Fix input group read out from table to nothing.

---

src/NuGetGallery/NuGetGallery.csproj

Quick fix to add in a missing icon in the NugetGallery

Adding extra icon to csproj

---

src/NuGetGallery/Content/fabric.css

This PR updates Fabric to 7.3.0 on the Gallery. This is needed for Advanced Search UI.

Updated Fabric

---

src/NuGetGallery/Content/gallery/css/fabric.css

[A previous PR](https://github.com/NuGet/NuGetGallery/pull/8095) has been created to update the fabric.css file. But it turns out I forgot to update the second copy of the fabric.css on the gallery.

Update Fabric.css from 7.0.0 to 7.3.0

---

src/NuGetGallery/App_Start/GalleryMachineKeyConfigurationProvider.cs
src/NuGetGallery/App_Start/OwinStartup.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Web.config

Address https://github.com/NuGet/Engineering/issues/3206
1. Done: test using configured machine key settings before and after this PR
1. Done: test default (unconfigured) machine key settings before and after this PR
1. TODO: test on DEV environment

Use protected configuration provider instead of reflection

---

tests/GitHubVulnerabilities2Db.Facts/AdvisoryIngestorFacts.cs

@loic-sharma I made one of these more realistic in response to your comment here (https://github.com/NuGet/NuGetGallery/pull/8088) but missed one alas! Here's the fix.

Adjust a test permalink

---

src/NuGetGallery.Core/Infrastructure/TableErrorLog.cs

Clean up Elmah logs of some information.

Clean Elmah

---

src/NuGetGallery/App_Start/OwinStartup.cs
src/NuGetGallery/App_Start/SessionPersistence.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Web.config

This reverts commit e6d6dc88d316f93fb21ff5081c581e3f19f305c0.

Revert "Use protected configuration provider instead of reflection" (#8098)

---

src/NuGetGallery/Services/PackageMetadataValidationService.cs
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
tests/NuGetGallery.Core.Facts/TestUtils/PackageServiceUtility.cs
tests/NuGetGallery.Core.Facts/TestUtils/TestPackage.cs
tests/NuGetGallery.Facts/Services/PackageMetadataValidationServiceFacts.cs

* add validation readme 
Addresses NuGet/Engineering#2342

Add validtion readme 

---

src/GalleryTools/Commands/VerifyGitHubVulnerabilitiesCommand.cs
src/GalleryTools/GalleryTools.csproj
src/GalleryTools/Program.cs
src/GitHubVulnerabilities2Db/Collector/AdvisoryCollector.cs
src/GitHubVulnerabilities2Db/Collector/AdvisoryQueryService.cs
src/GitHubVulnerabilities2Db/Collector/IAdvisoryQueryService.cs
tests/GitHubVulnerabilities2Db.Facts/AdvisoryQueryServiceFacts.cs

https://github.com/nuget/nugetgallery/issues/7685

Add command to compare PackageVulnerabilities to GitHub API

---

docs/README.md
docs/Using-AAD.md

You can preview the documentation here: https://github.com/NuGet/NuGetGallery/blob/document-aad-login/docs/Using-AAD.md
This is based off [this internal OneNote](https://microsoft.sharepoint.com/teams/NuGet/_layouts/OneNote.aspx?id=%2Fteams%2FNuGet%2FTeam%2FNugetServer%2FNugetServerTeamNote&wd=target%28Security.one%7CD36A0B17-E33C-43DE-B487-A40CAFAAA9E4%2FMicrosoft%20Logins%20%28MSA%5C%29%20and%20Nuget%20Gallery%7C4DD50740-0935-4235-8ADC-9F9A9CF013F1%2F%29onenote:https://microsoft.sharepoint.com/teams/NuGet/Team/NugetServer/NugetServerTeamNote/Security.one#Microsoft%20Logins%20(MSA)%20and%20Nuget%20Gallery&section-id={D36A0B17-E33C-43DE-B487-A40CAFAAA9E4}&page-id={4DD50740-0935-4235-8ADC-9F9A9CF013F1}&end). Note that I made several changes as our internal documentation was stale.

Document how to use Azure Active Directory

---

docs/Deploying/README.md

Improve the Azure documentation with problems discovered during my chat with the Rackspace engineer today.

Improve deploy to Azure documentation

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/dist/css/bootstrap.css
src/Bootstrap/less/mixins/background-variant.less
src/Bootstrap/less/theme/page-list-packages.less
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

Addresses the following:
https://github.com/NuGet/NuGetGallery/issues/7847
https://github.com/NuGet/NuGetGallery/issues/8091
https://github.com/NuGet/NuGetGallery/issues/8152
Selected row is slightly darkened.
Reset Button text slightly darkened.

[A11y]Fix some minor text contrast issues.

---

src/VerifyGitHubVulnerabilities/README.md

Add verifyGitHubVulnerabilities job info to the gallery readme.
Preview:

Add instructions for VerifyGitHubVulnerabilities to readme

---

src/NuGetGallery/Controllers/PackagesController.cs
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs

Address https://github.com/NuGet/NuGetGallery/issues/8198

Don't show missing version warning for absoluteLatest

---

src/NuGetGallery/Scripts/gallery/page-api-keys.js

Address https://github.com/NuGet/NuGetGallery/issues/8183

Focus edit button after form is closed

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-api-keys.less
src/NuGetGallery/Views/Users/ApiKeys.cshtml

Adding an * by required fields for Key Name
Before changes:
After changes: 
Addresses https://github.com/NuGet/NuGetGallery/issues/8181

adding an * by required fields in forms

---

tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs

The fix is tracked by https://github.com/NuGet/NuGetGallery/issues/8231.

Disable flaky test

---

src/NuGetGallery/Services/IconUrlDeprecationValidationMessage.cs
src/NuGetGallery/Services/InvalidLicenseUrlValidationMessage.cs
src/NuGetGallery/Services/InvalidUrlEncodingForLicenseUrlValidationMessage.cs
src/NuGetGallery/Services/LicenseUrlDeprecationValidationMessage.cs
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx

Updating the aria-label in this case to a more descriptive text is sufficient
Addresses  https://github.com/NuGet/NuGetGallery/issues/8184

Accessibility fix: Make Learn more link more descriptive

---

src/NuGetGallery/Views/Users/ApiKeys.cshtml

add  a new aria-live region that will read this information out when it changes. 
Addresses https://github.com/NuGet/NuGetGallery/issues/8194

 Announcing the Status message displayed after selecting the create button without giving any glob pattern

---

src/NuGetGallery.Services/Configuration/FeatureFlagService.cs
src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs
src/NuGetGallery/App_Data/Files/Content/flags.json
src/NuGetGallery/Controllers/ODataV1FeedController.cs
src/NuGetGallery/Controllers/ODataV2FeedController.cs
tests/NuGetGallery.Facts/Controllers/ODataV1FeedControllerFacts.cs
tests/NuGetGallery.Facts/Controllers/ODataV2FeedControllerFacts.cs

Related to https://github.com/NuGet/Engineering/issues/2902
Address https://github.com/NuGet/Engineering/issues/3442

Add feature flags to OData $count endpoints

---

src/NuGetGallery/Views/Shared/Gallery/Header.cshtml

Reverts NuGet/NuGetGallery#8262

Revert "Revert "survey banner (#8249)""

---

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

add aria-live to read status message 
Copy for install instructions on package details page
Steps to Reproduce :
Launch application using provided URL.(https://www.nuget.org/)
Navigated to Home page
Search for a key term (say “json”)
Look at the package search results and select any package.
Navigate till "Package Manager" and select it.
Start Narrator and navigate till "Copy" control.
Hit enter on the "Copy" control and observe the announcement by screen reader.
Addresses https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1061326 (https://github.com/NuGet/NuGetGallery/issues/8284 )

read status message when command been copied

---

README.md

Update the readme file:
Install the visual studio 2019 instead of 2017 
https://github.com/NuGet/Engineering/issues/3417

update readme to VS2019

---

src/VerifyMicrosoftPackage/README.md

Following the blog post https://devblogs.microsoft.com/nuget/microsoft-author-signing-certificate-update/
Updating the cert thumbprints in the documented verify command to include new cert.

Certificate update in docs

---

src/NuGetGallery/Views/Shared/Gallery/Header.cshtml

Remove code related to survey banner since we want to end survey banner this week 
We also made change to css that have underline for link when we added survey banner. I decided to not remove that because style is useful other banners.
Addresses https://github.com/NuGet/NuGetGallery/issues/8225

Remove survey banner

---

NuGet.config
tests/NuGet.Config

Migrate nuget-build feed from myget to Azure DevOps

---

src/NuGetGallery/Views/Organizations/_OrganizationAccountManageMembers.cshtml

**Manage members of an organization:**
As an administrator:
As a collaborator:
**Responsive after reflowing:**
As an administrator:
As a collaborator:
**Before:**

[A11y] Manage members of an organization - responsive after reflowing

---

src/NuGetGallery/GalleryConstants.cs
tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs

Addresses https://github.com/NuGet/NuGetGallery/issues/8316

Accept packages with a minClientVersion of 5.8.0

---

build.ps1

Related:
https://devblogs.microsoft.com/nuget/getting-started-with-nuget-5-8/#known-issues

Move to new build tools

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-manage-organizations.less
src/Bootstrap/less/theme/page-sign-in.less
src/NuGetGallery/ExtensionMethods.cs
src/NuGetGallery/Views/Authentication/_Register.cshtml
src/NuGetGallery/Views/Packages/_ManageListing.cshtml
src/NuGetGallery/Views/Shared/_AccountChangeEmail.cshtml
src/NuGetGallery/Views/Users/ApiKeys.cshtml

Addresses https://github.com/NuGet/NuGetGallery/issues/8181

Add * by required field 

---

src/NuGetGallery/Views/Packages/_VerifyMetadata.cshtml

Addresses https://github.com/NuGet/NuGetGallery/issues/8184

add description for readmore

---

src/NuGetGallery/Views/Packages/_VerifyMetadata.cshtml

Reverts NuGet/NuGetGallery#8329
It was supposed to merge in dev first. Revert it

Revert "add description for readmore"

---

src/NuGetGallery/Views/Packages/_VerifyMetadata.cshtml

Same PR was merged to Master(We reverted it): https://github.com/NuGet/NuGetGallery/pull/8329
It was supposed to merge to Dev first
Addresses https://github.com/NuGet/NuGetGallery/issues/8184

Add description for readmore 

---

src/NuGetGallery/GalleryConstants.cs

Related to https://github.com/NuGet/NuGet.Services.Index/pull/178

Update minClientVersion to 5.9.0 to support new client version

---

src/NuGetGallery/Views/Packages/_ManageDeprecation.cshtml

We normally don't announce the warning. But vendor pointed out need announce warning here. 
This fix only for ticket below.
**Question**: will be good idea to announce all the alert warning since we normally don't do?
Addresses https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1069948

Read out warning message

---

src/AccountDeleter/Configuration/GalleryConfiguration.cs
src/NuGetGallery.Services/Configuration/AppConfiguration.cs
src/NuGetGallery.Services/Configuration/FeatureFlagService.cs
src/NuGetGallery.Services/Configuration/IAppConfiguration.cs
src/NuGetGallery.Services/Configuration/IBlobStorageConfiguration.cs
src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs
src/NuGetGallery.Services/Configuration/SimpleBlobStorageConfiguration.cs
src/NuGetGallery.Services/NuGetGallery.Services.csproj
src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Services/CloudDownloadCountService.cs
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
src/NuGetGallery/Views/Packages/_ManageDeprecation.cshtml
src/NuGetGallery/Web.config
tests/NuGetGallery.Facts/Services/CloudDownloadCountServiceFacts.cs

Enables (behind a feature flag) support for allowing an alternate location for downloads.v1.json source.

[Stats]Enable Alternate storage for downloads.v1.json

---

src/NuGetGallery/App_Data/Files/Content/Trusted-Image-Domains.json
src/NuGetGallery/Scripts/gallery/async-file-upload.js

Create new PR because I accidently delete branch name by renaming branch. 
Same as this PR https://github.com/NuGet/NuGetGallery/pull/8443
Add one more change here: remove dev.azure.com from allowlist since there is uncertainty about this host in terms of cookies.
dev.azure.com drops cookies when we display image from this host. Remove it from now to unblock readme feature release. Might add it later once we figure out compliance requirement for third party cookie.
Addresses https://github.com/NuGet/Engineering/issues/3507

Bugfix upload page & remove dev.azure from allowlist

---

src/NuGetGallery.Services/Configuration/FeatureFlagService.cs
src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs
src/NuGetGallery.Services/PackageManagement/IPackageService.cs
src/NuGetGallery.Services/PackageManagement/PackageService.cs
src/NuGetGallery/App_Data/Files/Content/flags.json
src/VerifyMicrosoftPackage/Application.cs
src/VerifyMicrosoftPackage/Fakes/FakeFeatureFlagService.cs
src/VerifyMicrosoftPackage/VerifyMicrosoftPackage.csproj
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
tests/NuGetGallery.Facts/Services/ReflowPackageServiceFacts.cs
tests/NuGetGallery.Facts/TestUtils/MockPackageArchiveReader.cs
tests/NuGetGallery.Facts/TestUtils/TestServiceUtility.cs

Adding a feature flag to this change: https://github.com/NuGet/NuGetGallery/pull/8432
I'd like a fallback codepath in case this triggers anything unforeseen.
@agr this is the change I'd like to get in before integrations.

Add feature flag for new TFM heuristics

---

src/NuGetGallery/App_Data/Files/Content/Symbols-Configuration.json
src/NuGetGallery/App_Data/Files/Content/flags.json
src/NuGetGallery/Controllers/ApiController.cs
tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs

Fixes issue: https://github.com/NuGet/Engineering/issues/3676
Also changed default behavior of Symbols upload & Icons upload in Gallery to improve on-prem experience.

Symbols perf improvement

---

src/DatabaseMigrationTools/DatabaseMigrationTools.csproj
src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj
src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery.Services/NuGetGallery.Services.csproj
src/NuGetGallery/NuGetGallery.csproj
tests/NuGetGallery.Facts/Services/AsynchronousDeleteAccountServiceFacts.cs

See: https://github.com/NuGet/ServerCommon/pull/359
Tracked by: https://github.com/NuGet/Engineering/issues/3650
DEV build: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4585079&view=results
DEV test release: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=989991
NuGetGallery.Core build: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4585250&view=results

Update Service Bus libraries from ServerCommon

---

src/NuGetGallery/Services/PackageMetadataValidationService.cs
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx

Reverts NuGet/NuGetGallery#8464

Revert "reject empty readme file & fix error message for invalid extension"

---

src/Bootstrap/package-lock.json

Resolved with `npm audit fix`. 
Verified by running `grunt`. No changes to .css or .js files.

Resolve Dependabot alert

---

src/NuGetGallery/Views/Users/Organizations.cshtml

Addresses: https://github.com/NuGet/NuGetGallery/issues/8489
Note that the only code changes here are lines 28 and 96--the addition of a `div` which references a style created here: https://github.com/NuGet/NuGetGallery/pull/8340/files#diff-e26d2a1700d1dbfc8fcd3f8e68744fd1c5a96d09b27553d3155785be3a86263eR248
...giving the desired behavior.
This change moves the scrollbar to the table, and away from the page.

a11y fix - remove horizontal scrollbar from page

---

src/NuGetGallery/Scripts/gallery/page-display-package.js

Reverts NuGet/NuGetGallery#8501

Revert "show more link jumps problem"

---

src/NuGetGallery/Views/Shared/Gallery/Header.cshtml

Addresses https://github.com/NuGet/docs.microsoft.com-nuget/pull/2330

Add survey banner

---

src/NuGetGallery/Web.config

Addresses a build [warning](https://dev.azure.com/nuget/NuGetBuild/_build/results?buildId=80976&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=eae017ea-0d55-5834-e313-398fb5d39f4c&l=3622).

Fixing build warning

---

src/NuGetGallery/Services/PackageVulnerabilitiesService.cs
tests/NuGetGallery.Facts/Services/PackageVulnerabilitiesServiceFacts.cs

Reverts NuGet/NuGetGallery#8540

Revert "[Hotfix]change sql get vulnerabilities by package id"

---

src/NuGetGallery/Scripts/gallery/page-display-package.js
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
src/NuGetGallery/Views/Users/Profiles.cshtml

Addresses https://github.com/nuget/nugetgallery/issues/8621
Profile page: Leveraging the work done here: https://github.com/NuGet/NuGetGallery/pull/8521, utilizing its JS file in the profile page's package list. 
Package details page: added this code to relevant JS and adjusted checkmark.

Add accessible popovers to reserved checkmarks

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-home.less

Resolve https://github.com/NuGet/NuGetGallery/issues/8671

Make the package downloads box a bit bigger for macOS

---

src/NuGetGallery/Services/MarkdownService.cs
tests/NuGetGallery.Facts/Services/MarkdownServiceFacts.cs

Closes https://github.com/NuGet/NuGetGallery/issues/8627

Strip html comments from markdown

---

src/NuGetGallery/Services/MarkdownService.cs
tests/NuGetGallery.Facts/Services/MarkdownServiceFacts.cs

Bring changes in main to dev to be consistent for dev process. (some changes in main are not in dev.)

[ReleasePrep][2021.7.16]NuGetGallery of main into dev

---

src/NuGetGallery/App_Data/Files/Content/Trusted-Image-Domains.json

Include app.codacy.com in trusted domain

---

src/NuGetGallery/App_Data/Files/Content/Trusted-Image-Domains.json

Added i.imgur.com in trusted domain

---

src/NuGetGallery/App_Data/Files/Content/Trusted-Image-Domains.json

Align allowlist from local and one where stored in blob.
dev.azure.com is missing in local file

add dev.azure.com

---

src/AccountDeleter/AccountDeleter.csproj
src/AccountDeleter/Job.cs
src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/base.less
src/DatabaseMigrationTools/DatabaseMigrationTools.csproj
src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj
src/GitHubVulnerabilities2Db/Job.cs
src/NuGet.Services.DatabaseMigration/Job.cs
src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj
src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery.Services/NuGetGallery.Services.csproj
src/NuGetGallery/App_Code/ViewHelpers.cshtml
src/NuGetGallery/App_Data/Files/Content/Trusted-Image-Domains.json
src/NuGetGallery/Areas/Admin/Controllers/ValidationController.cs
src/NuGetGallery/Areas/Admin/Services/ValidationAdminService.cs
src/NuGetGallery/Areas/Admin/Views/Validation/Index.cshtml
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/UrlHelperExtensions.cs
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
src/NuGetGallery/Views/Shared/Gallery/Layout.cshtml
src/NuGetGallery/Views/Shared/_ListPackage.cshtml
src/VerifyGitHubVulnerabilities/Job.cs
src/VerifyGitHubVulnerabilities/VerifyGitHubVulnerabilities.csproj
tests/NuGetGallery.Facts/Areas/Admin/Services/ValidationAdminServiceFacts.cs
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs

Tracked by: https://github.com/NuGet/NuGetGallery/issues/8748

[ReleasePrep][2021.08.18] RI of dev into main

---

src/NuGetGallery.Core/Services/ICorePackageService.cs
src/NuGetGallery/Controllers/PackagesController.cs
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs

Fix https://github.com/NuGet/NuGetGallery/issues/8778

Check for deleted packages on several read and write operations

---

tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedTests.cs
tests/NuGetGallery.LoadTests/LoadTests.cs

Pull hotfix changes to dev branch in preparation for deployment.

[2021-09-14] FI of main to DEV

---

src/NuGetGallery/Services/PackageVulnerabilitiesCacheService.cs
tests/NuGetGallery.Facts/Services/PackageVulnerabilitiesCacheServiceFacts.cs

Addresses https://github.com/NuGet/NuGetGallery/issues/8666
(also works fine on new package details page design)

Make pva cache case insensitive to support all package details urls

---

src/NuGetGallery/Controllers/UsersController.cs
src/NuGetGallery/Views/Users/ForgotPassword.cshtml

Addresses https://github.com/NuGet/NuGetGallery/issues/8848

Add reCAPTCHA to the forgot password page

---

src/NuGetGallery.Services/Authentication/ApiKeyV4.cs
src/NuGetGallery.Services/Extensions/Base32Encoder.cs
src/NuGetGallery.Services/Models/ReportPackageReason.cs
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Controllers/UsersController.cs
src/NuGetGallery/ViewModels/ReportViewModel.cs
src/NuGetGallery/Views/Packages/ReportAbuse.cshtml
src/NuGetGallery/Views/Users/ForgotPassword.cshtml
tests/NuGetGallery.Facts/Infrastructure/Authentication/ApiKeyV4Facts.cs
tests/NuGetGallery.Facts/Infrastructure/Authentication/Base32EncoderTests.cs

Addresses https://github.com/NuGet/NuGetGallery/issues/8850

[ReleasePrep][2021.10.15]RI of dev into main

---

NuGet.config
build.ps1

This is for the package build pipeline.
Test in both local build and build pipeline.

[Gallery] Configure local build.ps1 for Roslyn Analyzer

---

NuGet.config
build.ps1

There is no need for a deployment.

[Gallery] Merge from dev to main for Roslyn Analyzer

---

src/DatabaseMigrationTools/DatabaseMigrationTools.csproj
src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Web.config

Required for service bus managed identities.

[SB-MSI] Update server common libs in gallery and core

---

src/NuGetGallery.Core/Frameworks/FrameworkCompatibilityService.cs
src/NuGetGallery.Core/Frameworks/IFrameworkCompatibilityService.cs
src/NuGetGallery.Core/Frameworks/SupportedFrameworks.cs
tests/NuGetGallery.Core.Facts/Frameworks/FrameworkCompatibilityServiceFacts.cs
tests/NuGetGallery.Core.Facts/Frameworks/SupportedFrameworksFacts.cs
tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj

This reverts commit 01216a07f9ab96e0e5015947b74d1d1786a28ca0.

Revert "Revert "[TFM Display] Add service that generates compatible frameworks. (#8869)""

---

src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Web.config

Last update of server common libs introduced assembly conflicts. Fixed it with latest libs.

Fix assembly warnings

---

src/AccountDeleter/EmptyFeatureFlagService.cs
src/GitHubVulnerabilities2Db/Fakes/FakeFeatureFlagService.cs
src/NuGetGallery.Services/Configuration/FeatureFlagService.cs
src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml
src/NuGetGallery/Web.config
src/VerifyMicrosoftPackage/Fakes/FakeFeatureFlagService.cs
tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs

Progress on NuGet/Engineering#4197

Add search heuristic based on package registration age

---

.github/ISSUE_TEMPLATE/NUGETORG_ISSUE.yml

Fix https://github.com/NuGet/NuGetGallery/issues/8944

Fix issue template links

---

.github/ISSUE_TEMPLATE/NUGETORG_ISSUE.yml

Part of https://github.com/NuGet/NuGetGallery/issues/8955

[ReleasePrep][2022.01.25]FI of main into dev

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-display-package-v2.less
src/Bootstrap/less/theme/page-display-package.less

https://github.com/NuGet/NuGetGallery/issues/8886 Prevent autoselection in command box so user can select parts he wants.

Allow user selection in install command

---

src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs

Raised the blocking period to 3 weeks.

Increase blocking time for search indexing

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/common-supported-frameworks.less

* Removed family-font on .framework class, so that css uses the default font.
Addresses: https://github.com/NuGet/Engineering/issues/4260.

[TFM Display] Fix font issue for safari.

---

tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs
tests/NuGetGallery.FunctionalTests/Commandline/NuGetCommandLineTests.cs
tests/NuGetGallery.FunctionalTests/Statistics/PackageStatisticsTests.cs

Improve inclusiveness of language used in code

Improve inclusiveness of language used in code

---

src/NuGetGallery.Services/Security/MicrosoftTeamSubscription.cs
src/VerifyMicrosoftPackage/README.md
tests/NuGetGallery.Facts/Security/MicrosoftTeamSubscriptionFacts.cs

Add more copy right string
Addresses https://github.com/NuGet/Engineering/issues/4308

[HotFix]Add copystring different language

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/common-readme.less

Addresses https://github.com/NuGet/NuGetGallery/issues/8505
before: 
after:

[README] Improve blockquote styling

---

src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs

Addresses https://github.com/NuGet/Engineering/issues/4350

Increase search engine indexing blocking duration to 90 days

---

src/Bootstrap/package-lock.json
src/Bootstrap/package.json

The lock file version was automatically updated by the tooling.
Switched to a maintained fork for grunt-postcss.

Resolve Bootstrap dependency alerts

---

src/DatabaseMigrationTools/DatabaseMigrationTools.csproj
src/NuGetGallery.Core/NuGetGallery.Core.csproj

Required for ESRP Submitter job.

Update server common libs to 2.100.0

---

src/DatabaseMigrationTools/DatabaseMigrationTools.csproj
src/NuGetGallery.Core/NuGetGallery.Core.csproj

I need to run DB migration on validation db in INT and PROD. Need to create a release from the main branch.

RI of dev to main

---

src/Bootstrap/dist/css/bootstrap-theme.css

Missed CSS update in the previous accessibility [fixes](https://github.com/NuGet/NuGetGallery/pull/9148).

Ran grunt after recent change to LESS files, to update actual used CSS

---

src/NuGetGallery/Views/Packages/ReportAbuse.cshtml
src/NuGetGallery/Views/Statistics/PackageDownloadsByVersion.cshtml
src/NuGetGallery/Views/Statistics/PackageDownloadsDetail.cshtml
src/NuGetGallery/Views/Statistics/PackageVersions.cshtml
src/NuGetGallery/Views/Statistics/Packages.cshtml
src/NuGetGallery/Views/Users/Profiles.cshtml

Add the `noindex` meta tag to the user profiles page (for locked users) and to the report abuse page and package statistics pages for all packages. 
Addresses https://github.com/NuGet/Engineering/issues/4457

Add noindex meta tag 

---

src/NuGetGallery/App_Start/AppActivator.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Views/Packages/Manage.cshtml
src/NuGetGallery/Views/Packages/UploadPackage.cshtml
tests/NuGetGallery.FunctionalTests/StaticAssets/StaticAssetsTests.cs

syntaxhighlight.js was added by changes https://github.com/NuGet/NuGetGallery/issues/8632
Need update the functional test
functional test: https://nuget.visualstudio.com/NuGetBuild/_build?definitionId=94&_a=summary

Bundle script for syntaxhighlight.js

---

.eslintignore
src/NuGetGallery/App_Start/AppActivator.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Scripts/gallery/moment-2.29.4.js
tests/NuGetGallery.FunctionalTests/StaticAssets/StaticAssetsTests.cs

moment.js 2.29.2 is being flagged by Dependabot and Component Governance.

Update to the latest version of moment.js to resolve CG

---

src/NuGetGallery/Telemetry/CustomerResourceIdEnricher.cs
tests/NuGetGallery.Facts/Telemetry/CustomerResourceIdEnricherFacts.cs

Progress on https://github.com/NuGet/Engineering/issues/4524.

Add a constant dimension to package push metrics

---

src/AccountDeleter/EmptyFeatureFlagService.cs
src/GitHubVulnerabilities2Db/Fakes/FakeFeatureFlagService.cs
src/NuGetGallery.Services/Configuration/FeatureFlagService.cs
src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs
src/NuGetGallery/App_Data/Files/Content/flags.json
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Filters/OptionalAccountConfirmationAttribute.cs
src/NuGetGallery/Filters/OptionalUIAuthorizeAttribute.cs
src/NuGetGallery/Filters/RequiresAccountConfirmationAttribute.cs
src/NuGetGallery/NuGetGallery.csproj
src/VerifyMicrosoftPackage/Fakes/FakeFeatureFlagService.cs

This will get us into the UploadPackage get action with a null user (at which point it will NRE).

[hackathon 2022] Add anon uploads feature flag support to packages controller

---

src/NuGetGallery/App_Code/ViewHelpers.cshtml

Changes: 
-[support more language for syntax highlighting (](https://github.com/NuGet/NuGetGallery/commit/a46fd29bf1d14230dcb4da234fccc03732538453)https://github.com/NuGet/NuGetGallery/pull/9232[)](https://github.com/NuGet/NuGetGallery/commit/a46fd29bf1d14230dcb4da234fccc03732538453)

[ReleasePrep][2022.09.21]FI of dev into main for NuGetGallery

---

src/NuGet.Services.Entities/Constants.cs
src/NuGet.Services.Entities/User.cs
src/NuGetGallery.Services/PackageManagement/PackageService.cs

Generates values for new columns for anonymous upload.

Adding ClaimKey and TemporaryId

---

src/NuGetGallery/Controllers/OrganizationsController.cs

Include email verification for new account. 
not necessary but it's ok to keep align
Addresses https://github.com/NuGet/NuGetGallery/issues/9258

Correct link for email of new account verification

---

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

Addresses: https://github.com/NuGet/NuGetGallery/issues/9288
@clairernovotny, I'd like your thoughts on this before merging.

Swap Package Manager and dotnet CLI tabs in display package UI

---

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml

Addresses https://github.com/NuGet/NuGetGallery/issues/9299

[A11y] Make aria-hidden elements not focusable

---

src/NuGetGallery/App_Data/Files/Content/Trusted-Image-Domains.json

Add image domain 'flat.badgen.net' to allowlist 
Addresses https://github.com/NuGet/NuGetGallery/issues/9307

Add domain flat.badgen.net

---

src/AccountDeleter/EmptyFeatureFlagService.cs
src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-list-packages.less
src/GitHubVulnerabilities2Db/Fakes/FakeFeatureFlagService.cs
src/NuGetGallery.Core/CredentialTypes.cs
src/NuGetGallery.Core/Frameworks/FrameworkCompatibilityService.cs
src/NuGetGallery.Core/Frameworks/SupportedFrameworks.cs
src/NuGetGallery.Services/Configuration/FeatureFlagService.cs
src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Controllers/PagesController.cs
src/NuGetGallery/Scripts/gallery/page-list-packages.js
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
src/NuGetGallery/UrlHelperExtensions.cs
src/NuGetGallery/Views/Shared/ListPackages.cshtml
src/VerifyMicrosoftPackage/Fakes/FakeFeatureFlagService.cs
tests/NuGetGallery.Core.Facts/Frameworks/FrameworkCompatibilityServiceFacts.cs
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
tests/NuGetGallery.Facts/Controllers/PagesControllerFacts.cs
tests/NuGetGallery.Facts/Services/PackageMetadataValidationServiceFacts.cs
tests/NuGetGallery.Facts/UrlHelperExtensionsFacts.cs

* https://github.com/NuGet/NuGetGallery/pull/9364 (tracked by https://github.com/NuGet/NuGetGallery/issues/9337)
* https://github.com/NuGet/NuGetGallery/pull/9358 (tracked by https://github.com/NuGet/NuGetGallery/issues/9359)
* https://github.com/NuGet/NuGetGallery/pull/9347 (tracked by https://github.com/NuGet/Engineering/issues/4669)
* https://github.com/NuGet/NuGetGallery/pull/9360 (tracked by https://github.com/NuGet/Engineering/issues/4762)
* https://github.com/NuGet/NuGetGallery/pull/9366
https://github.com/NuGet/NuGetGallery/issues/9381

[ReleasePrep][2023.02.08] RI of dev into main

---

src/NuGetGallery/App_Data/Files/Content/Trusted-Image-Domains.json

Addresses https://github.com/NuGet/NuGetGallery/issues/9330

add domain avatars.githubusercontent.com

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/base.less
src/Bootstrap/less/theme/common-supported-frameworks.less
src/NuGetGallery.Services/Authentication/Providers/AzureActiveDirectoryV2/AzureActiveDirectoryV2Authenticator.cs
src/NuGetGallery/App_Data/Files/Content/Trusted-Image-Domains.json
src/NuGetGallery/Content/fabric.css
src/NuGetGallery/Content/gallery/css/fabric.css
src/NuGetGallery/Controllers/AuthenticationController.cs
src/NuGetGallery/Filters/ValidateRecaptchaResponseAttribute.cs
src/NuGetGallery/Scripts/gallery/page-list-packages.js
src/NuGetGallery/Services/MarkdownService.cs
src/NuGetGallery/ViewModels/LogOnViewModel.cs
src/NuGetGallery/Views/Authentication/LinkExternal.cshtml
src/NuGetGallery/Views/Packages/_SupportedFrameworksTable.cshtml
src/NuGetGallery/Views/Shared/ListPackages.cshtml
src/NuGetGallery/Views/Shared/_ListPackage.cshtml
tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
tests/NuGetGallery.Facts/Services/MarkdownServiceFacts.cs

Addresses https://github.com/NuGet/Engineering/issues/4817

[ReleasePre][2023.03.28]FI of dev into main

---

src/NuGetGallery/Views/Organizations/_OrganizationAccountManageMembers.cshtml

Adds proper aria-labelling to the dropdowns on the Manage Organizations page.
Addresses https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1744545

[A11y][Organizations]Ensures select element has an accessible name

---

.github/ISSUE_TEMPLATE/config.yml
src/NuGetGallery/App_Data/Files/Content/Trusted-Image-Domains.json

Add wakatime.com domain to whitelisted domains

---

src/NuGetGallery/GalleryConstants.cs

NuGet.exe 6.6.0 was released. Updating Gallery to support it.

minClientVersion update

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/common-readme.less

render readme table more pretty with word warp setting.
[rec-screen (2).webm](https://github.com/NuGet/NuGetGallery/assets/64443925/bf9db3a6-3c6e-4bca-b857-c351f8fe0bdd)
Addresses https://github.com/NuGet/NuGetGallery/issues/9518

Readme table style

---

src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj
src/NuGet.Services.Entities/NuGet.Services.Entities.csproj
src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery.Services/NuGetGallery.Services.csproj
tests/NuGetGallery.FunctionalTests.Core/NuGetGallery.FunctionalTests.Core.csproj
tests/NuGetGallery.FunctionalTests/NuGetGallery.FunctionalTests.csproj

Updating NuGet.Protocol version.

---

src/DatabaseMigrationTools/DatabaseMigrationTools.csproj
src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj
src/NuGetGallery.Core/NuGetGallery.Core.csproj
src/NuGetGallery.Services/NuGetGallery.Services.csproj
src/NuGetGallery/NuGetGallery.csproj

Bringing in the lates changes from ServerCommon.

Updating to the latest servercommon

---

src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj
src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj
src/VerifyGitHubVulnerabilities/VerifyGitHubVulnerabilities.csproj

Wrapping up with propagating package updates from ServerCommon.

Updating NuGet.Jobs dependencies

---

src/NuGetGallery/Views/Users/PasswordChanged.cshtml

* Updated link to password login page.
Addresses: https://github.com/NuGet/NuGetGallery/issues/9467

Password reset redirects to password login page.

---

src/NuGetGallery.Core/Auditing/AuditedUserAction.cs
src/NuGetGallery/Areas/Admin/Controllers/ChangeUsernameController.cs
src/NuGetGallery/Areas/Admin/Models/ValidateAccountResult.cs
src/NuGetGallery/Areas/Admin/Models/ValidateUsernameResult.cs
src/NuGetGallery/Areas/Admin/Views/ChangeUsername/Index.cshtml
src/NuGetGallery/Areas/Admin/Views/Home/Index.cshtml
src/NuGetGallery/GalleryConstants.cs
src/NuGetGallery/NuGetGallery.csproj
tests/NuGetGallery.Core.Facts/Auditing/AuditedUserActionTests.cs
tests/NuGetGallery.Facts/Areas/Admin/Controllers/ChangeUsernameControllerFacts.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj

* Added Change Username admin panel.
* Added 2 helper forms.
* Verify account: Helps verifying SR information.
* Validate new username: Helps validating if the new username can be created.
* Added audit when a change username action is performed.
<details><summary>Admin panel</summary>
</details> 
<details><summary>Change username forms</summary>
</details> 
<details><summary>Verify account examples</summary>
Individual account
Organization account
</details> 
<details><summary>Validate new username</summary>
</details> 
<details><summary>Change username</summary>
</details> 
Addresses: https://github.com/NuGet/Engineering/issues/4883

[Admin] Added change username admin panel.

---

tests/NuGet.Services.DatabaseMigration.Facts/NuGet.Services.DatabaseMigration.Facts.csproj
tests/NuGetGallery.Facts/Areas/Admin/Controllers/ChangeUsernameControllerFacts.cs
tests/VerifyMicrosoftPackage.Facts/VerifyMicrosoftPackage.Facts.csproj

Added dispose for some tests.
Removed direct dependency on xunit.core, xunit brings what it wants [implicitly](https://www.nuget.org/packages/xunit#dependencies-body-tab).

Some build warnings addressed

---

src/Bootstrap/dist/css/bootstrap-theme.css

I didn't know that I was also supposed to add bootstrap-theme.css with my UI changes. Adding it now.

Added bootstrap file

---

src/NuGetGallery/Views/Shared/Gallery/Footer.cshtml

Addresses issue: https://github.com/NuGet/NuGetGallery/issues/9511
// cc @JonDouglas

Update FAQ link in footer

---

README.md
tests/README.md

Update directions for Visual Studio 2022

---

src/GalleryTools/Commands/ApplyTenantPolicyCommand.cs
src/NuGet.Services.DatabaseMigration/IMigrationContext.cs
src/NuGet.Services.Entities/Credential.cs
src/NuGetGallery.Core/Entities/EntitiesContext.cs
src/NuGetGallery.Services/Authentication/Providers/AzureActiveDirectory/AzureActiveDirectoryAuthenticator.cs
src/NuGetGallery.Services/Authentication/Providers/AzureActiveDirectory/AzureActiveDirectoryAuthenticatorConfiguration.cs
src/NuGetGallery.Services/Authentication/Providers/AzureActiveDirectoryV2/AzureActiveDirectoryV2Authenticator.cs
src/NuGetGallery.Services/Authentication/Providers/AzureActiveDirectoryV2/AzureActiveDirectoryV2AuthenticatorConfiguration.cs
src/NuGetGallery.Services/Configuration/AppConfiguration.cs
src/NuGetGallery.Services/Configuration/IAppConfiguration.cs
src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs
src/NuGetGallery.Services/ServicesStrings.Designer.cs
src/NuGetGallery.Services/ServicesStrings.resx
src/NuGetGallery.Services/SupportRequest/Models/SupportRequestDbContext.cs
src/NuGetGallery.Services/UserManagement/UserService.cs
src/NuGetGallery/Areas/Admin/Views/PasswordAuthentication/Index.cshtml
src/NuGetGallery/Controllers/AuthenticationController.cs
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
src/NuGetGallery/Views/Organizations/_OrganizationAccountManageMembers.cshtml
src/NuGetGallery/Views/Pages/Contact.cshtml
src/NuGetGallery/Views/Users/_UserAccountChangeExternalCredential.cshtml
src/VerifyGitHubVulnerabilities/README.md
tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
tests/NuGetGallery.Facts/Security/RequireOrganizationTenantPolicyFacts.cs

Change "Azure AD" to "Microsoft Entra ID"
Addresses https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1869215

Azure AD Rebranding

---

src/NuGetGallery/Views/Users/DeleteAccount.cshtml

It's not cohesive to read this text, improved it.

Improve text, fix typo

---

Directory.Build.props

Progress on https://github.com/NuGet/Engineering/issues/4992

Move to latest NuGet.Jobs packages to align with ServerCommon update

---

Directory.Build.props

update serverCommon and jobs align with ServerCommon updat
Addresses https://github.com/NuGet/Engineering/issues/4933

update serverCommon and jobs align with ServerCommon update

---

src/NuGetGallery/Areas/Admin/Controllers/CorrectIsLatestController.cs
src/NuGetGallery/Areas/Admin/Models/CorrectIsLatestPackage.cs
src/NuGetGallery/Areas/Admin/ViewModels/CorrectIsLatestRequest.cs
src/NuGetGallery/Areas/Admin/Views/CorrectIsLatest/Index.cshtml
src/NuGetGallery/Areas/Admin/Views/Home/Index.cshtml
src/NuGetGallery/NuGetGallery.csproj
tests/NuGetGallery.Facts/Areas/Admin/Controllers/CorrectIsLatestControllerFacts.cs
tests/NuGetGallery.Facts/Helpers/ReflowServiceSetupHelper.cs
tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
tests/NuGetGallery.Facts/Services/ReflowPackageServiceFacts.cs

* Added Correct IsLatest admin panel.
* Refactor reflow test utils.
[Correct IsLatest walkthrough](https://github.com/NuGet/NuGetGallery/assets/17834924/0d77ae77-c5ca-4363-afe9-967fcbb61e69)
Addresses https://github.com/NuGet/Engineering/issues/4880

[Admin] Correct IsLatest admin panel

---

Directory.Build.props
src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj
src/NuGet.Services.Entities/NuGet.Services.Entities.csproj
src/NuGetGallery/NuGetGallery.csproj

Resolve Security Vulnerability for System.Data.SqlClient 4.8.5
Addresses https://github.com/NuGet/Engineering/issues/5199

Update sql.client packages version

---

Directory.Build.props

Update the job.commons since we updated sql.client fix in nuget.jobs, here is related PR: https://github.com/NuGet/NuGet.Jobs/pull/1172
Addresses https://github.com/NuGet/Engineering/issues/5199

update job.common with security fix

---

Directory.Build.props
src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj
src/NuGet.Services.Entities/NuGet.Services.Entities.csproj
src/NuGetGallery/NuGetGallery.csproj

Deployment for System.data.SqlClient security vulnerability

[Release 1/25/2024] Gallery dev to main

---

src/AccountDeleter/EmptyFeatureFlagService.cs
src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-list-packages.less
src/GitHubVulnerabilities2Db/Fakes/FakeFeatureFlagService.cs
src/NuGetGallery.Core/Frameworks/IPackageFrameworkCompatibilityFactory.cs
src/NuGetGallery.Core/Frameworks/PackageFrameworkCompatibilityBadges.cs
src/NuGetGallery.Core/Frameworks/PackageFrameworkCompatibilityFactory.cs
src/NuGetGallery.Services/Configuration/FeatureFlagService.cs
src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs
src/NuGetGallery/App_Data/Files/Content/flags.json
src/NuGetGallery/Controllers/PackagesController.cs
src/NuGetGallery/Helpers/ViewModelExtensions/ListPackageItemViewModelFactory.cs
src/NuGetGallery/Infrastructure/Lucene/ExternalSearchService.cs
src/NuGetGallery/Infrastructure/Lucene/GallerySearchClient.cs
src/NuGetGallery/Infrastructure/Lucene/ISearchClient.cs
src/NuGetGallery/OData/SearchService/SearchAdaptor.cs
src/NuGetGallery/Scripts/gallery/page-list-packages.js
src/NuGetGallery/Services/SearchFilter.cs
src/NuGetGallery/Services/SearchSideBySideService.cs
src/NuGetGallery/UrlHelperExtensions.cs
src/NuGetGallery/ViewModels/PackageListSearchViewModel.cs
src/NuGetGallery/ViewModels/PackageListViewModel.cs
src/NuGetGallery/Views/Packages/_SupportedFrameworksBadges.cshtml
src/NuGetGallery/Views/Shared/ListPackages.cshtml
src/NuGetGallery/Views/Shared/_ListPackage.cshtml
src/VerifyMicrosoftPackage/Fakes/FakeFeatureFlagService.cs
tests/NuGetGallery.Core.Facts/Frameworks/PackageFrameworkCompatibilityFactoryFacts.cs
tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
tests/NuGetGallery.Facts/Infrastructure/Lucene/GallerySearchServiceFacts.cs
tests/NuGetGallery.Facts/Services/SearchAdaptorFacts.cs

Addresses https://github.com/NuGet/Engineering/issues/5171
This change adds 2 new framework filter options to the search page:
- **Include Computed Frameworks**
Checkbox that sets a boolean `true`/`false` value (default is `true`). When this is set to `false`, we filter packages only by their asset frameworks, and only show asset framework badges. When this is set to `true`, we filter packages by asset frameworks + computed frameworks, and we show both types of badges as well.
- **Framework Filter Mode**
Toggle that chooses between `All` and `Any` (default is `All`). This affects cases when multiple framework or TFM filters are selected. When this is set to `All`, we will show packages matching **all** the framework and TFM filters. If it is set to `Any`, we will show packages matching …

[Search-by-TFM] New Framework Filter Options UI

---

Directory.Build.props
src/VerifyGitHubVulnerabilities/Verify/PackageVulnerabilitiesVerifier.cs

Update package vulnerability.  
Addresses : https://github.com/NuGet/Engineering/issues/5251

update the NuGet package

---

src/NuGetGallery/Services/MarkdownService.cs

This is temporary solution; we are working on more robust solution meanwhile.
Test locally. 
Addresses: https://github.com/NuGet/Engineering/issues/5253

Disable javascript protocol on markdown render

---

src/NuGetGallery/Scripts/gallery/page-downloads.js
src/NuGetGallery/Views/Pages/Downloads.cshtml

This reverts commit acb9dab68e367b0caef379c0911fb4ed9aacc074.

Revert "Downloads page changed"

---

src/AccountDeleter/Scripts/Functions.ps1
src/AccountDeleter/Scripts/PostDeploy.ps1
src/GitHubVulnerabilities2Db/Scripts/Functions.ps1
src/GitHubVulnerabilities2Db/Scripts/PostDeploy.ps1
src/GitHubVulnerabilities2v3/Scripts/Functions.ps1
src/GitHubVulnerabilities2v3/Scripts/PostDeploy.ps1
src/VerifyGitHubVulnerabilities/Scripts/Functions.ps1
src/VerifyGitHubVulnerabilities/Scripts/PostDeploy.ps1

Removed unused username/password parameters

---

src/AccountDeleter/Scripts/Functions.ps1
src/AccountDeleter/Scripts/PostDeploy.ps1
src/GitHubVulnerabilities2Db/Scripts/Functions.ps1
src/GitHubVulnerabilities2Db/Scripts/PostDeploy.ps1
src/GitHubVulnerabilities2v3/Scripts/Functions.ps1
src/GitHubVulnerabilities2v3/Scripts/PostDeploy.ps1
src/NuGetGallery/Scripts/gallery/page-list-packages.js
src/NuGetGallery/Strings.Designer.cs
src/NuGetGallery/Strings.resx
src/NuGetGallery/Views/Packages/_SupportedFrameworksBadges.cshtml
src/NuGetGallery/Views/Shared/ListPackages.cshtml
src/VerifyGitHubVulnerabilities/Scripts/Functions.ps1
src/VerifyGitHubVulnerabilities/Scripts/PostDeploy.ps1

[ReleasePrep][2024.03.05]RI of dev into main

---

src/Bootstrap/dist/css/bootstrap.css
src/Bootstrap/less/alerts.less

Adding the new themes to the alert component, this PR only changes CSS files, actual usage of the component will be in future PR's. 
Addresses https://github.com/NuGet/NuGetGallery/issues/9862

[UI] Add new themes for Alert component

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/dist/css/bootstrap.css
src/Bootstrap/less/forms.less
src/Bootstrap/less/panels.less
src/Bootstrap/less/theme/base.less
src/Bootstrap/less/theme/modals.less
src/Bootstrap/less/theme/themes.less
src/NuGetGallery/App_Code/ViewHelpers.cshtml
src/NuGetGallery/Areas/Admin/Views/PackageOwnership/Index.cshtml
src/NuGetGallery/ExtensionMethods.cs
src/NuGetGallery/Scripts/gallery/common.js
src/NuGetGallery/Scripts/gallery/page-api-keys.js
src/NuGetGallery/Views/Authentication/_Register.cshtml
src/NuGetGallery/Views/Authentication/_SignIn.cshtml
src/NuGetGallery/Views/Authentication/_SigninAssistance.cshtml
src/NuGetGallery/Views/Packages/_ManageDeprecation.cshtml
src/NuGetGallery/Views/Shared/_SearchBar.cshtml
src/NuGetGallery/Views/Users/ApiKeys.cshtml
src/NuGetGallery/Views/Users/ForgotPassword.cshtml
src/NuGetGallery/Views/Users/TransformToOrganization.cshtml

These PR adds theme to the Input component as a new class named "input-brand".  For error's I changed the class to be "has-error-brand", it will change border color. 
| Light | Dark |
|---|---|
| ![image](https://github.com/NuGet/NuGetGallery/assets/43253759/744b29c7-dee2-4378-97f0-bec56a80a966) | ![image](https://github.com/NuGet/NuGetGallery/assets/43253759/c131d95c-d85d-4b37-b545-d19cc69ce917)|
| ![image](https://github.com/NuGet/NuGetGallery/assets/43253759/106bdad5-330c-46e2-9d09-6191a83c580d) | ![image](https://github.com/NuGet/NuGetGallery/assets/43253759/6b7878ac-4d9d-49ff-a426-59d517340902)|
Addresses https://github.com/NuGet/NuGetGallery/issues/9869
Addresses https://github.com/NuGet/NuGetGallery/issues/9868

[UI] Input component and Login pages

---

Directory.Build.props
tests/NuGetGallery.Core.Facts/Frameworks/PackageFrameworkCompatibilityFactoryFacts.cs

Addresses: https://github.com/NuGet/Engineering/issues/5250
Adding 2 new columns to persist extra details about scan operation

Add error code for ScanOperationStates table

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/dist/css/bootstrap.css
src/Bootstrap/less/buttons.less
src/Bootstrap/less/popovers.less
src/Bootstrap/less/theme/base.less
src/Bootstrap/less/theme/page-display-package.less
src/Bootstrap/less/type.less
src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
src/NuGetGallery/Views/Packages/_DisplayPackageDeprecation.cshtml
src/NuGetGallery/Views/Packages/_DisplayPackageRenames.cshtml
src/NuGetGallery/Views/Packages/_DisplayPackageVulnerabilities.cshtml

Addresses https://github.com/NuGet/NuGetGallery/issues/9880
This PR adds the theme to the Package page, it also adds styles for the Copy and Tabs components,

[UI] Package view page new theme

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/dist/css/bootstrap.css
src/Bootstrap/less/buttons.less
src/Bootstrap/less/forms.less
src/Bootstrap/less/tables.less
src/Bootstrap/less/theme/base.less
src/Bootstrap/less/theme/page-admin-index.less
src/Bootstrap/less/type.less
src/NuGetGallery/Areas/Admin/Views/ChangeUsername/Index.cshtml
src/NuGetGallery/Areas/Admin/Views/CorrectIsLatest/Index.cshtml
src/NuGetGallery/Areas/Admin/Views/Delete/Index.cshtml
src/NuGetGallery/Areas/Admin/Views/Delete/_ReflowBulk.cshtml
src/NuGetGallery/Areas/Admin/Views/Delete/_ReflowBulkConfirm.cshtml
src/NuGetGallery/Areas/Admin/Views/DeleteAccount/Index.cshtml
src/NuGetGallery/Areas/Admin/Views/DeleteAccount/_DeleteUserAccountForm.cshtml
src/NuGetGallery/Areas/Admin/Views/PackageOwnership/Index.cshtml
src/NuGetGallery/Areas/Admin/Views/PasswordAuthentication/Index.cshtml
src/NuGetGallery/Areas/Admin/Views/SecurityPolicy/Index.cshtml
src/NuGetGallery/Areas/Admin/Views/Shared/LockIndex.cshtml
src/NuGetGallery/Areas/Admin/Views/SiteAdmins/Index.cshtml
src/NuGetGallery/ExtensionMethods.cs
src/NuGetGallery/Views/Authentication/_SignIn.cshtml
src/NuGetGallery/Views/Shared/ListPackages.cshtml
src/NuGetGallery/Views/Shared/_DeletePackage.cshtml
src/NuGetGallery/Views/Users/_DeleteUserAccountForm.cshtml
src/NuGetGallery/Views/Users/_UserOrganizationsListForDeletedAccount.cshtml
src/NuGetGallery/Views/Users/_UserPackagesListForDeletedAccount.cshtml

Addresses https://github.com/NuGet/NuGetGallery/issues/9866
This PR adds the new theme to 3 Admin pages. **Lock Packages**, **Delete Packages** and **Change package ownership**. Error logs points to a different URL.
The select component has the same styles as the Input and TextArea components, the only problem with it is that the "dropdown" that the select generates cannot be styled since it's generated by the browser, but I was able to change the background of it, so it's still responds to the theme.
 
This PR also adds two new types of buttons, secondary and danger. 
<p float="left">
</p>
<p float="left">
</p>
<p float="left">
</p>
<p float="left">
</p>
<p float="left"> …

[UI] Add new theme to Admin pages (part 1)

---

src/NuGetGallery.Services/NuGetGallery.Services.csproj

Addresses https://github.com/NuGet/Engineering/issues/5237

Update Microsoft.IdentityModel.JsonWebTokens fix vulnerability.

---

src/NuGetGallery/Web.config

Similar to https://github.com/NuGet/NuGetGallery/pull/9597
We updated some packages recently, and need to update the assembly bindings in Web.config alongside that.
DEV release succeeded: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=1521319&_a=release-pipeline-progress

Fixing runtime issues because of assembly bindings

---

.pipelines/NuGetGallery-CI.yml

Progress on https://github.com/NuGet/Engineering/issues/5226
Storing CI pipeline in GH, so we don't have to invent anything with pipeline triggers.

CI pipeline

---

src/NuGetGallery/Views/Organizations/Add.cshtml
src/NuGetGallery/Views/Organizations/DeleteAccount.cshtml
src/NuGetGallery/Views/Organizations/ManageOrganization.cshtml
src/NuGetGallery/Views/Organizations/_OrganizationAccountManageMembers.cshtml

Adds new theme to Organization pages
Addresses https://github.com/NuGet/NuGetGallery/issues/9866
Most of the sections in this page are shared with Users pages

[UI] Add new themes to Organizations pages

---

src/NuGetGallery/Views/Packages/UploadPackage.cshtml
src/NuGetGallery/Views/Pages/About.cshtml

Remove aria-label and alt from links for bug # 1979902
Bug link:
https://devdiv.visualstudio.com/DevDiv/_queries/edit/?tempQueryId=86f20051-1835-446b-b283-b35a28cb6618&id=1979902

Fix Link Screen Reading Issue On Upload Package Page And About Page

---

Directory.Build.props

Merged this https://github.com/NuGet/NuGet.Jobs/pull/1198/commits
We need to flow stable version change to Gallery back due to circular dependency. Otherwise DB migration tool is failing due to dependency resolution problem.

Flow stable version change from NuGet.Jobs

---

src/NuGetGallery/Scripts/gallery/common.js

Emit telemetry when the user changes the theme using the select in Account Settings.
The event is going to look like this: 
Addresses https://github.com/NuGet/NuGetGallery/issues/9896

[Telemetry] Emit telemetry when Theme is changed.

---

.pipelines/NuGetGallery-CI.yml

Not really using any of those, so not producing them in the first place.

Not publishing unsigned artifacts.

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/dist/css/bootstrap.css
src/Bootstrap/less/buttons.less
src/Bootstrap/less/forms.less
src/Bootstrap/less/theme/base.less
src/Bootstrap/less/theme/page-admin-index.less
src/Bootstrap/less/theme/page-api-keys.less
src/Bootstrap/less/theme/page-delete-package.less
src/Bootstrap/less/theme/page-downloads.less
src/Bootstrap/less/theme/page-manage-owners.less
src/Bootstrap/less/theme/page-manage-packages.less
src/Bootstrap/less/theme/page-sign-in.less
src/Bootstrap/less/theme/themes.less
src/Bootstrap/less/variables.less
src/NuGetGallery/ExtensionMethods.cs
src/NuGetGallery/Views/Packages/ReportMyPackage.cshtml
src/NuGetGallery/Views/Pages/Contact.cshtml
src/NuGetGallery/Views/Pages/_Enable2FA.cshtml
src/NuGetGallery/Views/Pages/_TransformOrLink.cshtml
src/NuGetGallery/Views/Users/ApiKeys.cshtml
src/NuGetGallery/Views/Users/Organizations.cshtml
src/NuGetGallery/Views/Users/Packages.cshtml
src/NuGetGallery/Views/Users/ResetPassword.cshtml
src/NuGetGallery/Views/Users/TransformToOrganization.cshtml
src/NuGetGallery/Views/Users/_UserAccountChangeExternalCredential.cshtml
src/NuGetGallery/Views/Users/_UserAccountChangePassword.cshtml
src/NuGetGallery/Views/Users/_UserAccountLinkExternalCredential.cshtml

Adds new styles to User pages.
Addresses https://github.com/NuGet/NuGetGallery/issues/9865 and  https://devdiv.visualstudio.com/DevDiv/_queries/edit/?tempQueryId=86f20051-1835-446b-b283-b35a28cb6618&id=1985625

[UI] Add new themes to User pages

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-edit-package.less
src/Bootstrap/less/theme/page-upload.less
src/NuGetGallery/Views/Experiments/SearchSideBySide.cshtml
src/NuGetGallery/Views/Packages/ContactOwners.cshtml
src/NuGetGallery/Views/Packages/DeleteSymbols.cshtml
src/NuGetGallery/Views/Packages/ReportAbuse.cshtml
src/NuGetGallery/Views/Packages/ReportMyPackage.cshtml
src/NuGetGallery/Views/Packages/UploadPackage.cshtml
src/NuGetGallery/Views/Packages/_EditForm.cshtml
src/NuGetGallery/Views/Packages/_ImportReadMe.cshtml
src/NuGetGallery/Views/Packages/_ManageDeprecation.cshtml
src/NuGetGallery/Views/Packages/_ManageDocumentation.cshtml
src/NuGetGallery/Views/Packages/_ManageListing.cshtml
src/NuGetGallery/Views/Packages/_ManageOwners.cshtml
src/NuGetGallery/Views/Packages/_VerifyForm.cshtml
src/NuGetGallery/Views/Packages/_VerifyMetadata.cshtml

Adds new styles to Package pages.
Addresses https://github.com/NuGet/NuGetGallery/issues/9880
** Adding screenshots asap

[UI] Add new themes to Packages pages

---

src/Bootstrap/dist/css/bootstrap-theme.css
src/Bootstrap/less/theme/page-statistics-most-downloaded.less
src/Bootstrap/less/theme/page-statistics-overview.less
src/NuGetGallery/Views/Statistics/Index.cshtml
src/NuGetGallery/Views/Statistics/PackageVersions.cshtml
src/NuGetGallery/Views/Statistics/Packages.cshtml

Make the tables scrollable, remove all the css making the text  truncated. 
Bug link:
https://devdiv.visualstudio.com/DevDiv/_queries/edit/?tempQueryId=86f20051-1835-446b-b283-b35a28cb6618&id=1980703
https://devdiv.visualstudio.com/DevDiv/_queries/edit/?tempQueryId=86f20051-1835-446b-b283-b35a28cb6618&id=1980707

Solve Table Text Getting Truncated Issue

---

src/NuGetGallery/Views/Authentication/_Register.cshtml
src/NuGetGallery/Views/Experiments/SearchSideBySide.cshtml
src/NuGetGallery/Views/Shared/Gallery/Footer.cshtml

Ask from Privacy Review: change the link on the Nuget.org site from "Privacy Policy" to be instead "Privacy Statement" per the Microsoft guidelines (guidance is on this page - https://microsoft.sharepoint.com/sites/privacy/SitePages/Privacy-Statement.aspx)
Helps with https://github.com/NuGet/Engineering/issues/5267

Ask from Privacy Review: Update "Privacy Policy" to be instead "Privacy Statement"

---

src/NuGetGallery/App_Data/Files/Content/Trusted-Image-Domains.json

Allow images from infragistics.com

---

tests/NuGetGallery.Facts/TestData/TestDataResourceUtility.cs

remove TestDataResourceUtility.GetResourceString

---

src/NuGetGallery/Views/Shared/ListPackages.cshtml

* Add button role to tooltip target
* Fix tooltip popup issue
* Remove link from tooltip
Bug URLs: 
1. https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2089796
2. https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2089795
3. https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2087140
4. https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2087164/?view=edit

Fixed tooltip layout

---

build.ps1

This does not change behavior, just brings alignment.

Move to latest ServerCommon build tools

---

src/NuGet.Services.AzureSearch/BlobContainerBuilder.cs
tests/NuGet.Services.AzureSearch.Tests/IndexBuilderFacts.cs

Progress on https://github.com/NuGet/Engineering/issues/5576

Disable public blob access on search containers

---

src/NuGet.Jobs.Catalog2Registration/DependencyInjectionExtensions.cs
src/NuGet.Jobs.Common/JsonConfigurationJob.cs
src/NuGet.Jobs.Common/StorageAccountExtensions.cs
src/NuGet.Jobs.Common/StorageMsiConfiguration.cs
src/NuGet.Jobs.GitHubIndexer/Job.cs
src/NuGet.Services.AzureSearch/DependencyInjectionExtensions.cs
src/NuGet.Services.Validation.Orchestrator/Job.cs
src/Validation.Common.Job/Leases/CloudBlobLeaseService.cs
src/Validation.Common.Job/ValidationJobBase.cs
src/Validation.Symbols/Job.cs

This is @agr's latest work on the job base types supporting MSIs for storage account access. Tested via other changes as discussed offline.

Job base classes MSI support

---

src/NuGet.Jobs.Common/StorageAccountExtensions.cs

Some follow-up work from https://github.com/NuGet/NuGetGallery/pull/10153

Add fall back option if Storage MSI isn't specified

---

src/NuGet.Services.Licenses/NuGet.Services.Licenses.csproj

Part of https://github.com/NuGet/Engineering/issues/5532
Missed in https://github.com/NuGet/NuGetGallery/pull/10098

Update System.Formats.Asn1 package

---

src/NuGet.Services.Storage/AzureStorage.cs
src/Validation.PackageSigning.ProcessSignature/Job.cs
src/Validation.PackageSigning.ValidateCertificate/Job.cs

Updates to ValidateCertificate and ProcessSignature to use new SDK stuff and support ManagedIdentity authenciation.

[NewSDK]Update ValidateCertificate and ProcessSignature for new SDK

---

src/AccountDeleter/app.config
src/NuGetGallery.Core/Services/CloudBlobClientWrapper.cs

Cherrypicking this commit to unblock us in DEV/INT.
@drewgillies please be aware of this when the feature branch gets merged in.

Additional config changes to support AccountDeleter migration (#10180)

---

src/NuGet.Services.Sql/README.md

Ran into an issue using the library in app service, added workaround information.

Create README.md for NuGet.Services.Sql

---

src/GitHubVulnerabilities2Db/Job.cs

Addresses: https://github.com/NuGet/Engineering/issues/5568

Use MSI for storage access in GitHubVulnerabilities2Db

---

src/NuGetGallery/Scripts/gallery/jquery-ui-1.10.3.js

Addresses: https://github.com/NuGet/Engineering/issues/5661
Solution copied from: https://github.com/jquery/jquery-ui/commit/afe20b79a64266e64011f34b26a30b3d1c62fd47#diff-9fe9167f897d640e82537adc5391958ffe6284b413a08152cd31d061e97a644aL243

Use user-provided data correctly

---

src/NuGetGallery/Web.config

Fix runtime assembly binding conflicts

Fix assembly bindings

---

src/NuGetGallery/Controllers/ApiController.cs
src/NuGetGallery/Controllers/AuthenticationController.cs

Following guidance provided in: https://aka.ms/codeql#guidance-on-suppressions

CodeQL suppressions + suppression fixes

---

src/NuGetGallery/Web.config

Need to fix binding redirect for https://github.com/NuGet/NuGetGallery/pull/10211

Update System.Text.Json binding redirect

---

src/NuGetGallery/App_Start/DefaultDependenciesModule.cs

Thanks for the recommendation, @jimmylewis!
This improves on top of https://github.com/NuGet/NuGetGallery/pull/10229 and is clean-up I found while working on https://github.com/NuGet/NuGetGallery/issues/10212.

Use discard _ for fire and forget task

---

src/NuGetGallery.Services/Authentication/ApiKeyV4.cs

Reverts NuGet/NuGetGallery#10234.
This place needs to be updated first to detect the new format:
https://github.com/microsoft/security-utilities/blob/dd491f725a22796e25b52ccb677d305558793f29/src/Microsoft.Security.Utilities.Core/PreciselyClassifiedSecurityKeys/SEC101_030_NuGetApiKey.cs#L15

Revert "Improve API key v4 implementation based on internal feedback"

---

src/NuGetGallery/Services/PackageDeprecationManagementService.cs
tests/NuGetGallery.Facts/Services/PackageDeprecationManagementServiceFacts.cs

Resolve https://github.com/NuGet/NuGetGallery/issues/10242

Package deprecation should be case insensitive on version

---

src/NuGet.Services.KeyVault/NuGet.Services.KeyVault.csproj
src/NuGet.Services.Messaging.Email/NuGet.Services.Messaging.Email.csproj
src/NuGet.Services.Messaging/NuGet.Services.Messaging.csproj
src/NuGet.Services.ServiceBus/NuGet.Services.ServiceBus.csproj
src/NuGet.Services.Validation/NuGet.Services.Validation.csproj

Related to https://github.com/NuGet/Engineering/issues/5546
There're some transitive vulnerable versions are still coming from Azure.Core

Address transitive azure.core CG

---

src/ArchivePackages/ArchivePackages.Job.cs

Addresses: https://github.com/NuGet/Engineering/issues/5441
I took the opportunity to make this code consistent with like types (style, etc.). Essentially the logic flow is untouched, but some methods consumed here needed updates to parameters.

Migrate ArchivePackages to using MSI for storage access

---

Directory.Packages.props
NuGet.config
sign.thirdparty.props
src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
src/NuGetGallery/NuGetGallery.csproj
src/NuGetGallery/Services/MarkdownService.cs
src/NuGetGallery/Web.config
tests/NuGetGallery.Facts/Services/MarkdownServiceFacts.cs

Already deployed to production. 
Merge to production to create release package for security advisory

[MR] markdown render with html sanitizer

---

src/NuGetGallery/App_Code/ViewHelpers.cshtml

Needed for CDN update. See microsoft/ApplicationInsights-JS#2457 for full details.

Change references of “az416426.vo.msecndnet” to “js.monitor.azure.com”

---

src/NuGet.Services.Cursor/NuGet.Services.Cursor.csproj
src/NuGet.Services.KeyVault/NuGet.Services.KeyVault.csproj
src/NuGet.Services.ServiceBus/NuGet.Services.ServiceBus.csproj
src/NuGet.Services.Status.Table/NuGet.Services.Status.Table.csproj
src/NuGet.Services.Storage/NuGet.Services.Storage.csproj
src/NuGet.Services.Validation/NuGet.Services.Validation.csproj
src/NuGetGallery.Core/NuGetGallery.Core.csproj

Fixes: https://github.com/NuGet/Engineering/issues/5545
New transitive dependency triggered CG again in release pipeline.

Fix transitive System.text.json CG warning

---

src/NuGetGallery/Views/Organizations/_OrganizationAccountManageMembers.cshtml

Addresses https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2397626
Updates the aria-label on the member roles dropdown from "Role Filter" to "Add Member Role" to align with the visual labelling.

[A11y] Align Aria-Label on Adding member roles to organization with the visual label

---

python/StatsLogParser/pyproject.toml

Follow-up for https://github.com/NuGet/NuGetGallery/pull/10350.
Bumping the python package version since the code was updated.

Bumping package version

---

tests/NuGetGallery.FunctionalTests/Security/HttpToHttpsRedirectTests.cs
tests/Scripts/Import-GalleryConfiguration.ps1
tests/Scripts/RunFunctionalTestsLocally.ps1
tests/Scripts/TestUtilities.psm1

Not really part of NuGet protocol, has issues with AFD.
Also added script to run functional tests locally.

Disabling TRACE method functional tests

---

src/NuGetGallery/Scripts/gallery/async-file-upload.js

1. Remove add/remove "hidden" class function for the submit buttoncontainer,  make the submit button show all the time.
2. Bug link: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2417390
3. Result:
https://github.com/user-attachments/assets/320cd9c1-d1a7-4085-86e5-0178eba0f1fd

Remove package upload submit dropdown

---

src/NuGetGallery/Views/Users/Profiles.cshtml

Add the administration counter and collaborator counter to aria label at member profile section.
Bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2417393
result:
Screenshot:
Screen reader:
https://github.com/user-attachments/assets/4aa16ef1-2264-4b3d-86b1-832555549894

Change profile section aria label

---

src/NuGet.Services.AzureSearch/AzureSearchTelemetryService.cs
src/NuGet.Services.AzureSearch/BatchPusher.cs
src/NuGet.Services.AzureSearch/IAzureSearchTelemetryService.cs
src/NuGet.Services.AzureSearch/Wrappers/ISearchClientWrapper.cs
src/NuGet.Services.AzureSearch/Wrappers/SearchClientWrapper.cs
tests/NuGet.Services.AzureSearch.Tests/Auxiliary2AzureSearch/Integration/PopularityTransferIntegrationTests.cs
tests/NuGet.Services.AzureSearch.Tests/BatchPusherFacts.cs
tests/NuGet.Services.AzureSearch.Tests/Catalog2AzureSearch/Integration/InMemorySearchClient.cs

This should help investigating on https://github.com/NuGet/Engineering/issues/5075, so we can share the related request IDs with the Azure Search team.

Log the Azure search request-id to help future debugging

---

.github/copilot-instructions.md

The latest version of Visual Studio 2022 allows repo-specific Copilot instructions to better guide AI (LLM) generated code to be more compatible with existing code and follow the same coding pattern, improve code quality. I created this instruction based on https://github.com/dotnet/android/blob/main/.github/copilot-instructions.md and our existing repo-specific documentations. 
I tested it with prompts to add new services and a few unit test mocks, and it seems to work very well.
We could start with one and improve on it later.
For example:
`prompt: Add new service that reject all the packages don't have proper size logo image`
`prompt: Add missing unit test for this code`
```
using System;
using System.IO;
using System.Threading.Tasks;
using Moq;
using NuGet.Packaging;
using …
```

Add copilot instructions for Visual Studio

---

src/Bootstrap/package.json

Update NPM package IP to 2.0.1 
ip (
[npm](https://github.com/advisories?query=ecosystem%3Anpm)
)
Affected versions
= 2.0.0
< 1.1.9
Patched versions
2.0.1
1.1.9
Addresses https://github.com/NuGet/Engineering/issues/5873

update IP package version

---

src/Gallery.Maintenance/DeleteExpiredApiKeysTask.cs
src/Gallery.Maintenance/Models/ApiKey.cs

Delete the expired key by Gallery.Maintenance.

[OIDC] API Key v5 - 5: Delete the expired key.

---

RemovedPackages.md

Add NethereumNet to removed packages list

Add NethereumNet to removed packages list
