src/AccountDeleter/Configuration/GalleryConfiguration.cs, src/NuGetGallery.Services/Configuration/AppConfiguration.cs, src/NuGetGallery.Services/Configuration/IAppConfiguration.cs, src/NuGetGallery/Controllers/AuthenticationController.cs, src/NuGetGallery/Strings.Designer.cs, src/NuGetGallery/Strings.resx, src/NuGetGallery/Web.config, tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
As part of getting rid of old AAD/MSA configs, we want to bolster the site admin check. https://github.com/NuGet/Engineering/issues/2567
This PR needs the new configs, will send that PR out separately.
=> Add site admin check for tenant

tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
Address https://github.com/NuGet/Engineering/issues/2499
Sorry @xavierdecoster. Should we move our CIs to CET 😄? Seems like the negative offsets from the prime meridian are a great edge case for our tests.
=> Fix timezone issues

.github/CODEOWNERS
* Scott was a fan of our code owners file on client side. 
https://github.com/NuGet/NuGet.Client/blob/dev/.github/CODEOWNERS
I think server gallery should have it as well :) 
Example: https://github.com/NuGet/NuGet.Client/pull/3053
Look at the key near most of the names in the reviewers :) 
//cc @scottbommarito
=> Add codeowners for the NuGetGallery repo to get reviews requested automatically

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/905742
Although we are compliant with `aria-label` alone, according to one of our accessibility contacts, we should add `abbr` as well.
=> Add abbr tags to hidden column headers in display package version history table

src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs, tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceFacts.cs, tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceIntegrationTests.cs
Gallery.Core uses the SHA512 for copy checks. 
Towards fixing MD5 task:
NuGet/Engineering#2377
NuGet/Engineering#2672
The integration test has covered the tests for this change.
=> [SDL] Gallery.Core uses the SHA512 for copy checks. 

src/NuGetGallery.Services/Telemetry/UserPackageDeleteEvent.cs, src/NuGetGallery/Controllers/StatisticsController.cs, src/NuGetGallery/Services/JsonStatisticsService.cs, src/NuGetGallery/ViewModels/StatisticsFact.cs, src/NuGetGallery/ViewModels/StatisticsNuGetUsageItem.cs, src/NuGetGallery/ViewModels/StatisticsPackagesItemViewModel.cs, src/NuGetGallery/ViewModels/StatisticsPackagesReport.cs, src/NuGetGallery/ViewModels/StatisticsPackagesViewModel.cs, src/NuGetGallery/ViewModels/StatisticsPivot.cs, src/NuGetGallery/ViewModels/StatisticsWeeklyUsageItem.cs, src/NuGetGallery/Views/Statistics/Index.cshtml, tests/NuGetGallery.Facts/Controllers/StatisticsControllerFacts.cs
https://github.com/NuGet/NuGetGallery/issues/7543
Tested locally against stats files with 1 trillion downloads and works great.
=> Hotfix: Stats index page should not use integers to store download counts

src/NuGetGallery.Services/Authentication/Providers/AzureActiveDirectoryV2/AzureActiveDirectoryV2Authenticator.cs, tests/NuGetGallery.Facts/Authentication/Providers/CommonAuth/AzureActiveDirectoryV2AuthenticatorFacts.cs
Addresses: https://github.com/NuGet/NuGetGallery/issues/7324 
Earlier we were using `preferred_username` claim as the email, from my initial observations it was working fine. However, for certain accounts(skype account used as MSA) the `preferred_username` returns the handle rather than email. This fix addresses the bug and also keeps consistent with the expected claims.
=> [MSA] Use EmailClaim instead of preferred_username during auth/register

src/NuGetGallery.Services/PackageManagement/PackageUpdateService.cs, tests/NuGetGallery.Facts/Services/PackageUpdateServiceFacts.cs
https://github.com/NuGet/NuGetGallery/issues/7536
Relisting a package properly resets the latest state of the package, so any packages that are unlisted and marked latest will be fixed. By throwing here, we are making it so that users cannot fix the data issue they have.
=> Do not throw if trying to list an unlisted package that is marked latest

src/NuGetGallery/Helpers/ViewModelExtensions/DisplayPackageViewModelFactory.cs, src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
With this change, the donet CLI template packages will show the `dotnet-new-install` command.
Addresses https://github.com/NuGet/NuGetGallery/issues/5216
=> Render dotnet-new-install for template packages

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/common-edit-metadata.less
As suggested in the issue, this should solve the bug. Not sure if I found the correct location for this less changes. 
* Added a new less rule to display multiline in a correct way
* The CSS is should only affect the verify package site.
* Didn't found any other CSS/LESS stuff, so I used the "common-edit-metadata.less" file. 
Works in more or less all modern browsers :)
Addresses https://github.com/NuGet/NuGetGallery/issues/6622
=> Fix #6622 via CSS (multiline on verify page)

src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Services/IconUrlDeprecationValidationMessage.cs, src/NuGetGallery/Services/PackageUploadService.cs, src/NuGetGallery/Strings.Designer.cs, src/NuGetGallery/Strings.resx, tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs
Addresses https://github.com/NuGet/NuGetGallery/issues/7478
Browser:
Command line:
=> IconUrl deprecation message.

src/NuGetGallery.Services/NuGetGallery.Services.csproj, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Telemetry/ClientInformationTelemetryEnricher.cs, src/NuGetGallery/Telemetry/DeploymentIdTelemetryEnricher.cs, src/NuGetGallery/Web.config, tests/NuGetGallery.Facts/Telemetry/ClientInformationTelemetryEnricherTests.cs, tests/NuGetGallery.Facts/Telemetry/DeploymentIdTelemetryEnricherFacts.cs
This upgrades NuGetGallery to v2.10 of Application Insights.
Addresses https://github.com/NuGet/Engineering/issues/2537
Todo:
=> Upgrade to AppInsights v2.10

src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/Helpers/ViewModelExtensions/DeletePackageViewModelFactory.cs, src/NuGetGallery/Helpers/ViewModelExtensions/DisplayPackageViewModelFactory.cs, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Scripts/gallery/page-edit-readme.js, src/NuGetGallery/Services/IReadMeService.cs, src/NuGetGallery/Services/ReadMeService.cs, src/NuGetGallery/Services/RenderedReadMeResult.cs, src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, src/NuGetGallery/Views/Packages/_ImportReadMe.cshtml, tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs, tests/NuGetGallery.Facts/Services/ReadMeServiceFacts.cs, tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs
We introduced a change that causes http images in readme files to be rewritten using https.
This change alerts an owner when their documentation contains an image that causes this to happen, both at edit time, and on package details page.
Introduces compound return type from readme service.
=> Warn owners when ReadMe contains images that would be rewritten

src/NuGetGallery/Telemetry/ClientTelemetryPIIProcessor.cs, tests/NuGetGallery.Facts/Telemetry/ClientTelemetryPIIProcessorTests.cs
Fixes `NullReferenceException` introduced by AI's new intermediate request support that causes `RequestTelemetry.Url` to be `null`.
```
Value cannot be null. Parameter name: uri 
System.ArgumentNullExceptionValue cannot be null. Parameter name: uri
System.ArgumentNullException: Value cannot be null.
Parameter name: uri
at NuGetGallery.RouteExtensions.ObfuscateUrlQuery(Uri uri, ObfuscatedQueryMetadata[] metadata) in E:\A\_work\2455\s\src\Gallery\submodules\Gallery\src\NuGetGallery\Extensions\RouteExtensions.cs:line 105
at NuGetGallery.ClientTelemetryPIIProcessor.ModifyItem(ITelemetry item) in E:\A\_work\2455\s\src\Gallery\submodules\Gallery\src\NuGetGallery\Telemetry\ClientTelemetryPIIProcessor.cs:line 52
at NuGetGallery.ClientTelemetryPIIProcessor.Process(ITelemetry item) in …
```
=> Handle RequestTelemetry.Url == null (AI intermediate requests)

src/NuGetGallery.Services/Authentication/Providers/AzureActiveDirectoryV2/AzureActiveDirectoryV2Authenticator.cs, tests/NuGetGallery.Facts/Authentication/Providers/CommonAuth/AzureActiveDirectoryV2AuthenticatorFacts.cs
The fix for the https://github.com/NuGet/NuGetGallery/issues/7324 regressed the behavior for certain AAD logins. For some AAD tenants, the `EmailClaim` is null. In such scenarios `preferred_username` claim seems to have been giving us the correct data, which is what we were using previously.
=> [Hotfix] Fix AAD login issues for some tenants.

src/NuGetGallery/Services/PackageUploadService.cs, tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs
Addresses https://github.com/NuGet/NuGetGallery/issues/7605.
=> Fix for iconUrl deprecation message appearing for packages without any icon

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/base.less, src/NuGet.Services.Entities/Certificate.cs, src/NuGetGallery/Helpers/ViewModelExtensions/ListPackageItemViewModelFactory.cs, src/NuGetGallery/Services/CertificateService.cs, src/NuGetGallery/ViewModels/ListCertificateItemViewModel.cs, src/NuGetGallery/ViewModels/ListPackageItemViewModel.cs, src/NuGetGallery/Views/Shared/_AccountCertificates.cshtml, tests/NuGetGallery.Facts/Controllers/OrganizationsControllerFacts.cs, tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs, tests/NuGetGallery.Facts/Services/CertificateServiceFacts.cs, tests/NuGetGallery.Facts/ViewModels/ListCertificateItemViewModelFacts.cs, tests/NuGetGallery.Facts/ViewModels/ListPackageItemViewModelFacts.cs
Address https://github.com/NuGet/Engineering/issues/2758.
In general we are avoiding the use of SHA-1 anyway as a cleanliness practice. SHA-256 or greater is the hash algorithm recommendation.
=> Display SHA-256 instead of SHA-1 for user certificates

src/NuGetGallery.Core/Auditing/AuditedUserAction.cs, src/NuGetGallery.Core/Auditing/CredentialAuditRecord.cs, src/NuGetGallery.Services/Authentication/AuthenticationService.cs, tests/NuGetGallery.Core.Facts/Auditing/AuditedUserActionTests.cs, tests/NuGetGallery.Core.Facts/Auditing/CredentialAuditRecordTests.cs
We need to audit the credential which was used to attempt to login in the gallery before it was identified and authorized(from DB). This is necessary for retrospective analysis. Also, log the `Tenant Id` and `OID` used with the external credential.
This depends on the shims changes.
Addresses: https://github.com/NuGet/Engineering/issues/2652
=> [MSA] Audit the external credential for attempted login in Gallery

src/NuGetGallery.Core/NuGetGallery.Core.csproj, src/NuGetGallery.Core/Services/BlobResultSegmentWrapper.cs, src/NuGetGallery.Core/Services/CloudBlobContainerWrapper.cs, src/NuGetGallery.Core/Services/CloudBlobWrapper.cs, src/NuGetGallery.Core/Services/ICloudBlobContainer.cs, src/NuGetGallery.Core/Services/ISimpleBlobResultSegment.cs, src/NuGetGallery.Core/Services/ISimpleCloudBlob.cs, tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceIntegrationTests.cs, tests/NuGetGallery.Core.Facts/TestUtils/BlobStorageFixture.cs
Add Azure Blob Storage enumeration and snapshot APIs.
This allows applications using the gallery-based storage abstractions to take snapshots of blobs if they one does not exist, which is a behavior supported by the V3 (NuGet.Services.Metadata) storage abstractions.
In particular, I am working on rewriting Catalog2Registration and I am aligning on the gallery storage abstractions. Current Catalog2Registration uses the V3 storage abstractions and ensures every blob has at least one snapshot to mitigate accidental deletion. In general the NuGetGallery.Core storage abstractions (`ISimpleCloudBlob` and friends) are better for mocking because they more closely match the shape of the underlying Azure Storage APIs. Many non-gallery jobs already use the gallery storage abstractions: Azure Search, …
=> Add storage abstractions for list and snapshots

src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj
Missed this when I added the job.
=> GitHubVulnerabilities2Db should sign third-party assemblies

src/NuGetGallery/Views/Users/Organizations.cshtml
I was browsing through the NuGet UI and notices a UI glitch on the organization page:
The "divider" is using the "ms-font-xxl", which enlarges the complete navigation bread crumb area. With a smaller version it keeps the same size as similar pages. 
Be aware:
There are (at least) two other pages with this xxl dividers, but they have some other controls on the same line, so... it would be more complicated to fix those.
Hope this helps :)
=> Removes the height differences when switching to the organization page

src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.nuspec
When I made it, I copied the nuspec from NuGet.Jobs instead of the nuspec from AccountDeleter, so it had the wrong `bin` path.
Succeeded with this fix at https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3212606
=> Fix nuspec for GitHubVulnerabilities2Db

src/NuGetGallery/Controllers/ManageDeprecationJsonApiController.cs, src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/Views/Packages/Manage.cshtml, tests/NuGetGallery.Facts/Controllers/ManageDeprecationJsonApiControllerFacts.cs, tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
https://github.com/nuget/nugetgallery/issues/7567
https://github.com/nuget/nugetgallery/issues/7495
Currently, when you submit a form on the Manage Package page (Deprecation, Listing, Documentation) you are linked back to the package details page. This is annoying when you are trying to do other management operations at the same time.
This changes it so that submitting the forms stays on the Manage Package page. Additionally, I added "TempData" messages so that it's clearer what operation was performed.
=> Manage Package page forms should link back to the Manage page

src/NuGetGallery/ViewModels/UserProfileModel.cs, src/NuGetGallery/Views/Users/Profiles.cshtml
=> Allow admins to see users' MFA setting on profile page

src/NuGetGallery.Services/Configuration/FeatureFlagService.cs, src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs, src/NuGetGallery.Services/Configuration/IODataCacheConfiguration.cs, src/NuGetGallery.Services/Configuration/ODataCacheConfiguration.cs, src/NuGetGallery.Services/NuGetGallery.Services.csproj, src/NuGetGallery.Services/ServicesConstants.cs, src/NuGetGallery.Services/Storage/ContentObjectService.cs, src/NuGetGallery.Services/Storage/IContentObjectService.cs, src/NuGetGallery/App_Data/Files/Content/OData-Cache-Configuration.json, src/NuGetGallery/App_Data/Files/Content/flags.json, src/NuGetGallery/App_Start/NuGetODataConfig.cs, src/NuGetGallery/Controllers/ODataV1FeedController.cs, src/NuGetGallery/Controllers/ODataV2CuratedFeedController.cs, src/NuGetGallery/Controllers/ODataV2FeedController.cs, src/NuGetGallery/Infrastructure/ODataCacheOutputAttribute.cs, src/NuGetGallery/Infrastructure/ODataCachedEndpoint.cs, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Web.config, tests/NuGetGallery.Facts/Infrastructure/ODataCacheOutputAttributeFacts.cs, tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
Progress on https://github.com/NuGet/Engineering/issues/2773#issuecomment-551338259.
This introduces a feature flag and JSON configuration file to manipulating cache duration on OData endpoints.
My plan is to ship this to PROD and take the following steps:
1. Bring FindPackagesById/$count caching up to 60 seconds (to match with the non-count endpoint).
- Wait 1 full business day
1. Bring Increase FindPackagesById and FindPackageById/$count caching up to 120 seconds
- Wait 1 full business day
1. ... repeat until duration is 5 minutes
1. Wait 7 days and closely observe memory and search service impact (i.e. cache "misses").
- Memory should not go out of control and cache misses should decrease
This is the state of cache durations today:
Endpoint | Controller | Cache Duration (seconds)
-- | …
=> Make server-side OData cache configurable

test.ps1, tools/Setup-DevEnvironment.ps1, tools/Update-Databases.ps1
This addresses a breaking change introduced in 6.3.0 which eliminates migrate.exe and replaces it with ef6.exe.
Address https://github.com/NuGet/NuGetGallery/issues/7699
Migration details available here: https://github.com/aspnet/EntityFramework.Docs/issues/1740#issuecomment-557204757
I also removed some sad "Nuget" instances with "NuGet". You're welcome, marketing!
=> Use ef6.exe instead of migrate.exe

tests/Scripts/Import-Configuration.ps1
Progress on https://github.com/NuGet/Engineering/issues/1912
Need to be able to run the functional tests against the app service. For that, new "region" is introduced, this change, extends the test parameter validation to include that new region. The main change is in the functional test configuration.
=> Adding the "USNC-Preview" "region" for functional tests

src/AccountDeleter/AccountDeleter.csproj, src/DatabaseMigrationTools/DatabaseMigrationTools.csproj, src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj, src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj, src/NuGetGallery.Core/NuGetGallery.Core.csproj, src/NuGetGallery.Services/NuGetGallery.Services.csproj, src/NuGetGallery/NuGetGallery.csproj
There was a mismatch in the graph. Some dependencies used 2.58.0 ServerCommon, others used 2.59.0. This resolved to 2.59.0. A breaking change was introduced in 2.59.0. This caused a runtime issue in entry points that use NuGet.Jobs dependencies.
Essentially this change moved to the latest version of NuGet.Jobs and aligns with 2.60.0.
=> [Hotfix] Align NuGet.Jobs and ServerCommon dependencies to 2.60.0

src/AccountDeleter/AccountDeleter.csproj, src/DatabaseMigrationTools/DatabaseMigrationTools.csproj, src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj, src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj, src/NuGetGallery.Core/NuGetGallery.Core.csproj, src/NuGetGallery.Services/NuGetGallery.Services.csproj, src/NuGetGallery/App_Start/OwinStartup.cs, src/NuGetGallery/NuGetGallery.csproj
Reverting to 2.58.0 of ServerCommon libraries until NuGet.Jobs has pulled in the latest version (2.60.0 or later).
Address https://github.com/NuGet/NuGetGallery/issues/7747.
=> [Hotfix] Revert to ServerCommon 2.58.0

src/AccountDeleter/AccountDeleter.csproj, src/AccountDeleter/Job.cs, src/DatabaseMigrationTools/DatabaseMigrationTools.csproj, src/DatabaseMigrationTools/Program.cs, src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj, src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj, src/NuGetGallery.Core/NuGetGallery.Core.csproj, src/NuGetGallery.Services/Diagnostics/DiagnosticsService.cs, src/NuGetGallery.Services/NuGetGallery.Services.csproj, src/NuGetGallery.Services/Telemetry/QuietLog.cs, src/NuGetGallery.Services/Telemetry/TelemetryClientWrapper.cs, src/NuGetGallery.Services/Telemetry/TelemetryService.cs, src/NuGetGallery/App_Start/DefaultDependenciesModule.cs, src/NuGetGallery/App_Start/OwinStartup.cs, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/OData/NuGetODataController.cs, src/NuGetGallery/OData/QueryAllowed/ODataQueryVerifier.cs, tests/GitHubVulnerabilities2Db.Facts/AdvisoryIngestorFacts.cs, tests/NuGetGallery.Facts/Diagnostics/DiagnosticsServiceFacts.cs, tests/NuGetGallery.Facts/OData/Filter/ODataFilterFacts.cs, tests/NuGetGallery.Facts/Security/TestSecurityPolicyService.cs, tests/NuGetGallery.Facts/Services/FeedServiceFacts.cs, tests/NuGetGallery.Facts/Services/TelemetryServiceFacts.cs, tests/NuGetGallery.Facts/TestUtils/TestServiceUtility.cs
This PR updates the Gallery (and the jobs within the solution) to use the new Application Insights initialization logic introduced in ServerCommon 2.60.0 and NuGet.Jobs (current dev branch).
Goal is to move off obsolete AppInsights APIs, such as `TelemetryConfiguration.Active`.
In doing so, some legacy code and static classes required refactoring. Work in progress, but opening the PR already to collect feedback early on.
Also needs to consume a to-be-released update of `NuGet.Services.Logging` ([PR pending](https://github.com/NuGet/ServerCommon/pull/324))
=> No longer depend on Obsolete AppInsights APIs

src/AccountDeleter/AccountDeleter.csproj, src/AccountDeleter/Job.cs, src/DatabaseMigrationTools/DatabaseMigrationTools.csproj, src/DatabaseMigrationTools/Program.cs, src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj, src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj, src/NuGetGallery.Core/NuGetGallery.Core.csproj, src/NuGetGallery.Services/Diagnostics/DiagnosticsService.cs, src/NuGetGallery.Services/NuGetGallery.Services.csproj, src/NuGetGallery.Services/Telemetry/QuietLog.cs, src/NuGetGallery.Services/Telemetry/TelemetryClientWrapper.cs, src/NuGetGallery.Services/Telemetry/TelemetryService.cs, src/NuGetGallery/App_Start/DefaultDependenciesModule.cs, src/NuGetGallery/App_Start/OwinStartup.cs, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/OData/NuGetODataController.cs, src/NuGetGallery/OData/QueryAllowed/ODataQueryVerifier.cs, tests/GitHubVulnerabilities2Db.Facts/AdvisoryIngestorFacts.cs, tests/NuGetGallery.Facts/Diagnostics/DiagnosticsServiceFacts.cs, tests/NuGetGallery.Facts/OData/Filter/ODataFilterFacts.cs, tests/NuGetGallery.Facts/Security/TestSecurityPolicyService.cs, tests/NuGetGallery.Facts/Services/FeedServiceFacts.cs, tests/NuGetGallery.Facts/Services/TelemetryServiceFacts.cs, tests/NuGetGallery.Facts/TestUtils/TestServiceUtility.cs
This reverts commit bb5a8eb46483c383c9c4e42317b9a62bb6f27856. The PR that pushed this in was https://github.com/NuGet/NuGetGallery/pull/7745.
=> Revert "No longer depend on Obsolete AppInsights APIs"

tests/NuGetGallery.FunctionalTests/Security/HttpToHttpsRedirectTests.cs
Progress on https://github.com/NuGet/Engineering/issues/2863
Cloud and app services handle the HTTP to HTTPS redirect differently (we can enable "Always HTTPS" for an app service, while we can't do that for the cloud service), so the test update is required to accommodate for that difference.
This change also requires the test configuration to be updated.
=> HTTP to HTTPS redirect differences between App and Cloud services

tests/Scripts/RunTestScripts.ps1
Progress on https://github.com/NuGet/Engineering/issues/2863
App service deployment reports success way before the service initialization completes successfully and is able to serve requests. This breaks our tests that encounter 502 responses and fail.
This change adds a delay and a response test to the test run script to make sure we run tests against the working service.
=> Functional test script update to wait for the service to start up after the deployment

src/NuGetGallery/Views/Packages/_ManageDeprecation.cshtml
The punctuation on the deprecation reasons are inconsistent:
Addresses https://github.com/NuGet/NuGetGallery/issues/7811
=> Make deprecation reasons have consistent punctuation

src/NuGetGallery.Core/Services/CorePackageService.cs, src/NuGetGallery.Services/Configuration/FeatureFlagService.cs, src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs, src/NuGetGallery.Services/PackageManagement/IPackageService.cs, src/NuGetGallery.Services/PackageManagement/PackageService.cs, src/NuGetGallery.Services/Permissions/ActionRequiringEntityPermissions.cs, src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/Helpers/ViewModelExtensions/DeletePackageViewModelFactory.cs, src/NuGetGallery/Helpers/ViewModelExtensions/DisplayPackageViewModelFactory.cs, src/NuGetGallery/Services/IPackageDeprecationService.cs, src/NuGetGallery/Services/PackageDeprecationService.cs, tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs, tests/NuGetGallery.Facts/Services/FeatureFlagServiceFacts.cs, tests/NuGetGallery.Facts/Services/PackageDeprecationServiceFacts.cs, tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs
This change improves the display package page's performance by optimizing its SQL queries:
1. The first SQL query gets the metadata for all versions of the package, including their deprecations. Our telemetry shows this query is particularly expensive. I've simplified this query.
1. I reduced the number of lazily loaded SQL queries.
Part of https://github.com/NuGet/Engineering/issues/2910.
I will validate this change using this [test plan](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc={15b3fddd-11c7-4f67-8f84-456297b3b279}&action=edit&wd=target%28BugBash.one%7Ce898229f-c60d-49f9-8c4a-1906ea8efd76%2FDisplay%20package%20page%20performance%20improvements%7C63ebcec6-9f14-4f20-ab2f-39a73e1b045d%2F%29&wdorigin=703).
See [postmortem …
=> Improve the display package page's performance

src/NuGetGallery.Services/Configuration/ConfigurationService.cs, src/NuGetGallery/Helpers/HtmlExtensions.cs, src/NuGetGallery/Helpers/RegexEx.cs, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, src/NuGetGallery/Views/Packages/_DisplayPackageDeprecation.cshtml, tests/NuGetGallery.Facts/Helpers/HtmlExtensionsFacts.cs
Just a suggestion. 
Currently package links in descriptions look like this:
What if we did something similar to what github does with issue links and formatted them with a shorter text:
Current regex is relatively strict to avoid any other links masquerading as nuget ones.
=> Format package URLs in descriptions

src/NuGetGallery.Core/CoreStrings.Designer.cs, src/NuGetGallery.Core/CoreStrings.resx, src/NuGetGallery.Core/Packaging/ManifestValidator.cs, tests/NuGetGallery.Core.Facts/Packaging/ManifestValidatorFacts.cs
When you try to pack a .nuspec with a floating version in it, NuGet pack prevents this by taking out the floating part and substituting in min version. "12.*" turns into "12.0.0". However, someone can hand-craft a .nuspec to get around it.
When we moved from 2.x APIs to 3.x APIs in gallery, we started supporting this without realizing it. Our .nuspec validation looks at each dependency version and parses it as a `VersionRange` which supports floating (since it's the same model that is used for `<PackageReference>` version).
These are the only packages that have utilized this:
Id | Version | Created
-- | -- | --
PInvokeCompiler  |  1.0.0-rc1 |  2017-01-09
Scissorhands.Helpers |   1.0.0-alpha-17  |  2016-01-13
Scissorhands.Helpers |   1.0.0-alpha-16  | 2016-01-13
Thanks @zivkan for the …
=> Block version ranges that NuGet pack does not allow

src/NuGetGallery/App_Start/DefaultDependenciesModule.cs, src/NuGetGallery/Infrastructure/Lucene/ResilientSearchHttpClient.cs, tests/NuGetGallery.Facts/Infrastructure/Lucene/ResilientSearchServiceFacts.cs, tests/NuGetGallery.Facts/Queries/AutocompleteServicePackageIdsQueryFacts.cs, tests/NuGetGallery.Facts/Queries/AutocompleteServicePackageVersionsQueryFacts.cs
This was logging *every* time a search service request was sent. This line alone produces 500k-1m log lines per hour and duplicates the `dependencies` logging that is populated automatically.
=> Removed some hot path logs

src/NuGetGallery.Services/Configuration/ConfigurationService.cs, tests/NuGetGallery.Facts/App_Start/ConfigurationServiceFacts.cs
In order to enable the on-line active update of SQL certificates, we should not inject the SQL connection string to build the "SqlConnectionFactory".
Test locally and verify the behavior.
=> [ECR] Enable the active update of SQL certificates without restarting.

src/DatabaseMigrationTools/DatabaseMigrationTools.csproj, src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj, src/NuGetGallery.Core/NuGetGallery.Core.csproj, src/NuGetGallery.Services/NuGetGallery.Services.csproj, src/NuGetGallery/NuGetGallery.csproj
Update the server common dependencies to 2.69.0.
Introduce the logs around the catching control of secret reader.
=> [ECR] Update the server common dependencies to 2.69.0

src/NuGetGallery.Services/Providers/RuntimeServiceProvider.cs, src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
This enables synchronous initialization (via the constructor) of the cookie compliance shim.
Also, move the refresh to the background so that initial start-up is not slowed down.
Fully lights up with https://nuget.visualstudio.com/NuGetMicrosoft/_git/NuGet.Shims/pullrequest/1342.
Related to https://github.com/NuGet/Engineering/issues/2980.
=> Expose domain and diagnostics source in MEF container

src/Bootstrap/dist/js/bootstrap.js, src/Bootstrap/grunt/configBridge.json, src/Bootstrap/package-lock.json, src/Bootstrap/package.json
This addresses the warning currently visible in NuGetGallery.
I also updated `grunt` to 1.1.0 per `npm audit` suggestion.
I also regenerated the lock file to pull latest minor versions for all dependencies and verified that `grunt` still works and generates the same output. `autoprefixer` wanted us to move the configuration so I did this to avoid a warning.
=> Update Bootstrap dependency minimalist to 1.2.3

src/NuGetGallery/Areas/Admin/Controllers/ValidationController.cs, src/NuGetGallery/Areas/Admin/Services/ValidationAdminService.cs, src/NuGetGallery/Areas/Admin/Views/Validation/Index.cshtml
Today the on-call engineer has to connect to the database to find the pending validations. This adds a link to the admin panel to fetch the currently pending validations:
Addresses https://github.com/NuGet/NuGetGallery/issues/7926
Build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3595685
Release: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=628330
=> Add link to search for pending validations

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-display-package.less, src/NuGetGallery/Scripts/gallery/page-edit-readme.js, src/NuGetGallery/Views/Organizations/Add.cshtml, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, src/NuGetGallery/Views/Packages/_DisplayPackageDeprecation.cshtml, src/NuGetGallery/Views/Packages/_ImportReadMe.cshtml, src/NuGetGallery/Views/Users/ApiKeys.cshtml
[A11y]'MIT' Link is not descriptive. #7882
- Updated link description to read "License {LicenseType}" instead of "{LicenseType}"
[A11y]"Learn more" link is not descriptive. #7879
- Update link description to read "Learn more about Organizations on NuGet.Org" from "Learn more"
[A11y]Focus is not visible on the expand/collapse button #7885
- This was actually introduced by #7326 when trying to address #7305
- Undo this change, reintroduces #7305 on click.
[A11y]Narrator is reading improper role for Expand/Collapse button #7889
- Gave element attribute role="button"
[A11y]Narrator does not announce the error message "At least one scope must be selected" after unchecking the 'Push' button. #7876
- Added aria-live region and role="alert"
- Delayed update of text …
=> [A11y]Accessibility fixes 1

build.ps1, ops.cmd, src/AccountDeleter/AccountDeleter.csproj, src/DatabaseMigrationTools/DatabaseMigrationTools.csproj, src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj, src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj, src/NuGetGallery.Core/NuGetGallery.Core.csproj, src/NuGetGallery.Services/NuGetGallery.Services.csproj, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Web.config
This brings in the NoWarn and the 3.0.0.0 assembly version for ServerCommon assemblies.
Depends on https://github.com/NuGet/NuGet.Jobs/pull/880
=> Update to latest ServerCommon

src/NuGetGallery/Helpers/GravatarHelper.cs, src/NuGetGallery/Scripts/gallery/common-multi-select-dropdown.js, src/NuGetGallery/Views/Packages/_ImportReadMe.cshtml, src/NuGetGallery/Views/Packages/_ManageDeprecation.cshtml
Follow-up to https://github.com/NuGet/NuGetGallery/pull/7927
[A11y]Narrator is not reading the labels for "Select Version(s)" drop-down and "Select reason(s)" check-box group #7888
- Update the descriptions on these to indicate context.
[A11y]The narrator announces same name for all 3 actionable images present under Owner section #7883
- Updated gravatar image alt text to include username
[A11y]Incorrect name property provided for the "Custom" tab item. #7884
- Updated descriptions to include proper title.
=> [A11y]Accessibility fixes 2

src/NuGetGallery/App_400.aspx, src/NuGetGallery/App_404.aspx, src/NuGetGallery/App_500.aspx, src/NuGetGallery/App_Start/AppActivator.cs, src/NuGetGallery/Infrastructure/CookieTempDataProvider.cs, src/NuGetGallery/Infrastructure/RequestValidationExceptionFilter.cs, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Web.config, tests/NuGetGallery.FunctionalTests/ErrorHandling/ErrorHandlingTests.cs
The core purpose of this change is to stop redirecting when some kind of error occurs. The root cause of this is the `ResponseRedirect` directive in the web.config. This makes telemetry more difficult because we see a lot of 302 cases but really it's a bad request or an exception getting thrown by our application.
I also cleaned up the things that get logged to Elmah since this will make Elmah useful again to see real problems (right now it is flooded by nasty URL exceptions).
I spent quite some time evaluating the best options and it seems there is not a very effective way to use the pretty error pages for cases that escape MVC error handling and are dealt with by IIS. Therefore, I introduced three simple HTML pages that IIS can `ResponseRewrite` to. Another way of explaining this is: …
=> Remove redirects from error handling and clean Elmah

src/NuGetGallery.Services/Authentication/ApiKeyV4.cs
Addressing https://github.com/NuGet/NuGetGallery/issues/7961
Issue was being caused by local sensitive lower casing.
=> Fix locale sensitive API key copy

src/AccountDeleter/Configuration/GalleryConfiguration.cs, src/NuGetGallery.Services/Configuration/AppConfiguration.cs, src/NuGetGallery.Services/Configuration/IAppConfiguration.cs, src/NuGetGallery/App_Code/ViewHelpers.cshtml, src/NuGetGallery/App_Start/AppActivator.cs, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Scripts/gallery/common.js, src/NuGetGallery/Scripts/gallery/instrumentation.js, src/NuGetGallery/Scripts/gallery/page-home.js, src/NuGetGallery/Views/Shared/ListPackages.cshtml
Progress on https://github.com/NuGet/Engineering/issues/3020
We will use this on nuget.org to swap out the instrumentation system with the Microsoft internal one that allows sending data to both Application Insights and to the internal endpoint which uses the "tenant key" configuration that I added.
=> Add support for alternate instrumentation system in browser 

src/NuGetGallery/Helpers/ValidationHelper.cs, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Services/PackageUploadService.cs, src/NuGetGallery/Services/SymbolPackageUploadService.cs, src/NuGetGallery/Strings.Designer.cs, src/NuGetGallery/Strings.resx, tests/NuGetGallery.Core.Facts/TestUtils/PackageServiceUtility.cs, tests/NuGetGallery.Facts/Helpers/ValidationHelperFacts.cs, tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj, tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs, tests/NuGetGallery.Facts/Services/SymbolPackageUploadServiceFacts.cs
A new validation was added at the ValidateBeforeGeneratePackageAsync method.
#7922
=> Packages with duplicated entries in zip file should be blocked on upload.

src/NuGetGallery/Controllers/AuthenticationController.cs, src/NuGetGallery/GalleryConstants.cs, src/NuGetGallery/Strings.Designer.cs, src/NuGetGallery/Strings.resx
Appending a FAQ link to the AAD authentication error when user account is in an unmanaged tenant state. Also added aka.ms to support this.
Addresses https://github.com/NuGet/NuGetGallery/issues/7544
Resultant error message on page (this change adds the last sentence):
=> Append FAQ address to AAD unmanaged tenant authentication error

src/NuGetGallery/Controllers/PackagesController.cs
nuget.exe doesn't provide an anti-forgery token, so we require an endpoint without one here, and should suppress the FxCop message.
=> Suppress ValidateAntiForgeryToken message in FxCop 

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-display-package.less, src/Bootstrap/less/theme/page-profile.less
* Fix the long username in profile page with newline if there is not enough space
* Fix the long username in display package, use ... if context has overflow, show full username when hover it
Addresses https://github.com/NuGet/NuGetGallery/issues/123
=> UI fix for long username in profile page and display package(#7809)

tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj, tests/NuGetGallery.Core.Facts/Packaging/PackageMetadataFacts.cs, tests/NuGetGallery.Core.Facts/TestUtils/UseInvariantCultureAttribute.cs, tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs, tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs, tests/NuGetGallery.Facts/TestUtils/ContractAssert.cs
* Change to Assert.StartWith instead of Assert.Equal, avoid checking localized 'parameter'  
* Add new class called 'UseInvariantCultureAttribute', change thread UI culture before test, and reset 
after test
* Addressed those unit test:  1.NuGetGallery.Packaging.PackageMetadataFacts.ThrowsForEmptyAndNonEmptyDuplicatesWhenDuplicateMetadataElementsDetectedAndParsingIsNotStrict
2. NuGetGallery.Packaging.PackageMetadataFacts.ThrowsWhenInvalidMinClientVersion
3.NuGetGallery.PackagesControllerFacts+TheUploadFileActionForPostRequests.WillRejectBrokenZipFiles  NuGetGallery.PackagesControllerFacts+TheUploadFileActionForPostRequests.WillShowViewWithErrorsIfPackageIdIsBreaksParsing
4.NuGetGallery.Authentication.AuthenticationServiceFacts+TheAuthenticateMethod.GivenPasswordCred …
=> Fix unit test failed due to localized culture and line ending (#7779)

src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
Linked directly to a blog post with workarounds for affected systems outlined.
=> Changing the banner to indicate that TLS 1.2 enforcement took place

src/NuGetGallery/Migrations/MigrationsConfiguration.cs
We added a migration to add an index on the `PackageDependencies` table. This migration takes longer than 30 seconds to run on PROD and is timing out. This change increases the timeout to 30 minutes which we hope is enough to create the new index.
⚠TODO: verify on DEV
Build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3820287&view=results
Release: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=712036
=> [HOTFIX] Increase migration's database timeout

src/Bootstrap/package-lock.json
Bump `websocket-extensions` to the latest version. This is pulled in transitively by the `grunt-contrib-watch` development dependency. I verified this change by ensuring `grunt` still ran fine.
Addresses https://github.com/NuGet/NuGetGallery/network/alert/src/Bootstrap/package-lock.json/websocket-extensions/open
Addresses https://github.com/nuget/engineering/issues/3231
=> Update `websocket-extensions` dependency

src/GitHubVulnerabilities2Db/Gallery/ThrowingTelemetryService.cs, src/NuGetGallery.Services/Telemetry/ITelemetryService.cs, src/NuGetGallery.Services/Telemetry/TelemetryService.cs, src/NuGetGallery/Controllers/ApiController.cs, src/NuGetGallery/Strings.Designer.cs, src/NuGetGallery/Strings.resx, src/NuGetGallery/Telemetry/CustomerResourceIdEnricher.cs, src/VerifyMicrosoftPackage/Fakes/FakeTelemetryService.cs, tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs, tests/NuGetGallery.Facts/Services/TelemetryServiceFacts.cs, tests/NuGetGallery.Facts/Telemetry/CustomerResourceIdEnricherFacts.cs
Address https://github.com/NuGet/NuGetGallery/issues/8022
I was unable to reproduce the issue with many wild attempts (local devbox, app service directly, APIM, custom HTTP client implementation, raising firewall in the middle of request, killing connection via external tools, etc) but from reading online this seems like the recommended implementation. See https://stackoverflow.com/questions/4772597 for some recommendations. We can't use the cancellation token approach because the API that is throwing does not accept a token. It's this line that throws:
https://github.com/NuGet/NuGetGallery/blob/84ea5890b77e79b1f218521f2c031f8ee6c311f5/src/NuGetGallery/Controllers/ApiController.cs#L984
=> Don't track the package push failure if the client has disconnected

src/NuGetGallery/ViewModels/StatisticsPackagesViewModel.cs, tests/NuGetGallery.Facts/ViewModels/StatisticsPackagesViewModelFacts.cs
Addresses https://github.com/NuGet/NuGetGallery/issues/8032
Adds culture-awareness to string operations creating short numbers for Y-axis on graphs. Added culture cases to unit tests. Examples:
fr-FR:
en-US:
=> Make statistical significant figures formatting culture-sensitive

src/NuGetGallery/Public/robots.txt
The `/packages/*/*/Contents` route does not exist
Thanks for the heads up @xavierdecoster
=> Remove non-existent endpoints from robots.txt

src/NuGetGallery.Core/Entities/EntitiesContext.cs, src/NuGetGallery.Core/Entities/IReadOnlyEntitiesContext.cs, src/NuGetGallery.Core/Entities/QueryHintInterceptor.cs, src/NuGetGallery.Core/Entities/ReadOnlyEntitiesContext.cs, src/NuGetGallery.Core/NuGetGallery.Core.csproj, src/NuGetGallery.Services/PackageManagement/PackageService.cs, src/NuGetGallery/App_Data/Files/Content/AB-Test-Configuration.json, src/NuGetGallery/App_Data/Files/Content/flags.json, src/NuGetGallery/App_Start/DefaultDependenciesModule.cs, src/VerifyMicrosoftPackage/Fakes/FakeEntitiesContext.cs, tests/NuGetGallery.Facts/Entities/EntitiesContextFacts.cs, tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs, tests/NuGetGallery.Facts/TestUtils/FakeEntitiesContext.cs
Progress on https://github.com/NuGet/NuGetGallery/issues/8078
The alternative was to revert to raw SQL. I discussed with @agr and we agreed to go with this EF extension approach.
=> Add RECOMPILE query hint to package dependents SQL

src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/8100
This effectively reverses changes introduced by https://github.com/NuGet/NuGetGallery/pull/8012 and https://github.com/NuGet/NuGetGallery/pull/8046 dropping the `<div>` with the banner. The CSS changes are preserved for later reuse.
=> Removing TLS banner

src/NuGetGallery.Services/Configuration/IQueryHintConfiguration.cs, src/NuGetGallery.Services/Configuration/QueryHintConfiguration.cs, src/NuGetGallery.Services/NuGetGallery.Services.csproj, src/NuGetGallery.Services/PackageManagement/PackageService.cs, src/NuGetGallery.Services/ServicesConstants.cs, src/NuGetGallery.Services/Storage/ContentObjectService.cs, src/NuGetGallery.Services/Storage/IContentObjectService.cs, src/NuGetGallery/App_Data/Files/Content/Query-Hint-Configuration.json, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Web.config, src/VerifyMicrosoftPackage/Application.cs, src/VerifyMicrosoftPackage/Fakes/FakeContentObjectService.cs, src/VerifyMicrosoftPackage/VerifyMicrosoftPackage.csproj, tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs, tests/NuGetGallery.Facts/Services/ReflowPackageServiceFacts.cs, tests/NuGetGallery.Facts/TestUtils/TestServiceUtility.cs
Progress on https://github.com/NuGet/NuGetGallery/issues/8078.
Some parameter values, such as EPPlus, CsvHelper, and others perform poorly even with up-to-date statistics when using `RECOMPILE`. I have provided these cases to the SQL Server team but in the meantime we can't use the `RECOMPILE` approach. The other suggestion that SQL Server team provided was the `OPTIMIZE FOR UNKNOWN` query hint. This essentially tells SQL Server to treat all parameter values as if they have no statistics (i.e. no dependents at all). This causes SQL Server to use the index that we original anticipated using and added for this purpose. Unfortunately, this query plan is not very fast for very depended upon packages (where the `RECOMPILE` approach really shined).
I took a data set of the top 1000 package IDs …
=> Use OPTIMIZE FOR UNKNOWN for dependents queries

tests/NuGetGallery.FunctionalTests.Core/Constants.cs, tests/NuGetGallery.FunctionalTests/NuGetGallery.FunctionalTests.csproj, tests/NuGetGallery.FunctionalTests/PackageRetrieval/PackageListTests.cs
This PR adds some basic functional tests on the Gallery for Advanced Search. Stuff being tested:
- package type filter (dependency, template and a random type "ARandomType")
- total downloads sorting
- last updated sorting
Edit:
- Functional tests on [DEV](https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=72898)
- Functional tests on [PROD](https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=72897)
=> Add functional tests on Gallery for Advanced Search

src/GitHubVulnerabilities2Db/Job.cs, src/NuGetGallery.Services/PackageManagement/PackageService.cs
Addresses https://github.com/NuGet/NuGetGallery/issues/8138
If the ContentObjectService parameter becomes optional in the PackageService constructor, dependency injection in GitHubVulnerabilities2Db won't inflate the type (which is what caused the failure--no DI registration). Inflating the type properly wouldn't be the right fix here as its dependencies aren't lightweight and it's unused in this utility. So we need an optional parameter and failsafes for nulls in PackageService.
Some formatting fixes resulted from a copy/paste operation. Why not.
=> Unbreak GitHubVulnerabilities2Db dependency injection

src/NuGetGallery/Controllers/ODataV2FeedController.cs
Addresses https://github.com/NuGet/Engineering/issues/3303
No need to log exceptions for user input errors. Those are not "exceptional".
=> Fix for: Malicious OData requests trigger exception monitoring

src/NuGetGallery.Services/PackageManagement/PackageVulnerabilityService.cs
Addresses: https://github.com/NuGet/Engineering/issues/3211
Move VulnerablePackageVersionRange entity update to after its vulnerability is correct. This stops a multiplicity issue which results in an INSERT sent by EF for a record which already exists.
=> Fix PackageVulnerability indexing uniqueness error

src/NuGetGallery.Services/PackageManagement/PackageFilter.cs, src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/ViewModels/PackageViewModel.cs, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Currently when specifying a version that doesn't exist (eg, https://www.nuget.org/packages/Newtonsoft.Json/1337.42.42.0)  it just takes you to the latest version with no warning. This PR adds that warning. 
Addresses #4624
=> Display warning when specified version was not found

src/NuGetGallery/UrlHelperExtensions.cs, tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs, tests/NuGetGallery.Facts/UrlHelperExtensionsFacts.cs
Fixes breadcrumb links for packages with build metadata:
The only question now is if we want to continue to display the build metadata in the link (the +6...) part. I think it's ok, but that's me. 
Addresses #8136
=> Fixed breadcrumb links for packages with build metadata

src/NuGetGallery/Controllers/ODataV2FeedController.cs, src/NuGetGallery/Infrastructure/ODataCacheOutputAttribute.cs, src/NuGetGallery/Strings.Designer.cs, src/NuGetGallery/Strings.resx, tests/NuGetGallery.Facts/Infrastructure/ODataCacheOutputAttributeFacts.cs, tests/NuGetGallery.FunctionalTests.Core/Helpers/ClientSdkHelper.cs, tests/NuGetGallery.FunctionalTests.Core/Helpers/ODataHelper.cs, tests/NuGetGallery.FunctionalTests/ODataFeeds/CuratedFeedTest.cs, tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedExtendedTests.cs, tests/NuGetGallery.LoadTests/LoadTests.cs
This will facilitate functional tests and end-to-end tests that require querying for package availability in DB instead of availability in V3 (search hijack). See the functional tests containing `hijack=true` for context. There is also one such case in the end-to-end tests. In short, there are many integration tests today that depend on checking for a package's availability prior to V3 indexing.
Essentially the difference when the new parameter is specified as `hijack=false`, you can see a package even before it has made its way the search service but _after_ validation is complete. This was previously achieved in various monitoring and testing places in our code via opaque hacks like adding an `$orderby` that can't be hijacked or adding `1 eq 1` to a `$filter`. 
Given the excellent …
=> Add hijack=false parameter to OData get specific package

src/GalleryTools/GalleryTools.csproj
This was causing a forced downgrade to 4.6.2. The dependency now come in transitively at a higher version.
=> Remove unnecessary dependency

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/all.less, src/Bootstrap/less/theme/common-readme.less, src/NuGetGallery.Services/PackageManagement/PackageService.cs, src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/RequestModels/VerifyPackageRequest.cs, src/NuGetGallery/Scripts/gallery/async-file-upload.js, src/NuGetGallery/Services/IReadMeService.cs, src/NuGetGallery/Services/ReadMeService.cs, src/NuGetGallery/Strings.Designer.cs, src/NuGetGallery/Strings.resx, src/NuGetGallery/Views/Packages/_VerifyMetadata.cshtml, tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
* UI to display preview of readme content
* Disable documentation section at manage package page when embeddedReadme feature is enabled 
- EmbeddedReadme flag feature enable
- 1. Uploading packages with embedded readme
- 2. Uploading packages without embedded readme
- EmbeddedReadme flag feature disable:
- 1. Uploading packages with embedded readme: 
- 2.  Uploading packages without embedded readme:
Addresses :https://github.com/NuGet/Engineering/issues/3267
=> Preview readme 

src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/Services/IPackageFileService.cs, src/NuGetGallery/Services/PackageFileService.cs, src/NuGetGallery/Services/PackageUploadService.cs, tests/NuGetGallery.Facts/Services/PackageFileServiceFacts.cs, tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs
* Store embedded readme into readmes container
No change in terms of displaying view model, use the current implementation to display 
Display embedded readme on details page
Addresses https://github.com/NuGet/Engineering/issues/3266
=> Store embedded readme file to storage

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/base.less, src/NuGetGallery.Services/PackageManagement/PackageService.cs, src/NuGetGallery/Controllers/UsersController.cs, src/NuGetGallery/Scripts/gallery/page-manage-packages.js, src/NuGetGallery/ViewModels/ListPackageItemViewModel.cs, src/NuGetGallery/Views/Users/Packages.cshtml, tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
This adds support for ordering the "Published Packages" and "Unlisted Packages" tables on the "Manage my packages" screen, eg:
Clicking on any of the column headers sorts by that column. I am by no means a JS guru but hopefully this does what we want and works for most people.
Addresses https://github.com/NuGet/NuGetGallery/issues/7806
=> package list can be sorted by ID, owners, downloads and version

src/NuGetGallery/Scripts/gallery/page-display-package.js, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Address https://github.com/NuGet/Engineering/issues/3400
Currently we have very little understanding of whether a user is "successful" after they reach a package details page. We have floated the idea several times in the past about instrumenting the "Copy" button. I decided to do that now so we can establish a baseline leading up to the next feature, whatever that might be (perhaps readmes? 👍)
The event looks like this:
=> Emit AI event when install command is copied

src/NuGetGallery/Scripts/gallery/common.js
Address https://github.com/NuGet/NuGetGallery/issues/7784
Many tracker blockers prevent Usabilla from fully loading leaving a dead "Feedback" button on the page. This is a poor user experience.
Best view when hiding the whitespace:
https://github.com/NuGet/NuGetGallery/pull/8208/files?diff=unified&w=1
=> Don't show Usabilla button if it's blocked

src/NuGetGallery/Controllers/ApiController.cs, src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/Infrastructure/Lucene/ExternalSearchService.cs, src/NuGetGallery/Infrastructure/Lucene/GallerySearchClient.cs, src/NuGetGallery/Infrastructure/Lucene/ISearchClient.cs, src/NuGetGallery/OData/SearchService/SearchAdaptor.cs, src/NuGetGallery/Queries/AutocompleteDatabasePackageIdsQuery.cs, src/NuGetGallery/Queries/AutocompleteDatabasePackageVersionsQuery.cs, src/NuGetGallery/Queries/AutocompleteServicePackageIdsQuery.cs, src/NuGetGallery/Queries/AutocompleteServicePackageVersionsQuery.cs, src/NuGetGallery/Queries/AutocompleteServiceQuery.cs, src/NuGetGallery/Queries/IAutocompletePackageIdsQuery.cs, src/NuGetGallery/Queries/IAutocompletePackageVersionsQuery.cs, src/NuGetGallery/Services/SearchFilter.cs, src/NuGetGallery/Services/SearchSideBySideService.cs, src/NuGetGallery/ViewModels/PackageListSearchViewModel.cs, tests/NuGetGallery.Facts/Queries/AutocompleteDatabasePackageIdsQueryFacts.cs, tests/NuGetGallery.Facts/Queries/AutocompleteDatabasePackageVersionsQueryFacts.cs, tests/NuGetGallery.Facts/Queries/AutocompleteServicePackageIdsQueryFacts.cs, tests/NuGetGallery.Facts/Queries/AutocompleteServicePackageVersionsQueryFacts.cs, tests/NuGetGallery.Facts/Queries/AutocompleteServiceQueryFacts.cs, tests/NuGetGallery.Facts/Services/SearchAdaptorFacts.cs, tests/NuGetGallery.FunctionalTests/PackageRetrieval/PackageListTests.cs
These endpoints are used by automated tests and must allow test data to be shown. It is filtered out of search qeuries by default with https://github.com/NuGet/NuGet.Jobs/pull/915.
The package list (`/packages`) is hit by gallery functional tests when testing the advanced search sorting behavior.
The V2 autocomplete endpoints (`/api/v2/package-ids` and `/api/v2/package-version`) are used by end-to-end tests to verify V2 autocomplete behavior.
Related to https://github.com/NuGet/NuGetGallery/issues/8172
=> Add testData parameter to package list and V2 autocomplete

src/NuGetGallery/Views/Shared/_AccountCertificates.cshtml
Remove additional call for @ViewHelpers.AjaxAntiForgeryToken(Html) in _AccountCertificates.cshtml to avoid duplicate attribute id value
Addresses https://github.com/NuGet/NuGetGallery/issues/8189
=> make attribute id value unique

src/Bootstrap/dist/css/bootstrap.css, src/Bootstrap/less/variables.less
For WCAG 2.1, web components must have a 3:1 contrast ratio. This darkens both the "search" button in the header as well as the "copy" button for installation instructions.
Before:
After:
Addresses https://github.com/NuGet/NuGetGallery/issues/8195
=> Darken the orange buttons for accessibility

src/NuGetGallery.Core/NuGetGallery.Core.csproj, src/NuGetGallery.Core/Packaging/PackageMetadata.cs, src/NuGetGallery.Services/NuGetGallery.Services.csproj, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Web.config, tests/NuGetGallery.Facts/Services/PackageMetadataValidationServiceFacts.cs
The Gallery uses an older version of `NuGet.Packaging` that depends on `NuGet.Packaging.Core`. The Orchestrator was updated to use a newer version of `NuGet.Packaging` that no longer depends on `NuGet.Packaging.Core`. The Orchestrator uses assemblies produced from the Gallery, thereby causing runtime issues when these assemblies attempt to reference types from `NuGet.Packaging.Core.dll` which is unavailable.
Build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4116398&view=results
Release: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=833326
Part of https://github.com/NuGet/NuGetGallery/issues/8228
=> Update NuGet client libraries to 5.8.0 prerelease

src/NuGetGallery/Strings.Designer.cs, src/NuGetGallery/Strings.resx
Progress on https://github.com/NuGet/Engineering/issues/3428
There are two variants of error messages because the `/api/v1/Packages()` endpoint will be entirely disabled (it does not hijack at all) and will therefore need different wording than the rest of the endpoints which just have some sets of parameter combinations disabled.
```
https://localhost/api/v1/Packages()?$orderby=Version
```
Response with formatting (my browser):
Response without formatting (most likely experience):
<code>
&lt;?xml version="1.0" encoding="utf-8"?&gt;&lt;m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"&gt;&lt;m:code /&gt;&lt;m:message xml:lang="en-US"&gt;This OData endpoint is disabled. Please refer to the following URL for more information about this deprecation: …
=> Enhance OData deprecation error message

tests/Scripts/BuildTests.ps1
Change MS build point to VS2019 instead of VS2017 since we migrate all VM to VS2019.
=> Path fix in script point to VS2019

src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
UI:
Addresses https://github.com/NuGet/NuGetGallery/issues/8225
=> NuGet survey banner

src/NuGetGallery/App_Data/Files/Content/AB-Test-Configuration.json, src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/Infrastructure/ABTestEnrollment.cs, src/NuGetGallery/Infrastructure/ABTestEnrollmentFactory.cs, src/NuGetGallery/Infrastructure/CookieBasedABTestService.cs, src/NuGetGallery/Infrastructure/IABTestService.cs, tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs, tests/NuGetGallery.Facts/Infrastructure/ABTestEnrollmentFactoryFacts.cs
Address https://github.com/NuGet/NuGetGallery/issues/8250
Also, did a little thinking about what the next A/B test would do. Either re-use the "pd" property in the cookie if you don't care much about independent treatment groups or add a new schema version and leave "pd" as vestigial.
=> Remove A/B test check for the package dependents feature

src/NuGetGallery/Views/Users/ApiKeys.cshtml
Update the API key form to call out the `select scopes` label after tabbing to inputs within that field group.
Addresses https://github.com/NuGet/NuGetGallery/issues/8182
=> [A11y] Call out the 'select scopes' field label

src/NuGetGallery/Views/Organizations/_OrganizationAccountManageMembers.cshtml
Fix for #8193 
For repro details please refer to the issue.
The problem was that when narrator reaches those SelectRole, ChangeRole combo boxes it reads 
"Select new member role combo box Administrator collapsed"
According to the requirements in https://w3c.github.io/wcag21/understanding/label-in-name.html
We need to 
> Ensure that visible labels match their accessible names
> **The following are common mistakes that are considered failures of this Success Criterion by the WCAG Working Group.**
> 
> Accessible name does not contain the visible label text
> Accessible name contains the visible label text, but the words of the visible label are not in the same order as they are in the visible label text
> Accessible name contains the visible label text, but one or more other words is …
=> Fix accessibility bug in SelectRole, ChangeRole combo boxes labels

src/Bootstrap/dist/css/bootstrap.css, src/Bootstrap/less/variables.less, src/NuGetGallery/Views/Organizations/_OrganizationAccountManageMembers.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/8192
Example:
Hovering over the button darkens it:
Note: this change also affects external login buttons. The new style is closer to Microsoft's [guidelines](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-add-branding-in-azure-ad-apps#visual-guidance-for-sign-in) but does not follow them completely. I've opened https://github.com/NuGet/NuGetGallery/issues/8258 to track this issue.
You can find the test plan here: https://github.com/NuGet/NuGetGallery/issues/8192#issuecomment-698598530
=> [A11y] Improve color contrast of grey buttons

src/Bootstrap/dist/css/bootstrap.css, src/Bootstrap/less/variables.less
Updates the orange button's color such that its color contrast is at least 3:1 on both our body's and header's background colors. Currently, the color is dark enough on our white background, but too dark for our blue background.
Addresses https://github.com/NuGet/NuGetGallery/issues/8265
Screenshot:
💡 Pro tip: Chrome may render different colors than requested by the stylesheet (see [this StackOverflow](https://stackoverflow.com/questions/48642753/css-color-difference-between-browsers)). If you work on color contrast accessibility issues using Chrome, make sure to disable this behavior here: chrome://flags/
Here is an excerpt from WCAG 2.1 ([here](https://w3c.github.io/wcag21/guidelines/#dfn-contrast-ratio)):
> WCAG conformance should be evaluated for color pairs specified in the content …
=> [A11y] Improve the color contrast of the header's search button

.eslintignore
VS2019 seems to put temporary files in one more place that ESLint now catches.
See https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4150098&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=e900fa28-66c4-55e5-4e9c-0ba63fb92fbd.
=> Make the ESLint ignore pattern more generic

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/base.less, src/NuGetGallery/Views/Shared/Gallery/Header.cshtml
Add underline with survey link
Less space between like you and the link
UI: 
Addresses https://github.com/NuGet/NuGetGallery/issues/8225
=> Add underline for banner

src/NuGetGallery/Areas/Admin/Controllers/SupportRequestController.cs, src/NuGetGallery/Controllers/PackagesController.cs
=> Change httpPost to httpGet

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/8196
Previously, version history table always had 2 hardly visible columns: 1 for signature information and another for deprecation information. When user is not authenticated on the web site, we never show the package signature information, so the cells although exist are always empty. The deprecation information is present, but most of the time packages are not deprecated and empty cells do not have any narrator markup, so are not read (but headers are).
This change moves the `Model.IsCertificatesUIEnabled` check up to the lines that generate column header, causing the certificate column to be completely absent for unauthenticated users. Same is done for `Model.IsPackageDeprecationEnabled` but it is always `true` in our case. Also …
=> Version history table rendering update for accessibility

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-display-package.less
Darkens the orange GitHub star icon for 3:1 color contrast ratio.
Addresses https://github.com/NuGet/NuGetGallery/issues/8286
=> [A11y] Darken the GitHub star icon

src/NuGetGallery/ExtensionMethods.cs, tests/NuGetGallery.Facts/ExtensionMethodsFacts.cs
Address https://github.com/NuGet/NuGetGallery/issues/8235
Address https://github.com/NuGet/NuGetGallery/issues/8268
Instead of using the custom framework display logic that nuget.org currently has for framework names in dependency groups, use `NuGetFramework.ToString()`. This is the recommended approach from client team and aligns with the package management UI in Visual Studio. The VS UI is spec'd here which we are mimicking.
https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md
> - Package Manager UI in VS
>    - [Use short form](https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md#tfms-in-the-ui)
=> Display net5.0 using ToString instead of custom logic

src/GitHubVulnerabilities2Db/Gallery/ThrowingTelemetryService.cs, src/NuGetGallery.Services/Telemetry/ITelemetryService.cs, src/NuGetGallery.Services/Telemetry/TelemetryService.cs, src/NuGetGallery/Infrastructure/ABTestEnrollmentFactory.cs, src/NuGetGallery/Infrastructure/CookieBasedABTestService.cs, src/VerifyMicrosoftPackage/Fakes/FakeTelemetryService.cs, tests/NuGetGallery.Facts/Infrastructure/ABTestEnrollmentFactoryFacts.cs, tests/NuGetGallery.Facts/Infrastructure/CookieBasedABTestServiceFacts.cs, tests/NuGetGallery.Facts/Services/TelemetryServiceFacts.cs
We should expire any cookie in 13 months, no matter whether it's in EU or not.
We upgrade the cookie to V3, in order to handle these already dropped cookies.
=> [Cookies] Expire the AB test cookie in a year

src/Bootstrap/dist/css/bootstrap.css, src/Bootstrap/less/mixins/tab-focus.less
Improve the color contrast of Firefox's outline for focused items. This effectively reverts https://github.com/NuGet/NuGetGallery/commit/c245f2caeedc052be830a791879f2d4c8e0cc943 as Firefox now properly outlines elements.
Chromium browsers (Chrome, Edgium, Opera) are all unaffected by this change. I also verified that Internet Explorer's focus outlines pass the 3:1 color contrast requirement.
Note that radio buttons and checkboxes are unaffected by this change.
The color contrast for links on our white background is not 3:1
Addresses https://github.com/NuGet/NuGetGallery/issues/8185
=> [A11y] Improve color contrast of focus outline on Firefox

src/NuGetGallery/Controllers/ODataV1FeedController.cs, src/NuGetGallery/Controllers/ODataV2FeedController.cs, src/NuGetGallery/OData/NuGetODataController.cs, tests/NuGetGallery.Facts/Controllers/ODataFeedControllerFactsBase.cs, tests/NuGetGallery.Facts/Controllers/ODataV1FeedControllerFacts.cs, tests/NuGetGallery.Facts/Controllers/ODataV2FeedControllerFacts.cs
Address https://github.com/NuGet/NuGetGallery/issues/8296
=> Add OData error code for deprecate response messages

src/NuGetGallery/Views/Users/Account.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/8302.
The page was missing anti-forgery token for ajax requests.
=> Fix for being unable to delete user account certificates

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/base.less
Addresses https://github.com/NuGet/NuGetGallery/issues/8282
Narrowing the width at minimum width by a small amount keeps the horizontal scrollbar from appearing.
=> [A11y][WCAG2.1]Shrink narrow width by a small amount

src/NuGetGallery/Services/SqlAggregateStatsService.cs
Unclear why the code was written this way originally, but we can get rid of `Task.Result` call here pretty painless.
=> Not using Task.Result in async context.

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Another take on https://github.com/NuGet/NuGetGallery/issues/8196 (Previous attempt: https://github.com/NuGet/NuGetGallery/pull/8287)
The expectation actually was that empty cells are not read completely by a narrator, instead of producing an explanation regarding why the cell is empty.
The new behavior is as follows: if there are no deprecation or signature icons in the table, narrator completely ignores the existence of those columns (i.e. says "3 by 4" instead of "3 by 6" for the table size and it is no longer possible to navigate to those empty cells with Ctrl+Alt+Arrow keys); if there are deprecation or signature icons the column number will accommodate (i.e. will become "3 by 5" or "3 by 6" depending on number of icons) and those icons can be focused, empty cells still cannot be …
=> Dropping the narration completely for absent signature and deprecation information

src/NuGetGallery.Core/Auditing/CloudAuditingService.cs, src/NuGetGallery/App_Start/DefaultDependenciesModule.cs, tests/NuGetGallery.Core.Facts/Auditing/CloudAuditingServiceTests.cs
While looking for `Task.Result` code I stumbled upon `localIp = AuditActor.GetLocalIpAddressAsync().Result` call in `DefaultDepenenciesModule` that then was passed into the `CloudAuditingService` constructor, stored in its member and never used.
Looking at the [commit](https://github.com/NuGet/NuGetGallery/commit/0972d34ca76c22d8d0fde38c56634e0fd88008e3#diff-37cab84da1c323a1f9471a097fe7961e57f58238dd39a25cfa4558799920cc8eR27) that introduced that constructor argument, it was unused from the beginning. Removing it, will get rid of one `Task.Result` call.
=> Removed unused localIP member of CloudAuditingService.

src/NuGetGallery/Views/Shared/_AccountCertificates.cshtml
I decide to move to a quicker solution, and just break word for a certificate thumbprint:
Before:
@ryuyu
=> [A11y] break word for a certificate thumbprint

tests/NuGetGallery.FunctionalTests.Core/Constants.cs, tests/NuGetGallery.FunctionalTests/PackageRetrieval/PackageListTests.cs
Progress on https://github.com/NuGet/Engineering/issues/3513
All temporary test data will be owed by the NugetTestAccount and orgs. This data should be cleaned up.
All static test data that should not be deleted will be owned by NuGetTestData organization.
=> Switch to NuGetTestData for static test packages

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/dist/css/bootstrap.css, src/Bootstrap/less/tables.less, src/Bootstrap/less/theme/page-status.less
Required to be only one scroll. 
- set up min-width for table
- word break
After changes: 
Addresses https://github.com/NuGet/NuGetGallery/issues/8313
=> Fix two scroll bar at status page 

src/DatabaseMigrationTools/DatabaseMigrationTools.csproj, src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj, src/NuGet.Services.Entities/NuGet.Services.Entities.csproj, src/NuGetGallery.Core/NuGetGallery.Core.csproj, src/NuGetGallery.Services/NuGetGallery.Services.csproj, src/NuGetGallery/NuGetGallery.csproj, tests/NuGetGallery.FunctionalTests/NuGetGallery.FunctionalTests.csproj
Progress on https://github.com/NuGet/NuGetGallery/issues/8230
To enable Gallery to accept new OSI and FSF approved licenses need to bump NuGet.Packaging version.
The rest of NuGet.* packages were updated to align with NuGet.Packaging and get off preview version.
=> Latest release version of NuGet.*

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/base.less, src/NuGetGallery/Views/Shared/_AccountCertificates.cshtml
This PR enables a scroll bar on the Certificates table.
According to Accessibility team, it is ok to have the scrollbar on the table itself, but not on the page.
Preview:
=> [A11y]Enable horizontal scrollbar on cert table

src/NuGetGallery/Views/Shared/_AccountChangeEmail.cshtml
It's a better UI when reflowing to align Account Change Email with others, by dropping the form-group:
Before:
=> [UI] No need to use form-group for Account Change Email

src/NuGetGallery.Core/NuGetGallery.Core.csproj
This PR fixes the currently broken transform-user-to-organization flow: https://github.com/NuGet/NuGetGallery/issues/8344
This flow was broken by my move to .SDK-based projects. When converting NuGetGallery.Core.csproj to SDK-based, I missed an embedded resource item.
I have verified this on DEV. I'd like to take this to INT and PROD today to unblock our users.
=> [Hotfix] Add missing resource

src/GitHubVulnerabilities2Db/Ingest/AdvisoryIngestor.cs, src/GitHubVulnerabilities2Db/Job.cs, src/NuGetGallery.Services/Configuration/FeatureFlagService.cs, src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs, src/NuGetGallery.Services/NuGetGallery.Services.csproj, src/NuGetGallery.Services/PackageManagement/IPackageVulnerabilitiesManagementService.cs, src/NuGetGallery.Services/PackageManagement/PackageVulnerabilitiesManagementService.cs, src/NuGetGallery/App_Data/Files/Content/flags.json, src/NuGetGallery/App_Start/DefaultDependenciesModule.cs, src/NuGetGallery/Services/PackageUploadService.cs, src/VerifyGitHubVulnerabilities/Job.cs, src/VerifyGitHubVulnerabilities/Verify/PackageVulnerabilitiesVerifier.cs, src/VerifyGitHubVulnerabilities/VerifyGitHubVulnerabilities.csproj, tests/GitHubVulnerabilities2Db.Facts/AdvisoryIngestorFacts.cs, tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj, tests/NuGetGallery.Facts/Services/PackageUploadServiceFacts.cs, tests/NuGetGallery.Facts/Services/PackageVulnerabilitiesManagementServiceFacts.cs
Starts to address: https://github.com/nuget/nugetgallery/issues/7650
This is a rename of the existing vulnerability service to a vulnerability management service, and the vulnerability service verifier to a vulnerability verifier. Quite a few files in this PR, but it's very repetitive.
Also, I've introduced a feature flag here for use in vulnerability messaging.
This is all groundwork for the PRs to follow.
=> Rename vulnerability management service, add feature flag

src/NuGet.Services.Entities/Package.cs, src/NuGetGallery.Core/Entities/EntitiesContext.cs, src/NuGetGallery.Services/PackageManagement/PackageVulnerabilitiesManagementService.cs, src/NuGetGallery/App_Start/DefaultDependenciesModule.cs, src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/Helpers/ViewModelExtensions/DeletePackageViewModelFactory.cs, src/NuGetGallery/Helpers/ViewModelExtensions/DisplayPackageViewModelFactory.cs, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Services/IPackageVulnerabilitiesService.cs, src/NuGetGallery/Services/PackageVulnerabilitiesService.cs, src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs, src/VerifyGitHubVulnerabilities/Verify/PackageVulnerabilitiesVerifier.cs, tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs, tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj, tests/NuGetGallery.Facts/Services/PackageVulnerabilitiesManagementServiceFacts.cs, tests/NuGetGallery.Facts/Services/PackageVulnerabilitiesServiceFacts.cs, tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs
Starts to address: https://github.com/nuget/nugetgallery/issues/7650.
PR https://github.com/NuGet/NuGetGallery/pull/8356 must be merged before this one.
Here I introduce the new package vulnerability service. This service's job is simple at this point--return a dictionary of package keys with a list of vulnerabilities for each. Some plumbing is also added to make those values available to view models.
There is also the renaming of an EF navigation property Vulnerabilities to VulnerablePackageRanges, which is more representative.
Again, a few files here, but there's quite a bit of repetition for the rename and plumbing.
=> Add vulnerabilities service

NuGet.config
Restrict package sources to those explicitly listed in the `nuget.config` file. This prevents build issues where packages may come from unexpected package sources due to other `nuget.config` files (see [this](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses)).
Part of https://github.com/NuGet/Engineering/issues/3525
=> Restrict package sources

tests/NuGetGallery.FunctionalTests/PackageCreation/ApiPushTests.cs
Functional tests on PROD are currently failing repeatedly:
* https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=77508&view=results
* https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=77522&view=results
* https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=77526&view=results
The duplicate package push functional test pushes 160 packages in parallel. This is causing SQL timeouts. To unblock functional tests, we will temporarily reduce the number of duplicated packages we push to just 16. As part of https://github.com/NuGet/NuGetGallery/issues/8368, we will improve the SQL query used to push packages and revert this change.
Part of https://github.com/NuGet/NuGetGallery/issues/8368
=> [HOTFIX] Fix functional tests by reducing number of pushed duplicate packages

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-display-package.less, src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/Helpers/ViewModelExtensions/DisplayPackageViewModelFactory.cs, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Scripts/gallery/page-display-package.js, src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, src/NuGetGallery/Views/Packages/_DisplayPackageVulnerabilities.cshtml, tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
Completes: https://github.com/nuget/nugetgallery/issues/7650
Here we change the view to include a vulnerabilities panel for an affected package version.
Non-owner view, not expanded:
Owner view, expanded:
- bangs and tooltips in the version list (combined for deprecations and vulnerabilities). Again, formats and icons may be tweaked going forward. 
Vulnerability only:
Vulnerability + deprecation:
=> Add vulnerability messaging to package details page

src/NuGetGallery.Services/PackageManagement/IPackageService.cs, src/NuGetGallery.Services/PackageManagement/PackageService.cs, src/NuGetGallery/Controllers/ApiController.cs, tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs, tests/NuGetGallery.FunctionalTests/PackageCreation/ApiPushTests.cs
Previously, the functional tests on PROD failed repeatedly:
* https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=77508&view=results
* https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=77522&view=results
* https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=77526&view=results
The functional tests push many packages in parallel, which caused an expensive SQL query to time out.
This improves the push package API performance by avoiding a costly SQL query on the "hot" path.
<details>
<summary>Verification...</summary>
Build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4362696&view=results
Release: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=923920
Test plan:
</details>
Addresses …
=> Optimize the push package API

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Screenshot:
Addresses https://github.com/NuGet/Engineering/issues/3527
/cc @cartermp @jonsequitur
=> Add F# interactive instructions

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-account-settings.less, src/NuGetGallery/Views/Users/_UserAccountChangeExternalCredential.cshtml
Fixing https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1188115 being reopened.
=> [A11y]Fixing a missed horizontal scroll bar case

src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Despite the name of this branch, this change removes the target="_blank" attribute, because it's ignored by chromium browsers, and we don't do it in other anchors for 3rd party site.
But the important thing is that this change fixes a bug where the icons for the FuGet links aren't bundled--they weren't appearing on the deployed webapp. This completes this work: https://github.com/NuGet/NuGetGallery/issues/7850
=> Add icons to project to ensure bundling

src/DatabaseMigrationTools/DatabaseMigrationTools.csproj, src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj, src/NuGetGallery.Core/NuGetGallery.Core.csproj, src/NuGetGallery.Services/NuGetGallery.Services.csproj, src/NuGetGallery/NuGetGallery.csproj
Brings in the changes from: https://github.com/NuGet/ServerCommon/pull/356.
This will be used to create a new `NuGetGallery.Core` package to update the Orchestrator. See: https://github.com/NuGet/NuGet.Jobs/pull/958
Part of: https://github.com/NuGet/Engineering/issues/3614
=> Update Gallery to the latest ServerCommon

src/NuGetGallery/Controllers/ApiController.cs, src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/Services/PackageUploadService.cs, src/NuGetGallery/Services/SymbolPackageUploadService.cs, tests/NuGetGallery.Facts/Infrastructure/Lucene/SearchPolicyFacts.cs
This will allow us to debug a strange push failure that I've seen.
=> Use throw instead of throw ex to preserve call stack

src/DatabaseMigrationTools/DatabaseMigrationTools.csproj, src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj, src/NuGetGallery.Core/NuGetGallery.Core.csproj, src/NuGetGallery.Services/NuGetGallery.Services.csproj, src/NuGetGallery/Areas/Admin/Controllers/ValidationController.cs, src/NuGetGallery/Areas/Admin/Services/ValidationAdminService.cs, src/NuGetGallery/Areas/Admin/ViewModels/NuGetPackageValidationViewModel.cs, src/NuGetGallery/Areas/Admin/ViewModels/ValidationPageViewModel.cs, src/NuGetGallery/NuGetGallery.csproj
Updates the Gallery to the latest validation database entities, which had breaking changes. Note that this change does not display generic validations, this will be added by https://github.com/NuGet/Engineering/issues/3587.
See: https://github.com/NuGet/ServerCommon/pull/357
Part of: https://github.com/NuGet/Engineering/issues/3576
=> Update the Gallery to reflect the latest validation database

src/NuGetGallery/Scripts/gallery/page-display-package.js, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
We currently are using bootstrap popover in nuget gallery, tooltips uses aria-describedby which is dynamically added once the tooltip is triggered 
in aria-describedby, it doesn't have aria attribute also it won't focus on the tooltip, what’s why Narrator would not read status. Besides that Narrator doesn’t read data content attribute as well.  For other screen readers like NVDA, they would read data content. That’s why our current fix in gallery work with NVDA, not Narrator.
This is common issue that existing in bootstrap community.(https://github.com/twbs/bootstrap/issues/28446)
This is workaround for narrator announce the staus of copy button to statisfy accessibility requirement
expected behavior with current changes: Narrator will …
=> workaround for narrator announce the status changes of copy button

src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs, src/NuGetGallery.Core/Services/CorePackageFileService.cs, src/NuGetGallery.Core/Services/ICoreFileStorageService.cs, src/NuGetGallery.Core/Services/ICorePackageFileService.cs, src/NuGetGallery/Services/FileSystemFileStorageService.cs, tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceFacts.cs, tests/NuGetGallery.Core.Facts/Services/CorePackageFileServiceFacts.cs
Added new methods to retrieve the file/package uri. This will help us support sas tokens that are not generated on methods that returns an uri with the sas token embeded.
=> [SAS Token] Create get only uri methods for files.

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/dist/js/bootstrap.js, src/Bootstrap/less/theme/page-display-package.less, src/NuGetGallery/Extensions/CakeBuildManagerExtensions.cs, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, tests/NuGetGallery.Facts/Extensions/CakeBuildManagerExtensionsFacts.cs, tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
Add installation instructions of NuGet packages in Cake scripts.
Credits to Nils Andresen ( @nils-a ), member of the Cake team, who did all the hard work :muscle:
| :jigsaw: | Packages identified as Cake extension of type "Addin" (via tags) |
|:---: | --- |
| | ![image](https://user-images.githubusercontent.com/177608/109409604-86344980-796a-11eb-8f93-c147eabf07ac.png) |
| | Packages of type `Dependency` that have the tag `cake-addin` |
---
| :jigsaw: | Packages identified as Cake extension of type "Module" (via tags) |
|:---: | --- |
| | ![image](https://user-images.githubusercontent.com/177608/109409748-a0baf280-796b-11eb-8b8b-eef7d283b870.png) |
| | Packages of type `Dependency` that have the tag `cake-module` |
---
| :jigsaw: | Packages identified as Cake extension of type "Recipe" …
=> Implementation of Cake tab with instructions for NuGet packages

src/NuGet.Services.Entities/NuGet.Services.Entities.csproj, src/NuGetGallery.Core/NuGetGallery.Core.csproj, src/NuGetGallery.Services/NuGetGallery.Services.csproj, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Web.config, tests/NuGetGallery.Facts/ExtensionMethodsFacts.cs, tests/NuGetGallery.FunctionalTests/NuGetGallery.FunctionalTests.csproj
Finally addresses https://github.com/NuGet/NuGetGallery/issues/8280.
Mostly brings support for `MIT-0` license in license expressions. Techincally, we only needed to update `NuGet.Packaging` to get it, but I had all client libraries updated to have their versions aligned.
Had to update some tests due to a [bugfix](https://github.com/NuGet/Home/issues/10177) in the client library.
=> Updating the client libraries to 5.9

src/NuGetGallery.Services/PackageManagement/IPackageService.cs, src/NuGetGallery.Services/PackageManagement/PackageService.cs, tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
Addresses: https://github.com/NuGet/NuGetGallery/issues/8386
The existing logic in `PackageService` relies on `package.GetSupportedFrameworks`, which while giving (largely) correct data, doesn't give enough of it--~85% with this change increasing it to ~93%. The new method in `PackageService` utilizes the restore logic employed by restore, gathering it into a single location for easy and robust maintenance. This logic will give us the supported frameworks for packages whose anatomy follows our guidelines, e.g. https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks. Some notes on this:
- Pattern set matching is our heuristic here--the only time we use the nuspec (which has misled us in the prior approach) is to determine package type, specifically …
=> New TFM logic for package ingestion

src/NuGetGallery/Extensions/CakeBuildManagerExtensions.cs, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, tests/NuGetGallery.Facts/Extensions/CakeBuildManagerExtensionsFacts.cs
This PR adds the Cake tab for `PackageType=DotnetTool`, which was not included in the [initial proposal](https://github.com/NuGet/NuGetGallery/issues/8381) because at the time of the proposal support for .NET Tools in Cake was provided by a community package.
Since then this feature has been added to the Cake core codebase and now Cake supports installing .NET tools directly from within Cake scripts through the `#tool` directive & `dotnet` scheme as shown in the screenshot below.
| :hammer_and_wrench: | Packages identified as .NET tool (via PackageType) |
|:---: | --- |
| | ![image](https://user-images.githubusercontent.com/177608/109409586-5dac4f80-796a-11eb-862a-f0b0a84a4df8.png) |
| | Packages of type `DotnetTool` |
---
/cc @joelverhagen
Addresses …
=> Implementation of Cake tab with instructions for .NET Tool packages

src/GalleryTools/Commands/BackfillCommand.cs, src/GalleryTools/Commands/BackfillDevelopmentDependencyMetadataCommand.cs, src/GalleryTools/Commands/BackfillRepositoryMetadataCommand.cs, src/GalleryTools/Commands/BackfillTfmMetadataCommand.cs, src/GalleryTools/GalleryTools.csproj, src/GalleryTools/Program.cs, src/NuGetGallery.Core/Entities/EntitiesContext.cs, src/NuGetGallery.Core/Entities/IEntitiesContext.cs, src/VerifyMicrosoftPackage/Fakes/FakeEntitiesContext.cs, tests/NuGetGallery.Facts/TestUtils/FakeEntitiesContext.cs
Please address https://github.com/NuGet/NuGetGallery/pull/8432 first (this PR depends on it).
Addresses: https://github.com/NuGet/Engineering/issues/3605
This adds a new backfill command to update TFM details in packages, using the improved logic in the abope PR's branch. Some notes on this:
- In order to get a file list efficiently from the flat container blob, I've used @joelverhagen's Knapcode.MiniZip utility to extract from the stream the file list--this circumvents the needs to download the whole nupkg.
- Backfill commands all extend `BackfillCommand`, and while the structure of the type is appropriate for use here, I needed to make it more flexible while not compromising other backfill jobs. For example, specifying includes and limits in query sets, and providing the above file list …
=> Use new TFM logic for package ingestion in backfill command

src/NuGetGallery.Services/PackageManagement/IPackageService.cs, src/NuGetGallery.Services/PackageManagement/PackageService.cs, src/NuGetGallery/Controllers/UsersController.cs, src/NuGetGallery/Helpers/ViewModelExtensions/ListPackageItemRequiredSignerViewModelFactory.cs, src/NuGetGallery/Services/IPackageVulnerabilitiesService.cs, src/NuGetGallery/Services/PackageVulnerabilitiesService.cs, src/NuGetGallery/ViewModels/ManagePackagesViewModel.cs, src/NuGetGallery/ViewModels/PackageViewModel.cs, tests/AccountDeleter.Facts/EvaluatorFacts.cs, tests/NuGetGallery.Facts/Controllers/OrganizationsControllerFacts.cs, tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs, tests/NuGetGallery.Facts/Services/DeleteAccountServiceFacts.cs, tests/NuGetGallery.Facts/Services/PackageVulnerabilitiesServiceFacts.cs, tests/NuGetGallery.Facts/ViewModels/ListPackageItemRequiredSignerViewModelFacts.cs
Addresses view model portion of https://github.com/NuGet/NuGetGallery/issues/8361.
The intent is to add an `IsVulnerable` field to the packages listed in the Manage Packages view. The packages listed (in both the listed and unlisted lists) are the latest versions of those packages. If those latest versions are vulnerable, we want to display a warning, indicating that something needs to be done. It will be generic and will direct customers to the Package Details page for more information.
=> Add IsVulnerable to Manage Packages view model

src/VerifyGitHubVulnerabilities/Configuration/VerifyGitHubVulnerabilitiesConfiguration.cs, src/VerifyGitHubVulnerabilities/Job.cs, src/VerifyGitHubVulnerabilities/Verify/IPackageVulnerabilitiesVerifier.cs, src/VerifyGitHubVulnerabilities/Verify/PackageVulnerabilitiesVerifier.cs, src/VerifyGitHubVulnerabilities/VerifyGitHubVulnerabilities.csproj
Addresses: https://github.com/NuGet/Engineering/issues/3623
The verification test already existed for doing a full set check of database vulnerabilities--this change adds the capability of downloading registration metadata blobs to determine that the pipeline has propagated incremental changes correctly.
The config file changes allow you to test either or both.
=> Extend vulnerabilities verification to metadata

sign.thirdparty.props
Build broken due to Knapcode.MiniZip.dll not being 3rd party signed. Added.
=> Add Knapcode.MiniZip to 3rd party signing

src/NuGetGallery.Services/Configuration/FeatureFlagService.cs, src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs, src/NuGetGallery.Services/PackageManagement/PackageService.cs, src/NuGetGallery/App_Data/Files/Content/flags.json, src/NuGetGallery/Controllers/UsersController.cs, src/NuGetGallery/ViewModels/ManagePackagesViewModel.cs, src/NuGetGallery/Views/Users/Packages.cshtml, src/VerifyMicrosoftPackage/Fakes/FakeFeatureFlagService.cs
I've done some perf testing in DEV, and it's a slight regression, so I want to release this specific page under its own flag. 
Part of this work: https://github.com/NuGet/NuGetGallery/issues/8361
...and a follow on from https://github.com/NuGet/NuGetGallery/pull/8436 and https://github.com/NuGet/NuGetGallery/pull/8435
The regression on this page is around 50% in DEV, but it's only a matter of 2 seconds so unsure how it will scale. Would like to see it on PROD data with the ability to disable it.
=> Give the manage packages page its own PVA flag

src/NuGetGallery/ViewModels/PackageManagerViewModel.cs, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Implementation of the tab with installation instructions for .NET local tools:
- Rename the existing `.NET CLI` tab to `.NET CLI (Global)`
- Update the info text at the bottom:
```diff
- This package contains a .NET Core Global Tool you can call from the shell/command line
+ This package contains a .NET tool you can call from the shell/command line
```
- Add a new tab `.NET CLI (Local)` with the following instructions:
```
dotnet new tool-manifest # if you are setting up this repo
dotnet tool install --local <ToolName> --version <ToolVersion>
```
---
---
---
Addresses https://github.com/NuGet/NuGetGallery/issues/8373
=> Add dotnet local tool instructions tab

src/NuGetGallery/Services/PackageMetadataValidationService.cs, src/NuGetGallery/Strings.Designer.cs, src/NuGetGallery/Strings.resx
reject empty readme file: 
correct error message for invalid extension: 
Addresses https://github.com/NuGet/Engineering/issues/3707, https://github.com/NuGet/NuGetGallery/issues/8460
=> reject empty readme file & fix error message for invalid extension

src/NuGetGallery/App_Start/DefaultDependenciesModule.cs, src/NuGetGallery/Services/CloudReportService.cs, src/NuGetGallery/Services/JsonAggregateStatsService.cs
Adds support for sourcing other reports from the alternate stats container.
Currently, feature flagging is all-or-nothing.
=> [Statistics]Adding Support for other reports from alternate container

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
This is a follow up to https://github.com/NuGet/NuGetGallery/pull/8375
Since `#r` is not exclusive to F#, it is a bit inaccurate to use the current header for the instructions - it would make sense to use a more generic name for it. 
Therefore I propose to rename `F# Interactive` to `.NET Interactive` as it then correctly captures both C# and F#.
=> improved the #r directive instructions

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-add-organization.less, src/NuGetGallery/Views/Organizations/Add.cshtml
Addresses: https://github.com/NuGet/NuGetGallery/issues/8492
Adds red asterisk to required fields on add organizations page
Note that the screen reader also reads "required" for these now.
This change is consistent with: https://github.com/NuGet/NuGetGallery/blob/main/src/Bootstrap/less/theme/page-manage-organizations.less#L46
=> Added mandatory styles to add organizations page

src/NuGetGallery.Core/Infrastructure/AzureEntityList.cs, src/NuGetGallery.Core/Infrastructure/TableErrorLog.cs, src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
Using connection string factory in `AzureEntityList`  instead of explicit connection string. Allows singleton to refresh connection string.
=> Preparing ErrorLog for secret refresh.

src/NuGetGallery.Core/Auditing/CloudAuditingService.cs, src/NuGetGallery/App_Start/DefaultDependenciesModule.cs, tests/NuGetGallery.Core.Facts/Auditing/CloudAuditingServiceTests.cs
Changed `CloudAuditService` to use `ICloudBlobClient` to access blob storage instead of using SDK classes directly, so it is ready for secret refresh changes. Also, DI registration was updated to resolve all dependencies within DI container instead of pulling in values from closures, which should help with secret refresh, too.
=> CloudAuditService preparing for secret refresh

src/NuGetGallery/Scripts/gallery/page-display-package.js, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
before changes: 
Clicking the Show More link clears the URL fragment and goes to the top of the page.
after changes: 
The README should expand but the viewport should stay where it is.
Addresses https://github.com/NuGet/NuGetGallery/issues/8461
=> show more link jumps problem

src/GitHubVulnerabilities2Db/Fakes/FakeContentService.cs, src/GitHubVulnerabilities2Db/Fakes/FakeFeatureFlagService.cs, src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj, src/GitHubVulnerabilities2Db/Job.cs
Address: https://github.com/NuGet/NuGetGallery/issues/8515
Dependency injection was broken by the inclusion of the feature flag service in the package service constructor. Added a fake type for this and moved it and an additional fake into a fakes directory.
[this surfaced in BCDR analysis]
=> Fix break in githubvulnerabilities2db dependency injection

src/GalleryTools/Commands/BackfillCommand.cs, src/GalleryTools/Commands/BackfillTfmMetadataCommand.cs
Backfill job was ordered in such a way as to not work with cursoring. There was a filtering condition removed which also needed to be reinstated. I also upped the batching size to 1000 for the TFM backfill.
=> return backfill to order by date, batch size 1000

src/GitHubVulnerabilities2Db/Fakes/FakeFeatureFlagService.cs, src/NuGetGallery.Services/Configuration/FeatureFlagService.cs, src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs, src/NuGetGallery/Controllers/PagesController.cs, src/NuGetGallery/ViewModels/GalleryHomeViewModel.cs, src/NuGetGallery/Views/Pages/Home.cshtml, src/NuGetGallery/Views/Shared/Gallery/Header.cshtml, src/VerifyMicrosoftPackage/Fakes/FakeFeatureFlagService.cs
add feature flag to display banner.
Addresses https://github.com/NuGet/NuGetGallery/issues/8525
=> add feature flag for banner

src/GalleryTools/Commands/BackfillCommand.cs, src/GalleryTools/Commands/BackfillTfmMetadataCommand.cs
Pivoting to use `ToShortNameOrNull` introduced the possibility of nulls (which are explicitly returned by this method for the `any` TFM), and these need to be excluded from the collection list--these packages were throwing.
Also removed a redundant catch, as the calling method has an identical catch which will log collection errors.
=> adjust backfill logic - remove redundant catch, process null TFMs

src/NuGetGallery/App_Start/AppActivator.cs, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Scripts/gallery/page-list-packages.js, src/NuGetGallery/Views/Shared/ListPackages.cshtml, src/NuGetGallery/Views/Shared/_ListPackage.cshtml
Addresses: https://github.com/NuGet/NuGetGallery/issues/8490
We need a tab stop on this checkmark (`tabindex='0'` means it won't mess with tab ordering), and an id that can be found by the popover code. This will respond to hover and focus events.
Screenreaders also read the text as written (tested on Narrator and NVDA).
Just realized how fast this popover flashes by in the below video. The text is the same as the current tooltip: 
```The ID prefix of this package has been reserved for one of the owners of this package by NuGet.org```
=> [a11y] Add popovers to verification checkmarks

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Added `tabindex` to every `td` tag on the version history table so that the value can be announced using NVDA or other announcers.
Addresses https://github.com/NuGet/NuGetGallery/issues/8491
=> [A11y] Make announcers read the version history table data correctly.

src/NuGetGallery/Views/Users/ApiKeys.cshtml
* Added aria-required="true" to announce a required input.
Addresses https://github.com/NuGet/NuGetGallery/issues/8494
=> [A11Y] Screenreader does not read required keyword for the control “Package Owner".

src/GalleryTools/Commands/BackfillCommand.cs, src/GalleryTools/Commands/BackfillTfmMetadataCommand.cs
Logic tweak--exceptions were still sneaking through because the try block for harvesting TFMs only surrounded the method call doing the extraction - it didn't surround the loop enumerating them. The collection is `IEnumerable`, so of course throwing can still take place while enumerating. The diffing isn't great here, but that's what's happening in `UpdatePackage`. Forcing another enumeration `ToList` is for the same reason.
Also, the case where no TFMs were being persisted to the metadata file was throwing on the update cycle. I needed to null the `MissingFieldFound` action on the csvReader (this instruction comes from the exception thrown by csvReader). The null case is covered in update code so this fixed the issue.
=> Adjust try blocks, repair empty TFM metadata case

src/NuGetGallery/Areas/Admin/Views/SupportRequest/Index.cshtml
Addresses: https://github.com/NuGet/NuGetGallery/issues/8535
A text update for the hint of the text area in the support request edit dialog, prompting users to format their resolution to cover the  data we need for searches.
=> Adjust support request hint to include DMCA text

src/NuGetGallery/App_Start/DefaultDependenciesModule.cs, src/NuGetGallery/Services/PackageVulnerabilitiesService.cs, tests/NuGetGallery.Facts/Services/PackageVulnerabilitiesServiceFacts.cs
* Detail 1
* Detail 2
Addresses https://github.com/NuGet/Engineering/issues/3788#issuecomment-816126501
=> change sql get vulnerabilities by package id

src/NuGetGallery/Views/Users/ApiKeys.cshtml
The cancel button is announced as expanded when it's clickable (you don't know it's collapse because it's disabled), but since that button doesn't actually expands data we got a bug for that behavior.
* removed collapse from cancel button.
Addresses https://github.com/NuGet/NuGetGallery/issues/8496.
=> [A11y] Remove collapse from cancel button in ApiKey page.

src/NuGetGallery/Views/Users/ApiKeys.cshtml
* Moved aria-labelledby to `label` instead of the `input` element.
With this change it's more clear that radio button is checked or not when traversing the page with arrow keys.
Addresses https://github.com/nuget/nugetgallery/issues/8495.
=> [A11y] Moved aria-labelledby so that announcer says correctly radio button grouping.

src/NuGetGallery/App_Data/Files/Content/flags.json
- currently cannot upload package with embedded readme or icons in local development enviroment as the features were disabled by default
- Found that both features were missing flights, so added them in and set to true for all
Addresses https://github.com/NuGet/NuGetGallery/issues/8557
=> fixed missing flights for icons and readMes

src/GalleryTools/Commands/BackfillCommand.cs, src/GalleryTools/Commands/BackfillTfmMetadataCommand.cs, src/NuGetGallery/App_Data/Files/Content/flags.json, src/NuGetGallery/App_Start/AppActivator.cs, src/NuGetGallery/Areas/Admin/Views/SupportRequest/Index.cshtml, src/NuGetGallery/Infrastructure/Lucene/CloudDownloadCountServiceRefreshJob.cs, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Scripts/gallery/page-list-packages.js, src/NuGetGallery/Services/CloudDownloadCountService.cs, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, src/NuGetGallery/Views/Packages/UploadPackage.cshtml, src/NuGetGallery/Views/Packages/_VerifyMetadata.cshtml, src/NuGetGallery/Views/Shared/ListPackages.cshtml, src/NuGetGallery/Views/Shared/_ListPackage.cshtml, src/NuGetGallery/Views/Users/ApiKeys.cshtml, src/NuGetGallery/Web.config, tests/NuGetGallery.Facts/Services/CloudDownloadCountServiceFacts.cs
Tracked by https://github.com/NuGet/NuGetGallery/issues/8552
=> [ReleasePrep][2021.04.26] RI of dev into main

src/NuGetGallery/Views/Packages/_VerifyMetadata.cshtml
Hides licence file section on package upload if empty.
Addresses https://github.com/NuGet/NuGetGallery/issues/8547
=> Hide Licence file section on package upload if empty

src/NuGetGallery/Scripts/gallery/page-display-package.js
we are using clamp.js to cut off the html element.  Here we are going to increase the number of lines to cut off. 
clamp(): this controls where and when to clamp the text of an element. 
useNativeClamp (Boolean). Enables or disables using the native -webkit-line-clamp in a supported browser (ie. Webkit). It defaults to true if you're using Webkit, but it can behave wonky sometimes so you can set it to false to use the JavaScript- based solution.
```
var height = getMaxHeight(clampValue);
if (height <= element.clientHeight) {
clampedText = truncate(getLastChild(element), height);
}
```
before: 
after : 
Addresses https://github.com/NuGet/NuGetGallery/issues/8564
=> show some content of readme if is too long

src/NuGetGallery/Helpers/ViewModelExtensions/PackageViewModelFactory.cs, src/NuGetGallery/ViewModels/PackageViewModel.cs, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, src/NuGetGallery/Views/Shared/_ListPackage.cshtml
Minor changes to the UI so that the version metadata only appears inside an info box on the view package page. Before:
after:
The issue has a screenshot of a warning but it seems to be that an info box might be more appropriate, as version metadata isn't really cause for an alert.
The build metadata is also removed from the search page. Before:
after:
Addresses https://github.com/NuGet/NuGetGallery/issues/7662
=> Display version metadata only in an info box

src/GalleryTools/Commands/BackfillCommand.cs
This makes monitoring a large-scale collect/update job a lot easier to track--it writes a monitoring cursor (date only) file every time it updates the locked cursor file. Not being locked, the monitoring cursor can be inspected randomly to determine progress.
=> [non-Gallery] Add a non-locked monitoring cursor for inspection during backfill job

src/NuGetGallery/Controllers/AppController.cs, src/NuGetGallery/Controllers/PagesController.cs, src/NuGetGallery/ViewModels/GalleryHomeViewModel.cs, src/NuGetGallery/Views/Pages/Home.cshtml, tests/NuGetGallery.Facts/Controllers/AppControllerFacts.cs, tests/NuGetGallery.Facts/Controllers/StatisticsControllerFacts.cs
before: banner only show on the home page
after: banner show on all pages
package details page: 
Upload package page: 
Addresses https://github.com/NuGet/NuGetGallery/issues/8525
=> Add banner to all pages

src/GitHubVulnerabilities2Db/Gallery/ThrowingTelemetryService.cs, src/NuGetGallery.Services/Telemetry/ITelemetryService.cs, src/NuGetGallery.Services/Telemetry/TelemetryService.cs, src/NuGetGallery/App_Start/OwinStartup.cs, src/VerifyMicrosoftPackage/Fakes/FakeTelemetryService.cs, tests/NuGetGallery.Facts/Services/TelemetryServiceFacts.cs
Progress on https://github.com/NuGet/Engineering/issues/3718.
Since transient configuration objects have too much of a performance impact, instead of going that way, we'll track the Gallery instance uptime so we could make an alert that would tell us that we hadn't deployed for a while.
=> Gallery instance uptime tracking

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/all.less, src/Bootstrap/less/theme/page-display-package-v2.less, src/GitHubVulnerabilities2Db/Fakes/FakeFeatureFlagService.cs, src/NuGetGallery.Services/Configuration/FeatureFlagService.cs, src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs, src/NuGetGallery/App_Data/Files/Content/flags.json, src/NuGetGallery/App_Start/AppActivator.cs, src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Scripts/gallery/page-display-package-v2.js, src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml, src/NuGetGallery/Web.config, src/VerifyMicrosoftPackage/Fakes/FakeFeatureFlagService.cs, tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs, tests/NuGetGallery.Facts/TestUtils/ResultAssert.cs, tests/NuGetGallery.FunctionalTests/StaticAssets/StaticAssetsTests.cs
Created a flight for the new page design and created the necessary duplicate files for my changes. I also made all the necessary additions so those files would work if flight turned off. 
If you have any questions for why I am doing this look at the Display Package Page Redesign Engineering spec, comment, or reach out to me.
=> New Display Package Page: created flight and setup for implementation of new page 

src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml
For the redesign of the display package page, the new layout follows this image 
In order to achieve this I used Bootstraps grid feature to create this new layout. Here is the code needed to achieve this structure without any of the page content. Below it is the output that the code creates
I used this code as a guide for editing the DispayPackageV2.cshtml as to not impact the existing page. After completeing my changes, the page now looks like this 
The mobile view looks like this 
To check that my solution had worked I ran the page and 
- checked that there were no errors in the .js by looking at the console 
- collapsed the code so that only the row/column divs were shown and compared to the simplified structure code above 
- Inspected the page and hovered over the sections to see that …
=> Created gird for new page layout of Display Package Page for redesign 

src/NuGetGallery/Scripts/gallery/common.js, src/NuGetGallery/Scripts/gallery/page-display-package.js, src/NuGetGallery/Scripts/gallery/page-list-packages.js, src/NuGetGallery/Scripts/gallery/page-manage-packages.js, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, src/NuGetGallery/Views/Users/Packages.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/8623.
=> Add accessible popovers to vulnerability alerts

src/NuGetGallery/Helpers/ViewModelExtensions/DisplayPackageViewModelFactory.cs, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs
Add message about embedded readme available after validation 
after: 
Addresses: https://github.com/NuGet/NuGetGallery/issues/8507
=> [Readme]Add message for readme during validation

src/GitHubVulnerabilities2Db/Collector/AdvisoryQueryBuilder.cs, src/GitHubVulnerabilities2Db/GraphQL/SecurityVulnerability.cs, tests/GitHubVulnerabilities2Db.Facts/AdvisoryIngestorFacts.cs
Addresses: https://github.com/NuGet/NuGetGallery/issues/8474
All of the logic exists in the service and UTs for processing the withdrawn field, but it needs to be added to the query.
Note that there are no withdrawn advisories for NuGet packages at this time, but we need this in place.
=> Ingest withdrawn data in GitHub GraphQL

src/NuGetGallery/App_Data/Files/Content/flags.json
enable NuGetGallery.ImageAllowlist and NuGetGallery.MarkdigMdRendering in local environment to alig with prod
=> Set default flags in local environment 

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-display-package-v2.less, src/NuGetGallery/App_Data/Files/Content/flags.json, src/NuGetGallery/Scripts/gallery/page-display-package-v2.js, src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml
I used bootstrap to created tabs to match the new redesign. The tabs were made sticky the same way that the installation tabs are by adding code in the .js file that saves the last tab clicked onto local storage. For styling, I went into the .less file and added the blue bar at the bottom of the clicked on tab and added padding to keep the distance of the tab content to the tabs consistent for each content. The final now looks like this: 
The mobile is still a work in progress as we are finalizing how we want it to look to keep the experience just as strong as it will be on desktop. All the features and experiences are the same currently and the only issue is the tabs in the bottom row get pushed if a tab in the top row is clicked(see picture below). We decided to punt this as we have a …
=> Tabs for the new Display Package page redesign 

src/GitHubVulnerabilities2Db/Fakes/FakeFeatureFlagService.cs, src/NuGetGallery.Services/Configuration/FeatureFlagService.cs, src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs, src/NuGetGallery.Services/Models/ReportPackageReason.cs, src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/Views/Packages/ReportAbuse.cshtml, src/VerifyMicrosoftPackage/Fakes/FakeFeatureFlagService.cs
Addresses https://github.com/NuGet/NuGetGallery/issues/8590
Spec: https://github.com/NuGet/Home/blob/dev/proposed/2021/NuGetOrgReportForm-SafetyChanges.md
- Adds online safety categories and associated text to form
- Adds tab indexes for a11y to other text (more a11y work is needed for this form, but this was a quick win for now)
- Removed contacted owner checkbox for safety categories - we don't want customers to feel they should do this
- All under a feature flag for now
[note that the gif below shows inconsistent "the" and "this" in dropdown. Since fixed.]
=> [online safety] Add safety categories to report abuse form

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-display-package-v2.less, src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml
This PR is all about styling the header of the new display package page. I changed the sizing, spacing, and colors of the header elements to match the redesign mock ups. I also added a "prefix reserved" label that links to the ID prefix reservation docs. The goal of this PR was do all the necessary changes in the header except for the installation instructions, so I have left them untouched and will do those changes in a later PR. Here is what the final product looks like 
I tested all the links to make sure that they worked with the feature flag on and off, checked the console to make sure that there were no errors in the .js file, and resized the page to make sure the styling stayed the same. 
This addresses issue #8601
=> Styled Header for new display package page

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/common-readme.less, src/NuGetGallery/App_Data/Files/Content/flags.json
Remove bullet point for task list when  we render readme markdown
before:
After:
display page:
upload page: 
manage package page: 
Addresses https://int.nugettest.org/packages/license-expression-test4
=> remove bullet point for tasklist

src/NuGetGallery/Services/ImageDomainValidator.cs, tests/NuGetGallery.Facts/Services/ImageDomainValidatorFacts.cs
by adding the missing `/actions/` segment into the URL regex
`GithubBadgeUrlRegEx`.
Addresses https://github.com/NuGet/NuGetGallery/issues/8645
=> Fixed ImageDomainValidator for GitHub URLs

src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml
I added a warning for packages without READMEs that only owners can see. It is meant to let them know that the package description is being shown in the README tab when there is no README. Along with telling them what is being shown it also links to docs on package READMEs on NuGet.org. 
Here is the link to the docs: https://docs.microsoft.com/nuget/nuget-org/package-readme-on-nuget-org
Here is what it looks like when logged in as the owner
Here is what it looks like when not an owner
=> Added warning banner for owners that description is in README tab

build.ps1
- BuildBranch was changed to BuildBranchCommit to reflect the actual value.
- BuildBranchCommit now points to the newest commit that's needed for migrating to new Agent Pools.
=> [Microbuild] NuGetGallery Update ServerCommon commit on build.ps1.

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-display-package-v2.less, src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml
I rearranged the information in the sidebar and got rid of Authors to match the redesign mockups. This included moving the download information to the top of the sidebar, moving report to above the tags, and adding the full stats and contact owners link to be across from their respective header. I then went into the .less files and added the necessary styling changes to match the mockups. This included rounding the owner icons, changing the color and spacing of the section headers, and changing the font size of all the text. 
Here is what it looks like now:
Here is what the whole page looks like:
In order to test my changes I checked the console to make sure nothing happened to the .js file. Inspected the elements to make sure that the corrected styling was being applied to them, and made …
=> Sidebar for New Display Package Page

src/NuGetGallery/Filters/ApiAuthorizeAttribute.cs, src/NuGetGallery/Strings.Designer.cs, src/NuGetGallery/Strings.resx, tests/NuGetGallery.Facts/Filters/ApiAuthorizeAttributeFacts.cs
Improve expiration warning messages and adds unit tests.
Addresses https://github.com/NuGet/NuGetGallery/issues/8675
=> Improve API key expiration warnings

src/NuGetGallery/Services/MarkdownService.cs, tests/NuGetGallery.Facts/Services/MarkdownServiceFacts.cs
Fixes https://github.com/NuGet/NuGetGallery/issues/8642
=> Fix newline breaks in markdown

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/dist/css/bootstrap.css, src/Bootstrap/less/buttons.less, src/Bootstrap/less/theme/page-display-package-v2.less, src/NuGetGallery/Scripts/gallery/page-display-package-v2.js, src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml
Addresses https://github.com/nuget/nugetgallery/issues/8602
<details>
<summary>Default screenshot...</summary>
Package with long ID:
</details>
<details>
<summary>Installation instructions with banners below...</summary>
</details>
<details>
<summary>Multi-line installation instructions...</summary>
</details>
<details>
<summary>.NET Tools...</summary>
</details>
<details>
<summary> ⚠ .NET Template...</summary>
⚠ NOTE: There is only one package manager that supports .NET Templates today. The UI has a dropdown with only a single option.
</details>
<details>
<summary>Mobile...</summary>
FYI the installation instructions are sideways scrollable. You can swipe (or is it pan?) to see the text:
</details>
=> [Redesign] Update installation instructions

src/GitHubVulnerabilities2Db/Fakes/FakeFeatureFlagService.cs, src/NuGetGallery.Services/Configuration/FeatureFlagService.cs, src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs, src/NuGetGallery/App_Data/Files/Content/flags.json, src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/Helpers/ViewModelExtensions/DisplayPackageViewModelFactory.cs, src/NuGetGallery/UrlHelperExtensions.cs, src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml, src/VerifyMicrosoftPackage/Fakes/FakeFeatureFlagService.cs, tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs
* A link was added for both detail page versions (current, tabs).
* The link sends you to a nuget.info page where you can see the package assets.
* The link will only be displayed when the package is "Available", to avoid sending the user to a broken/non ready page.
* When you click the link it goes to a new page instead of using the current one.
* Minor refactor to the FuGet link to behave like this one.
Addresses https://github.com/nuget/nugetgallery/issues/8428
=> Display NuGet Package Explorer link on details page.

src/AccountDeleter/AccountDeleter.csproj, src/AccountDeleter/EmptyFeatureFlagService.cs, src/AccountDeleter/EmptyIndexingService.cs, src/AccountDeleter/Job.cs
Stubs out a minimal FeatureFlagService (used by PackageService) to allow DI to proceed successfully.
=> [AccountDeleter]Adding stubbed definition for missing DI objects.

src/NuGetGallery/Scripts/gallery/page-display-package-v2.js, src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml
For packages with an embedded readme, registration's `readmeUrl` links to the display package page using the `#show-readme-container` URL fragment. For example: https://api.nuget.org/v3/registration5-gz-semver2/knapcode.torsharp/index.json:
<details>
<summary>Example registration JSON for package with embedded readme...</summary>
```json
{
...
"items": [
{
...
"items": [
{
...
"@id": "https://api.nuget.org/v3/registration5-gz-semver2/knapcode.torsharp/2.7.0.json",
"catalogEntry": {
...
"licenseUrl": "https://www.nuget.org/packages/Knapcode.TorSharp/2.7.0/license",
"readmeUrl": "https://www.nuget.org/packages/Knapcode.TorSharp/2.7.0#show-readme-container",
...
"version": "2.7.0"
},
...
},
...
],
...
}
]
...
}
```
</details>
In the current design, this is implemented using Bootstrap 3's …
=> [Redesign] Fix registration's link to the README

src/AccountDeleter/EmptyFeatureFlagService.cs, src/NuGetGallery/Scripts/gallery/page-display-package-v2.js
Addresses https://github.com/nuget/nugetgallery/issues/8613
Tested on DEV:
* Test build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5014342&view=results
* Test release: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=1107455
=> [Redesign] Add telemetry

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-display-package-v2.less, src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml
Lighthouse is a tool to check a website follows best practices: https://developers.google.com/web/tools/lighthouse
Category | Score before | Score after | Change
-- | -- | -- | --
Performance | 100 | 100 | -
Accessibility | 96 | 100 | +4
Best practices | 80 | 87 | +7
SEO | 91 | 100 | +9
Remaining issues I did not address:
* Fabric font loading inefficiently. May be fixed by updating `fabric.css`.
* Gallery assets served without efficient cache policy. Tracked by: https://github.com/NuGet/NuGetGallery/issues/8706
* Known vulnerabilities in jQuery@3.4.1 and Moment.js@2.18.1. Tracked by https://github.com/NuGet/Engineering/issues/3983
* SameSite cookie use by WCP consent cookie. Owned by WCP team
Addresses https://github.com/nuget/nugetgallery/issues/8605
=> [Redesign] Improve Lighthouse score

src/AccountDeleter/EmptyFeatureFlagService.cs, src/GitHubVulnerabilities2Db/Fakes/FakeFeatureFlagService.cs, src/NuGetGallery.Services/Configuration/FeatureFlagService.cs, src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs, src/NuGetGallery/App_Data/Files/Content/flags.json, src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/UrlHelperExtensions.cs, src/NuGetGallery/Views/Shared/Gallery/Header.cshtml, src/VerifyMicrosoftPackage/Fakes/FakeFeatureFlagService.cs, tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs, tests/NuGetGallery.Facts/UrlHelperExtensionsFacts.cs
Add a banner that links to a preview of the redesign:
Once on the preview, you see a banner to take a survey:
Addresses https://github.com/nuget/nugetgallery/issues/8672
Build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5022595&view=results
Release: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=1109431
=> [Redesign] Add preview banner & URL

src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml
Fixes a few bugs found while preparing for the bug bash:
1. Show all versions for a package
2. Don't show the "Used by" tag on .NET Tools or if the feature is disabled
3. Removed the repeated `Dependencies` heading if a package's dependencies could not be processed
Part of: https://github.com/nuget/nugetgallery/issues/8606
=> [Redesign] Fix a few bugs

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-display-package-v2.less
<details>
<summary>Before...</summary>
</details>
After:
After (for packages that support all frameworks):
Addresses https://github.com/NuGet/NuGetGallery/issues/8715
Test build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5037654
Test release:
=> [Redesign] Fix spacing of dependency groups

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-display-package-v2.less
Safari does not support the Segoe UI font and falls back to the next font. This does not affect Chrome, Firefox, Edge, Internet Explorer, Opera
Before 🤮
After 💪 
Addresses https://github.com/NuGet/NuGetGallery/issues/8722
Test build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5037774&view=results
Test release: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=1115031
=> [Redesign] Fix Safari font issue

src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml
When package with embedded README is uploaded:
If package fails validation and has an embedded README:
Addresses https://github.com/NuGet/NuGetGallery/issues/8716
Test build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5036467&view=results
Test release: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=1113856
=> [Redesign] Fix README alerts if package hasn't passed validation

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-display-package-v2.less, src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml
Fixes a few problems. Addresses https://github.com/NuGet/NuGetGallery/issues/8719
I recommend reviewing without whitespace changes:
<details>
<summary>Before...</summary>
</details>
<details>
<summary>After...</summary>
</details>
<details>
<summary>Before...</summary>
Notice the scrollbar and the lack of gutter.
</details>
<details>
<summary>After...</summary>
</details>
<details>
<summary>Before...</summary>
Notice the installation instructions do not stretch all the way across.
Notice there is space below the scrollbar.
</details>
<details>
<summary>After...</summary>
</details>
=> [Redesign] Fix visual issues on narrow screens

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-display-package-v2.less, src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml
I recommend reviewing without whitespace changes:
Here is a summary of the changes:
```diff
-* "About package" section
+* "About" section
* Last updated date
* Project website
* Source repository
* License info
-  
-    <whitespace>
- 
* Download package
* Download symbols
+   * "Open in NuGet package explorer" link
+   * "Open in FuGet package explorer" link
+   * "Report package" link
+
+* "Manage" section
* "Manage package" link
* "Delete symbols" link
* "Reflow package" link
* "Revalidate package" link
* "Revalidate symbols" link
* "View validations" link
+   * "Contact support" link 
-   * "Open in NuGet package explorer" link
-   * "Open in FuGet package explorer" link
-   * "Contact support" or "Report package" link
```
<details>
<summary>Screenshot if logged out...</summary> …
=> [Redesign] Address sidebar feedback

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-display-package-v2.less
Without warning:
With warning (notice there is no extra space now and it is consistent as without warning):
Addresses https://github.com/NuGet/NuGetGallery/issues/8729
=> [Redesign] Remove extra space on README warnings

src/NuGetGallery/App_Data/Files/Content/Trusted-Image-Domains.json
Closes https://github.com/NuGet/NuGetGallery/issues/8541
=> Include jsdelivr CDN in the trusted image domains list

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/base.less, src/NuGetGallery/App_Code/ViewHelpers.cshtml, src/NuGetGallery/Areas/Admin/Controllers/ValidationController.cs, src/NuGetGallery/Areas/Admin/Services/ValidationAdminService.cs, src/NuGetGallery/Areas/Admin/Views/Validation/Index.cshtml, src/NuGetGallery/Controllers/PackagesController.cs, tests/NuGetGallery.Facts/Areas/Admin/Services/ValidationAdminServiceFacts.cs, tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
Fix https://github.com/NuGet/NuGetGallery/issues/8702.
This PR makes three changes to the Validation admin panel
1. **Polish:** Redirect back to admin panel when clicking an individual revalidate (feedback in retrospective from @loic-sharma)
1. **Bug fix:** Fix the individual revalidate link. Previously, only the first form on the page worked due to duplicate IDs 😨
1. **Feature:** Adds two links to the Validation admin panel
- Revalidate pending packages
- Revalidate pending symbol packages
Each link queries for all entities of the respective type that are in the `Validating` state then enqueues a validation for each entity.
Each link has a confirmation dialog to avoid accidental clicks.
=> Add bulk revalidate buttons to Validation admin panel

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, src/NuGetGallery/Views/Shared/_ListPackage.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/8743
Behavior of the checkmarks is unchanged, attributes added (which may support screen readers that we don't test). We've tested Windows Narrator and NVDA. These new attributes satisfy compliance requirements.
Note that a lot of suggested compliance changes resulted in screen readers reading text twice--adding `role="presentation"` seems to be the cleanest fix.
=> Add role attributes to reserved checkmarks

tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedTests.cs
Currently gallery releases are blocked by this issue, just changed jQuery for Newtonsoft.Json when searching for a package that is part of the top30.
=> [Hotfix] Update test to use Newtonsoft.Json instead of jQuery.

src/NuGetGallery/Helpers/ViewModelExtensions/DisplayPackageViewModelFactory.cs, src/NuGetGallery/Services/PackageVulnerabilitiesCacheService.cs, tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs
Fixes #8703
I'm not sure how much this will impact the performance. Do we have an environment to do any kind of performance test?
I've tried to put the order inside the query but without success.
Accept any tips on this ❤
=> Fixing the vulnerability order inside the dictionary cache

src/NuGetGallery/ViewModels/ThirdPartyPackageManagerViewModel.cs
Screen reader will now announce `Contact the maintainers of the X client` after focusing the maintainers link:
Part of https://github.com/NuGet/NuGetGallery/issues/8790
=> [A11y] Label the maintainers link

src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml
Bootstrap 3 tabs do not have `aria-expanded` or `aria-selected` attributes until the user switches the tab. This causes issues with Windows Narrator. This change manually adds the `aria-expanded` and `aria-selected` attributes to ensure Windows Narrator properly announces these tabs.
Part of https://github.com/NuGet/NuGetGallery/issues/8790
=> [A11y] Make Windows Narrator announce redesign tabs properly

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-display-package-v2.less, src/NuGetGallery/Scripts/gallery/page-display-package-v2.js, src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml
Content in the Used By section gets incorrectly hidden when increasing the spacing in text:
<details>
<summary>Screenshot of bug...</summary>
</details>
This fixes the accessibility bug by using `clamp.js` to clamp text. Note that this bug affects both the old and new designs, however, this fix only targets the redesign.
<details>
<summary>Screenshot of fix with increased spacing disabled...</summary>
Notice there are no visible changes from the current design:
</details>
<details>
<summary>Screenshot of fix with increased spacing enabled...</summary>
Notice how all text is properly visible:
</details>
See WCAG 2.1 requirement: https://www.w3.org/TR/WCAG21/#text-spacing
Part of https://github.com/NuGet/NuGetGallery/issues/8790
=> [A11y] Prevent hidden text when increasing text spacing

src/NuGetGallery/Extensions/NumberExtensions.cs, src/NuGetGallery/GalleryConstants.cs, src/NuGetGallery/Services/PackageMetadataValidationService.cs, src/NuGetGallery/Services/ReadMeService.cs, tests/NuGetGallery.Facts/Extensions/NumberExtensionsFacts.cs, tests/NuGetGallery.Facts/Services/ReadMeServiceFacts.cs
Issue: inconsistent max readme file size between validation during upload and preview readme at manage package page
validation readme max size:
https://github.com/NuGet/NuGetGallery/blob/c71e12429b108c4d87e2da41790b164149a43389/src/NuGetGallery/Services/PackageMetadataValidationService.cs#L61
Preview at manage package: 
https://github.com/NuGet/NuGetGallery/blob/db62de43e24b704e9ab16d8abc39bdfa3e73260b/src/NuGetGallery/Services/ReadMeService.cs#L24
Fix: Make maxmdreadme length to be consistent while uploading and preview
Before:
After: 
Addresses https://github.com/NuGet/NuGetGallery/issues/8771
=> Update maxMdLengthByte to be consistent with validation 

src/NuGetGallery/Scripts/gallery/page-display-package-v2.js, src/NuGetGallery/Scripts/gallery/page-display-package.js, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml
The previous fix (https://github.com/NuGet/NuGetGallery/pull/8758) seems to have broken after the latest Windows update. This new fix aligns with GitHub's solution to this problem.
This solution "flashes" the aria label of the focused item, causing the screen reader to re-announce it. 
Addresses https://github.com/NuGet/NuGetGallery/issues/8809
Addresses: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1061326
This change passes Accessibility Insights FastPass:
Here is what Windows Narrator announces when you press the copy button:
* Before: Nothing :(
* After: `Button, copied`. Then after 1.5 seconds: `Copy the package manager command, button`
Here is what NVDA announces when you press the copy button:
* Before: `Copied, copied` 
* After: `Copied`. Then after 1.5 seconds `Copy the …
=> [A11y] Improve copy button accessibility

src/NuGetGallery/Web.config
Addresses https://github.com/NuGet/Engineering/issues/4071
Differences between .Net 4.5 and 4.7.2: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.5-4.7.2
Concerns:
- https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.5-4.7.2#allow-unicode-bidirectional-control-characters-in-uris (we don't allow non-printable characters neither in package IDs nor in versions nor in usernames, so it shouldn't affect us)
- https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.5-4.7.2#change-in-path-separator-character-in-fullname-property-of-ziparchiveentry-objects (we don't use `CreateFromDirectory` anywhere in Gallery, so shouldn't affect us)
- https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting …
=> Switching httpRuntime to 4.7.2

src/NuGetGallery.Services/Models/ReportPackageReason.cs, src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/ViewModels/ReportViewModel.cs, src/NuGetGallery/Views/Packages/ReportAbuse.cshtml
* Incorporates feedback on contents of report abuse (now "report package") form
* Removed error case on bug/failed to install as we now need to cover multiple error cases and include hyperlinks. This is achieved through hiding the form and showing the message explicitly on-page.
* Adds security vulnerability instructions
Addresses https://github.com/NuGet/NuGetGallery/issues/8657, https://github.com/NuGet/NuGetGallery/issues/8751 and https://github.com/NuGet/NuGetGallery/issues/8655.
We can track copyright instruction changes in a separate issue.
The top of the form now looks like this: 
Updated Reason dropdown:
Updated bug/failed to restore error:
New security vulnerability error:
=> Streamline report package page and add vulnerability text

src/DatabaseMigrationTools/DatabaseMigrationTools.csproj, src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj, src/NuGetGallery.Core/NuGetGallery.Core.csproj, src/NuGetGallery.Services/Configuration/ConfigurationService.cs, src/NuGetGallery.Services/NuGetGallery.Services.csproj, src/NuGetGallery/App_Start/DefaultDependenciesModule.cs, src/NuGetGallery/NuGetGallery.csproj, tests/NuGetGallery.Facts/App_Start/ConfigurationServiceFacts.cs, tests/NuGetGallery.Facts/App_Start/DefaultDependenciesModuleFacts.cs, tests/NuGetGallery.Facts/Framework/TestGalleryConfigurationService.cs
Addresses #8858 
All the changes are in https://github.com/NuGet/ServerCommon/pull/374
This just applies the API change to Gallery. `CreateDbConnection` method was updated to call sync version that tries to use cache and simply fails if any required information is not cached, then it falls back to the old behavior.
Some basic tests in dev indicate that the change reduces the amount of `Task.Result` calls in `CreateDbConnection` by a factor of more than 100x.
=> Trying to create sync DB connection synchronously before doing async

src/NuGetGallery/App_Start/AppActivator.cs
Fixed incorrect call to `Routes.RegisterRoutes` which prevented admin access to some pages.
=> [Hotfix] Registering admin panel routes when admin panel is not disabled.

Directory.Build.props
The old Roslyn Analyzer package has been deprecated and not recommended:
https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/
This is to use the new one.
=> Update Roslyn Analyzer

src/NuGetGallery/Views/Packages/ReportAbuse.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/8899
This change instructs the reporter of abuse to include specifics that will help us address the problem quickly. The other accommodations for online safety reporting (no contact checkbox, additional detail for imminent harm reporting, revenge porn portal directions) are all preserved.
=> Additional online safety instructions in report package page

src/NuGetGallery/Scripts/gallery/page-display-package-v2.js, src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/8897
- Adds the popovers into the new v2 package details page for reserved checkmarks (including alt tag) and vulnerable/deprecated bangs. 
- Narrator support also restored.
- There needed to be tab stops added to ID and version at the top. 
- I also removed a double tab stop on the versions in the version table.
Here are the changes (I pause and point at them):
=> Re-add a11y to checkmarks and bangs in package details page

src/DatabaseMigrationTools/DatabaseMigrationTools.csproj, src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj, src/NuGetGallery.Core/NuGetGallery.Core.csproj, src/NuGetGallery.Services/NuGetGallery.Services.csproj, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Web.config, tests/NuGetGallery.FunctionalTests/NuGetGallery.FunctionalTests.csproj
- Update reference to 2.94.0 where built from serverCommon
- Update NuGet.packaging to 6.0.0 align with serverCommon, avoid package downgrading.
ServerCommon: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5560161&view=artifacts&pathAsName=false&type=publishedArtifacts
=> Update ServerCommon version to pull in the latest Markdig version (0.26.0)

src/NuGetGallery/Views/Packages/ReportAbuse.cshtml
Addresses: https://github.com/NuGet/Engineering/issues/4172
Removes an unnecessary link from the Report Package page (see issue for details).
=> Remove cybertip link from report package page

src/AccountDeleter/EmptyFeatureFlagService.cs, src/GitHubVulnerabilities2Db/Fakes/FakeFeatureFlagService.cs, src/NuGetGallery.Services/Configuration/FeatureFlagService.cs, src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs, src/NuGetGallery/App_Data/Files/Content/flags.json, src/VerifyMicrosoftPackage/Fakes/FakeFeatureFlagService.cs
- `ComputeTargetFramework`: This feature flag will be turned on to perform computations on the backend for TFM work, this will help us to check performance before showing TFM to public.
- `DisplayTargetFramework`: This flight is to help testing the behavior of TFMs on display page showing both badges and tab, if this feature flag is turned on, it will override the `ComputeTargetFramework `behavior.
Address: https://github.com/NuGet/Engineering/issues/4183.
=> [TFM Display] Add feature flags for TFM.

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/dist/js/bootstrap.js, src/Bootstrap/less/theme/base.less, src/Bootstrap/less/theme/common-list-packages.less, src/NuGetGallery/Views/Shared/_ListPackage.cshtml
Fixes https://github.com/NuGet/NuGetGallery/issues/8921
When viewing package search results on nuget.org, the links for the tags were indistinguishable from non-hyperlink text around it:
This PR fixes it and changes the tag hyperlink color such that users can differentiate between regular text and the links:
=> [A11y] Fixes tag link color in search results

src/Bootstrap/dist/css/bootstrap.css, src/Bootstrap/less/forms.less, src/Bootstrap/less/mixins/tab-focus.less
Fixes https://github.com/NuGet/NuGetGallery/issues/8924
**Problem:**
On NuGet.org, when navigating a page using the keyboard (tab key), checkboxes were not completely visible, especially in high-contrast mode.
Previous version:
Previous version (high-contrast mode):
**Fix:**
To fix this, I changed the outline to solid (and reduced the size of the outline so it wasn't too big and overbearing).
After making the changes:
New version:
New version (high-contrast mode):
=> [A11y] Improved visibility of checkboxes when keyboard navigating a page (especially in high-contrast mode)

src/NuGetGallery/Scripts/gallery/page-edit-readme.js
NVDA was working fine, but Windows Narrator was not reading readme error alerts. A workaround for this was to add the same error content as aria-label.
Addresses: https://github.com/NuGet/NuGetGallery/issues/8923
=> [A11y Bug] Narrator not announcing error messages for ReadMe.

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/dist/js/bootstrap.js, src/Bootstrap/less/theme/common-readme.less, src/Bootstrap/less/variables.less, src/NuGetGallery/Services/MarkdownService.cs, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml, src/NuGetGallery/Views/Packages/_ImportReadMe.cshtml, tests/NuGetGallery.Facts/Services/MarkdownServiceFacts.cs
Make table pretty similar to Github table style but without border:
upload preview page: 
manage page: 
package detail page: 
[example table](https://github.com/microsoft/PowerToys/blob/main/README.md)
github vs before change vs after change 
github:
before change: 
after change: 
Addresses: https://github.com/NuGet/NuGetGallery/issues/8503
=> Pretty readme table

src/GalleryTools/App.config, src/GalleryTools/Commands/BackfillCommand.cs, src/GalleryTools/GalleryTools.csproj, src/GalleryTools/Readme.md
We have found some cases in the TFM data where we may need to reprocess several thousand packages to fix their data. 
This update to the backfill tool allows a list of package IDs to be provided instead of backfilling everything in the DB.
See the README changes for more information.
Fix https://github.com/NuGet/NuGetGallery/issues/8961
/cc @dannyjdev
=> Add option to backfill tools for specific IDs list

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-home.less, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Views/Pages/Home.cshtml
The banner is broken on INT as the image wasn't included in the release artifacts. See:
* https://int.nugettest.org/
* https://int.nugettest.org/Content/gallery/img/dotnet-20-banner.svg
Also the previous implementation used a padding hack to force a container to have a minimal height. This solution did not work well on very wide screens as it caused the background image to be noticeably clipped. This new solution looks much better on very wide screens and removes the padding hack.
I will test this on DEV before merging:
* Build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5689834&view=results
* Release: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=1253840
Here's what it looks like:
Follow up to …
=> Redo .NET banner

src/NuGetGallery/Scripts/gallery/stats-perpackagestatsgraphs.js
Addresses https://github.com/NuGet/NuGetGallery/issues/8920
Turns out this was actually caused by a bug where the data being sent in on resize was actually a null object, which broke the graph for the rest of the session.
This update passes in the object that is attached to the window on page load instead and should prevent the graph data being lost.
=> [A11y]Update statistics chart to resize correctly.

src/NuGetGallery/Views/Users/ApiKeys.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/8919
This was being caused by a table in the API keys page being wider than the page when zoomed in.
This behaviour could also be replicated by making the window very narrow.
Update this table to use BootStrap's table-responsive, which causes the table content to correctly collapse with page width.
=> Use table-responsive for sample glob descriptions.

src/NuGetGallery/NuGetGallery.csproj
Verified locally. SharpZipLib is a dependency of the local, Lucene-based search indexing.
=> Update to latest SharpZipLib to resolve CG alert

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-home.less
Our black focus outline does not work well on the .NET banner:
This moves to a white dashed outline to align with develper.microsoft.com:
This passes Accessibility Insights FastPass (the previous focus outline also passed 🙁)
Build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5697521&view=results
Release: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=1255175
Part of https://github.com/NuGet/Engineering/issues/4226
=> [HOTFIX] Improve .NET banner accessibility

tests/NuGetGallery.FunctionalTests.Core/Helpers/UrlHelper.cs, tests/NuGetGallery.FunctionalTests/ErrorHandling/ErrorHandlingTests.cs
Some of these bad cookies cause flaky error responses. It's not important enough to chase down why do we'll make the tests less specific.
Also enable TLS 1.2 in another static constructor. This makes running some individual tests possible.
=> Only assert HTTP 400 for bad cookies since behavior is flaky in App Service

src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs
* Badges and Frameworks tab doesn't show when a package is deleted, or if the package is a template.
Addresses:  https://github.com/NuGet/Engineering/issues/4231
Addresses:  https://github.com/NuGet/Engineering/issues/4225
=> [TFM Display] Stop showing badges and tab when package is deleted or a template.

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/common-supported-frameworks.less, src/NuGetGallery/Views/Packages/_SupportedFrameworksTable.cshtml
* Asset TFM badge border adjusted to be the same size as computed.
* Background color changed to light blue instead of teal.
Addresses https://github.com/NuGet/Engineering/issues/4229
=> [TFM Tab] Fix border and background color.

tests/NuGetGallery.WebUITests.P2/BasicPages/SecurityHeaderTest.cs, tests/NuGetGallery.WebUITests.P2/ValidationRuleFindHeaderText.cs
This unblocks functional tests.
=> Allow case insensitive comparison of X-Frame-Options

src/NuGetGallery.Services/Helpers/PackageValidationHelper.cs, src/NuGetGallery.Services/NuGetGallery.Services.csproj, src/NuGetGallery.Services/PackageManagement/IPackageService.cs, src/NuGetGallery.Services/PackageManagement/PackageService.cs, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Services/PackageMetadataValidationService.cs, src/NuGetGallery/Services/SymbolPackageUploadService.cs, tests/NuGetGallery.Facts/Helpers/PackageValidationHelperFacts.cs, tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
* Added normalization of package entry paths using `FileNameHelper.GetZipEntryPath`.
Addresses https://github.com/NuGet/Engineering/issues/4220.
=> [TFM Display][Bug] Packages with backslash path didn't show TFM information.

src/GalleryTools/Commands/BackfillCommand.cs, src/GalleryTools/Commands/BackfillTfmMetadataCommand.cs, src/NuGetGallery.Core/Frameworks/PackageFrameworkCompatibilityFactory.cs, src/NuGetGallery.Services/PackageManagement/PackageService.cs, tests/NuGetGallery.Core.Facts/Frameworks/PackageFrameworkCompatibilityFactoryFacts.cs, tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs
* TFM data now allows a package that contains `any` framework to collect all their asset frameworks and store them in DB.
* `PackageFrameworkCompatibilityFactory` filters `any` framework, this won't show on the package details page.
* `BackfillTfmMetadataCommand` now supports adding `any` as a supported framework.
Addresses https://github.com/NuGet/Engineering/issues/4219.
=> [TFM Display][Bug] Any framework fix as supported framework.

src/NuGetGallery.Core/Packaging/PackageMetadata.cs, tests/NuGetGallery.Core.Facts/Packaging/PackageMetadataFacts.cs
Addresses https://github.com/NuGet/Engineering/issues/4218
Packages with empty descriptions (empty string), when reflowed, see their description parsed as `null`, which triggers an HTTP 500 on the Package Details page.
_NOTE:_ New packages cannot be uploaded with empty descriptions, these packages were already in the system, probably from before these validation checks were enabled.
=> [Bug Fix] Packages with empty descriptions cause HTTP 500 on reflows

src/NuGetGallery.Core/Frameworks/NuGetFrameworkExtensions.cs, tests/NuGetGallery.Core.Facts/Frameworks/NuGetFrameworkExtensionsFacts.cs
* If a package asset contains an empty version, it won't show 0.0 on the badge component, just the framework name.
Addresses https://github.com/NuGet/Engineering/issues/4259
=> [TFM Display] Display empty version with only the framework name as badge.

src/NuGetGallery/Scripts/gallery/common.js, src/NuGetGallery/Scripts/gallery/page-display-package.js, src/NuGetGallery/Strings.Designer.cs, src/NuGetGallery/Strings.resx, src/NuGetGallery/Views/Packages/_SupportedFrameworksBadges.cshtml
Since we wanted to improve the experience of users on what badges means, we added tooltip for the badges, this will show one of two messages depending if the badge contains a version or if it's an empty version.
* When clicking the badge the tooltip will take 2 seconds to hide, it was one second before and it was just to short for users to read it.
* Added role button for better A11y experience.
* Verified that Narrator/NVDA reads the tooltip when traversing the page.
Addresses: https://github.com/NuGet/Engineering/issues/4230.
=> [TFM Badges][UI] Add tooltip on badges.

src/Bootstrap/dist/css/bootstrap.css, src/Bootstrap/less/mixins/buttons.less
Addresses https://github.com/NuGet/NuGetGallery/issues/8987
_Note:_ One of the original problems called out in the [a11y bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1468969) was related to the contrast between the search sign and the white background (the search bar), but it looks like the wrong background color was selected in their tests, and I could not reproduce it while using Accessibility Insights myself.
Their screenshot:
When I looked into it:
However, there were other accessibility concerns because of contrast ratios here, which I've tried to fix.
**Problem:**
On NuGet.org, when navigating a page using the keyboard (tab key), buttons would get a black outline and would darken their original color. This reduced the contrast on certain buttons like the Search button …
=> [A11y] Improved contrast of buttons when in tab focus mode

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/dist/css/bootstrap.css, src/Bootstrap/less/navbar.less, src/Bootstrap/less/theme/base.less
Addresses https://github.com/NuGet/NuGetGallery/issues/8986
**Problem:**
On NuGet.org, when navigating a page using the keyboard (tab key), elements in the navbar and footer were given a black outline, which had a low contrast ratio with the blue background.
**Previous version**
Header:
Footer:
**Fix:**
To fix this, I changed the focus outline to white.
After making the changes:
**New version**
Header:
Footer:
=> [A11y] Improved contrast of focus outline on elements in the header and footer

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/9036
**Problem:**
In the Package Details page's 'Used By' tab, the 'reserved namespace' icons next to the Package Dependents did not have alt attributes.
Previous version:
**Fix:**
To fix this, I added the alt attribute to the reserved namespace img element.
After the changes:
=> [A11y] Added alt text to reserved namespace icon on package details page

src/NuGetGallery/Areas/Admin/Views/ApiKeys/Index.cshtml, src/NuGetGallery/Areas/Admin/Views/Delete/Index.cshtml, src/NuGetGallery/Areas/Admin/Views/Features/Index.cshtml, src/NuGetGallery/Areas/Admin/Views/ReservedNamespace/Index.cshtml, src/NuGetGallery/Areas/Admin/Views/SiteAdmins/Index.cshtml, src/NuGetGallery/Areas/Admin/Views/SupportRequest/Admins.cshtml, src/NuGetGallery/Areas/Admin/Views/UpdateListed/Index.cshtml, src/NuGetGallery/Areas/Admin/Views/Validation/Index.cshtml, src/NuGetGallery/Views/Organizations/_OrganizationMembersListForDeletedAccount.cshtml, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, src/NuGetGallery/Views/Packages/_DisplayPackageVulnerabilities.cshtml, src/NuGetGallery/Views/Statistics/Index.cshtml, src/NuGetGallery/Views/Statistics/PackageVersions.cshtml, src/NuGetGallery/Views/Statistics/Packages.cshtml, src/NuGetGallery/Views/Users/ApiKeys.cshtml, src/NuGetGallery/Views/Users/Organizations.cshtml, src/NuGetGallery/Views/Users/_UserOrganizationsListForDeletedAccount.cshtml, src/NuGetGallery/Views/Users/_UserPackagesListForDeletedAccount.cshtml
Addresses https://github.com/nuget/nugetgallery/issues/9042
**Problem:**
In the Package Details page's 'Used By' tab, the Dependent Packages table did not have an aria-label attribute that would allow screen readers to read its name.
Previous version: (See the "Name" attribute on the right side of the image)
**Fix:**
To fix this, I added the aria-label attribute to the table element here, as well as other table elements where I noticed the issue.
After the changes:
=> [A11y] Added aria-label attributes to table elements

src/NuGetGallery.Services/Security/MicrosoftTeamSubscription.cs, src/VerifyMicrosoftPackage/README.md, tests/NuGetGallery.Facts/Security/MicrosoftTeamSubscriptionFacts.cs
* Add localized copyright string:
© Microsoft Corporation. 保留所有权利.
Before change:  example package contains copyright string above
Executing the verify tool...
================================================================================
Using the following package path argument:
*.nupkg
INVALID.
.\Microsoft.AspNet.SignalR.nupkg
The package Microsoft.AspNet.SignalR 2.2.1 is not compliant.
There is 1 problem.
- The package metadata contains a non-compliant copyright element.
After change:
Executing the verify tool...
================================================================================
Using the following package path argument:
*.nupkg
VALID.
.\Microsoft.AspNet.SignalR.nupkg
The package Microsoft.AspNet.SignalR 2.2.1 is …
=> [HotFix]Add copy right string

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/base.less, src/NuGetGallery/ExtensionMethods.cs, src/NuGetGallery/Views/Users/ForgotPassword.cshtml
- Every `label` element with class `required` inside another element with `form-group` class will have the red `*` as a representation of a required field.
Example:
``` html
<div class="form-group">
<label class="required">Email: </label>
</div>
```
Addresses https://github.com/nuget/engineering/issues/4309
=> [A11y bug] Add visual representation for required field on forgot password page.

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/9048
**Problem:**
In the Package Details page's 'Used By' tab, screen readers weren't reading the table header names when using tab navigation.
**Fix:**
To fix this, I added tabindex to the table headers in the two tables in the 'Used By' tab (Dependent packages and dependent GitHub repos) and in the Version History table in the 'Versions' tab.
=> [A11y] Added tabindex to table headers on Package Details page so that screen readers can read them

src/NuGetGallery/Scripts/gallery/stats-perpackagestatsgraphs.js, src/NuGetGallery/Views/Statistics/_PivotTable.cshtml
Disables removing the chart when screen in very narrow.
Moves the title out of the chart itself since chart no longer is removed. This also improves readability of the title.
Old:
New:
Note difference in displayed data comes from dev vs public.
=> [A11y]Fix Graph on stats for narrow screen.

src/NuGetGallery/Areas/Admin/Controllers/ReservedNamespaceController.cs, src/NuGetGallery/Areas/Admin/ViewModels/ReservedNamespaceViewModel.cs, src/NuGetGallery/Areas/Admin/Views/ReservedNamespace/Index.cshtml, tests/NuGetGallery.Facts/Areas/Admin/Controllers/ReservedNamespaceControllerFacts.cs, tests/NuGetGallery.Facts/Controllers/StatisticsControllerFacts.cs, tests/NuGetGallery.Facts/Queries/AutocompleteDatabasePackageIdsQueryFacts.cs, tests/NuGetGallery.Facts/Queries/AutocompleteDatabasePackageVersionsQueryFacts.cs, tests/NuGetGallery.Facts/TestUtils/ContractAssert.cs
Progress on https://github.com/NuGet/Engineering/issues/4269
This will allow admins to find the root cause of the "more liberal" error message.
=> Add namespace and package prefix search tools to namespace reservation admin panel

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-display-package.less, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- Removed `display: table, table-row, table-cell` from css for installation command styles.
- Since the installation commands had table layouts, NVDA was announcing this button as part of a table, which was not correct.
- Removed unecessary `div` element from `DisplayPackage.cshtml`
https://github.com/nuget/engineering/issues/4315
=> [Ally Bug] Installation command copy button reads as table.

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-home.less, src/NuGetGallery/Content/gallery/img/circuit-board.svg
Addresses https://github.com/nuget/nugetgallery/issues/8988
**Problem:**
On the Home page, when text spacing is applied, the 'package versions' and 'unique packages' text overflows outside its container.
*NOTE:* I was told to use [codepen.io](https://codepen.io/stevef/pen/YLMqbo/) to apply text spacing, but it can also be achieved by adding this to the stylesheet:
```
* {
line-height: 1.5 !important;
letter-spacing: 0.12em !important;
word-spacing: 0.16em !important;
}
p{
margin-bottom: 2em !important;
}
```
Regular home page:
After applying text spacing:
**Fix:**
To fix this, I made the label containers wider to accommodate the expanded text. The resulting UI changes seem minor to look at, but I'm happy to get additional feedback on that.
**After the changes,**
Regular home page:
After …
=> [A11y] Adjusted homepage circuit board label sizes to accommodate text spacing

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-statistics-per-package.less
* `overflow-wrap: break-word` added so avoid title overflowing the content.
Addresses https://github.com/nuget/engineering/issues/4322
=> [A11y bug] Package title on stats is overflowing the content.

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Addresses https://github.com/nuget/nugetgallery/issues/9061
**Problem:**
On the Package Details page, individual tabs do not have descriptive aria-labels that can be read by screen readers to inform users. We need to describe the purpose of the tab contents to account for cases where it may not be self-evident, like this isolated link in the Release Notes section here:
**Fix:**
To fix this, I added aria-label attributes to each of the tab content divs.
=> [A11y] Added aria-labels to tabs on Package Details page

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/9048
**Problem:**
Reopened a previous a11y bug that I hadn't fixed all the way through.
In the Package Details page's 'Used By' tab, screen readers weren't reading the table header names when using tab navigation. To fix this, I had added tabindex to the table headers so that screen readers would access them and read out the contents ('Package', Downloads', etc.), but I needed to make those cells identifiable as column headers, so that each data cell below it would also be identified with that column header. I have made that fix here.
**Fix:**
To fix this, I added scope and role attributes to identify these header cells as column headers and allow accessibility aids to pick up on that detail.
I also added tabindex to table data cells …
=> [A11y] Added column header roles to tables, made each cell accessible with keyboard navigation

src/NuGetGallery/App_Code/ViewHelpers.cshtml
Addresses https://github.com/nuget/nugetgallery/issues/9052
**Problem:**
On the Forgot Password page, when tab navigating from the 'Email' input field onwards, you expect the focus to move to the 'Send' button, but the focus shifts to the Privacy and Terms links in the ReCAPTCHA element in the bottom-right of the page, before resuming the regular tab stop order from the 'Send' button onwards.
**Currently:**
The parent div that we were loading the ReCAPTCHA element into had a data-tabindex="-1" attribute, but the iframes within this were still receiving tab focus.
**Fix:**
To fix this, I added the tabindex="-1" attribute to all the ReCAPTCHA iframes after they have been loaded into the page, so that they do not receive tab focus.
**After the changes:**
**_NOTE:_** These changes mean that …
=> [A11y] Added tabindex="-1" to ReCAPTCHA iframes

src/NuGetGallery/Scripts/gallery/common.js
Currently, when navigated to by keyboard, the verified tooltip cannot be dismissed without tabbing away from the icon.
This change enables dismissing this tooltip by usage of the esc key for all locations where this tooltip is used.
As a bonus it also fixes a bug that could cause the tooltip to stop working altogether when clicked on.
=> [A11y]Enable dismissing Verified tooltip with esc

src/Bootstrap/dist/js/bootstrap.js, src/Bootstrap/js/tab.js, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, src/NuGetGallery/Views/Packages/_ImportReadMe.cshtml
Addresses https://github.com/nuget/nugetgallery/issues/9068
**Problem:**
On the Package Details page, tabs are navigated between using the tab key, rather than the left and right arrow keys, as it is supposed to be. This means that once a user has selected a tab, they must still tab navigate through the remaining inactive tabs before they can access the tab content.
**Previously,**
**Fix:**
I added an event listener for left and right arrow keys, and changed the tab in focus based on the input. I used keyUp as the trigger here rather than keyDown, because adding an event listener for keyDown also messed with other keyboard functionality (eg. 'tab' and 'enter' keys) when focused on the tab element.
To enable this, I also made it such that only the selected/expanded tab has _tabindex="0"_ …
=> [A11y] Made Package Details page's tabs navigable with left/right arrow keys

src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Services/InvalidLicenseUrlValidationMessage.cs, src/NuGetGallery/Services/LicenseUrlDeprecationValidationMessage.cs, src/NuGetGallery/Services/MissingLicenseValidationMessage.cs, src/NuGetGallery/Services/PackageMetadataValidationService.cs, src/NuGetGallery/Strings.Designer.cs, src/NuGetGallery/Strings.resx, tests/NuGetGallery.Facts/Services/PackageMetadataValidationServiceFacts.cs
The web UI shows a warning if you upload a package without a license:
This switches the `Learn more` URL from https://aka.ms/deprecateLicenseUrl to https://aka.ms/nuget/authoring-best-practices#licensing as that's a more helpful guide in this scenario.
Addresses https://github.com/NuGet/NuGetGallery/issues/9037
Build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5859049&view=results
Release: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=1282731
/cc @agr @chgill-MSFT
=> [Upload UI]: Improve experience when package has no license

src/GitHubVulnerabilities2Db/Gallery/ThrowingTelemetryService.cs, src/NuGetGallery.Services/NuGetGallery.Services.csproj, src/NuGetGallery.Services/Telemetry/DurationMetric.cs, src/NuGetGallery.Services/Telemetry/ITelemetryService.cs, src/NuGetGallery.Services/Telemetry/TelemetryService.cs, src/NuGetGallery/App_Start/DefaultDependenciesModule.cs, src/VerifyMicrosoftPackage/Fakes/FakeTelemetryService.cs, tests/NuGetGallery.Facts/App_Start/DefaultDependenciesModuleFacts.cs, tests/NuGetGallery.Facts/Services/TelemetryServiceFacts.cs
Added a client-side aggregated metric for SQL connection creation duration.
=> SQL connection creation duration tracking

src/NuGetGallery/Scripts/gallery/page-support-requests.js
Admin-only instance in support requests links accounts and packages to the originating host (www.nuget.org) which creates complications for processing support requests.
This change replaces absolute URLs with relative ones that works around the issue.
=> Make sure account and package links on the support requests page use the same host

tests/NuGetGallery.FunctionalTests/ErrorHandling/ErrorHandlingTests.cs
`/packages` request produces 400 for the test only if the code path that analyzes the content of `nugetab` cookie is executed (i.e. A/B testing feature flag is enabled). When it is not, the cookie is completely ignored and tests that involve it fail. We don't need that feature flag dependency in tests that are gateway for the deployment, hence the removal.
=> Removing tests that are feature-flag-state-dependent.

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/common-supported-frameworks.less
* When high contrast, badges on table and on badge component now have border and font bolder.
* Compatible target bottom label now has a square icon with bolder border.
The following are screenshot from different contrast themes on windows 11.
<details>
<summary>Aquathic theme</summary>
</details>
<details>
<summary>Desert theme</summary>
</details>
<details>
<summary>Dusk theme</summary>
</details>
<details>
<summary>Night Sky theme</summary>
</details>
https://github.com/nuget/engineering/issues/4347
=> [A11y Bug] Make TFM badges asset and compatible different for high contrast.

src/NuGetGallery/Scripts/gallery/common.js, src/NuGetGallery/Views/Packages/_SupportedFrameworksBadges.cshtml
* `role="button"` removed from badges.
* Added aria-label to badges for screen reader.
* Fixed screen reader not announcing popover content on focus/click.
https://github.com/nuget/engineering/issues/4352
=> [A11y Bug] TFM remove role button from badges.

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, src/NuGetGallery/Views/Packages/_SupportedFrameworksBadges.cshtml, src/NuGetGallery/Views/Packages/_SupportedFrameworksTable.cshtml
* `tabindex="0"` removed from package title, version, tfm badges, and tfm table.
https://github.com/nuget/engineering/issues/4351
=> [A11y Bug] Remove focus from non-interactive elements on TFM badge and table.

src/NuGetGallery/Scripts/gallery/page-display-package.js
1. Read window hash param from url
2. Use passed hash to focus body tab
3. Replace window history on activate tab to
- adjust current url (so you can copy and share it)
- avoid navigating back through tabs
Addresses https://github.com/NuGet/NuGetGallery/issues/8822
=> Make package body tabs linkable

src/NuGetGallery.Core/Services/GalleryCloudBlobContainerInformationProvider.cs
They are already set as private in Blob Storage. There is no known scenario that needs public (unauthenticated) access to these blobs.
=> Mark backup folders as private

src/Bootstrap/package-lock.json
Hotfix to clean up the warning faster. There is no runtime impact. Verified by running `grunt`. I will merge this back to `dev` after this PR merges.
=> Update grunt to 1.5.3 to remediate Dependabot warning

src/NuGetGallery/Services/MarkdownService.cs, tests/NuGetGallery.Facts/Services/MarkdownServiceFacts.cs
Support
strike through ~~,
Before change: 
After change: 
Addresses https://github.com/NuGet/NuGetGallery/issues/8726
=> Support emphasis

src/NuGetGallery/Scripts/gallery/page-display-package.js, src/NuGetGallery/Views/Shared/_ListPackage.cshtml
The search result may point to a URL like this:
https://dev.nugettest.org/packages/Newtonsoft.Json/
The existing approach appends the tab fragment like this:
https://dev.nugettest.org/packages/Newtonsoft.Json/#versions-body-tab
This is to remove the trailing slash when formatting the tab fragment:
https://dev.nugettest.org/packages/Newtonsoft.Json#versions-body-tab
=> Remove the trailing slash when formatting the tab fragment

src/NuGet.Services.Entities/Package.cs, src/NuGet.Services.Entities/PackageRegistration.cs, src/NuGetGallery.Services/PackageManagement/PackageService.cs, src/NuGetGallery/Services/TyposquattingCheckListCacheService.cs, tests/NuGet.Services.DatabaseMigration.Facts/PendingMigrationsFacts.cs
Temporarily disables mapping of the DownloadCount column to the Package and PackageRegistration entities.
After this has been merged, there will be a second PR reverting this as we only need this changeset to enable readonly scenarios while the DownloadCount column data type is being migrated.
=> [Hotfix]Disable DownloadCount Mapping temporarily

src/NuGet.Services.Entities/Package.cs, src/NuGet.Services.Entities/PackageRegistration.cs, src/NuGetGallery.Services/PackageManagement/PackageService.cs, src/NuGetGallery/Services/TyposquattingCheckListCacheService.cs, tests/NuGet.Services.DatabaseMigration.Facts/PendingMigrationsFacts.cs
This reverts commit 1dc90c2f0bf8fafc4d0b38f48acf4aa8d5dfbee6.
This explicitly should not be deployed until AFTER DB migration has completed.
=> Revert "[Hotfix]Disable DownloadCount Mapping temporarily (#9150)"

src/NuGetGallery.Services/NuGetGallery.Services.csproj
This adds the Models classes to the netstandard2.1 target for consumption in this work: https://github.com/NuGet/Engineering/issues/4376.
=> Add Models classes to netstandard2.1

tests/NuGetGallery.LoadTests/NuGetGallery.LoadTests.csproj
Functional test failed with error message below: 
Run deployment issue: The assembly or module 'Newtonsoft.Json' directly or indirectly referenced by the test container 'd:\a\_work\1\s\tests\nugetgallery.loadtests\bin\release\nugetgallery.loadtests.dll' was not found.
There are several workarounds: 
1. Add package reference with specific version
2. Download assembly to Global Assembly Cache at agent where we run functional tests
Since we don't have control of agent pool, I think workaround 1 will be better.  Please let me know if there is better workaround
Addresses https://github.com/NuGet/Engineering/issues/4452
=> Update newtonsoft.json 

src/AccountDeleter/EmptyFeatureFlagService.cs, src/GitHubVulnerabilities2Db/Fakes/FakeFeatureFlagService.cs, src/NuGetGallery.Core/Auditing/AuditedAuthenticatedOperationAction.cs, src/NuGetGallery.Services/Authentication/AuthenticationService.cs, src/NuGetGallery.Services/Authentication/PasswordAuthenticationResult.cs, src/NuGetGallery.Services/Configuration/FeatureFlagService.cs, src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs, src/NuGetGallery.Services/Configuration/ILoginDiscontinuationConfiguration.cs, src/NuGetGallery.Services/Configuration/LoginDiscontinuationConfiguration.cs, src/NuGetGallery/App_Data/Files/Content/flags.json, src/NuGetGallery/Controllers/AuthenticationController.cs, src/NuGetGallery/Controllers/UsersController.cs, src/NuGetGallery/Strings.Designer.cs, src/NuGetGallery/Strings.resx, src/NuGetGallery/ViewModels/LogOnViewModel.cs, src/NuGetGallery/ViewModels/PasswordResetRequestViewModel.cs, src/NuGetGallery/Views/Authentication/SignIn.cshtml, src/NuGetGallery/Views/Authentication/_SignIn.cshtml, src/NuGetGallery/Views/Users/ForgotPassword.cshtml, src/VerifyMicrosoftPackage/Fakes/FakeFeatureFlagService.cs, tests/NuGetGallery.Core.Facts/Auditing/AuditedAuthenticatedOperationActionTests.cs, tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs, tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs, tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs, tests/NuGetGallery.Facts/Services/LoginDiscontinuationConfigurationFacts.cs
- `NuGetAccountPasswordLoginSupported` feature flag added.
- When feature flag is enabled, the site behaves the following way:
- `Sign in using NuGet.org account` is removed.
- NuGet Password login shows an error if email is not in exception list.
- `ForgotPassword` page shows a warning.
- On `ForgotPassword` page, if you submit an email, an error will show since the endpoint will be blocked on the backend.
- https://github.com/NuGet/Engineering/issues/4234
- https://github.com/NuGet/Engineering/issues/4314
=> [2FA] Disable nuget.org password login

src/GitHubVulnerabilities2Db/Job.cs
Addresses: https://github.com/NuGet/NuGetGallery/issues/9194
If we set a registration to `ExternallyOwned` we control its life cycle--an early disposal was breaking this service: https://autofac.readthedocs.io/en/latest/lifetime/disposal.html
=> Manage disposal of httpclient directly - autofac disposing early

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Added `role = alert` to the warning below the Paket CLI command so that the screen reader will read the warning out to the user without having to tab to the warning element itself. 
Addresses https://github.com/NuGet/NuGetGallery/issues/9172
=> [A11y] Read warning when tabbing to Paket CLI tab

src/NuGetGallery/OData/PackageExtensions.cs, tests/NuGetGallery.Facts/OData/Interceptors/PackageExtensionsFacts.cs
The Hijacked v2 endpoints return the download counts as is, however, few old package download clients suffer from Integer overflow during the deserialization of the package metadata due to the use of `Int32` for the `DownloadCount` field.
This is now a noticeable issue due to multiple packages exceeding this threshold (`Newtonsoft.Json`, `Microsoft.Extensions.DependencyInjection.Abstractions` etc.)
As a workaround, we can set this field to the max allowed value on the v2 returned response.
=> [Hotfix] Set download count to Int32.MaxValue for V2 feed packages exceeding this threshold

src/NuGetGallery/Services/MarkdownService.cs, tests/NuGetGallery.Facts/Services/MarkdownServiceFacts.cs
Fixes the issue where internal section links in a README do not link to the specified section, but instead take a user back to the top.
Addresses https://github.com/NuGet/NuGetGallery/issues/8833
=> Add section link support for READMEs

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
* Install-Package exists in both Microsoft's NuGet module and PackageManagement module. This clarifies which Install-Package is expected, which helps PowerShell end-users
* Added a PowerShell tab to further clarify
Addresses https://github.com/NuGet/NuGetGallery/issues/9201
=> Fully Qualify Install-Package command on website

src/NuGetGallery/Views/Organizations/DeleteAccount.cshtml, src/NuGetGallery/Views/Users/DeleteAccount.cshtml
Fix https://github.com/NuGet/NuGetGallery/issues/7447
We have a standing policy of blocking user account and organization account usernames after deletion. The `Users` table record essentially remains in a soft deleted state preventing future registrations. This is to avoid impersonation attacks.
Over support requests, it's clear that this surprises some users. Let's make it more clear in the deletion pages that this is the case.
=> Add additional warning about blocked usernames

src/NuGetGallery/Areas/Admin/Controllers/ReservedNamespaceController.cs, src/NuGetGallery/Areas/Admin/ViewModels/ReservedNamespaceResultModel.cs, src/NuGetGallery/Areas/Admin/Views/ReservedNamespace/Index.cshtml, tests/NuGetGallery.Facts/Areas/Admin/Controllers/ReservedNamespaceControllerFacts.cs
Progress on https://github.com/NuGet/Engineering/issues/4523
This PR adds:
- The "Parent namespaces:" section when reserving a new namespace
- A prompt to remind the site admin to check the owners of the parent namespaces. This will likely be a case we escalate to PM.
Screenshot:
This is the prompt:
=> Show information about parent namespaces on the ID prefix reservation admin panel

src/NuGetGallery/App_Data/Files/Content/Trusted-Image-Domains.json
After evaluation of api.resue.software, we decide to include this domain to our allowlist
Addresses https://github.com/NuGet/NuGetGallery/issues/9200
=> Add api.reuse.software to image allowlist

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-display-package.less, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Prevent the 'Prefix Reserved' element on a package page from being read when using the 'H' option in the screen reader by setting the element's `aria-hidden` attribute to `true`.
Current Behavior:
New Behavior:
Addresses https://github.com/NuGet/NuGetGallery/issues/9173
=> [A11y][ScreenReader] Prevent Screen Reader from reading non-header elements

src/NuGetGallery/Scripts/gallery/common.js
Also, delete an ancient clickonce line that is unused
Progress on https://github.com/NuGet/Engineering/issues/4555
=> Use Application Insights JS SDK instead of Google Analytics

src/GitHubVulnerabilities2Db/Ingest/AdvisoryIngestor.cs, src/NuGetGallery.Services/PackageManagement/PackageVulnerabilitiesManagementService.cs, src/VerifyGitHubVulnerabilities/Job.cs, src/VerifyGitHubVulnerabilities/README.md, src/VerifyGitHubVulnerabilities/Verify/PackageVulnerabilitiesVerifier.cs, tests/GitHubVulnerabilities2Db.Facts/AdvisoryIngestorFacts.cs, tests/NuGetGallery.Facts/Services/PackageVulnerabilitiesManagementServiceFacts.cs
Entity Framework clears dependent collections when the parent entity is removed from the DB context. This means it can't be used to do further cleanup. The database was properly updated (based on cascading deletion logic from EF) but the packages did not get their LastEdited timestamp updated meaning Db2Catalog did not flow the latest (no longer vulnerable) state into V3.
Progress on https://github.com/NuGet/Engineering/issues/4566.
Here's an example of a GitHub advisory that had its version range reduced: https://github.com/github/advisory-database/commit/3fa7f26a3e7d23d5fd4feb255720d53d27f68286#diff-601b57f388e2622aed5945b89aef348e24c299b05d64c1cddf7f0870fee6b05f (package ID: Microsoft.AspNetCore.Authentication.JwtBearer).
After running VerifyGitHubVulnerabilities and reflowing any …
=> Fix bug causing reduced vulnerabilities version ranges to not flow into V3

src/NuGetGallery/Services/MarkdownService.cs, src/NuGetGallery/Web.config, tests/NuGetGallery.Facts/Services/MarkdownServiceFacts.cs
Added a hotfix for the 500 internal server error resulting from the added support for section links.
Addresses https://github.com/NuGet/NuGetGallery/issues/9226
=> [README] Hotfix for section links 500 error

src/GitHubVulnerabilities2Db/Ingest/AdvisoryIngestor.cs, src/NuGetGallery.Services/PackageManagement/PackageVulnerabilitiesManagementService.cs, src/NuGetGallery/Scripts/gallery/common.js, src/VerifyGitHubVulnerabilities/Job.cs, src/VerifyGitHubVulnerabilities/README.md, src/VerifyGitHubVulnerabilities/Verify/PackageVulnerabilitiesVerifier.cs, tests/GitHubVulnerabilities2Db.Facts/AdvisoryIngestorFacts.cs, tests/NuGetGallery.Facts/Services/PackageVulnerabilitiesManagementServiceFacts.cs
Part of https://github.com/NuGet/NuGetGallery/issues/9237
=> [ReleasePrep][2022.09.16]RI of dev into main

src/NuGetGallery/App_Code/ViewHelpers.cshtml
Add syntax highlighting for supporting fsharp, dos, powershell. 
before: 
after: 
Addresses https://github.com/NuGet/NuGetGallery/issues/9125
Additional:
1.  This is blocked by issue https://github.com/NuGet/NuGetGallery/issues/9226, need merge after. 
2.  We also want to support cshtml, razor, it is in separate library, we will support them later.  Track issue here: https://github.com/NuGet/NuGetGallery/issues/9231
=> Support more languages for syntax highlighting

src/NuGetGallery/ViewModels/ThirdPartyPackageManagerViewModel.cs
The original fix for the issue specified below reads out the warning message when tabbing to the Paket CLI tab in the package details page but does not specify that the message is a warning message. This fix adds a hidden element with `aria-label="warning"` before the warning message.
Addresses https://github.com/NuGet/NuGetGallery/issues/9172
=> [A11y] Read out "warning" when tabbing to Paket CLI

src/NuGetGallery.Core/CoreConstants.cs, src/NuGetGallery/Migrations/MigrationsConfiguration.cs
This one is up for discussion--we can do one of:
- Not do this at all and make it a manual process
- Do this as-is
- Ensure not just the existence of an `AnonymousUploaders` Role, but also a User that is joined to it
=> Ensure new role exists for anonymous uploaders when migrating db

src/NuGetGallery/Helpers/ViewModelExtensions/DisplayPackageViewModelFactory.cs, src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
It could be formatted up a little more nicely, but it follows the convention of other informational lines like min client version.
=> If a claim key is present for an anonymously uploaded package, show it

src/NuGetGallery.Core/Services/CorePackageService.cs, src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/Helpers/ViewModelExtensions/DisplayPackageViewModelFactory.cs, src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- changes the post-publish URL to use the temporary ID
- changes package lookup to use temporary ID first
- displays temporary ID on Display Package page, while leaving persistent metadata (actual ID, version) in page titles and publish message
=> Alter landing displaypackage URL to use a temporary ID for anon uploads

src/NuGetGallery/Web.config
Resolves issue caused by https://github.com/NuGet/NuGetGallery/pull/9254.
=> Add missing binding redirect for Microsoft.Owin

src/NuGetGallery.Core/Services/AssetFrameworkHelper.cs, src/NuGetGallery.Core/Services/AssetFrameworkService.cs, src/NuGetGallery.Services/PackageManagement/PackageService.cs
Addresses https://github.com/NuGet/Engineering/issues/4577
We need to reuse some asset framework logic from PackageService in NuGet.Jobs' Catalog2AzureSearch for Search-by-TFM, and moving this logic to NuGetGallery.Core would allow us to reuse this code with minimal changes.
This change:
* Creates the AssetFrameworkHelper, which now holds the asset framework logic in its GetAssetFrameworks method
* Redirects the previous GetSupportedFrameworks method in PackageService (NuGetGallery.Services) to this logic
All previous tests passed after this change.
=> Refactored PackageService code for use by Search-by-TFM

CodeQL.yml, src/NuGetGallery/Scripts/gallery/autocomplete.js, src/NuGetGallery/Services/CertificateService.cs
First, ignore moment.js issues by classifying it as a library.
Second, resolve an escaping issue by using a built-in jQuery method.
Third, supress a usage of MD5 for backwards compatibility reasons.
=> Address three CodeQL errors

src/NuGetGallery.Core/Services/AssetFrameworkHelper.cs
This is part of the work in https://github.com/NuGet/NuGet.Jobs/pull/1096.
We will need to use these constants to represent Framework Generations in the search index, and in the URL query parameters, so they will be used by both NuGet.Jobs and NuGetGallery.
These Framework Generation strings are based on the shortname framework identifiers. There isn't currently a shortname identifier for .NET Framework (< 5.0), so we created our own constants, which includes "netframework" for .NET Framework.
=> Framework Generation constants for Search-by-TFM

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/common-readme.less, src/NuGetGallery/App_Code/ViewHelpers.cshtml
Approach: use our own syntax highlighting css style to have more control over
contrast issue:  
- Change color from #d73a49 to #cc3745
- Change from #e36209 to #b74e05
Test: Ran few packages with code fence readme with FastPass
Addresses https://github.com/NuGet/NuGetGallery/issues/9269
=> Address accessibility for syntax highlighting

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-statistics-per-package.less, src/NuGetGallery/Views/Statistics/_PivotTable.cshtml
=> Update Download table heading

src/NuGetGallery/Helpers/ViewModelExtensions/DisplayPackageViewModelFactory.cs, src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- Added "IsMSBuildSdkPackageType" to determine whether a package is of type MSBuildSdk.
- DisplayPackage view modified to show specific instructions for SDK types in project files as per #8800 
Let me know what you think, I've tested this on a few different packages of different types
=> Add instructions to install MSBuildSdk packages

src/NuGetGallery/Controllers/ApiController.cs
Fixed 3 CodeQL bugs that required us to add checks to validate anti-forgery tokens on HttpPost requests.
Part of https://github.com/NuGet/Engineering/issues/4593
Addresses https://github.com/NuGet/Engineering/issues/4608
(https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1632798, https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1632799, https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1632803)
=> Added CSRF token checks to address CodeQL bugs

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/base.less, src/Bootstrap/less/theme/page-display-package.less
* Added support for Firefox browser
* Make thinner border when navigating page with TAB or clicking a link
Addresses https://github.com/NuGet/NuGetGallery/issues/9072
=> Make thiner border for focused links

src/GitHubVulnerabilities2Db/Collector/AdvisoryQueryBuilder.cs, src/GitHubVulnerabilities2Db/Collector/AdvisoryQueryService.cs, src/GitHubVulnerabilities2Db/GraphQL/QueryResponse.cs, src/GitHubVulnerabilities2Db/GraphQL/QueryService.cs, src/GitHubVulnerabilities2Db/GraphQL/SecurityAdvisory.cs, src/GitHubVulnerabilities2Db/Job.cs, tests/GitHubVulnerabilities2Db.Facts/QueryServiceFacts.cs
The original implementation used a `securityAdvisory(databaseId)` query which no longer exists. This switches to using GHSA ID as the parameter.
Fixes https://github.com/NuGet/Engineering/issues/4619.
=> Fix bug around handling security advisories with 100 or more affected packages

src/NuGetGallery.Core/NuGetVersionExtensions.cs, src/NuGetGallery.Core/Services/FIleNameHelper.cs, src/NuGetGallery.Services/SupportRequest/SupportRequestService.cs
Addresses: https://github.com/NuGet/Engineering/issues/4637
=> Use package's NormalizedVersion to create support requests

src/AccountDeleter/EmptyFeatureFlagService.cs, src/GitHubVulnerabilities2Db/Fakes/FakeFeatureFlagService.cs, src/NuGetGallery.Services/Configuration/FeatureFlagService.cs, src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs, src/NuGetGallery/App_Data/Files/Content/flags.json, src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/RequestModels/SubmitPackageRequest.cs, src/NuGetGallery/RequestModels/VerifyPackageRequest.cs, src/NuGetGallery/Scripts/gallery/async-file-upload.js, src/NuGetGallery/Services/MissingLicenseValidationMessage.cs, src/NuGetGallery/Services/MissingLicenseValidationMessageV2.cs, src/NuGetGallery/Services/PackageMetadataValidationService.cs, src/NuGetGallery/Services/UploadPackageMissingReadme.cs, src/NuGetGallery/Strings.Designer.cs, src/NuGetGallery/Strings.resx, src/NuGetGallery/Views/Packages/_VerifyMetadata.cshtml, src/NuGetGallery/Web.config, src/VerifyMicrosoftPackage/Fakes/FakeFeatureFlagService.cs, tests/NuGetGallery.Facts/Services/PackageMetadataValidationServiceFacts.cs
* Add feature flag
* Add warning when package without readme
* Reword warning when package without license, align with readme
* Upload collapse hide when there is metadata display in verify
* Display unnecessary metadata when is not specified
* Remove Italic font 
**Additionally** UX is reviewed by UX team
Before: 
After: 
Feature flag is off: 
Feature flag is on
Addresses
=> Upload page UX polish

src/NuGetGallery/Controllers/PackagesController.cs, tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
Address https://github.com/NuGet/NuGetGallery/issues/9295
=> Return 404 when the null version is provided to the license endpoint

src/Bootstrap/dist/css/bootstrap.css, src/Bootstrap/less/list-group.less, src/NuGetGallery/Views/Shared/ListPackages.cshtml, src/NuGetGallery/Views/Shared/_ListPackage.cshtml, src/NuGetGallery/Views/Users/Profiles.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/9301
**Problem:**
On the Profiles page and the List Packages page, the lists of packages were flagged for not having the appropriate role on the individual list items. These were already marked with role="listitem" and the enclosing div was marked with role="list", so I'm unsure why this was flagged. However, we can bypass the need for these manual role attributes by using `<ul>` and `<li>` tags directly instead.
**Previously,**
**Fix:**
These package lists now use `<ul>` and `<li>` tags, which do not require additional role attributes. I also had to remove the bullet and left padding from these package list `<ul>`s.
**After the changes,**
=> [A11y] Correct role attribute for package lists

src/NuGetGallery/App_Code/ViewHelpers.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/9300
**Problem:**
Th Recaptcha iframes on pages like the Forgot Password page and the Report Abuse page were marked with the role `presentation` by default, but this role (as well as the `none` role) disables some accessibility properties, which is why FastPass was flagging it.
**Previously,**
**Fix:**
Iframes are only allowed to be marked with the roles `document`, `application` or `img` (also `presentation` or `none`, but that causes other a11y problems). I changed the role of this iframe to `document`, and it clears FastPass checks now (on both the pages flagged in the bug, the Forgot Password page and the Report Abuse page).
**After the changes,**
=> [A11y] Change role attribute of Recaptcha iframe

src/NuGetGallery/App_Code/ViewHelpers.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/9310
The breadcrumb headings on pages like the 'Report Package' page were flagged for having the "list" role on an `<h1>` tag. Since these serve more as headings anyway, I simply removed the role attributes from these elements without adding anything (`<h1>` tags are announced as headers anyway), and FastPass doesn't flag it anymore.
Previously,
After the change,
=> [A11y] Removed incorrect role attribute from breadcrumb headings

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Previous PR addressing the below issued introduced a new accessibility issue in which the prefix reserved checkmark was not accessible to screen readers. This PR removes the aria-hidden attribute associated with the prefix reserved icon and link. This solves the issue of the below a11y bug while also maintaining that the prefix reserved icon is not read aloud along with the package title header.
Previous PR: https://github.com/NuGet/NuGetGallery/pull/9314
Addresses https://github.com/NuGet/NuGetGallery/issues/9299
=> [A11y] Remove aria-hidden attribute for prefix reserved element

src/NuGetGallery.Services/Authentication/AuthenticationService.cs, tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs
This allows the new DB key on the credential to be included in the audit record.
Resolve https://github.com/NuGet/Engineering/issues/4660.
=> Audit the AddCredential action after we commit to the DB

CODE_OF_CONDUCT.md, src/NuGetGallery.Core/Frameworks/SupportedFrameworks.cs
Addresses https://github.com/NuGet/NuGetGallery/issues/9321
This adds support for .NET Framework 4.8.1, which now shows up as a compatible framework on the Frameworks tab.
Previously,
After the changes,
=> Added support for .NET Framework 4.8.1

src/NuGetGallery/Services/UploadPackageMissingReadme.cs, src/NuGetGallery/Views/Packages/UploadPackage.cshtml
Fix https://github.com/NuGet/NuGetGallery/issues/9336
=> Move the error message container outside of the Upload section

src/NuGetGallery.Services/Authentication/Providers/AzureActiveDirectoryV2/AzureActiveDirectoryV2Authenticator.cs, src/NuGetGallery.Services/Authentication/Providers/AzureActiveDirectoryV2/AzureActiveDirectoryV2AuthenticatorConfiguration.cs, src/NuGetGallery/Web.config
We were only ever using the id_token which contains enough detail for NuGet.org sign in. The code response is not used. Progress on https://github.com/NuGet/Engineering/issues/4099
The benefit here is that we have less secrets to rotate 😄.
I've confirmed the general approach with the team that owns the AAD SDK.
=> Remove the client secret from AAD V2 authenticator

src/NuGetGallery/Scripts/gallery/async-file-upload.js, src/NuGetGallery/Scripts/gallery/page-edit-readme.js
Removed the `aria-expanded` attribute from the following `div` elements:
URL: https://www.nuget.org/packages/manage/upload
- #verify-package-block
- #import-readme-block
- #submit-block
Addresses https://github.com/NuGet/NuGetGallery/issues/9320
=> [A11y][Fastpass] Remove aria-expanded attribute where not allowed

src/NuGetGallery/ViewModels/ThirdPartyPackageManagerViewModel.cs
Added the `role="alert"` attribute to the warning message for the third party package managers. 
Addresses https://github.com/NuGet/NuGetGallery/issues/9319
=> [A11y][Fastpass] Add role attribute where aria-label attribute is used

src/GitHubVulnerabilities2Db/Gallery/ThrowingTelemetryService.cs, src/NuGetGallery.Services/Telemetry/ITelemetryService.cs, src/NuGetGallery.Services/Telemetry/TelemetryService.cs, src/NuGetGallery/App_Start/DefaultDependenciesModule.cs, src/NuGetGallery/Services/CloudDownloadCountService.cs, src/VerifyMicrosoftPackage/Fakes/FakeTelemetryService.cs, tests/NuGetGallery.Facts/Services/CloudDownloadCountServiceFacts.cs
Related to https://github.com/NuGet/NuGetGallery/issues/9352.
We have a weird situation when downloads.v1.json, Gallery DB and Search service all align on a downloads count for a certain package, yet the number displayed in the package list is different.
It should come from DB: https://github.com/NuGet/NuGetGallery/blob/c1ccf24a931fb3e048e23c484f663580e906f30d/src/NuGetGallery/Helpers/ViewModelExtensions/PackageViewModelFactory.cs#L58
But some EF interception magic happens and it is actually ends up being populated from data retrieved by [CloudDownloadCountService](https://github.com/NuGet/NuGetGallery/blob/main/src/NuGetGallery/Services/CloudDownloadCountService.cs) and it is unclear if it actually refreshes the statistics data fully. To investigate the issue from that angle, more …
=> More telemetry for downloads service.

src/NuGetGallery.Core/Frameworks/FrameworkCompatibilityService.cs, src/NuGetGallery.Core/Frameworks/SupportedFrameworks.cs, tests/NuGetGallery.Core.Facts/Frameworks/FrameworkCompatibilityServiceFacts.cs
We use NuGet client sdk in order to create a compatibility matrix for displaying TFMs on nuget.org. Currently there is no knowledge on nuget client sdk on what net5+ platform version exists (like net6.0-windows7.0) and they are not computed.
* net6.0-windows7.0 compatibility has been hardcoded with known values.
* This compatibility will only show if a package contains that specific TFM in their assets.
* Why doesn't these PR cover all the other versions?
* We don't know the exhaustive compatibility on platform versions. 
* For further improvements we will need to collaborate with NuGet client and dotnet sdk: https://github.com/NuGet/Engineering/issues/4730. 
Addresses: https://github.com/NuGet/NuGetGallery/issues/9337
=> [TFM] net6.0-windows7.0 compatibility added.

src/NuGetGallery/Strings.Designer.cs, src/NuGetGallery/Strings.resx, tests/NuGetGallery.Facts/Services/PackageMetadataValidationServiceFacts.cs
* Update readme link to how to include readme instead of best practice 
issue: https://github.com/NuGet/NuGetGallery/issues/9359
=> Update readme link

src/NuGetGallery/Controllers/PagesController.cs, src/NuGetGallery/UrlHelperExtensions.cs, tests/NuGetGallery.Facts/Controllers/PagesControllerFacts.cs, tests/NuGetGallery.Facts/UrlHelperExtensionsFacts.cs
Privacy page https://www.nuget.org/policies/Privacy redirect to generic Microsoft privacy policy.
Addresses https://github.com/NuGet/Engineering/issues/4669
=> redirect to external privacy link

src/AccountDeleter/EmptyFeatureFlagService.cs, src/GitHubVulnerabilities2Db/Fakes/FakeFeatureFlagService.cs, src/NuGetGallery.Core/CredentialTypes.cs, src/NuGetGallery.Services/Configuration/FeatureFlagService.cs, src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs, src/NuGetGallery/Controllers/PackagesController.cs, src/VerifyMicrosoftPackage/Fakes/FakeFeatureFlagService.cs, tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
We'll allow safety report categories only on MSA-only account-owned packages as a first step.
=> AAD account checks on packages for safety reports

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-list-packages.less, src/NuGetGallery/Scripts/gallery/page-list-packages.js, src/NuGetGallery/Views/Shared/ListPackages.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/9367,
https://github.com/NuGet/NuGetGallery/issues/9368,
https://github.com/NuGet/NuGetGallery/issues/9369,
https://github.com/NuGet/NuGetGallery/issues/9370,
https://github.com/NuGet/NuGetGallery/issues/9371,
https://github.com/NuGet/NuGetGallery/issues/9375,
https://github.com/NuGet/NuGetGallery/issues/9377,
https://github.com/NuGet/NuGetGallery/issues/9376
This PR addresses some of the issues flagged by the Search-by-TFM bug bash:
1. The Prerelease url parameter sometimes had an uppercase boolean ('True') and sometimes a lowercase boolean ('true'). It will always show a lowercase boolean now. 
https://github.com/NuGet/NuGetGallery/issues/9367
2. The frameworks and tfms parameters were being added to the query string in the order …
=> Search-by-TFM Bug Bash feedback

src/NuGetGallery/App_Data/Files/Content/Trusted-Image-Domains.json
Add domain "caniuse.bitsofco.de" for image allowlist
Addresses https://github.com/NuGet/NuGetGallery/issues/9252
=> Add new domain for image allowlist 

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/common-readme.less, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Fix https://github.com/NuGet/NuGetGallery/issues/9354 and https://github.com/NuGet/NuGetGallery/issues/9355.
1. Use a new, prescribed info text for the `Script & Interactive` tab: https://github.com/NuGet/NuGetGallery/issues/9354#issuecomment-1405363060.
2. Make the code block bg color match the rest. I had to darken the comment color to avoid contrast issues.
3. Change the bg color of the README section on the upload page to be white. This fixes link contrast issues (newly discovered problem).
=> Fix two small UI issues (README bg color, Script & Interactive info)

src/AccountDeleter/EmptyFeatureFlagService.cs, src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-display-package.less, src/GitHubVulnerabilities2Db/Fakes/FakeFeatureFlagService.cs, src/NuGetGallery.Services/Configuration/FeatureFlagService.cs, src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs, src/NuGetGallery/App_Data/Files/Content/flags.json, src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, src/VerifyMicrosoftPackage/Fakes/FakeFeatureFlagService.cs
* Introduced new warning message on package display page when package is missing readme
* only display warning message to package authors
* added feature flag to this new warning
Before: 
After: 
Addresses https://github.com/NuGet/Engineering/issues/4695
=> Modify warning message on display package page when missing readme

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-list-packages.less, src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/Scripts/gallery/page-list-packages.js, src/NuGetGallery/ViewModels/PackageListViewModel.cs, src/NuGetGallery/Views/Shared/ListPackages.cshtml
1. This PR fixes an accessibility issue where, when the TFM section was collapsed and there were very few search results on the page, the black text of some of the TFM checkbox labels could overlap with the dark blue footer background (even though the checkboxes were not visible), causing a contrast issue on A11y FastPass. 
We now flip the TFM tab's `display` property between `'none'` and `'block'` when it is collapsed or expanded. This also means we don't need to manually toggle `tabindex` for the checkboxes when the section is collapsed or expanded.
2. The text we show when there's 0 package results also has an a11y issue, where it shouldn't have the `aria-expanded` property. I've removed that now.
3. I've also removed an unused ViewModel property (`ShouldDisplayAdvancedSearchPanel`).
=> Search page A11y fixes

src/NuGetGallery/Scripts/gallery/page-list-packages.js, src/NuGetGallery/Views/Shared/ListPackages.cshtml
The `/profiles` pages use the same js script as the search page, but do not have a `searchForm` element on the page, so we were getting exceptions from the javascript on the `/profiles` pages when we tried to reference the form elements.
I've now added checks in the script so that we do not reference anything that doesn't exist on the page.
I also removed a helper method that was not being used by the search page anymore (`AddSortByOption()`).
=> Added null checks to mitigate exceptions on the '/profiles' pages

src/NuGetGallery/Views/Shared/_ListPackage.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/9389
In the search results, tags sometimes spill over into the next line when there are multiple of them, but appear on the same line as downloads, version, etc. when there are very few of them.
Previously:
This is a consequence of the search results column now being narrower since the filter panel is on the left of the results rather than being above it.
Now, we will always show tags on the next line so that it is consistent.
After the change:
=> Tags sometimes spill over into the next line when there are multiple of them

src/NuGetGallery/Views/Packages/UploadPackage.cshtml
A [change](https://github.com/NuGet/NuGetGallery/commit/2e49db62585e14eb2fe65164f88e7f26109077cb) dropped the word "hosted" from the upload package page a while ago. Adding it back.
=> Putting back missing word

src/NuGetGallery/GalleryConstants.cs, tests/NuGetGallery.Facts/Controllers/ApiControllerFacts.cs
6.5 version of the client was published. Bumping the constant and updating tests.
=> MaxSupportedMinClientVersion update.

src/NuGetGallery/Services/MarkdownService.cs, tests/NuGetGallery.Facts/Services/MarkdownServiceFacts.cs
use reg to add alt = image to fix accessibility.
This is short term quick fix. we need come up a better long-term solution. 
For now, image just temporary image description.   
Addresses https://github.com/NuGet/Engineering/issues/4784
Issue created here to track for long term solution: https://github.com/NuGet/NuGetGallery/issues/9405
=> [WCP]alt attribute for img tag

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/common-supported-frameworks.less, src/NuGetGallery/Content/fabric.css, src/NuGetGallery/Content/gallery/css/fabric.css, src/NuGetGallery/Views/Packages/_SupportedFrameworksTable.cshtml
- Updated version 7.3.0 to 11.0.1
- Removed SquaredShape icon since it's no longer needed.
Addresses: https://github.com/NuGet/Engineering/issues/4756
=> Update Fabric Core to 11.0.1

src/NuGetGallery/Controllers/AuthenticationController.cs, src/NuGetGallery/ViewModels/LogOnViewModel.cs, src/NuGetGallery/Views/Authentication/LinkExternal.cshtml, tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
* Updated wording of the "Link Microsoft Account" page to include Legacy Account information.
* Legacy account page: This page will show when users have password account and are not part of the exception list.
* Link Microsoft account page: After a user with a legacy account issue sends a SR to us, we will verify the request and ownership. Once we approve it using our processes, the user will see this page and will be able to link their MSA if they know their password, otherwise they will be able to use the **Forgot your password?** link.
Addresses: https://github.com/NuGet/Engineering/issues/4617
=> [2FA] Update link msa/aad account page with legacy password account information.

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/base.less, src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/Scripts/gallery/page-list-packages.js, src/NuGetGallery/Views/Shared/ListPackages.cshtml, src/NuGetGallery/Views/Shared/_ListPackage.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/9402, https://github.com/NuGet/NuGetGallery/issues/9412 and https://github.com/NuGet/NuGetGallery/issues/9413
This PR fixes 3 a11y issues:
1. The tags in search results sometimes appeared on the same line as the other package metadata (version, last created, etc.) and sometimes appeared on the next line. We wanted to make this consistent and always have the 'tags' on the next line, but adding a `<br>` element in the middle of a list led to this a11y issue:
I've now removed the `<br>` element and fixed this with some css:
2. The chevrons that expanded/collapsed the TFM sections in the Filters panel did not indicate their expanded/collapsed state. The screen reader should be able to read their state. The 'aria-expanded' can be used to …
=> [A11y] Search page a11y fixes for tags and framework filter buttons

src/NuGetGallery/Views/Users/ApiKeys.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/9417
"Select Scopes" and "Select Packages" headings on the API Keys page were missing header tags. Added `h4` tag to both.
=> Fix accessibility issue - add missing header tag

src/NuGetGallery/App_Code/ViewHelpers.cshtml, src/NuGetGallery/Views/Users/ApiKeys.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/9415
Add a role to the `div` elements with the `aria-expanded` attribute. The role `form` is likely the best option in these scenarios.
=> Fix accessibility issue - role required when aria-expanded attribute is used

src/NuGetGallery/Views/Organizations/_OrganizationAccountManageMembers.cshtml
- change the order of html
- change the layout for extra small 
for extra small
Before: 
After: 
Addresses https://github.com/NuGet/NuGetGallery/issues/9450
=> [A11y]The focus order is not in left to right order 

src/NuGetGallery/Scripts/gallery/page-list-packages.js, src/NuGetGallery/Strings.Designer.cs, src/NuGetGallery/Strings.resx, src/NuGetGallery/ViewModels/PackageListViewModel.cs, src/NuGetGallery/Views/Shared/ListPackages.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/9414
The tooltip next to the Frameworks filters served both as a popover (showed some info when you hovered) and also as a link to our Target Frameworks docs, and the same tooltip icon produced two separate tab stops that told users this icon served different purposes. We needed to either separate these into 2 separate controls, or get rid of one of them. I got rid of the popover, but using the 'title' attribute in the link allows me to serve up the same information when a user hovers or tabs to the link icon. I think this should fix the a11y issue while still providing the users the same level of context.
I also changed the link to point to our [nuget.org filtering and sorting …
=> [A11y] Fix Framework filter tooltip's confusing double behavior

src/NuGetGallery/Views/Shared/_ListPackage.cshtml, src/NuGetGallery/Views/Users/Organizations.cshtml
* Added title for `More information` link on search page.
* Added title for `Add new` link on organization page.
Addresses https://github.com/NuGet/NuGetGallery/issues/9423
=> [A11y bug] More Information link on search results page is ambiguous.

src/NuGetGallery.Core/Infrastructure/TableErrorLog.cs, src/NuGetGallery/App_Code/ViewHelpers.cshtml, src/NuGetGallery/Scripts/gallery/page-list-packages.js, src/NuGetGallery/Strings.Designer.cs, src/NuGetGallery/Strings.resx, src/NuGetGallery/ViewModels/PackageListViewModel.cs, src/NuGetGallery/Views/Organizations/_OrganizationAccountManageMembers.cshtml, src/NuGetGallery/Views/Shared/ListPackages.cshtml, src/NuGetGallery/Views/Shared/_ListPackage.cshtml, src/NuGetGallery/Views/Users/ApiKeys.cshtml, src/NuGetGallery/Views/Users/Organizations.cshtml, tests/NuGetGallery.Core.Facts/Infrastructure/TableErrorLogFacts.cs, tests/NuGetGallery.Core.Facts/NuGetGallery.Core.Facts.csproj
[ReleasePrep][2023.04.05]RI of dev into main
@joelverhagen 
@theot12
=> [ReleasePrep][2023.04.05]RI of dev into main

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-api-keys.less, src/Bootstrap/less/theme/page-display-package.less
Problem:  Keyboard focus is not clearly visible because of overflow was set to hidden. 
Fix: Changed to visible since the button name length is fix, won't be overflow.
For "Eidt, Regenerate, Delete" buttons, it's ok to 
Addresses https://github.com/NuGet/Engineering/issues/4827
=> Keyboard focus is not clearly visible 

src/NuGetGallery/Views/Packages/_SupportedFrameworksTable.cshtml
* Added more explanatory column version message for screen readers.
* Added message to differentiate between compatible and computed TFMs for screen readers.
Addresses https://github.com/NuGet/NuGetGallery/issues/9421
=> [A11y] TFM table differentiate versions for screen readers

src/Bootstrap/dist/js/bootstrap.js, src/Bootstrap/js/tab.js, src/NuGetGallery/Scripts/gallery/page-display-package.js, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
* Removed `aria-expanded` from DisplayPackage for element that should only have `aria-selected`.
* Added comment stating that `data-toggle="tab"` adds `aria-expanded` every time it's selected/active. So, it needed to be removed when the script is loaded and after the `shown.bs.tab` event.
Addresses https://github.com/NuGet/NuGetGallery/issues/9418
=> [A11y bug] Package Manager tab on Package details reads as both selected and expanded

src/Bootstrap/dist/js/bootstrap.js, src/Bootstrap/js/collapse.js, src/NuGetGallery/App_Code/ViewHelpers.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/9415
Added a fix to the JavaScript that controls collapsible elements to not add the `aria-expanded` attribute for elements that do not have an [allowed role](https://w3c.github.io/aria/#aria-expanded).
=> Disallow aria-expanded for collapsible elements without an allowed role

src/NuGetGallery/Scripts/gallery/async-file-upload.js
Addresses #9393.
The error message for large files is now back and with updated error message:
=> Getting back the error message when uploading large files.

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-display-package.less, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Before: 
After:
Addresses: https://github.com/NuGet/Engineering/issues/4827
=> Keyboard focus on owner list on package detail page

src/NuGetGallery/Scripts/gallery/page-list-packages.js, src/NuGetGallery/Views/Shared/ListPackages.cshtml
* Gives focus to `results-column` element to tell screen readers were to start if the `Apply` button or the `Search` button were clicked.
* uses `localStorage` to track if those buttons were clicked before the page refresh.
Addresses: https://github.com/NuGet/NuGetGallery/issues/9422
=> [A11y] Make screen readers start with packages list on Search Page.

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Fixes an issue where JAWS and NVDA cannot access the package warnings column in Version History table using `ctrl` + `alt` + `right arrow key`. Removing the `span` element and distributing its attributes solves the issue. 
Addresses: https://github.com/NuGet/NuGetGallery/issues/9472
=> [a11y] remove span element in version history table

src/NuGetGallery/Views/Shared/_ListPackage.cshtml, src/NuGetGallery/Views/Users/Organizations.cshtml
* Apparently adding `title` didn't fix entirely this issue so I added `aria-label` to those links.
Addresses https://github.com/NuGet/NuGetGallery/issues/9423
=> [A11y] Add screen reader description to More information and Add new links

src/AccountDeleter/Configuration/GalleryConfiguration.cs, src/NuGetGallery.Services/Configuration/AppConfiguration.cs, src/NuGetGallery.Services/Configuration/IAppConfiguration.cs, src/NuGetGallery.Services/NuGetGallery.Services.csproj, src/NuGetGallery.Services/ServicesStrings.Designer.cs, src/NuGetGallery.Services/ServicesStrings.resx, src/NuGetGallery/Controllers/AuthenticationController.cs, src/NuGetGallery/Controllers/StatisticsController.cs, tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs, tests/NuGetGallery.Facts/Controllers/StatisticsControllerFacts.cs
This fixes the top 2 buckets of HTTP 500s on NuGet.org during the past 30 days. The first issue has user impact. The second one generates alerting noise for us.
Fix https://github.com/NuGet/NuGetGallery/issues/9486 - verified locally with a large stats blob. I believe the only risk here is increasing the load on our front-end nodes. Currently, the data is already being loaded into memory just failing at the time of JSON serialization. Memory utilization on our front-end nodes is very acceptable right now so I don't anticipate any problem. The largest response body I see is 11,339,294 bytes for AWSSDK.Core with all 3 checkboxes. That's why I picked a default of 16 MB.
Fix https://github.com/NuGet/NuGetGallery/issues/9487 - simply handle the null or unknown provider parameter and return an …
=> Resolve top 2 HTTP 500 sources on NuGetGallery

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-display-package.less, src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, tests/NuGetGallery.Facts/ViewModels/DisplayPackageViewModelFacts.cs
Address https://github.com/NuGet/NuGetGallery/issues/9466
- Hide package metadata even when the user is not locked, but the package is still locked. This allows more precise metadata hiding and administrative actions. We need not lock the entire user to hide some of the user's package metadata.
- Consider deleted the same as unlisted for this locking + hiding purpose.
- Hide more metadata when a package is locked and unlisted/deleted.
All in all, this makes package locking more powerful for hiding package content that breaks our terms of use.
(this example shows vulnerability even when unlisted/locked/deleted)
=> Hide metadata when a package is unlisted and locked

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
For the locked + unlisted case, the release notes tab is shown when none of the other tabs are. This is something I missed from a previous PR (https://github.com/NuGet/NuGetGallery/pull/9490).
=> Fix minor unlisted + locked metadata issue on package details page

tests/NuGetGallery.Facts/Services/SearchAdaptorFacts.cs
This UT fails locally, I believe due to a newer version of .NET Framework. Generally apostrophes should be URL encoded so I modified the test to avoid this behavior change.
=> Fix unit test that fails locally

src/GitHubVulnerabilities2Db/Gallery/ThrowingTelemetryService.cs, src/NuGetGallery.Core/Entities/EntitiesContext.cs, src/NuGetGallery.Core/Entities/IEntitiesContext.cs, src/NuGetGallery.Services/Extensions/HttpContextBaseExtensions.cs, src/NuGetGallery.Services/Telemetry/ITelemetryService.cs, src/NuGetGallery.Services/Telemetry/TelemetryService.cs, src/NuGetGallery/App_Data/Files/Content/flags.json, src/NuGetGallery/Controllers/ApiController.cs, src/NuGetGallery/Filters/RequiresUserAgentAttribute.cs, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Services/PackageDeprecationManagementService.cs, src/NuGetGallery/Services/PackageDeprecationService.cs, src/NuGetGallery/Telemetry/ClientInformationTelemetryEnricher.cs, src/NuGetGallery/Web.config, src/VerifyMicrosoftPackage/Fakes/FakeEntitiesContext.cs, src/VerifyMicrosoftPackage/Fakes/FakeTelemetryService.cs, tests/NuGetGallery.Facts/Filters/RequiresUserAgentAttributeFacts.cs, tests/NuGetGallery.Facts/Framework/TestAuditingService.cs, tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj, tests/NuGetGallery.Facts/Services/PackageDeprecationManagementServiceFacts.cs, tests/NuGetGallery.Facts/Services/PackageDeprecationServiceFacts.cs, tests/NuGetGallery.Facts/Services/TelemetryServiceFacts.cs, tests/NuGetGallery.Facts/Telemetry/ClientInformationTelemetryEnricherTests.cs, tests/NuGetGallery.Facts/TestUtils/FakeEntitiesContext.cs, tests/NuGetGallery.FunctionalTests/ErrorHandling/ErrorHandlingTests.cs
- No-op the last edit update if there are no changes (reduces V3 load)
- Require user agent and include the full UA as a custom dimension in App Insights
- Return 400 not 404 when the alternate package is missing 
- Require user agent for the deprecation endpoint
- These changes are backwards compatible with the known integrations with the Deprecation API
Depends on https://github.com/NuGet/NuGetGallery/pull/9505.
Align the API with the design changes described here: https://github.com/NuGet/Engineering/pull/4709 (internal PR now, will be public after public preview begins).
=> Adjust deprecation API slightly to prepare for public preview

src/NuGetGallery/Areas/Admin/Controllers/PasswordAuthenticationController.cs, src/NuGetGallery/Areas/Admin/Views/PasswordAuthentication/Index.cshtml
problem: `IsAADorMACredential` is not assigned. 
Fix: check if credential is AAD or MA, then assign `IsAADorMACredential = true`, otherwise false
Test: Tested in dev environment
Addresses: https://github.com/NuGet/Engineering/issues/4904
=> Fix user credential result on admin panel

src/NuGet.Services.Entities/CredentialRevocationSource.cs, src/NuGetGallery.Services/Authentication/AuthenticationService.cs, src/NuGetGallery/Controllers/UsersController.cs, src/NuGetGallery/Infrastructure/Mail/Messages/ApiKeyRevokedMessage.cs, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Scripts/gallery/page-api-keys.js, src/NuGetGallery/Strings.Designer.cs, src/NuGetGallery/Strings.resx, src/NuGetGallery/UrlHelperExtensions.cs, src/NuGetGallery/Views/Users/ApiKeys.cshtml, tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs, tests/NuGetGallery.Facts/Infrastructure/Mail/Messages/ApiKeyRevokedMessageFacts.cs, tests/NuGetGallery.Facts/NuGetGallery.Facts.csproj
* Revoke button added for api keys.
* Existing revocation mechanism used.
Addresses https://github.com/NuGet/NuGetGallery/issues/9426
edit by @joelverhagen -- added screenshot
=> Add revoke button to API keys page

.github/dependabot.yml
Configure Dependabot to check for updates:
- monthly for NuGet packages
- weekly for submodules
Create PRs and assign to Gallery team.
Addresses [Configure Dependabot properly](https://github.com/NuGet/Engineering/issues/4938)
=> Create dependabot.yml for Dependabot configuration

src/NuGet.Services.Entities/NuGet.Services.Entities.csproj
Dependabot made changes to this project file to upgrade a package version in **main** first, and then made changes to the same file in **dev** for a different package, so the file had conflicts that needed to be resolved. This should fix it.
=> Fixing package upgrade conflicts in NuGet.Services.Entities.csproj

tests/NuGetGallery.Facts/Areas/Admin/Controllers/DeleteControllerFacts.cs, tests/NuGetGallery.Facts/Controllers/OrganizationsControllerFacts.cs, tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs, tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
With latest .net sdk with command line build causing ton of warnings about Disposable is not implemented.
=> Fix dispose violation error in tests

src/NuGetGallery/Web.config
The DEV deployment seems to be working now with these binding redirects: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=1469494
=> Fixing bindings

src/Bootstrap/less/theme/page-list-packages.less, src/NuGetGallery/Scripts/gallery/page-list-packages.js, src/NuGetGallery/Views/Shared/ListPackages.cshtml
I made the advanced search collapsible on narrow screens.
Before:
After:
There are details in the problem description that I didn't change (removing sort-by and putting filters below packages returned) because I talked with PM and designers and we didn't find these changes useful.
Addresses https://github.com/NuGet/NuGetGallery/issues/9374ery/issues/123
=> Make search collapsible

.github/dependabot.yml
There are risks that we discovered associated with enabled Dependabot that we don't want to take now: After configuring it on Gallery, we had a lot of build breaks and runtime errors. There are also risks of performance regressions.
1ES is enabling 1ES Dependabot (see thread "1ES Dependabot is coming to your repositories for NuGet Service") which should take care of our CG alerts automatically for us.
Decision:
We are postponing enabling Dependabot for when we have more capacity. We will do it in priority order, updating some packages first, starting with the ones that are likely to be in security asks (Azure SDKs or anything else that we interact with resources, scary dependencies: SQL, KeyVault, etc.).
Related to https://github.com/NuGet/Engineering/issues/4938
=> Disable dependabot.yml

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/page-manage-organizations.less, src/NuGetGallery/Scripts/gallery/page-manage-organization.js, src/NuGetGallery/Views/Organizations/_OrganizationAccountManageMembers.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/9609
**Problem:**
Users want to see a confirmation message when they successfully add a member to their organization. They can currently see the Members list to see the new member with "(pending approval)" next to their name, but they want to see a more explicit success message.
**Solution:**
**NOTE:** I also fixed an a11y issue that showed up on A11y Fastpass where multiple 'member role' elements (the 'Select role' dropdowns in the screenshot) had the same ids. This id wasn't being used anywhere so I just moved the value to the element's class list instead.
=> [Usability] Show a success message when adding members to your org

src/NuGetGallery/Scripts/gallery/page-display-package.js, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Opening new tabs by right-clicking on buttons didn't work.
Buttons in question: 
It now works.
Addresses https://github.com/NuGet/NuGetGallery/issues/9283
=> Fix url frameworks tab

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/common-list-packages.less, src/NuGetGallery/App_Data/Files/Content/flags.json, src/NuGetGallery/Views/Shared/_ListPackage.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/9608
**Problem:**
Users don't like the fact that they have to tab through everything in each search result to move down the list of search results. They want to be able to navigate between search results more easily.
**Solution:**
I placed the package IDs for each search result inside `<h2>` heading tags. With screen readers, you can navigate between headings using `H/shift+H`, and then continue sequential navigation through each search result using `tab/shift+tab`. Users will now be able to move between individual search results quicker.
There is no visible UI change here. The css changes are there to just keep the package headers looking the same as they did previously.
**NOTE:** There was an old feature flight that was missing from …
=> [Usability] Users can now jump quickly between individual search results

src/NuGetGallery/Controllers/PackagesController.cs, tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
Addresses https://github.com/NuGet/Engineering/issues/4867
=> Not tracking package push failures when package is a duplicate.

NuGet.config, src/DatabaseMigrationTools/DatabaseMigrationTools.csproj, src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj, src/NuGetGallery.Core/NuGetGallery.Core.csproj, src/NuGetGallery.Services/Configuration/SecretReader/SecretReaderFactory.cs, src/NuGetGallery.Services/NuGetGallery.Services.csproj, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Web.config
Related to: https://github.com/NuGet/Engineering/issues/4704
Transition from Microsoft.Azure.KeyVault to Azure.Security.KeyVault package dependency. Former one is deprecated.
I manually tested this change in [Gallery dev environment](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=1478870)
=> Transition from Microsoft.Azure.KeyVault to Azure.Security.KeyVault

src/AccountDeleter/AccountDeleter.csproj, src/GitHubVulnerabilities2Db/GitHubVulnerabilities2Db.csproj, src/NuGet.Services.DatabaseMigration/NuGet.Services.DatabaseMigration.csproj, src/VerifyGitHubVulnerabilities/VerifyGitHubVulnerabilities.csproj
Related to: https://github.com/NuGet/Engineering/issues/4704
Transition from Microsoft.Azure.KeyVault to Azure.Security.KeyVault package dependency. Former one is deprecated.
This one is separate from previously merged https://github.com/NuGet/NuGetGallery/pull/9654, we have to another round of update due to circular dependency in NuGet.Jobs (`NuGetGallery -> NuGet.Jobs -> NuGetGallery`).
Previous `NuGetGallery -> NuGet.Jobs` iteration PR:  https://github.com/NuGet/NuGet.Jobs/pull/1148/files
This PR is for `NuGet.Jobs -> NuGetGallery` iteration and it's necessary for `Account Deleter job`.
=> Transition from Microsoft.Azure.KeyVault to Azure.Security.KeyVault, next iteration

src/NuGetGallery/Web.config
This makes it easier to remember to set this value when you set the storage type to `AzureStorage`. This is needed when uploading embedded licenses.
=> Add FlatContainer empty config to web.config

tools/Update-Databases.ps1
On DevBox, global packages folder location is overridden using NUGET_PACKAGES environment variable. This currently breaks the Update-Database.ps1 script, which assumes GPF is at the default location: %userprofile%\.nuget\packages.
NuGet Client docs: https://learn.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders
=> Fix Update-Database.ps1 to work on DevBox

Directory.Build.props, build.ps1, src/NuGetGallery.Core/NuGetGallery.Core.csproj, src/NuGetGallery/Web.config
Progress on https://github.com/NuGet/Engineering/issues/4992
- Drop `Microsoft.IdentityModel.Clients.ActiveDirectory` (ADAL), pick up `Microsoft.Identity.Client` (MSAL)
- Move to latest ServerCommon to pull in MSAL move
- Drop unnecessary ADAL reference
- Update build tools to latest to drop ADAL reference in a tool
- The NuGet.Jobs update is for the Service Bus update, I'll come back later with another NuGet.Jobs update once ServerCommon has gotten there
- Resolve minor DevSkim warnings
=> Move from ADAL to MSAL

src/NuGetGallery/Scripts/gallery/page-downloads.js
I removed the duplicate package and refactored the code a bit.
Before:
After:
How to test:
Go to [this file](https://github.com/NuGet/NuGet.Services.Index/blob/main/PROD/dist.nuget.org-index/index.json). Click on "raw" (see image)
Copy the URL of the raw file. Now, go to Downloads.cshtml line 86 and instead of //dist.nuget.org/index.json, paste the URL you previously copied. Run the code. Go to Downloads. Older versions of win-x86 should be collapsible. There should also be a red message indicating that these versions are unsupported.
=> Removed the duplicate package

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Fixed broken buttons.
Test: open a package and check that buttons for Package Manager, Paket CLI, Script & Interactive, Cake, and .NET CLI work.
Proof:
=> Fixed url bug final

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/all.less, src/Bootstrap/less/theme/page-admin-popularity-transfers.less, src/NuGetGallery/Areas/Admin/Controllers/PopularityTransferController.cs, src/NuGetGallery/Areas/Admin/ViewModels/PopularityTransferViewModel.cs, src/NuGetGallery/Areas/Admin/Views/Home/Index.cshtml, src/NuGetGallery/Areas/Admin/Views/PopularityTransfer/Index.cshtml, src/NuGetGallery/Areas/Admin/Views/ReservedNamespace/Index.cshtml, src/NuGetGallery/NuGetGallery.csproj
Addresses https://github.com/NuGet/Engineering/issues/4746
<details><summary>You can now enter a list of packages you want to transfer popularity from, and a list of packages you want to transfer to. </summary>
</details> 
<details><summary>It then validates your input. </summary>
</details> 
<details><summary>Submitting your changes updates the DB with new entries in the PackageRenames table.</summary>
You can see the new Serilog (Key = 11) --> Moq (Key = 9) entry
</details> 
<details><summary>Error Handling</summary>
</details> 
<details><summary>Checking for existing popularity transfers</summary>
**NOTE:** Our current playbook asks us to delete any existing popularity transfers for the 'From' packages, so the popularity transfer operation deletes previous entries from the DB. Let me …
=> Admin Panel for Popularity Transfers

src/VerifyGitHubVulnerabilities/Verify/PackageVulnerabilitiesVerifier.cs
Resolve https://github.com/NuGet/NuGetGallery/issues/9703. The job is currently failing with a long path problem due to the v3-cache. We don't need the v3-cache for this workflow.
This also sets the `includeUnlisted` to `true` because those should be verified also.
=> Hotfix: don't use v3-cache for VerifyGitHubVulnerabilities

src/NuGetGallery/Web.config
We updated some package versions in dev recently and started seeing runtime issues.
Changing this binding redirect in the Web.config file should fix it.
=> Changing a binding redirect to fix Gallery runtime issues

.editorconfig, NuGetGallery.sln, build.ps1, src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs, src/NuGetGallery/ViewModels/PackageViewModel.cs, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, src/NuGetGallery/Views/Packages/License.cshtml
Resolve https://github.com/NuGet/NuGetGallery/issues/9670.
The diff is best viewed when [hiding whitespace](https://github.com/NuGet/NuGetGallery/pull/9719/files?diff=unified&w=1).
- Add `no-index` to all license pages. I think this is the right approach. We index the "parent" page (per ID - version). 
- We already don't index the Report abuse page, which is the other child page not requiring sign in
- Hide license content when the package is locked
- Hide other warnings/info messages on the package details
- Unrelated: default generated assembly version to 4.4.5 to make matching release builds easier (strong name is unsolved)
- Unrelated: fix minor devskim warnings 
- Unrelated: two super helpful warnings back to editorconfig
=> [Hotfix] Don't index the license page and hide content when locked

src/GitHubVulnerabilities2Db/Job.cs
Previously, the config was not properly registered with AutoFAC as its base class, failing dependency injection at runtime.
This change properly registers the config as both config classes so DI doesn't fail.
=> [Hotfix][GithubVulnerabilites2Db]Register config as base class with AutoFAC

src/NuGetGallery.Core/Frameworks/SupportedFrameworks.cs
Addresses https://github.com/NuGet/Engineering/issues/5111
We want to add .NET 8 search filters and TFM badges in time for the .NET 8 release.
**Search filters:**
**TFM badges:**
Previously,
After the changes,
NOTE: We usually rely on constants from the NuGet.Frameworks package, but those changes have not been published yet. Once those changes are published with v6.9.0 of the Client SDK, we can remove our Gallery-only constants (`Version8` and `Net80`) and replace them with the appropriate constants from the NuGet.Frameworks package (See https://github.com/NuGet/Engineering/issues/5112).
=> Add .NET 8 constants for TFM badges and search filters

src/NuGetGallery/Areas/Admin/Controllers/PopularityTransferController.cs, src/NuGetGallery/Areas/Admin/ViewModels/PopularityTransferViewModel.cs, src/NuGetGallery/Areas/Admin/Views/PopularityTransfer/Index.cshtml, src/NuGetGallery/Services/IPackageRenameService.cs, src/NuGetGallery/Services/PackageRenameService.cs
1. The Popularity Transfer Admin Panel has a bug where it shows version-specific download counts for packages, rather than the package registration's download count, which is what we want (we transfer popularity from one package registration to another). I had to refactor some code to get that data correctly. This now works:
(DEV packages: https://dev.nugettest.org/packages/Newtonsoft.Json/)
2. I also added some more validation info to the Admin Panel page, which should save us from having to go look in the SQL DB manually every time every time:
=> Fixing popularity transfer download count bug, surfacing additional validation info

src/NuGetGallery/Areas/Admin/Views/UpdateListed/Index.cshtml
This PR adds a little prompt when you click in the `Select listed` or `Select unlisted` asking you how many packages you want to select. If you type anything but a number, it selects all (default behavior, just press enter) 
After Clicking: 
Addresses https://github.com/NuGet/NuGetGallery/issues/9517
=> Allow admins to select a specific number of package versions

src/VerifyGitHubVulnerabilities/README.md
Addresses https://github.com/NuGet/Engineering/issues/5149
This change updates the instructions with more concrete JSON, rather than the obscure description which was there before.
=> Put more customer-friendly instructions in the VerifyGitHubVulnerabilities readme

src/NuGetGallery/Views/Packages/ReportAbuse.cshtml
Addresses (in part) https://github.com/NuGet/Engineering/issues/5150
Page changes include:
1. Added detail to info box near top. Before:
After:
2. Disabled form for copyright/trademark infringements. Before:
After:
=> Remove copyright/trademark reporting from report package page

src/NuGetGallery.Core/Frameworks/SupportedFrameworks.cs
Addresses https://github.com/NuGet/NuGetGallery/issues/9761
.NET 8 added a new platform-specific TFM with `net8.0-browser`, so we need to include it in our supported platforms.
Previously,
After the changes,
=> Add net8.0-browser to supported platforms

src/NuGetGallery/Controllers/PackagesController.cs
Should address an odd issue with support requests where we get reasons that we shouldn't be seeing in support DB.
=> Reject POST to report abuse if the reason isn't one we allow reporting from the form.

src/NuGetGallery.Core/Frameworks/FrameworkCompatibilityService.cs, src/NuGetGallery.Core/Frameworks/SupportedFrameworks.cs, tests/NuGetGallery.Core.Facts/Frameworks/FrameworkCompatibilityServiceFacts.cs
Addresses https://github.com/NuGet/NuGetGallery/issues/9711
TFMs that contain platform monikers and versions, like `net6.0-android31.0`, were not showing the `net7.0-android` and `net8.0-android` TFMs as users expected. 
https://www.nuget.org/packages/Xamarin.AndroidX.Lifecycle.Common/2.6.2.2#supportedframeworks-body-tab
If the TFM didn't have a platform version, say just `net6.0-android`, then the corresponding `net7.0` and `net8.0` TFMs show up as expected.
https://www.nuget.org/packages/Microsoft.CognitiveServices.Speech.Extension.ONNX.Runtime/1.33.0#supportedframeworks-body-tab
Currently, if a TFM (.NET 5+) has a platform version, it does not show any computed compatible TFMs. Our compatibility matrix only includes TFMs without platform versions.
To fix this, if we see a TFM with a …
=> Normalize TFM platform versions when determining computed compatibility

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/less/theme/common-supported-frameworks.less, src/NuGetGallery/Scripts/gallery/page-list-packages.js
Addresses https://github.com/NuGet/NuGetGallery/issues/9795
This fixes:
1. The TFM badges were showing a trailing underline when someone hovered over it. This has now been removed.
2. When someone brought tab focus to the badges, it showed an outline, but the outline was distorted because the child elements (`<span>`) had different dimensions to the parent (`<a>`). This has been fixed.
Previously,
Now,
3. The TFM badges are supposed to have a tooltip when you hover over them (See the package display page: https://www.nuget.org/packages/Newtonsoft.Json). This tooltip was missing on the search page, but it's been added now.
=> TFM Badges: Fixed focus underline and outline + Added missing tooltip

src/NuGetGallery/Web.config
Similar to https://github.com/NuGet/NuGetGallery/pull/9597
We made recent package upgrades to Gallery, and started seeing runtime issues because of conflicting assembly versions. We have assembly bindings in the Web.config file, and these need to be deleted and regenerated when we see these binding conflicts ([Gallery runtime issues due to missing or conflicting assembly bindings](https://microsoft.sharepoint.com/teams/NuGet/_layouts/OneNote.aspx?id=%2Fteams%2FNuGet%2FTeam%2FNugetServer%2FNugetServerTeamNote&wd=target%28On-call.one%7CFFA95A40-BC9F-4CE4-A7D2-3ED62759712D%2FGallery%20runtime%20issues%20due%20to%20missing%20or%20conflicting%20assembly%20bindings%7C39633840-461E-427B-9305-9A483D4679D4%2F%29)).
Most of the changes here are just whitespace changes, outside of 5-6 package …
=> Fix assembly bindings to resolve runtime errors

src/NuGetGallery.Core/Services/CorePackageService.cs, src/NuGetGallery.Services/PackageManagement/IPackageService.cs, src/NuGetGallery.Services/PackageManagement/PackageService.cs, src/NuGetGallery/Controllers/PackagesController.cs, tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
As the package details page loads the metadata of all package versions: https://github.com/NuGet/NuGetGallery/blob/e043791f59cc939c09df7802ae552dde5500039d/src/NuGetGallery/Helpers/ViewModelExtensions/DisplayPackageViewModelFactory.cs#L79-L87
it is better [eagerly loading](https://learn.microsoft.com/en-us/ef/ef6/querying/related-data) supported frameworks and deprecations of all versions together, rather than loading each version one by one.
Add another API rather than change the shape of existing ones, to avoid breaking other dependencies on [`IPackageService`](https://github.com/NuGet/NuGetGallery/blob/main/src/NuGetGallery.Services/PackageManagement/IPackageService.cs).
=> [Package Details] Eagerly load supported frameworks and deprecations.

src/NuGetGallery/Scripts/gallery/page-downloads.js, src/NuGetGallery/Views/Pages/Downloads.cshtml
The download page is now updated. Here's how it looked like before:
Here is how it looks like now:
Rationale for changes:
Having old versions of VS is not relevant anymore.
The list of versions has been updated and approved in a different PR.
There is no warning message anymore because the versions included are supported.
Testing:
Go to [this file](https://github.com/NuGet/NuGet.Services.Index/blob/main/PROD/dist.nuget.org-index/index.json). Click on "raw" (see image)
Copy the URL of the raw file. Now, go to Downloads.cshtml line 86 and instead of //dist.nuget.org/index.json, paste the URL you previously copied. Run the code. Go to Downloads. Older versions of win-x86 should be collapsible. There should also be a red message indicating that these versions are unsupported.
Addresses …
=> Downloads page changed

src/NuGetGallery/Scripts/gallery/page-list-packages.js, src/NuGetGallery/Views/Shared/ListPackages.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/9818
The bootstrap popover on the Framework Filter Mode tooltip had different colors within it:
We were using a `title` attribute for the text earlier. Switching to a `data-content` attribute fixes this issue:
=> Fix Framework Filter Mode tooltip colors

src/NuGetGallery/Views/Packages/_SupportedFrameworksTable.cshtml
- The idea of "compatible" and "computed" is an odd distinction
- "Compatible" and "included" seems much more useful, with the former being the high-value distinction
- More generally, we should ensure that we have common developer workflows that align with this checkerbox display.
- Sure would be nice to get EOL information in here
Example: https://www.nuget.org/packages/Microsoft.Extensions.Logging/9.0.0-preview.1.24080.9#supportedframeworks-body-tab
=> Update Frameworks table to use clearer "Included/Compatible framework" framing

src/NuGetGallery/Strings.Designer.cs, src/NuGetGallery/Strings.resx, src/NuGetGallery/Views/Packages/_SupportedFrameworksBadges.cshtml
Updates Tooltips on TFM badges to be more descriptive.
Addresses https://github.com/NuGet/NuGetGallery/issues/9814 and https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1970927
The badges currently say:
This package is compatible with this framework or higher.
This will update these to new strings
Asset framework:
This package targets < framework>. The package is compatible with this framework or higher.
Computed framework
This package is compatible with < framework> or higher.
No Version
This package is compatible with all versions of < framework>.
=> Update TFM Badge Tooltips

src/NuGetGallery/Scripts/gallery/page-list-packages.js, src/NuGetGallery/Views/Shared/ListPackages.cshtml
Fixes a couple of small things before we release the new framework filters:
- Change "Include **computed** frameworks" to "Include **compatible** frameworks" in light of this change to the terminology: https://github.com/NuGet/NuGetGallery/pull/9835
- https://github.com/NuGet/NuGetGallery/issues/9816: The tooltip on the Frameworks heading was browser-native, and not bootstrap like all the other tooltips.
- The tooltip used to say that it 'filters packages based on the frameworks **included in the package**'. Now that the default includes 'computed' compatible frameworks too, I've changed this to say 'filters packages based on the frameworks **they are compatible with**'.
- **[A11y bug]** https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1970827: The Framework Filter Mode tooltip was …
=> Small fixes to the framework filters

src/NuGetGallery/Controllers/PackagesController.cs, tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs
Fix a bug introduced in https://github.com/NuGet/NuGetGallery/pull/9727 where we were rejecting all safety reasons reported instead of a small subset of them.
=> [HotFix]Fix rejection of all safety reasons.

src/NuGetGallery/Strings.Designer.cs, src/NuGetGallery/Strings.resx, src/NuGetGallery/Views/Shared/ListPackages.cshtml
Some of my previous changes introduced a new a11y bug. The 'Frameworks' filter tooltip was missing an aria-label, which I've now fixed.
I also took the chance to change the aria-label string to a `NuGetGallery.Strings` resource so that we don't have to change the text in multiple places the next time we need changes.
This clears a11y Fast Pass now. There's no visible UI changes.
NOTE: The changes on lines 77-81 are just whitespace changes.
=> Fixes a11y bug on search page tooltip

src/NuGetGallery.Core/Frameworks/SupportedFrameworks.cs
Fixes https://github.com/NuGet/Engineering/issues/5112
We had worked on adding .NET 8 search filters to nuget.org (https://github.com/NuGet/Engineering/issues/5111), but couldn't use the appropriate constants from the `NuGet.Frameworks` package at the time, so had to create our own.
The latest version of this package (6.9.1) now has the constants we need, so we can remove our own constants.
=> Use `NuGet.Frameworks` constants for .NET 8 TFMs

src/AccountDeleter/Scripts/Functions.ps1, src/GitHubVulnerabilities2Db/Scripts/Functions.ps1, src/GitHubVulnerabilities2v3/Scripts/Functions.ps1, src/VerifyGitHubVulnerabilities/Scripts/Functions.ps1
Progress on https://github.com/NuGet/Engineering/issues/5226
Related to https://github.com/NuGet/NuGet.Jobs/pull/1188
Running NSSM with PowerShell directly instead of [incorrectly] constructing command line for cmd. Helps when `$ScriptToRun` needs some proper quoting.
=> Running NSSM with PowerShell to get proper parameter quoting

src/Bootstrap/dist/css/bootstrap.css, src/Bootstrap/less/forms.less
Addresses https://github.com/NuGet/NuGetGallery/issues/9872
Adds theme for the TextArea component, 
| | Light | Dark |
|---|---|---|
| Rest |![image](https://github.com/NuGet/NuGetGallery/assets/43253759/95a84c25-8f5f-4561-a4c3-2e876767eb62)|![image](https://github.com/NuGet/NuGetGallery/assets/43253759/6326830c-7e41-4044-a426-35ec3c750439)|
|Focus|![image](https://github.com/NuGet/NuGetGallery/assets/43253759/2fcb98aa-6b22-4341-8eea-87b259cb2635)|![image](https://github.com/NuGet/NuGetGallery/assets/43253759/52c81084-b6b6-453d-aa1d-50f061f9d13e)|
|Disabled|![image](https://github.com/NuGet/NuGetGallery/assets/43253759/81f2d61c-ff40-48f2-84ab-d276556500ed)|![image](https://git …
=> [UI] Add new themes to TextArea component

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/dist/css/bootstrap.css, src/Bootstrap/less/buttons.less, src/Bootstrap/less/forms.less, src/Bootstrap/less/scaffolding.less, src/Bootstrap/less/theme/base.less, src/Bootstrap/less/theme/common-list-packages.less, src/Bootstrap/less/theme/common-supported-frameworks.less, src/Bootstrap/less/theme/page-list-packages.less, src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/Scripts/gallery/page-list-packages.js, src/NuGetGallery/Views/Shared/ListPackages.cshtml, src/NuGetGallery/Views/Shared/_SearchBar.cshtml
Addresses https://github.com/NuGet/NuGetGallery/issues/9854
Figma: https://www.figma.com/file/ZaAD9rDujh8JDkRF4q9Fd8/NuGet---Simple-theme-updates?type=design&node-id=61%3A9109&mode=design&t=Urj8iIoXc4thBO3E-1
These PR add's colors/theme for the Package List view, for this page we added:
- transparent button
- new styles for checkbox and radio buttons
- new style for switch.
- new theme for badges.
|  State | Dark |  Light |  
|---|---|---|
| Focused | ![image](https://github.com/NuGet/NuGetGallery/assets/43253759/a6c8db99-4552-43db-9130-eab66bcada10)  | ![image](https://github.com/NuGet/NuGetGallery/assets/43253759/acaa4eac-ae92-4690-ba04-fcff38d9e962)  | 
| Hover | ![image](https://github.com/NuGet/NuGetGallery/assets/43253759/2f5dfb63- …
=> [UI] Add new themes to Packages List view page 

src/NuGetGallery/App_Data/Files/Content/Trusted-Image-Domains.json
Allow LFS tracked images from GitHub repositories which are served on media.githubusercontent.com
Fixes https://github.com/NuGet/NuGetGallery/issues/9856
=> Allow images from media.githubusercontent.com

src/NuGetGallery/ViewModels/LogOnViewModel.cs
Fixes https://github.com/NuGet/Engineering/issues/5309
The Password login page (deprecated, but still used for password-based account recovery) has a 'Username or Email' field that only accepts Emails. Usernames do not work here, and this has caused confusion for customers multiple times. This field should just say 'Email' or 'Email Address', so I've fixed that now.
This will also change how the password login page appears in local development, although usernames should still work there as they used to. This just changes the string we show in the Login form UI.
Previously,
Now,
(the 'no longer supported' info bar is missing because this is a screenshot from my local deployment, but it should still be there in an actual environment)
=> Change password login page 'Username or Email' field to just 'Email'

src/NuGetGallery/Views/Packages/_SupportedFrameworksBadges.cshtml
Fixes https://github.com/NuGet/NuGetGallery/issues/9793
This removes some duplication in our frontend code for the Framework Badges. It should make it easier to make changes here in the future. 
No visible changes.
=> Parametrize framework badge code

src/NuGetGallery/Services/TyposquattingCheckListCacheService.cs
Related to https://github.com/NuGet/Engineering/issues/5080
At runtime we're getting this error.
NormalizeString needs to be called after the EF query is materialized, right now it is trying to map it to a SQL function.
It works fine on my local, not sure why failing on dev.
=> Fix EF runtime error

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/dist/css/bootstrap.css, src/Bootstrap/less/buttons.less, src/Bootstrap/less/mixins/tab-focus.less, src/Bootstrap/less/theme/base.less, src/Bootstrap/less/theme/page-admin-popularity-transfers.less, src/NuGetGallery/Areas/Admin/Views/ApiKeys/Index.cshtml, src/NuGetGallery/Areas/Admin/Views/Features/Index.cshtml, src/NuGetGallery/Areas/Admin/Views/Features/_AddFeature.cshtml, src/NuGetGallery/Areas/Admin/Views/Features/_AddFlight.cshtml, src/NuGetGallery/Areas/Admin/Views/Features/_EditFeature.cshtml, src/NuGetGallery/Areas/Admin/Views/Features/_EditFlight.cshtml, src/NuGetGallery/Areas/Admin/Views/Lucene/Index.cshtml, src/NuGetGallery/Areas/Admin/Views/PopularityTransfer/Index.cshtml, src/NuGetGallery/Areas/Admin/Views/ReservedNamespace/Index.cshtml, src/NuGetGallery/Areas/Admin/Views/Revalidation/Index.cshtml, src/NuGetGallery/Areas/Admin/Views/UpdateListed/Index.cshtml, src/NuGetGallery/Areas/Admin/Views/Validation/Index.cshtml, src/NuGetGallery/ExtensionMethods.cs
Adds new theme to Admin pages Verify API, Feature Flags, Flights, Lucene, Popularity Transfers, Namespaces, Unlist/Relist packages and Validate/Revalidate packages.
Addresses https://github.com/NuGet/NuGetGallery/issues/9866
=> [UI] Add new theme to Admin pages (part 3)

src/NuGetGallery/Views/Packages/UploadPackage.cshtml
Remove aria-expanded="true" from div id="upload-package-form" from UploadPackage.cshtml to fix accessibility bug #1979939
Bug link:
https://devdiv.visualstudio.com/DevDiv/_queries/edit/?tempQueryId=86f20051-1835-446b-b283-b35a28cb6618&id=1979939
=> Remove aria-expanded Attribute from Div

NuGetGallery.sln, tests/GitHubVulnerabilities2v3.Facts/GitHubVulnerabilities2v3.Facts.csproj
Currently build.ps1 fails due to a casing difference in the project name. Strangely Visual Studio build works just fine.
=> Fix project name to fix build.ps1 build error

src/Bootstrap/dist/css/bootstrap-theme.css, src/Bootstrap/dist/css/bootstrap.css, src/Bootstrap/less/dropdowns.less, src/Bootstrap/less/navbar.less, src/Bootstrap/less/popovers.less, src/Bootstrap/less/progress-bars.less, src/Bootstrap/less/theme/base.less, src/Bootstrap/less/theme/common-multi-select-dropdown.less, src/Bootstrap/less/theme/common-supported-frameworks.less, src/Bootstrap/less/theme/page-profile.less, src/NuGetGallery/Scripts/gallery/common.js, src/NuGetGallery/Views/Shared/Gallery/Layout.cshtml, src/NuGetGallery/Views/Shared/ListPackages.cshtml, src/NuGetGallery/Views/Shared/_AccountCertificates.cshtml, src/NuGetGallery/Views/Shared/_AccountChangeEmail.cshtml, src/NuGetGallery/Views/Shared/_AccountChangeNotifications.cshtml, src/NuGetGallery/Views/Shared/_AccountChangeTheme.cshtml, src/NuGetGallery/Views/Shared/_ConfirmationResendForm.cshtml, src/NuGetGallery/Views/Shared/_MultiSelectDropdown.cshtml
Adds new theme to Shared pages
Addresses https://github.com/NuGet/NuGetGallery/issues/9865
=> [UI] Add theme to shared pages

src/VerifyGitHubVulnerabilities/Job.cs
The changeset that introduced the GitHubVulnerabilities library failed to account for the changed DI requirements in VerifyGitHubVulnerabilities.
Unfortunately, this only surfaced at runtime.
This change fixes the DI.
=> Fixing VerifyGitHubVulnerabilities Dependency Injection

.pipelines/Release-trigger.yml
The pipeline we use to trigger releases from main and dev branches gets triggered on  PRs, too. Explicitly disabling it.
=> Explicitly disabling PR validation trigger for release trigger pipeline.

src/NuGetGallery/Scripts/gallery/page-list-packages.js
We're seeing some javascript exceptions for the profiles page. We use the same scripts file on the search page and the profiles page, and need to deal with null values properly to avoid exceptions. This should be fixed now.
=> Fixing JS exceptions on profiles page

src/NuGetGallery.Services/Authentication/AuthenticationService.cs, src/NuGetGallery.Services/Authentication/NuGetScopes.cs, src/NuGetGallery.Services/ServicesStrings.Designer.cs, src/NuGetGallery.Services/ServicesStrings.resx, src/NuGetGallery/Controllers/UsersController.cs, src/NuGetGallery/Strings.Designer.cs, src/NuGetGallery/Strings.resx, src/NuGetGallery/ViewModels/ApiKeyListViewModel.cs, src/NuGetGallery/Views/Users/ApiKeys.cshtml, src/NuGetGallery/Web.config, tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs, tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.cs
The existing unlist API key scope already has the relist and deprecate capabilities. This updates the supporting text used on the API keys page to mention these capabilities.
Progress on https://github.com/NuGet/NuGetGallery/issues/8873.
- Add relist to the API key label since it's always been there
- Make wording of package vs. package versions consistent (unlist/relist/deprecate is done at the version level)
- Show deprecate capability on the API key if the user is in the flight
- Delete some unused string in `src/NuGetGallery/Strings.resx`
- Fix web.config indentation for binding redirects
=> Add relist and deprecate to unlist scope

src/NuGetGallery/Services/PackageDeprecationService.cs, tests/NuGetGallery.Facts/Services/PackageDeprecationServiceFacts.cs
Mitigation for https://github.com/NuGet/NuGetGallery/issues/9950 in the package deprecation path.
**Hotfix justification:** deprecation API calls that would otherwise no-op sometimes return HTTP 500. Since this is a private preview API, there is no data correctness impact, and non-no-op deprecations work just fine, we could choose to not do a hotfix. I would just to prefer to get this fixed ASAP to eliminate a source of HTTP 500s.
Currently, if a deprecation call no-ops all package version and the node handling the deprecation has a different download count cached for a package version than is what in the DB, an HTTP 500 occurs.
This is because the package entity has changes (per the issue referenced above) but the deprecation service does not detect any changes on the entity. …
=> [Hotfix] Allow unrelated entity changes to be committed in PackageDeprecationService

src/NuGetGallery/App_Data/Files/Content/Trusted-Image-Domains.json
Cloudback is a SaaS providing automatic daily backups and instant restores of GitHub repositories, metadata, and LFS. The service is  available via [GitHub Marketplace](https://github.com/marketplace/cloudback). The domain of the service is [cloudback.it](https://cloudback.it/).
One of the features of Cloudback is a [backup status badge](https://cloudback.it/docs/status-badge), which is used to display the repository backup status. Please see the badge example below:
[![Backup Status](https://cloudback.it/badge/cloudback/docs)](https://cloudback.it)
According to the NuGet documentation, there is [a list of allowed domains](https://learn.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org#allowed-domains-for-images-and-badges) for images and badges. 
We would like to add the …
=> Add cloudback.it to trusted image domains list

src/NuGetGallery/Areas/Admin/Views/SupportRequest/Index.cshtml
We can remove this comment for reasons described in the bug.
Addresses https://github.com/NuGet/Engineering/issues/5485
=> Remove DMCA message from SR edit dialog

src/NuGetGallery/Areas/Admin/Controllers/CorrectIsLatestController.cs, tests/NuGetGallery.Core.Facts/Frameworks/PackageFrameworkCompatibilityFactoryFacts.cs, tests/NuGetGallery.Facts/Controllers/ODataV1FeedControllerFacts.cs, tests/NuGetGallery.Facts/Controllers/ODataV2FeedControllerFacts.cs, tests/NuGetGallery.Facts/Controllers/SupportControllerFacts.cs, tests/NuGetGallery.Facts/Infrastructure/Lucene/SearchPolicyFacts.cs
Shorten Linq syntax by using just Count instead of Where+Count.
=> use Count instead of Where+Count

src/NuGetGallery.Core/Frameworks/PackageFrameworkCompatibilityFactory.cs, src/NuGetGallery/Areas/Admin/Controllers/CorrectIsLatestController.cs, src/NuGetGallery/Areas/Admin/Services/ValidationAdminService.cs, src/VerifyMicrosoftPackage/Application.cs, tests/NuGetGallery.Facts/Areas/Admin/Controllers/AdminControllerBaseFacts.cs, tests/NuGetGallery.Facts/Areas/Admin/Controllers/ReservedNamespaceControllerFacts.cs, tests/NuGetGallery.Facts/Services/DeleteAccountServiceFacts.cs, tests/NuGetGallery.Facts/Services/SupportRequestServiceFacts.cs
Simplify Linq syntax and improve performance
=> remove redundant Wheres

src/NuGetGallery/Infrastructure/Lucene/SearchClientPolicies.cs, tests/NuGetGallery.Facts/Services/StatusServiceFacts.cs
given these are not actual state machines, there is no dependability concerns
=> elide Task.FromResult asyncs

src/NuGetGallery.Core/Services/CloudBlobClientWrapper.cs
Added `readAccessGeoRedundant` and `requestTimeout` arguments to `UsingMsi`.
=> More arguments for `UsingMsi` method.

.pipelines/Release-trigger.yml
Existing trigger pipeline does not pass through triggering pipeline properly, so instead I wrote a script that just starts target pipelines explicitly using AzDO REST API.
Had to add a parameter to this pipeline that contains information about target pipelines because only parameters support complex values (arrays, objects).
=> Explicitly triggering release pipelines

src/NuGetGallery/App_Code/ViewHelpers.cshtml, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml, src/NuGetGallery/Views/Shared/_ListPackage.cshtml, src/NuGetGallery/Views/Users/_UserPackagesListForDeletedAccount.cshtml
There was no onerror handle for packages images, this was removed during but never added again. Since we want to make this default image responsive to the theme, my solution is to tie the image to a class `package-default-icon` and this class overrides the image from the component. 
Addresses https://github.com/NuGet/NuGetGallery/issues/123
=> [Dark Theme] Render default package image on error

src/GitHubVulnerabilities2Db/Configuration/GitHubVulnerabilities2DbConfiguration.cs, src/GitHubVulnerabilities2v3/Configuration/GitHubVulnerabilities2v3Configuration.cs, src/GitHubVulnerabilities2v3/Extensions/BlobStorageVulnerabilityWriter.cs, src/NuGet.Services.Entities/PackageDeprecation.cs, src/NuGet.Services.Entities/UserCertificate.cs, src/NuGet.Services.GitHub/Ingest/AdvisoryIngestor.cs, src/NuGetGallery.Core/Auditing/FeatureFlagsAuditRecord.cs, src/NuGetGallery.Core/Auditing/Obfuscation/Obfuscator.cs, src/NuGetGallery.Core/Entities/EntitiesContext.cs, src/NuGetGallery.Core/Login/IEditableLoginConfigurationFileStorageService.cs, src/NuGetGallery.Core/Login/ILoginDiscontinuationFileStorageService.cs, src/NuGetGallery.Core/Login/LoginDiscontinuation.cs, src/NuGetGallery.Core/Login/LoginDiscontinuationFileStorageService.cs, src/NuGetGallery.Services/Configuration/LoginDiscontinuationConfiguration.cs, src/NuGetGallery/App_Start/OwinStartup.cs, src/NuGetGallery/Areas/Admin/Controllers/PasswordAuthenticationController.cs, src/NuGetGallery/Areas/Admin/ViewModels/UserCredentialSearchResult.cs, src/NuGetGallery/Controllers/ApiController.cs, src/NuGetGallery/Helpers/ViewModelExtensions/ListPackageItemViewModelFactory.cs, src/NuGetGallery/Services/SymbolPackageUploadService.cs, tests/NuGetGallery.Core.Facts/Login/EditableLoginConfigurationFileStorageServiceFacts.cs, tests/NuGetGallery.Core.Facts/Services/CloudBlobWrapperFacts.cs, tests/NuGetGallery.Facts/Areas/Admin/HelperFacts.cs, tests/NuGetGallery.Facts/Controllers/StatisticsControllerFacts.cs, tests/NuGetGallery.Facts/Infrastructure/Mail/Messages/ContactOwnersMessageFacts.cs, tests/NuGetGallery.Facts/Services/TyposquattingServiceFacts.cs
This makes a future repository merge easier because it minimizes the number of project references that I might need to add when a PackageReference changes to a ProjectReference. For legacy csproj, project references are not transitive so I want as few type references as possible, including namespace usings.
=> Remove unnecessary usings

.editorconfig, src/NuGetGallery.Core/CoreConstants.cs, src/NuGetGallery.Services/Storage/CloudBlobFileStorageService.cs, src/NuGetGallery.Services/Storage/IFileStorageService.cs, src/NuGetGallery/Services/FileSystemFileStorageService.cs, src/NuGetGallery/Services/PackageFileService.cs, src/NuGetGallery/Services/SymbolPackageFileService.cs, tests/NuGetGallery.Facts/Services/CloudBlobFileStorageServiceFacts.cs, tests/NuGetGallery.Facts/Services/FileSystemFileStorageServiceFacts.cs, tests/NuGetGallery.Facts/Services/PackageFileServiceFacts.cs
New feature: Added support for handling a version parameter in cloud blob storage services
Implements #10082 
Introduced a version parameter to enhance file storage service methods and updated related tests.
- `CloudBlobFileStorageService.cs`: Modified constructor and methods to handle `versionParameter`.
- `IFileStorageService`: Updated interface to include `versionParameter`.
- `FileSystemFileStorageService.cs`: Updated methods to handle `versionParameter`.
- `PackageFileService`: Passed `versionParameter` in method calls.
- Updated tests in `CloudBlobFileStorageServiceFacts`, `FileSystemFileStorageServiceFacts`, and `PackageFileServiceFacts` to include `versionParameter`.
=> Add package version to query string for v2 CDN endpoint (#10082)

Directory.Packages.props, src/NuGet.Protocol.Catalog/NuGet.Protocol.Catalog.csproj, src/NuGetGallery.Core/NuGetGallery.Core.csproj, src/Validation.Common.Job/Validation.Common.Job.csproj
Fixes: https://github.com/NuGet/Engineering/issues/5532
In general since transitive `system.formats.asn1` package depends on NuGet root package, just updating direct NuGet package should be enough, but not in this case. So I updated transitive package `System.Formats.Asn1` too.
=> Update System.Formats.Asn1 package

.pipelines/NuGetGallery-CI.yml, src/Catalog/Persistence/AzureStorage.cs
I will also copy this implementation to ServerCommon. Great catch by @dannyjdev!
Without this, we loose any additional HTTP headers existing on the blob, not overridden on the `BlobHttpHeaders` instance. `SetHttpHeadersAsync` replaces ALL headers that can possible be set by it, not just the ones you explicitly assign.
Also, unrelated, remove a BuildConfiguration parameter from the CI YAML. Perhaps that is what is preventing the automatic CI build from working. (it's a guess, it's something I added as a nicety but it's not required at this time)
=> Fetch and copy HTTP headers if they are being updated

.pipelines/NuGetGallery-CI.yml, tests/NuGet.Services.AzureSearch.Tests/IndexBuilderFacts.cs
This test is flaky. It fails with:
```
Failed NuGet.Services.AzureSearch.BlobContainerBuilderFacts+CreateAsync.CanRetryOnConflict [22 ms]
Error Message:
Assert.InRange() Failure: Value not in range
Range:  (00:00:00.0100000 - 10675199.02:48:05.4775807)
Actual: 00:00:00.0098249
```
=> Fix flaky test CanRetryOnConflict

Directory.Packages.props, src/Gallery.CredentialExpiration/Job.cs, src/GitHubVulnerabilities2Db/Job.cs, src/GitHubVulnerabilities2v3/Job.cs, src/Stats.PostProcessReports/Job.cs, src/Validation.PackageSigning.ProcessSignature/Job.cs, src/Validation.PackageSigning.ValidateCertificate/Job.cs
The enablePublicAccess values were determined based on current PROD container public access.
=> Update to latest ServerCommon (v2.123.0)

src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Links and buttons inside package page tables receive double focus, need to remove the focus on table cell to make links and buttons receive single focus
* remove tabindex from all table cell from package page
Bug URL: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2175594
=> Remove Focus on Package Page Tables

src/Ng/CommandHelpers.cs, tests/NgTests/StorageFactoryTests.cs
This is blocking `catalog2dnx` job from running against Azure China storage.
=> Fix endpoint suffix (Azure China) not being used

src/Catalog/Persistence/AzureStorage.cs, src/Catalog/Persistence/Storage.cs, tests/CatalogMetadataTests/AzureStorageFacts.cs
This PR fix two bugs I've found in `dev` based on SDK move (1 and 2, below), and one pre-existing bug found due to blob corruption in DEV (3, below)
1. Scrub blob URL in logging, so we don't log SAS (query string)
2. Handle mismatch of scheme between base URL (http) and blob item from list blobs (https)
- This difference was leading to a substring being off by 1 ("http" is shorter than "https")
- It would be a much larger change to make it so we never use "http" in memory, this behavior pre-existed in the SDK move ([example](https://github.com/NuGet/NuGet.Jobs/blob/5b34c8e8ab48516f289db7d37a67c48f62f4667f/src/Catalog/Persistence/AzureStorage.cs#L148-L157))
3. When blob sizes are different, do not consider them synchronized.
- In DEV, there were some old blobs that had …
=> Fix Monitoring2Monitoring blob name generation, handle size mismatch when checking if blobs are synchronized

src/GitHubVulnerabilities2v3/Extensions/BlobStorageVulnerabilityWriter.cs, src/NuGet.Services.Storage/Storage.cs
This fixes the following jobs on the new storage SDK.
`ResolveUri` was not working since the container URL lost it's trailing `/`, leading to `new Uri(base, blob)` behavior changing. The cursor URL was resolving to the root of the blob storage account, not in the storage container. 
`GitHubVulnerabilities2Db` and `GitHubVulnernabilities2v3` were impacted.
- Fix `Storage.ResolveUri` to be tolerant of trailing and leading `/`. This fixes the GitHubVulnerabilities job cursors.
- Fix `DateTimeOffset.MinValue` comparison.
- On a UTC machine `DateTimeOffset.MinValue == DateTime.MinValue` (our VMs). Locally this is not true. This makes local debugging harder. I think this was left over from a `DateTime` to `DateTimeOffset` refactoring that was uncaught cause it works on VM.
=> First ResolveUri in NuGet.Services.Storage

python/StatsLogParser/loginterpretation/clientnametranslation.py, python/StatsLogParser/pyproject.toml, python/StatsLogParser/tests/test_clientnametranslation.py
This pull request includes significant updates to the `loginterpretation` module, primarily focusing on adding new functionality for client name translation using dataclasses and enhancing test coverage. The most important changes include the introduction of dataclasses for client categories and names, the implementation of client name translation logic, and the addition of unit tests to validate the new functionality.
* [`python/StatsLogParser/loginterpretation/clientnametranslation.py`](diffhunk://#diff-06e97ee9e63716b28eb1e56eddb92fc1661357638c30fd5c3abacfee8bcdadb2R1-R153): Introduced `ClientCategories` and `ClientNames` dataclasses to categorize client names and implemented the `ClientNameTranslation` class with static methods for client name translation logic.
* …
=> Add client name translation

build/common.ps1
The build log looks like this in Azure DevOps:
It's nice, but it could be even better if the stop lines are visible. This lets us see DONE/STOPPED/FAILED status as well as the step duration. Change SKIP to a warning since it's not a warning. Steps are disabled on demand.
=> Show DONE trace outside of the collapse build step block

src/Catalog/Downloads/DownloadsV1JsonClient.cs, src/Catalog/Downloads/IDownloadsV1JsonClient.cs, src/Catalog/NuGet.Services.Metadata.Catalog.csproj, src/Catalog/ServiceCollectionExtensions.cs, src/NuGet.Jobs.Auxiliary2AzureSearch/Job.cs, src/NuGet.Jobs.Db2AzureSearch/Job.cs, src/NuGet.Services.AzureSearch/Auxiliary2AzureSearch/UpdateDownloadsCommand.cs, src/NuGet.Services.AzureSearch/Db2AzureSearch/NewPackageRegistrationFromDbProducer.cs, src/NuGet.Services.AzureSearch/DependencyInjectionExtensions.cs, src/NuGet.Services.Configuration/ConfigurationExtensions.cs, src/Stats.AggregateCdnDownloadsInGallery/AggregateCdnDownloadsJob.cs, src/Stats.AggregateCdnDownloadsInGallery/Configuration/DownloadsV1JsonConfiguration.cs, tests/NuGet.Services.AzureSearch.Tests/Auxiliary2AzureSearch/Integration/PopularityTransferIntegrationTests.cs, tests/NuGet.Services.AzureSearch.Tests/Auxiliary2AzureSearch/UpdateDownloadsCommandFacts.cs, tests/NuGet.Services.AzureSearch.Tests/Db2AzureSearch/NewPackageRegistrationFromDbProducerFacts.cs
Progress on https://github.com/NuGet/Engineering/issues/5576.
This changes `DownloadsV1JsonClient` to use `BlobClient` instead of `HttpClient`. The initialized blob client (`BlobClient`) in this case is meant to be a singleton so I inverted the control so the downloads.v1.json is provided via DI. This works because we really only have one downloads.v1.json URL at a time, coming from config. It doesn't need to be a parameter.
=> Use auth for downloads.v1.json in stats and search jobs

.editorconfig, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
=> Hotfix: add UTF-8 BOM for package details page Razor

src/NuGetGallery.Services/Configuration/IBlobStorageConfiguration.cs, src/NuGetGallery.Services/Configuration/SimpleBlobStorageConfiguration.cs, src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
Apparently, it was missed during the migration. Added an option to use MSI for statistics and auditing storage access.
Extracted the code that creates `CloudBlobClientWrapper` in different ways depending on configuration into a method of its own and reused it for statistics and audit storage.
=> Statistics and Auditing storage access update.

src/NuGetGallery.Core/CoreConstants.cs, src/NuGetGallery.Core/Services/GalleryCloudBlobContainerInformationProvider.cs, src/NuGetGallery/Services/FileSystemFileStorageService.cs, tests/NuGetGallery.Core.Facts/Services/FolderNamesDataAttribute.cs
The "status" folder is managed by the status page and StatusAggregator. It is a config value not a constant.
The "downloads" folder was removed long ago with https://github.com/NuGet/NuGetGallery/pull/5483.
=> Delete unused downloads and status folders

src/NuGet.Services.Configuration/SecretDictionary.cs, src/NuGet.Services.KeyVault/CachingSecretReader.cs, src/NuGet.Services.KeyVault/EmptySecretReader.cs, src/NuGet.Services.KeyVault/IRefreshableSecretReaderFactory.cs, src/NuGet.Services.KeyVault/ISecretInjector.cs, src/NuGet.Services.KeyVault/ISecretReader.cs, src/NuGet.Services.KeyVault/KeyVaultReader.cs, src/NuGet.Services.KeyVault/RefreshableSecretReader.cs, src/NuGet.Services.KeyVault/RefreshableSecretReaderFactory.cs, src/NuGet.Services.KeyVault/SecretInjector.cs, src/NuGetCDNRedirect/NuGetCDNRedirect.csproj, tests/NuGet.Services.Configuration.Tests/SecretDictionaryFacts.cs, tests/NuGet.Services.KeyVault.Tests/CachingSecretReaderFacts.cs, tests/NuGet.Services.KeyVault.Tests/KeyVaultReaderFormatterFacts.cs, tests/NuGet.Services.KeyVault.Tests/RefreshableSecretReaderFactoryFacts.cs, tests/NuGet.Services.KeyVault.Tests/RefreshableSecretReaderFacts.cs, tests/NuGet.Services.KeyVault.Tests/SecretReaderFacts.cs
The new KeyVault SDK has a sync path that we can use. This adds `GetSecret` methods in addition to `GetSecretAsync` methods. The `SecretDictionary` can now use proper sync methods all the way through.
I saw MonitoringProcessor deadlock in DEV and INT, but not in PROD, all on the same bits. I captured a dump and saw it blocked on async KeyVault APIs inside a sync context. I believe this is a sync-over-async deadlock.
Progress on https://github.com/NuGet/NuGetGallery/issues/10146.
=> Move SecretDictionary away from sync-over-async

src/NuGet.Jobs.Catalog2Registration/DependencyInjectionExtensions.cs, src/NuGet.Jobs.Common/JsonConfigurationJob.cs, src/NuGet.Jobs.Common/StorageAccountExtensions.cs, src/NuGet.Jobs.Common/StorageMsiConfiguration.cs, src/NuGet.Jobs.GitHubIndexer/Job.cs, src/NuGet.Services.AzureSearch/DependencyInjectionExtensions.cs, src/NuGet.Services.Configuration/Constants.cs, src/NuGet.Services.V3/NuGet.Services.V3.csproj, src/NuGet.Services.Validation.Orchestrator/Job.cs, src/NuGetGallery.Core/Extensions/ConnectionStringExtensions.cs, src/NuGetGallery.Core/Services/CloudBlobClientWrapper.cs, src/Validation.Common.Job/Leases/CloudBlobLeaseService.cs, src/Validation.Common.Job/Validation.Common.Job.csproj, src/Validation.Common.Job/ValidationJobBase.cs, src/Validation.Symbols/Job.cs, tests/Validation.Common.Job.Tests/Leases/BlobStorageFixture.cs
Addresses https://github.com/NuGet/Engineering/issues/5440
This migrates some of the Validation Jobs to use MSI with the new SDKs. I've deployed these changes to DEV using these config files: https://nuget.visualstudio.com/NuGetMicrosoft/_git/NuGetDeployment/pullrequest/2473, and E2E tests pass + I don't see any exceptions in AI logs.
These are the jobs I tested:
- [[NuGet][Continuous] Validation.Orchestrator](https://devdiv.visualstudio.com/DevDiv/_release?_a=releases&view=all&definitionId=1617)
- [[NuGet][Continuous] Validation.Symbols.Job](https://devdiv.visualstudio.com/DevDiv/_release?_a=releases&view=all&definitionId=1584)
- [[NuGet][Continuous] Validation.SymbolsOrchestrator](https://devdiv.visualstudio.com/DevDiv/_release?_a=releases&view=all&definitionId=1605)
- [[NuGet][Daily] …
=> Migrating Validation jobs to new SDK + MSI (subset of jobs that had migrating NuGetGallery dependencies)

build/init.ps1
Related to https://github.com/NuGet/Engineering/issues/5593
After pointing the NuGetGallery instead of ServerCommon in internal repo, now we see this error on local build.
Please note you'll notice this error only during 1st build after cloning the repo.
In the original command, $File is an object of type FileInfo (or PSObject if not directly typed). When you pass the entire $File object to Join-Path, it may not behave as expected because Join-Path expects a string (or strings) that represent the components of a path. Passing a FileInfo object directly might cause unexpected results, especially since Join-Path isn't designed to handle objects but rather strings.
In the modified command, $File.Name is a string representing the name of the file, such as "example.txt". This is the correct …
=> Fix file exist logic in init.ps1 file

src/NuGet.Services.Validation.Orchestrator/Job.cs, src/Validation.Common.Job/ServiceProviderExtensions.cs, src/Validation.Common.Job/SubscriptionProcessorJob.cs, src/Validation.Common.Job/Validation.Common.Job.csproj
For jobs like AccountDeleter, they can have complex dependency injection (DI) setup, sometimes loading assembly built across multiple projects. 
To improve the visibility of DI/startup errors, this adds a step to our subscription processor jobs to test initializing the message handler prior to accepting messages.
If there is indeed a DI problem with the message handler, it will be detected prior to receiving messages. This will make job heartbeats go red (good) and prevent unnecessary message dead lettering (good).
=> Add a handler startup test to SubscriptionProcessorJob and Orchestrator

src/NuGet.Services.Configuration/Constants.cs
Adds 2 new constants for Storage MSI configuration:
`Storage_UseManagedIdentity` and `Storage_ManagedIdentityClientId`
In response to https://github.com/NuGet/NuGetGallery/pull/10153#discussion_r1728101855
=> Add new constants for Storage MSI configuration

src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Services/ITyposquattingCheckListCacheService.cs, src/NuGetGallery/Services/NormalizedPackageIdInfo.cs, src/NuGetGallery/Services/TyposquattingCheckListCacheService.cs, src/NuGetGallery/Services/TyposquattingService.cs, tests/NuGetGallery.Facts/Services/TyposquattingCheckListCacheServiceFacts.cs, tests/NuGetGallery.Facts/Services/TyposquattingServiceFacts.cs
Addresses: https://github.com/NuGet/Engineering/issues/5583
My [previous PR](https://github.com/NuGet/NuGetGallery/commit/ca170345892cddb68c83be446c39e2b138190660), I inadvertently made typosquatting check too strict, this change would allow if they're from same owners by keeping both original and normalized values in cache. It would add few mb memory, but not big deal, main concern was CPU time previously.
=> Allow if conflict with package from same owner

src/NuGet.Jobs.Common/NuGet.Jobs.Common.csproj, src/NuGet.Jobs.Common/StorageAccountExtensions.cs, src/NuGetGallery.Core/Extensions/UriExtensions.cs, src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs, src/NuGetGallery.Core/Services/CloudBlobWrapper.cs, src/NuGetGallery.Core/Services/ICoreFileStorageService.cs, src/NuGetGallery.Core/Services/ISimpleCloudBlob.cs, src/NuGetGallery/Services/FileSystemFileStorageService.cs, tests/NuGet.Services.V3.Tests/Support/InMemoryCloudBlob.cs, tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceFacts.cs
Partially addresses: https://github.com/NuGet/Engineering/issues/5387 and https://github.com/NuGet/Engineering/issues/5433
Introduce delegation SAS, which is more secure than SAK-based SAS. 
I didn't reuse or extend the existing SAS generate method and created a new `GetDelegationSasAsync` and `GetPrivilegedFileUriWithDelegationSasAsync` because I want to be explicit when the customer generates the SAS token and not accidentally consume the old SAK one. Eventually, we can deprecate the SAK-based one without worry later.
Also extending the old SAK based on caused API breaking change.
=> Introduce delegation SAS

src/NuGetGallery/Web.config
Adding binding redirect for `Microsoft.Extensions.DependencyInjection` following the version bump in shims library. Without it, Gallery fails on the first auditing call.
=> Binding redirect update

src/Catalog/Persistence/AzureStorage.cs
Fixes a blob service client constructor that was throwing null or whitespace Argument exceptions and causing the Ctalog2Icons job to restart repeatedly.
Had to close the previous PR as that was branched off main, and would have brough in extra commits.
=> Fix BlobServiceClient Constructor

src/AccountDeleter/app.config, src/NuGetGallery.Core/Services/CloudBlobClientWrapper.cs
Addresses: https://github.com/NuGet/Engineering/issues/5586 alongside https://github.com/NuGet/NuGetGallery/pull/10165.
This completes the migration for `AccountDeleter`--there was a null ref issue with configs in `AccountDeleter`'s `Job`'s base classes `ValidationJobBase` (which configures validation storage access) and `JsonConfigurationJob` (which configures feature flag storage access). Neither storage accounts are used by `AccountDeleter` and recent changes to `CloudBlobClientWrapper` had removed a tolerance for nulls in the connection strings. An experimental change to `CloudBlobWrapperClient` sought to address this but wasn't successful, but left a BOM removal in code which is an acceptable push. FYI @agr.
The `app.config` change is necessary for a break introduced in our …
=> Additional config changes to support AccountDeleter migration

src/NuGet.Services.KeyVault/KeyVaultReader.cs, src/NuGet.Services.KeyVault/Properties/AssemblyInfo.cs, tests/NuGet.Services.KeyVault.Tests/KeyVaultReaderFacts.cs
* Set the ClientCertificateCredentialOptions with SendCertificateChain when the KeyVaultConfiguration is configured with SendCertificateChain
=> Set `SendCertificateChain` option in KeyVaultReader to enable SN+I authentication

src/Catalog/NuGet.Services.Metadata.Catalog.csproj, src/NuGet.Protocol.Catalog/NuGet.Protocol.Catalog.csproj, src/NuGetGallery.Services/NuGetGallery.Services.csproj, tests/Validation.PackageSigning.Core.Tests/Validation.PackageSigning.Core.Tests.csproj
Addresses NuGetGallery part of https://github.com/NuGet/Engineering/issues/5545
CG alert: https://devdiv.visualstudio.com/DevDiv/_componentGovernance/NuGetPipelines/alert/9986282?typeId=20536579
Some projects were pulling in `System.Text.Json v7.0.3` through the `NuGet.Protocol` package. I've made `System.Text.Json` a top-level reference in the affected projects so that it uses `v8.0.4` from the `Directory.Packages.props` file.
I created a release with these changes, and it looks like it fixes the alert:
=> [CG] Upgrade System.Text.Json

src/Catalog/Persistence/AzureStorage.cs, src/Catalog/Persistence/Storage.cs
Fixes: https://github.com/NuGet/Engineering/issues/5628
Context is [here on teams](https://teams.microsoft.com/l/message/19:d10cd9192de2492986fba3baeea3093c@thread.skype/1726693433772?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=ad34ac55-6785-4e7c-82c3-7ba405d30c3c&parentMessageId=1726693433772&teamName=NuGet&channelName=Server&createdTime=1726693433772).
Deployment: [1550336](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=1550336)
Previously there was many exceptions for NuGet.Jobs `Catalog2Icon`, after deployment it's no more.
**Before:** ![image](https://github.com/user-attachments/assets/06871a7a-0c43-44af-a174-cda2d77a28d0)
**After:**
=> NuGet Job, don't rethrow exceptions if blob is not found

src/NuGet.Services.Storage/NuGet.Services.Storage.csproj, src/NuGet.Services.Validation/Entities/EntitiesConfiguration.cs, src/NuGet.Services.Validation/NuGet.Services.Validation.csproj
Internal projects targeting .net depend on those packages and produce build warnings because of unsupported targets. Nothing really prevents those from targeting netstandard 2.1 (not netstandard2.0 because of [EF](https://www.nuget.org/packages/EntityFramework#supportedframeworks-body-tab)).
Had to apply a fix to Validation DB's `EntitiesConfiguration` similar to what we have for Gallery DB:
https://github.com/NuGet/NuGetGallery/blob/febd3fb35bbf25b4a4d40f56859693e0bbf5d6f0/src/NuGetGallery.Core/Entities/EntitiesConfiguration.cs#L7-L43
Functionally, there are no changes for projects consuming those that target net472 and projects targeting .net can actually now use those.
=> Targeting netstandard 2.1 for more projects

src/NuGetGallery/Views/Shared/Gallery/Layout.cshtml
We only have [custom styles](https://github.com/NuGet/NuGetGallery/blob/f1434e76555bf7c8f8b29b0e9a7d08f1f1b76982/src/Bootstrap/less/theme/base.less#L624-L636) for when `id="/"`, no need to have it specified in any other case. Also fixes incorrect styling when query parameters are present for the root page.
Addresses https://github.com/NuGet/Engineering/issues/5636
=> Fix for issues with root page styling

src/Validation.ScanAndSign.Core/Validation.ScanAndSign.Core.csproj
At least one project consuming this package targets net6.0. Not sure how it worked so far, but multitargeting should address warnings produced while building that project.
=> Targeting netstandard2.0 for scanandsign.core

src/NuGetGallery.Services/Authentication/CredentialBuilder.cs, src/NuGetGallery.Services/Authentication/IAuthenticationService.cs, src/NuGetGallery.Services/Authentication/ICredentialBuilder.cs, src/NuGetGallery/Controllers/UsersController.cs
This allows more code sharing for other places that create credentials (such as a new endpoint to create a short-lived API key from an OIDC token).
Also, add a method to `IAuthenticationService` which is on the concrete implementation (`AuthenticationService`) to make mocking easier.
=> Push BuildScopes and VerifyScopes into ICredentialBuilder

src/NuGet.Services.Entities/Extensions/ExceptionExtensions.cs, src/NuGetGallery/Services/PackageUploadService.cs
Also, make the inner exception layer check be tolerant of changes or exception wrapping.
The existing semantics of actually accepting several API SQL error codes is unchanged.
This allows other code to use this check also. 
Supports https://github.com/NuGet/NuGetGallery/issues/10212.
=> Move unique constraint check to extension method

tests/NuGetGallery.FunctionalTests.Core/NuGetGallery.FunctionalTests.Core.csproj
Recent package update broke web tests and we didn't notice.
This is not a proper fix, but something fast to unblock deployments.
https://github.com/NuGet/Engineering/issues/5669 filed to track proper fix.
=> Hotfix for web tests

Directory.Packages.props, src/NuGetGallery/Web.config
Part of https://github.com/NuGet/Engineering/issues/5532
Part of https://github.com/NuGet/Engineering/issues/5546
Part of https://github.com/NuGet/Engineering/issues/5670
Part of https://github.com/NuGet/Engineering/issues/5531
Previously not identified root dependencies bringing `Azure.Core` vulnerable version, besides all of them are vulnerable so decided them update too.
=> Update Azure.Core and System.Formats.Asn1 package

Directory.Packages.props, src/NuGetGallery/Web.config
The package update from https://github.com/NuGet/NuGetGallery/pull/10184 broke deployments. Reverting it until we figure out proper way to update without breaking something.
The [deployment](https://dev.azure.com/devdiv/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=1554172) started from this branch was successful.
=> Reverting some packages

src/NuGet.Services.Storage/AzureStorage.cs
Can't update headers for a blob that haven't been uploaded yet. This change fixes the ProcessSignature job.
=> Order of operations update for `UploadAsync`

src/NuGetGallery/App_Start/DefaultDependenciesModule.cs
These are fire and forget tasks performed during app shutdown.
These errors appear in the IDE due to our .editorconfig settings, and can be suppressed. 
This is a little clean-up I found while working on https://github.com/NuGet/NuGetGallery/issues/10212.
=> Suppress warning on CS4014

src/NuGetGallery.Services/Authentication/ApiKeyV4.cs
Address https://github.com/NuGet/Engineering/issues/5678.
This is a non-breaking change.
- Improve comments in `ApiKeyV4`
- Use `ToUpperInvariant` instead of `ToUpper` (no need to be culture specific)
- Use crypto random for 16 bytes instead of `Guid.NewGuid()`.
- Technically this increases the entropy of the secret byte portion from 122 bits ([per docs](https://learn.microsoft.com/en-us/dotnet/api/system.guid.newguid?view=net-8.0#remarks)) to 128 bits.
=> Improve API key v4 implementation based on internal feedback

src/GitHubVulnerabilities2v3/Job.cs
Addresses: https://github.com/NuGet/Engineering/issues/5660
The job now uses MSIs to authenticate to blob storage.
=> Migrate GithubVulnerabilities2V3 to MSI

src/NuGet.Jobs.Common/StorageAccountExtensions.cs, src/NuGet.Services.AzureSearch/DependencyInjectionExtensions.cs, src/NuGet.Services.SearchService.Core/Startup.cs, src/NuGetGallery.Core/Frameworks/SupportedFrameworks.cs, tests/NuGetGallery.Core.Facts/Frameworks/FrameworkCompatibilityServiceFacts.cs
Addresses https://github.com/NuGet/Engineering/issues/5439
Part of https://github.com/NuGet/Engineering/issues/5512
Config changes PR: https://nuget.visualstudio.com/NuGetMicrosoft/_git/NuGetDeployment/pullrequest/2541
This adds MSI support for the search jobs and the search service.
We also add .NET TFMs to our list of "Supported Frameworks" so that they show up as computed frameworks on the frameworks tab and in the search index. The other changes in the `SupportedFrameworks.cs` file were just reordering to make it a bit more readable.
I also had to make some tests a bit less sensitive to changes. Earlier we were trying to match an exact list of 'computed' compatible frameworks in some tests. With that setup, we would need to keep updating the test cases every time a new .NET TFM is …
=> Search MSI migration + .NET 9 TFM support

src/Stats.AzureCdnLogs.Common/Collect/Collector.cs, src/Stats.AzureCdnLogs.Common/Collect/OutputLogLine.cs, src/Stats.CollectAzureChinaCDNLogs/ChinaStatsCollector.cs, src/Stats.CollectAzureChinaCDNLogs/Configuration/CollectAzureChinaCdnLogsConfiguration.cs, src/Stats.CollectAzureChinaCDNLogs/Job.cs, tests/Tests.Stats.CollectAzureChinaCDNLogs/ChinaCollectorTests.cs
Progress on https://github.com/NuGet/Engineering/issues/5601.
Added options to not write headers and add an extra column with original filename for HTTP logs ingested from Mooncake CDN. This aligns Mooncake log ingestion with other ingestion paths.
=> Mooncake log ingestion options to not write headers and add original filename column

tests/Validation.PackageSigning.Core.Tests/Support/CertificateIntegrationTestFixture.cs
This change ensures that test certificates are removed from the root store.
Addresses https://github.com/NuGet/NuGetGallery/issues/10259
This change fixes a bug where the disposal of an `X509Certificate2` instance causes the subsequent disposal (removal) of that certificate's trust because the `TrustedTestCert<X509Certificate2>` instance references the same certificate instance.  When the `X509Certificate2` instance is disposed, `TrustedTestCert<X509Certificate2>` cannot remove the certificate from the root store because its certificate reference is disposed.
The fix is to only dispose the `TrustedTestCert<X509Certificate2>` instance.
=> Test:  fix removal of test certificate from root store

src/NuGet.Jobs.Common/JsonConfigurationJob.cs, src/NuGetGallery.Core/Services/CloudBlobCoreFileStorageService.cs
Feature flags were calling `CreateIfNotExists` to get the container reference for the FF container ('content'). This container already exists, so we don't need to write anything, but the `CreateIfNotExists` call meant that we would need to have read-write permissions enabled regardless, and jobs/services using this path would need the MSI to be over-provisioned (eg. SearchService)
I've made changes so we avoid that call for Feature Flags. I've tested it for the SearchService and it worked, but I haven't tested anything else. Let me know if there's anything else I should try to test.
Related to/Part of https://github.com/NuGet/Engineering/issues/5439
=> Avoid calling CreateIfNotExists for Feature Flags

src/NuGetGallery.Services/Authentication/Federated/EntraIdTokenValidator.cs, src/NuGetGallery.Services/Authentication/Federated/FederatedCredentialConfiguration.cs, src/NuGetGallery.Services/Configuration/ConfigurationService.cs, src/NuGetGallery/App_Start/DefaultDependenciesModule.cs, src/NuGetGallery/Web.config, tests/NuGetGallery.Facts/Authentication/Federated/EntraIdTokenValidatorFacts.cs
This adds an `IEntraIdTokenValidator` interface which accepts a parsed JWT (JSON web token) and performs basic Entra ID validation. This will be used by higher level code in a future PR.
The goal of this class is to assert that a given JWT is issued by Entra ID and is valid. The following checks are performed:
1. The JWT signature is valid per Entra ID's signing keys, fetched via JWKS. This is done inside `ConfigurationManager<OpenIdConnectConfiguration>`.
2. The issuer is an expected Entra ID value (`iss` claim and `issuer` property on the key). This is done via `AadIssuerValidator.GetAadIssuerValidator` and `EnableAadSigningKeyIssuerValidation`.
3. The token is not expired (`nbf` and `exp` claims). This is done inside …
=> [OIDC 1] Add basic Entra ID token validation

src/AccountDeleter/EmptyFeatureFlagService.cs, src/GitHubVulnerabilities2Db/Fakes/FakeFeatureFlagService.cs, src/NuGetGallery.Services/Configuration/FeatureFlagService.cs, src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs, src/NuGetGallery/App_Data/Files/Content/flags.json, src/VerifyMicrosoftPackage/Fakes/FakeFeatureFlagService.cs
Depends on https://github.com/NuGet/NuGetGallery/pull/10252.
We want to be able to control exactly which package owners should be using this feature. This adds a flight (i.e. a feature flag specific to the user) for the new federated credentials (OIDC) feature.
I did some minor private const renaming to address an IDE suggestion (per `.editorconfig`) which is unrelated to the other changes.
The flight defaults to false meaning it is opt-in.
We generally do not have UTs for these changes since they are so simple.
=> [OIDC 3] Add flight for using federated credentials

src/NuGetGallery.Core/Auditing/CredentialAuditRecord.cs, src/NuGetGallery.Core/Auditing/FailedAuthenticatedOperationAuditRecord.cs, src/NuGetGallery.Core/Auditing/UserAuditRecord.cs, tests/NuGetGallery.Core.Facts/Auditing/CredentialAuditRecordTests.cs, tests/NuGetGallery.Core.Facts/Auditing/UserAuditRecordTests.cs, tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs
Today we audit the hashed API key value when a credential is deleted/revoked. This is not very useful (it is hashed) and it could trigger credential scanner in our audit logs at some point. I would like to remove it so our audit logs don't have this useless value.
Vaguely related to https://github.com/NuGet/NuGetGallery/issues/10212.
=> Do not audit values for removed/revoked API keys

src/NuGetGallery.Services/Authentication/AuthenticationService.cs, tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs
A collection modified exception is thrown since internally the DbContext modifies the collection we are enumerating.
Over 99% of requests are failing on this endpoint and this has been happening since 2024-08-22.
 
Fix https://github.com/NuGet/NuGetGallery/issues/10273.
=> Copy list of scopes before removing them from the EF context

src/NuGetGallery.Services/Authentication/CredentialBuilder.cs, src/NuGetGallery.Services/Authentication/ICredentialBuilder.cs, tests/NuGetGallery.Facts/Authentication/CredentialBuilderFacts.cs
Depends on https://github.com/NuGet/NuGetGallery/pull/10262.
This adds a new method to `CredentialBuilder` which creates a short-lived API key given a federated credential trust policy.
This method has a TODO in it linking to the OIDC work item because the exact shape of the short lived API key is still in discussion. The created credential is not yet associated with a user (the created by user account) because this is the responsibility of `IAuthenticationService.AddCredential`:
https://github.com/NuGet/NuGetGallery/blob/0ec99618043ae7f7e54a3ed8fdbbb47acc5e30b1/src/NuGetGallery.Services/Authentication/AuthenticationService.cs#L629-L641
This will be called in a future PR while executing the token trade endpoint.
This stub …
=> [OIDC 4] Add method to create a short-lived API key (minimal)

src/ArchivePackages/ArchivePackages.Job.cs
Bug fix for this change: https://github.com/NuGet/Engineering/issues/5441
The write operation for the secondary container was writing a second time to the primary container.
=> Bug fix for secondary archive location in archivepackages

src/GitHubVulnerabilities2v3/Extensions/BlobStorageVulnerabilityWriter.cs, src/GitHubVulnerabilities2v3/Job.cs, src/NuGet.Services.Storage/AzureStorage.cs, src/NuGet.Services.Storage/AzureStorageFactory.cs
* Removed explicit http scheme when creating storages.
* Not related: 2 unused lines on `src/GitHubVulnerabilities2v3/Extensions/BlobStorageVulnerabilityWriter.cs`
Addresses https://github.com/NuGet/NuGetGallery/issues/123
=> [Fix] GithubVulnerability2V3 use only HTTPS

Directory.Packages.props, NuGet.config, sign.thirdparty.props, src/NuGetGallery/App_Start/DefaultDependenciesModule.cs, src/NuGetGallery/NuGetGallery.csproj, src/NuGetGallery/Services/MarkdownService.cs, src/NuGetGallery/Web.config, tests/NuGetGallery.Facts/Services/MarkdownServiceFacts.cs
Introduced third party library called HtmlSanitizer
with default tags. By default, it removes script
tags, event handlers (e.g.,onclick), and other inline JavaScript code that can be used for XSS attacks.
Test: ran all markdown features on readme. Looks fine.
Address the issue: https://github.com/NuGet/Engineering/issues/5650
=> Introduced third party library called HtmlSanitizer

src/GitHubVulnerabilities2v3/Extensions/BlobStorageVulnerabilityWriter.cs
* The `GitHubVulnerabilities2v3` job was not reaching the index file due to a bug on the `FlushAsync` method where the `ExistAsync` require just the file name instead of the whole file uri.
* e.g. It expected only `index.json` instead of the `<storageaccount>/v3-vulnerabilities/index.json`.
* Before the fix, this method was looking for a file named `<storageaccount>/v3-vulnerabilities/<storageaccount>/v3-vulnerabilities/index.json`.
 
Addresses: https://github.com/NuGet/Engineering/issues/5720
=> [HotFix] Fix update path not being reached.

src/NuGetGallery.Services/Authentication/Federated/FederatedCredentialPolicyEvaluator.cs, src/NuGetGallery.Services/Authentication/Federated/FederatedCredentialService.cs, src/NuGetGallery/App_Start/DefaultDependenciesModule.cs, tests/NuGetGallery.Facts/Authentication/Federated/FederatedCredentialPolicyEvaluatorFacts.cs, tests/NuGetGallery.Facts/Authentication/Federated/FederatedCredentialServiceFacts.cs
Depends on https://github.com/NuGet/NuGetGallery/pull/10291.
This PR is a simple rename of a previously introduce service. 
Old name: `IFederatedCredentialEvaluator` (interface) and `FederatedCredentialEvaluator` (class)
New name: `IFederatedCredentialPolicyEvaluator` (interface) and `FederatedCredentialPolicyEvaluator` (class)
The reason for this change is I will be adding a new abstraction called `IFederatedCredentialValidator` which I felt is too close of a name to `IFederatedCredentialEvaluator`. 
In the end, this thing evaluates whether a bearer token matches a list of policies. So "policy evaluator" is probably more clear anyway.
=> [OIDC 14] Rename FederatedCredentialEvaluator to FederatedCredentialPolicyEvaluator

Directory.Packages.props
EntityFramework 6.4.4 is deprecated with vulnerable, update to latest stable. 
Note: There is change:  New SQL Server / Azure SQL Database provider (contributed by the community) - [Microsoft.EntityFramework.SqlServer](https://www.nuget.org/packages/Microsoft.EntityFramework.SqlServer/). This new provider uses the modern SQL Server client [Microsoft.Data.SqlClient](https://www.nuget.org/packages/Microsoft.Data.SqlClient). For more information about configuration of this provider, see [Microsoft.EntityFramework.SqlServer Guide](https://learn.microsoft.com/en-us/ef/ef6/what-is-new/microsoft-ef6-sqlserver).
It provides new provider configuration, no changes on default one. We should be good
Addresses https://github.com/NuGet/Engineering/issues/5732
=> Update EntityFramework package for vulnerability alert 

Directory.Packages.props, NuGet.config, src/NuGet.Jobs.GitHubIndexer/GitRepoSearchers/GitHub/GitHubSearcher.cs, tests/NuGet.Services.Contracts.Tests/ContractsFacts.cs
New versions of C# offer many features that improve quality of life: nullable annotations, record types, init and required properties, etc. These can be enabled in projects targeting older framework versions by adding the right attributes and types to the compilation.
PolySharp is a source generator which automatically does this.  For each project, it will generate all of the types/attributes which are missing. In the case of an InternalsVisibleTo reference, it is smart enough to only define types in the second assembly that are not being consumed from the first assembly (avoiding duplicate type definitions).
=> Add a polyfill to enable newer compiler features

src/Gallery.CredentialExpiration/Configuration/InitializationConfiguration.cs, src/Gallery.CredentialExpiration/Job.cs, src/NuGet.Jobs.Common/StorageAccountExtensions.cs, src/NuGet.Services.Configuration/Constants.cs
Update Gallery.CredentialExpiration job to use Managed Identity for storage access.
This changeset also includes changes to add a new setting for local development.
Adding "Local_Development": boolean to the top level of app.json will now inject the relevant TokenCredential for use (DefaultAzureCredential for local development true, and ManagedIdentityCredential for local development false).
=> [SDKMigration] Update Gallery.CredentialExpiration to use ManagedIdentity

src/NuGet.Services.AzureSearch/Db2AzureSearch/Db2AzureSearchConfiguration.cs, src/NuGet.Services.AzureSearch/Db2AzureSearch/NewPackageRegistrationFromDbProducer.cs
Addresses https://github.com/NuGet/Engineering/issues/5771
Db2AzureSearch was timing out on same large queries when run against the PROD DB. This PR adds a CommandTimeout config property for Db2AzureSearch. 
The default timeout is 30s, but we want to increase it for PROD, so we'll add a custom CommandTimout to the PROD configs for Db2AzureSearch. 
NuGetDeployment config changes: https://nuget.visualstudio.com/NuGetMicrosoft/_git/NuGetDeployment/pullrequest/2589
=> Add CommandTimeout property to Db2AzureSearch configuration

src/CopyAzureContainer/AzureContainerInfo.cs, src/CopyAzureContainer/Configuration/CopyAzureContainerConfiguration.cs, src/CopyAzureContainer/CopyAzureContainerJob.cs, src/CopyAzureContainer/README.md
* CopyAzureContainer job migrated to use new Azure Storage v12 SDK.
* Removed Storage Key usage.
* Migrated AzCopy to use latest AzCopy v10 version (previously we used v8) and newest syntax.
* Created a README file to know how to run locally the job.
* [Rendered version](https://github.com/NuGet/NuGetGallery/blob/325778d5a3d127b61a744028ef8cbb8fa96d7d26/src/CopyAzureContainer/README.md)
Addresses: https://github.com/NuGet/Engineering/issues/5695
=> [Storage Migration] CopyAzureContainer job

src/NuGetGallery.Services/NuGetGallery.Services.csproj
Missed in https://github.com/NuGet/NuGetGallery/pull/10211, package reference should have added into main package reference not to net472.
=> Correct tfm for System.Text.Json reference

src/NuGet.Services.Configuration/ConfigurationRootSecretReaderFactory.cs, src/NuGet.Services.KeyVault/KeyVaultConfiguration.cs, src/NuGet.Services.KeyVault/KeyVaultReader.cs
This makes the KeyVaultReader aware and reactive to the new top level Local_Development appsettings.json option (introduced in https://github.com/NuGet/NuGetGallery/pull/10297) and makes it fall back to using DefaultAzureCredential instead of ManagedIdentityCredential.
=> Make KeyVaultReader aware of Local_Development

src/NuGet.Services.Validation.Issues/UnauthorizedCertificateFailure.cs, src/NuGetGallery.Core/Extensions/ValidationIssueExtensions.cs, src/NuGetGallery/Views/Packages/_ValidationIssue.cshtml, src/StatusAggregator/Job.cs, src/StatusAggregator/StatusAggregator.csproj, src/Validation.PackageSigning.ProcessSignature/SignatureValidator.cs, tests/NuGet.Services.Validation.Issues.Tests/ValidationIssuesFacts.cs, tests/NuGetGallery.Facts/Infrastructure/Mail/MarkdownMessageServiceFacts.cs, tests/Validation.PackageSigning.ProcessSignature.Tests/SignatureValidatorFacts.cs
Update all messaging to use SHA256 hash instead of SHA-1 hashes for certificates.
Addresses https://github.com/NuGet/NuGetGallery/issues/10073
=> Show SHA256 everywhere.

python/StatsLogParser/loginterpretation/packagedefinition.py, python/StatsLogParser/tests/test_packagedefinition.py
Existing URL path parsing code for statistics is a bit too strict. It expected client URL path to contain at least 4 segments while it only ever looks at 2 of them. As a result, when log content changed from origin path to request path for logs we're getting from CDN, the code started to not consider those as client download URLs.
This PR addresses it.
=> Reducing restrictions on expected client paths when parsing versions

src/NuGetGallery.Core/Certificates/CertificateFile.cs, src/NuGetGallery/Controllers/ApiController.cs, tests/NuGetGallery.Core.Facts/Services/CloudBlobCoreFileStorageServiceIntegrationTests.cs
Progress on https://github.com/NuGet/Engineering/issues/5719.
For `GetSha1Thumbprint`: CodeQL started complaining about it, we already had warning suppression there, added CodeQL suppression as well.
For `CreatePackageVerificationKeyAsync`: we already had one in place, but it now started to complain about one line above, so, moved.
For `OpenWriteAsyncReturnsWritableStream` in tests: MD5 was calculated, but not used in test, so dropped the code.
Goes directly to `main` as CodeQL only checks that branch and there are no functional changes.
=> CodeQL-related updates.

Directory.Packages.props
Update NuGet client libraries from 6.9.1 to 6.13.2.
Resolves https://github.com/NuGet/Engineering/issues/5815
=> Update NuGet client from 6.9.1 to 6.13.2

Directory.Packages.props, NuGet.config, tests/Validation.PackageSigning.Core.Tests/Support/CertificateIntegrationTestFixture.cs, tests/Validation.PackageSigning.Core.Tests/Support/ExtensionMethods.cs, tests/Validation.PackageSigning.Core.Tests/Support/X509AuthorityInformationAccessExtension.cs, tests/Validation.PackageSigning.Core.Tests/Support/X509V3CertificateGeneratorExtensions.cs, tests/Validation.PackageSigning.Core.Tests/Validation.PackageSigning.Core.Tests.csproj, tests/Validation.PackageSigning.ProcessSignature.Tests/SignaturePartsExtractorFacts.cs, tests/Validation.PackageSigning.ProcessSignature.Tests/SignatureValidatorIntegrationTests.cs, tests/Validation.PackageSigning.ProcessSignature.Tests/Support/CertificateIntegrationTestFixture.cs, tests/Validation.PackageSigning.ProcessSignature.Tests/Support/TestLogger.cs, tests/Validation.PackageSigning.ProcessSignature.Tests/Validation.PackageSigning.ProcessSignature.Tests.csproj, tests/Validation.PackageSigning.ValidateCertificate.Tests/Support/CertificateIntegrationTestFixture.cs, tests/Validation.PackageSigning.ValidateCertificate.Tests/Support/X509V3CertificateGeneratorExtensions2.cs, tests/Validation.PackageSigning.ValidateCertificate.Tests/Validation.PackageSigning.ValidateCertificate.Tests.csproj
This change updates package signing test infrastructure to use System.Formats.Asn1 instead of BouncyCastle.
Resolve https://github.com/NuGet/Engineering/issues/5812.
=> Test:  Replace BouncyCastle with System.Formats.Asn1

src/NuGetGallery.Core/GitHub/NuGetPackageGitHubInformation.cs
Updates the number of dependent packages shown from 5 to 20.
Contributes to https://github.com/NuGet/NuGetGallery/issues/10266
=> Increase ReposPerPackage from 5 to 20

src/NuGetGallery/App_Code/ViewHelpers.cshtml, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
- Added `IsLicense` and `IsException` methods to improve license checking.
- Introduced `MakeExceptionLink` and `MakePlainSpan` helpers .
- Updated rendering logic for license links using new methods.
Addresses https://github.com/NuGet/NuGetGallery/issues/10341
Before:
After:
=> BUG: 10341 - Proper Display of License Information

README.md
I noticed, that the "up for grabs" label was removed and the best fit seems to be "good first issue".
Just changed the ReadMe.md to point to a valid label.
(No issue created)
=> Change "Up for grabs" to "good first issue" in ReadMe

CredScanSuppressions.json, src/NuGetGallery.Services/Authentication/ApiKeyV5.cs
We kept getting build errors that flag [this file](https://github.com/NuGet/NuGetGallery/blob/4b37d4d6bba949d81768f914bf99ea14e31168db/src/NuGetGallery.Services/Authentication/ApiKeyV5.cs#L54) for containing a secret. This is how the errors looked like:
The secret is false positive, and this code change tells credential scanner to suppress it.
NOTE: This PR is made against main branch and not dev, because the change is really small and requires fast action, since it's blocking wave 1 work.
=> Fix guardian false positive

src/NuGet.Services.Storage/AzureStorage.cs
This is causing an internal monitor job to time out because it is calling `GetProperties` on thousands of blobs. We don't need to do that because we pass the `BlobTraits.Metadata` in.
=> Do not call GetProperties on a blob when metadata is available via enumeration

src/NuGetGallery/Views/Users/ApiKeys.cshtml
Change API kay Manage section 2nd edit button text to "Save".
Bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2417389
=> Change API key edit button text

src/AccountDeleter/EmptyFeatureFlagService.cs, src/GitHubVulnerabilities2Db/Fakes/FakeFeatureFlagService.cs, src/NuGetGallery.Core/Packaging/ManifestValidator.cs, src/NuGetGallery.Core/Packaging/PackageIdValidator.cs, src/NuGetGallery.Services/Configuration/FeatureFlagService.cs, src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs, src/NuGetGallery/Controllers/ApiController.cs, src/NuGetGallery/Controllers/PackagesController.cs, src/NuGetGallery/Services/SymbolPackageService.cs, src/VerifyMicrosoftPackage/Fakes/FakeFeatureFlagService.cs, tests/NuGetGallery.Core.Facts/Packaging/ManifestValidatorFacts.cs, tests/NuGetGallery.Core.Facts/Packaging/PackageIdValidatorTest.cs
Related issue: https://github.com/NuGet/Engineering/issues/5850
Temporarily limit IDs to ASCII characters only until a fix is implemented.
=> [HotFix] Temporary limit to ascii only

tools/Setup-DevEnvironment.ps1
- make localhost SSL cert last 10 years
- refresh cert if it is expired
- fix powershell linter warnings
=> Make local dev script longer lived, recreate when expired

src/Catalog/Persistence/Storage.cs, tests/CatalogTests/Persistence/StorageTests.cs
Address: https://github.com/NuGet/Engineering/issues/5850
`uri.GetLeftPart` does encoding under the hood, which is causing the problem.
New change decode to make sure it is not double encoded later, tested on INT.
Companion PR: https://github.com/NuGet/NuGet.Services.EndToEnd/pull/131
=> [HotFix]: Fix double encoding

src/Catalog/Persistence/Storage.cs, tests/CatalogTests/Persistence/StorageTests.cs
Fix https://github.com/NuGet/Engineering/issues/5850
Follow up on https://github.com/NuGet/NuGetGallery/discussions/10410#discussioncomment-12947574
Previously https://github.com/NuGet/NuGetGallery/pull/10417 fixed double encoding problem for blob name for `db2catalog` job, but the `catalog2dnx` job was getting miscalculated length blob name because the base address was still encoded while the blob URI was decoded. Now, we decode/unescape both of them to avoid such mismatches.
Added matrix unit tests ensure that, regardless of whether the base address or blob URI have the same or mismatched encoding, we can still get the correct blob name. 
We leverage the fact that .GetLeftPart doesn't encode characters that are already encoded, although this behavior is not documented …
=> [HotFix]: Fix base address and blob uri decoding mismatch

src/StatusAggregator/Messages/MessageFactory.cs, tests/StatusAggregator.Tests/Messages/MessageFactoryTests.cs
StatusAggregator was throwing exceptions because of 404s.
This method is supposed to check if a message already exists in table storage, and then
- if it does exist, it just noops and moves on
- if it doesn't exist, it creates a new message
Previously, I'm guessing we used to get a null response if the message didn't exist, but with the new SDK, it throws a 404 exception. We need to catch this exception and handle it properly.
Tested, and it's working in dev.
=> Handle 404 exceptions in StatusAggregator

tests/Tests.Stats.CollectAzureChinaCDNLogs/JobTests.cs
I believe previously the storage account `name` existed and we hit an auth error. Now `name` no longer exists causing a retriable DNS error which results in an `AggregateException`.
=> [Hotfix] Fix broken unit test blocking hotifx

src/AccountDeleter/EmptyFeatureFlagService.cs, src/GitHubVulnerabilities2Db/Fakes/FakeFeatureFlagService.cs, src/NuGetGallery.Services/Configuration/FeatureFlagService.cs, src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs, src/NuGetGallery.Services/PackageManagement/IPackageService.cs, src/NuGetGallery.Services/PackageManagement/PackageService.cs, src/NuGetGallery/App_Data/Files/Content/flags.json, src/NuGetGallery/Controllers/UsersController.cs, src/NuGetGallery/ViewModels/UserProfileModel.cs, src/NuGetGallery/Views/Users/Profiles.cshtml, src/NuGetGallery/Web.config, src/VerifyMicrosoftPackage/Fakes/FakeFeatureFlagService.cs, tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs, tests/NuGetGallery.Facts/ViewModels/UserProfileModelFacts.cs
* Added paging to userprofile database call, and added feature flag
Addresses https://github.com/NuGet/NuGetGallery/issues/10221 (partly)
fixes #5877 
fixes #5659 
fixes #10025 
I used a modified version of the SQL based seeding script shared by @joelverhagen and tested that data are returned for a profile similar to MS within the query timeout.
I also verified locally that the feature flag toggle works as expected.
- it would be nice for contributors to have a better seeding facility and/or database dump
=> Reduce database calls for Microsoft profile page from 21.056 to 42

python/StatsLogParser/loginterpretation/knownclients.yaml
Following https://github.com/bonsai-rx/bonsai/pull/2266 we request addition of our NuGet client to the list of known clients. We have been a strong consumer of NuGet feeds with over 70 packages and 1M+ downloads which are all incorrectly assigned to "NuGet Client V3".
Related to https://github.com/NuGet/NuGetGallery/issues/5240
=> Add Bonsai to the list of known clients

python/StatsLogParser/pyproject.toml
Follow up on https://github.com/NuGet/NuGetGallery/issues/10452
Bumping the python package version since the code was updated. Build guide is [here](https://github.com/NuGet/NuGetGallery/blob/main/python/StatsLogParser/README.md).
I'm following https://github.com/NuGet/NuGetGallery/pull/10351 steps
=> Bumping package version

.pipelines/NuGetGallery-CI.yml
Branch may have underscores in their name, we use branch name to construct package version, which must be semver-compliant. Underscores are not allowed in semver pre-release labels which causes CI build failures. Adding transformation that replaces underscores with dashes for the purpose of version string generation.
=> Replacing underscores with dashes in branch name for use in versions.

src/Catalog/Helpers/Utils.cs, src/NuGet.Services.Validation.Orchestrator/ValidatorProvider.cs, src/NuGetGallery.Core/Entities/DatabaseWrapper.cs, src/NuGetGallery/App_Start/AutofacConfig.cs, src/NuGetGallery/OData/QueryAllowed/ODataQueryFilter.cs
Addresses https://github.com/NuGet/NuGetGallery/issues/10396
In case code inlining happens then Assembly.GetExecutingAssembly().Location may point to wrong location.
So we need to replace with typeof(T).Assembly.Location for reliability. This concern came up during review of another internal repo.
I'm only doing for product code, not for tests.
Previously I have done same change for https://github.com/NuGet/NuGet.Client/pull/5223
=> Replace Assembly.GetExecutingAssembly() with reliable method

src/NuGetGallery/ViewModels/PackageManagerViewModel.cs, src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
Quick stab at https://github.com/NuGet/NuGetGallery/issues/10481
Related to #10475. Helps with keeping everything on one line at least on wide-enough screens.
Introducing `InitialismExplanation` property for `PackageManagerViewModel` driving package manager tabs on package details page, so we can use shorter tab captions. The "explanation" is then used in the tool tip.
Replaced "Package manager" with "PMC" and "Central Package Management" with CPM.
Before
After
=> Initialism support in package manager tabs

src/NuGetGallery.Core/Frameworks/SupportedFrameworks.cs
Azure search index has been rebuilt, and I added the UI .NET10 checkbox to our search filters.
Addresses https://github.com/orgs/NuGet/projects/21/views/1?pane=issue&itemId=99610317&issue=NuGet%7CEngineering%7C5792
=> Added UI for .NET10 TFM

src/NuGetGallery.Core/Auditing/FederatedCredentialPolicyAuditRecord.cs, src/NuGetGallery.Services/Authentication/Federated/AddFederatedCredentialPolicyResult.cs, src/NuGetGallery.Services/Authentication/Federated/FederatedCredentialService.cs, src/NuGetGallery/Controllers/UsersController.cs, tests/NuGetGallery.Facts/Authentication/Federated/FederatedCredentialServiceFacts.cs, tests/NuGetGallery.Facts/Controllers/UsersControllerFacts.TrustedPublishing.cs
Currently we audit following `FederatedCredentialPolicy` activities, with **failed policy creation** added by this change
**Data Modification Auditing**
* Policy Creation - New policy successfully created
* Policy Deletion - Policy deleted with associated API keys
* Policy Update - Policy modified with API key cleanup
* 🆕 **Failed Policy Creation** - Creation attempt failed with reason
**Data Access/Usage Auditing**
* Policy Comparison - OIDC token evaluated against policy
* API Key Exchange - Successful token-to-API-key conversion
* Token Replay Rejection - Duplicate token usage blocked
* First Use Policy Update - Auto-update on initial use
https://github.com/NuGet/Engineering/issues/5934
=> Audit failures to create federated credential policies

src/NuGetGallery.Services/Authentication/Federated/EntraIdTokenValidator.cs, src/NuGetGallery.Services/Authentication/Federated/FederatedCredentialService.cs, src/NuGetGallery.Services/Authentication/Federated/GitHubTokenPolicyValidator.cs, src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs, src/NuGetGallery/App_Start/DefaultDependenciesModule.cs, tests/NuGetGallery.Facts/Authentication/Federated/EntraIdTokenValidatorFacts.cs, tests/NuGetGallery.Facts/Authentication/Federated/FederatedCredentialServiceFacts.cs, tests/NuGetGallery.Facts/Authentication/Federated/GitHubTokenPolicyValidatorFacts.cs
Currently we check 1P feature flag `CanUseFederatedCredentials` when validating policies for which apply to 3P, a.k.a. GitHub Actions. We should use `IsTrustedPublishingEnabled` instead.
=> Do not apply 1P OIDC feature flag to 3P scenarios

build/common.ps1
The `build/common.ps1` file in the Gallery repository is used for packing project into .nupkg files in internal repositories.
I added nuget.exe packing support for SDK-style .csproj files in the internal repository, since we’re already doing it for this Gallery repository. For example, [Auxiliary2AzureSearch.csproj](https://github.com/NuGet/NuGetGallery/blob/main/src/NuGet.Jobs.Auxiliary2AzureSearch/NuGet.Jobs.Auxiliary2AzureSearch.csproj) which SDK type, use [this NuGet.Jobs.Auxiliary2AzureSearch.nuspec file](https://github.com/NuGet/NuGetGallery/blob/ed98da6f9aa60d40e7b5c918440c6ee3c8e2aa95/build.ps1#L139C6-L139C90) for packing , actual nuspec [is here](https://github.com/NuGet/NuGetGallery/blob/main/src/NuGet.Jobs.Auxiliary2AzureSearch/NuGet.Jobs.Auxiliary2AzureSearch.nuspec). 
An …
=> Pack sdk style projects using nuspec file for internal projects

src/NuGetGallery.Core/CredentialTypes.cs, src/NuGetGallery.Services/Authentication/Federated/FederatedCredentialRepository.cs, src/NuGetGallery/Filters/ApiAuthorizeAttribute.cs, tests/NuGetGallery.Core.Facts/CredentialTypesFacts.cs, tests/NuGetGallery.Facts/Authentication/Federated/FederatedCredentialRepositoryFacts.cs, tests/NuGetGallery.Facts/Filters/ApiAuthorizeAttributeFacts.cs
1. Hide the short-lived API Key v5 in the API Keys page.
2. No warn about expiration in days as the key is short-lived and expires in a day.
=> [OIDC] API Key v5 - 3: Hide the key.

src/Validation.Symbols/ITelemetryService.cs, src/Validation.Symbols/SymbolsValidatorService.cs, src/Validation.Symbols/TelemetryService.cs, tests/StatusAggregator.Tests/Messages/MessageContentBuilderTests.cs
Currently the task to clean-up the temporary directory is not awaited. From telemetry and the disk on our compute nodes, it looks like we silently fail to clean up. This moves the clean-up step to be inside the validation flow, but leave the max time limit.
=> Synchronously wait for directory cleanup

src/NuGetGallery.Services/Authentication/AuthenticationService.cs, src/NuGetGallery/Controllers/AuthenticationController.cs, tests/NuGetGallery.Facts/Authentication/AuthenticationServiceFacts.cs, tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
Reverted part of https://github.com/NuGet/NuGetGallery/issues/6389.
Email addresses always need validation, even if they come from Azure AD tenants, which can be created by any user who can provide any email address.
Addresses https://github.com/NuGet/Engineering/issues/5929
=> Always validate email for new registrations
